import type { InflationLocaleData } from "../types";
import { INFLATION_EN_TEXTS } from "./en";

export const INFLATION_DE_TEXTS: InflationLocaleData = {
    ...INFLATION_EN_TEXTS,
    cardTitle: "INFLATION",
    cardSubtitle: "Die unsichtbare Steuer",
    cardDescription:
        "Visualisieren Sie, wie sich der Wert des Geldes im Laufe der Zeit verändert hat.",
    title: "Inflation - Das Gedächtnis ist fragil, aber die Daten bleiben",
    description:
        "Was ist Inflation? Visualisieren Sie, wie sich der Wert des Geldes im Laufe der Zeit verändert hat.",
    headerSubtitle: "Visualisieren Sie die realen Auswirkungen der Inflation auf Ihre Kaufkraft.",
    sliderTitle: "Bewegen Sie den Schieberegler, um durch die Zeit zu reisen",
    sliderYearPrefix: "Jahr",
    sliderValuePrefix: "100€ von damals entsprechen heute",
    billTitle: "100€ GELDSCHEIN",
    billYearLabel: "Jahr",
    billValueLabel: "Äquivalenter Wert heute",
    casesTitle: "Nostalgie vs. Realität",
    casesSubtitle: "Wischen Sie, um reale Beispiele von Preisveränderungen zu sehen",
    shareText: "Teilen",
    shareButton: "Fall teilen",
    infoTitle: "Was ist Inflation wirklich?",
    infoP1: "Inflation ist der fortschreitende Kaufkraftverlust der Währung.",
    infoP2: "Geld verliert an Wert, wenn die Geldmenge steigt oder die Produktionskosten steigen.",
    infoP3: "Geld unter der Matratze zu halten garantiert einen ständigen Verlust.",
    illusionTitle: "Die Geldillusion",
    illusionSubtitle: "Zu glauben, dass man mehr verdient, wenn man tatsächlich das Gleiche kauft.",
    illusionNominalLabel: "Nominalgehalt",
    illusionRealLabel: "Reale Kaufkraft",
    illusionExplanation:
        "Wenn Ihr Gehalt um 3% steigt, die Inflation aber 5% beträgt, verdienen Sie real 2% weniger.",
    hiddenTypesTitle: "Die Fallen der Inflation",
    hiddenTypesSubtitle: "Subtile Strategien, bei denen sich nicht nur der Preis ändert.",
    personalNoteTitle: "Anmerkung des Autors",
    personalNoteText: "Inflation ist eine stille Kraft, die die Zukunft prägt.",
    items: [
        { name: "Brot", price: 1.2, minYear: 1950, maxYear: 2025, icon: "bread" },
        { name: "Milch", price: 1.0, minYear: 1950, maxYear: 2025, icon: "milk" },
        { name: "Kaffee", price: 1.6, minYear: 1950, maxYear: 2025, icon: "coffee" },
        { name: "Bier", price: 3.0, minYear: 1950, maxYear: 2025, icon: "beer" },
        { name: "Buch", price: 22.0, minYear: 1950, maxYear: 2025, icon: "book" },
        { name: "T-Shirt", price: 20.0, minYear: 1950, maxYear: 2025, icon: "shirt" },
        { name: "Schuhe", price: 90.0, minYear: 1950, maxYear: 2025, icon: "shoe" },
        { name: "Schmuck", price: 500.0, minYear: 1950, maxYear: 2025, icon: "diamond" },
        { name: "Auto", price: 22000.0, minYear: 1950, maxYear: 2025, icon: "car" },
        { name: "Wohnung", price: 250000.0, minYear: 1950, maxYear: 2025, icon: "house" },
        {
            name: "Abendessen im Restaurant",
            price: 45.0,
            minYear: 1950,
            maxYear: 2025,
            icon: "restaurant",
        },
        { name: "Zeitung", price: 2.0, minYear: 1950, maxYear: 2025, icon: "newspaper" },
        { name: "Briefmarke", price: 1.0, minYear: 1950, maxYear: 2025, icon: "mail" },
        { name: "Kinokarte", price: 9.5, minYear: 1950, maxYear: 2025, icon: "movie" },
        { name: "Schallplatte", price: 30.0, minYear: 1950, maxYear: 2025, icon: "vinyl" },
        { name: "Konzertkarte", price: 60.0, minYear: 1950, maxYear: 2025, icon: "concert" },
        {
            name: "Schwarz-Weiß-Fernseher",
            price: 800.0,
            minYear: 1950,
            maxYear: 1980,
            icon: "tv_old",
        },
        { name: "Armbanduhr", price: 80.0, minYear: 1950, maxYear: 2025, icon: "watch" },
        { name: "Theaterkarte", price: 25.0, minYear: 1950, maxYear: 2025, icon: "theater" },
        { name: "Foto-Filmrolle", price: 12.0, minYear: 1950, maxYear: 2015, icon: "photo_roll" },
        { name: "Fotokamera", price: 300.0, minYear: 1950, maxYear: 2025, icon: "camera" },
        { name: "Zigarette", price: 5.0, minYear: 1950, maxYear: 2025, icon: "cigarette" },
        { name: "45-U/min-Single", price: 8.0, minYear: 1960, maxYear: 1995, icon: "single" },
        { name: "Farbfernseher", price: 1200.0, minYear: 1965, maxYear: 2010, icon: "tv_color" },
        { name: "Plattenspieler", price: 150.0, minYear: 1960, maxYear: 2000, icon: "turntable" },
        { name: "Fußballkarte", price: 45.0, minYear: 1960, maxYear: 2025, icon: "football" },
        { name: "Burger-Menü", price: 11.0, minYear: 1970, maxYear: 2025, icon: "burger" },
        { name: "Pizza", price: 14.0, minYear: 1970, maxYear: 2025, icon: "pizza" },
        { name: "Tankfüllung", price: 75.0, minYear: 1970, maxYear: 2025, icon: "fuel" },
        { name: "Digitaler Wecker", price: 20.0, minYear: 1970, maxYear: 2025, icon: "alarm" },
        { name: "Transistorradio", price: 40.0, minYear: 1970, maxYear: 2000, icon: "radio" },
        { name: "Walkman", price: 60.0, minYear: 1979, maxYear: 2005, icon: "walkman" },
        { name: "Taschenrechner", price: 15.0, minYear: 1975, maxYear: 2025, icon: "calculator" },
        { name: "Kassette", price: 10.0, minYear: 1980, maxYear: 2005, icon: "cassette" },
        { name: "VHS-Kassette", price: 20.0, minYear: 1980, maxYear: 2010, icon: "vhs" },
        { name: "VHS-Verleih", price: 3.0, minYear: 1985, maxYear: 2010, icon: "vhs_rental" },
        { name: "8-Bit-Konsole", price: 200.0, minYear: 1985, maxYear: 2000, icon: "console_8bit" },
        { name: "Festnetztelefon", price: 30.0, minYear: 1980, maxYear: 2025, icon: "phone" },
        { name: "Camcorder", price: 700.0, minYear: 1985, maxYear: 2010, icon: "videocamera" },
        {
            name: "Enzyklopädie-Set",
            price: 600.0,
            minYear: 1980,
            maxYear: 2005,
            icon: "encyclopedia",
        },
        { name: "Diskoette", price: 2.0, minYear: 1980, maxYear: 2005, icon: "floppy" },
        { name: "Audio-CD", price: 18.0, minYear: 1990, maxYear: 2015, icon: "cd" },
        { name: "Videospiel", price: 70.0, minYear: 1990, maxYear: 2025, icon: "game" },
        { name: "Altes Handy", price: 300.0, minYear: 1995, maxYear: 2010, icon: "mobile" },
        { name: "PC-Computer", price: 1200.0, minYear: 1995, maxYear: 2025, icon: "computer" },
        { name: "PlayStation", price: 400.0, minYear: 1995, maxYear: 2025, icon: "playstation" },
        { name: "Game Boy", price: 100.0, minYear: 1990, maxYear: 2010, icon: "gameboy" },
        {
            name: "Monatliches Internet",
            price: 40.0,
            minYear: 1995,
            maxYear: 2025,
            icon: "internet",
        },
        {
            name: "Digitalkamera",
            price: 250.0,
            minYear: 1995,
            maxYear: 2025,
            icon: "digital_camera",
        },
        {
            name: "Starbucks-Kaffee",
            price: 4.5,
            minYear: 1999,
            maxYear: 2025,
            icon: "coffee_premium",
        },
        { name: "DVD-Film", price: 15.0, minYear: 2000, maxYear: 2020, icon: "dvd" },
        { name: "iPod", price: 350.0, minYear: 2001, maxYear: 2017, icon: "ipod" },
        { name: "Smartphone", price: 900.0, minYear: 2007, maxYear: 2025, icon: "smartphone" },
        { name: "Tablet", price: 500.0, minYear: 2010, maxYear: 2025, icon: "tablet" },
        { name: "E-Book-Reader", price: 130.0, minYear: 2008, maxYear: 2025, icon: "ereader" },
        { name: "Streaming-Abo", price: 15.0, minYear: 2011, maxYear: 2025, icon: "streaming" },
        { name: "Kabellose Ohrhörer", price: 180.0, minYear: 2016, maxYear: 2025, icon: "earbuds" },
        { name: "Smartwatch", price: 300.0, minYear: 2014, maxYear: 2025, icon: "smartwatch" },
        { name: "E-Scooter", price: 400.0, minYear: 2017, maxYear: 2025, icon: "scooter" },
        { name: "Heißluftfritteuse", price: 100.0, minYear: 2018, maxYear: 2025, icon: "airfryer" },
        { name: "KI-Abonnement", price: 22.0, minYear: 2023, maxYear: 2025, icon: "ai_sub" },
    ],
    cases: [
        {
            year: 1970,
            title: "Seat 600",
            price: "390€",
            description: "Der Traum spanischer Familien kostete etwa 65.000 Peseten.",
            color: "bg-indigo-100 text-indigo-800 border-indigo-200",
            icon: "car",
        },
        {
            year: 1982,
            title: "WM-Ticket Naranjito",
            price: "4,80€",
            description: "Ein offizielles Ticket für ein WM-Spiel kostete 800 Peseten.",
            color: "bg-emerald-100 text-emerald-800 border-emerald-200",
            icon: "ticket",
        },
        {
            year: 1992,
            title: "Curro Maskottchen Plüschtier",
            price: "15€",
            description: "Das kultige Souvenir der Expo '92 in Sevilla kostete 2.500 Peseten.",
            color: "bg-rose-100 text-rose-800 border-rose-200",
            icon: "toy",
        },
        {
            year: 1995,
            title: "PlayStation 1 Markteinführung",
            price: "360€",
            description: "Erschien in Europa für 59.900 Peseten.",
            color: "bg-amber-100 text-amber-800 border-amber-200",
            icon: "game",
        },
        {
            year: 1998,
            title: "Nokia 5110",
            price: "150€",
            description: "Das unzerstörbare Handy mit Snake kostete 25.000 Peseten.",
            color: "bg-yellow-100 text-yellow-800 border-yellow-200",
            icon: "mobile",
        },
        {
            year: 2002,
            title: "Erster Euro-Kaffee",
            price: "0,60€",
            description: "Kostete genau bei der Euro-Umstellung 100 Peseten.",
            color: "bg-orange-100 text-orange-800 border-orange-200",
            icon: "coffee",
        },
    ],
    sourcesTitle: "Offizielle Quellen und Daten",
    sourcesSubtitle:
        "Institutionen und Behörden, die die realen Auswirkungen auf die Wirtschaft messen.",
    sourcesBadge: "Dokumentation",
    reportTitle: "Anhang I: Makroökonomischer Bericht",
    reportSubtitle:
        "Vergleichende Analyse der Preisentwicklung und Kaufkraft in Spanien (1980-2025).",
    table1Title: "Entwicklung der Lebenshaltungskosten",
    table1Ref: "Ref: INE / Zeitungsarchive / Ministerien",
    thConcept: "Konzept",
    thYear: "Jahr",
    thHistPrice: "Historischer Preis",
    thPrice2025: "Preis 2025",
    thVar: "Veränd. %",
    thSource: "Quelle",
    table2Title: "Lohnentwicklung",
    thAvgSalary: "Durchschnittlicher Jahreslohn",
    thSmiMonthly: "Monatlicher Mindestlohn (14x)",
    thSmiTotal: "Jährlicher Mindestlohn Gesamt",
    noteTitle: "Methodischer Hinweis",
    noteP1: "Die in diesem Bericht dargestellten Daten wurden auf laufende Euro normalisiert, um den Vergleich unter Verwendung des festen Wechselkurses (1€ = 166,386 ptas) zu erleichtern.",
    noteP2: 'Wichtig: Die Spalte "Veränd. %" spiegelt den nominalen Preisanstieg wider. Um den realen Kaufkraftverlust zu verstehen, muss er mit der Lohnentwicklung (Tabelle A.2) verglichen werden.',
    noteSources:
        "Quellen: INE, Bank von Spanien, Wohnungsbauministerium, BOE und digitale Zeitungsarchive.",
    reportTable1Rows: [
        {
            concept: "Wohnung (80m²)",
            year: 1985,
            priceHist: "27.000€ (4,5M ptas)",
            price2025: "287.000€",
            varPercent: "+963%",
            isPositive: false,
            sourceName: "Wohnungsbauministerium",
            sourceUrl: "https://www.boe.es/buscar/doc.php?id=BOE-A-2024-2088",
        },
        {
            concept: "Mindestlohn",
            year: 1980,
            priceHist: "154€ (25.620 ptas)",
            price2025: "1.134€",
            varPercent: "+636%",
            isPositive: true,
            sourceName: "BOE",
            sourceUrl: "https://www.boe.es/buscar/doc.php?id=BOE-A-2024-2088",
        },
        {
            concept: "Brot (250g)",
            year: 1985,
            priceHist: "0,12€ (20 ptas)",
            price2025: "1,20€",
            varPercent: "+900%",
            isPositive: false,
            sourceName: "INE (VPI)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "Benzin (Liter)",
            year: 1980,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,65€",
            varPercent: "+511%",
            isPositive: false,
            sourceName: "Energieministerium",
            sourceUrl: "https://www.miteco.gob.es",
        },
        {
            concept: "Kinokarte",
            year: 1980,
            priceHist: "1,20€ (200 ptas)",
            price2025: "9,00€",
            varPercent: "+650%",
            isPositive: false,
            sourceName: "Zeitungsarchiv",
            sourceTitle: "ABC / La Vanguardia Archive",
        },
        {
            concept: "Kleinwagen",
            year: 1985,
            priceHist: "4.500€ (750k ptas)",
            price2025: "24.000€",
            varPercent: "+433%",
            isPositive: false,
            sourceName: "Automobilmagazine",
            sourceTitle: "Motor Clásico / Autopista",
        },
        {
            concept: "Zeitung",
            year: 1985,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,80€",
            varPercent: "+566%",
            isPositive: false,
            sourceName: "Zeitungsarchiv",
            sourceTitle: "ABC / La Vanguardia Archive",
        },
        {
            concept: "Olivenöl (1L)",
            year: 2000,
            priceHist: "1,20€ (200 ptas)",
            price2025: "10,00€",
            varPercent: "+733%",
            isPositive: false,
            sourceName: "INE (VPI)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "Kaffee (Bar)",
            year: 1990,
            priceHist: "0,48€ (80 ptas)",
            price2025: "1,50€",
            varPercent: "+212%",
            isPositive: false,
            sourceName: "Gastronomieverband",
            sourceTitle: "Gastronomieverbände",
        },
    ],
    hiddenTypesCards: [
        {
            badge: "WENIGER FÜR GLEICHES",
            title: "Shrinkflation",
            graphicLabel1: "CHIPS",
            graphicLabel2: "NEUES FORMAT",
            graphicLegend1: "243g (Vorher 295g)",
            graphicLegend2: "Preis: +15%",
            tagline: '"Man verkauft Ihnen Luft zum Preis von Essen."',
            description:
                "Der Kartoffelchips-Fall ist Lehrbuchwissen: Die Menge sank von 295g auf 275g und dann auf 243g, während der Preis stieg.",
            sourceText: "Quelle: FACUA-Studie",
            shareText: "Shrinkflation ist real!",
        },
        {
            badge: "SCHLECHTER FÜR GLEICHES",
            title: "Skimpflation",
            graphicLabel1: "VERBESSERTE REZEPTUR",
            graphicLabel2: "ZUTATEN:",
            graphicRemoved1: "Sonnenblumenöl",
            graphicAdded1: "Palmfett/Mix",
            graphicRemoved2: "Butter",
            graphicAdded2: "Pflanzenöle",
            tagline: '"Gute Zutaten werden durch billigen Ersatz ausgetauscht."',
            description:
                "Nach Lieferkettenkrisen ersetzten viele Marken Sonnenblumenöl durch Palmöl oder Pflanzenölmischungen.",
            sourceText: "Quelle: NPR (Skimpflation)",
            shareText: "Skimpflation tauscht gute Zutaten aus!",
        },
        {
            badge: "FLUCHT NACH OBEN",
            title: "Premiumisierung",
            graphicLabel1: "Platinum",
            graphicLabel2: "ULTRA PRO",
            graphicLegend1: "12,99€",
            graphicLegend2: "AUSVERKAUFT!",
            graphicRemoved1: "Basis",
            graphicAdded1: "2,99€",
            tagline: '"Basisangebote werden gestrichen, um den Kauf von Luxuslinien zu erzwingen."',
            description:
                "Der High-Protein-Boom hat einfachen Joghurt verdrängt. Pulverwaschmittel verschwindet zugunsten teurer Pods.",
            sourceText: "Quelle: CESCE (Premiumisierung)",
            shareText: "Basisprodukte verschwinden!",
        },
        {
            badge: "SIE SIND DER MITARBEITER",
            title: "Schatteninflation",
            graphicLabel1: "FEHLER: BITTE WARTEN",
            graphicLabel2: "Ihr Lohn: 0€/Std.",
            tagline: '"Sie arbeiten kostenlos für den Supermarkt und zahlen denselben Preis."',
            description:
                "Selbstbedienungskassen verlagern Personalkosten auf den Kunden ohne Preisnachlässe.",
            sourceText: "Quelle: The Guardian (Schattenarbeit)",
            shareText: "Schatteninflation lässt Sie gratis arbeiten!",
        },
    ],
};
