import type { InflationLocaleData } from "../types";

export const INFLATION_EN_TEXTS: InflationLocaleData = {
    cardTitle: "INFLATION",
    cardSubtitle: "The Invisible Tax",
    cardDescription: "Visualize how the value of money has changed over time.",
    title: "Inflation - Memory is fragile, but data remains",
    description: "What is inflation? Visualize how the value of money has changed over time.",
    headerSubtitle: "What could you buy with €100?",
    sliderTitle: "Move the slider to travel back in time",
    sliderYearPrefix: "Year",
    sliderValuePrefix: "100€ back then is equivalent to",
    billTitle: "100€ BANKNOTE",
    billYearLabel: "Year",
    billValueLabel: "Equivalent value today",
    casesTitle: "From the bar counter I tell you...",
    casesSubtitle: "(the uncle who is sometimes right)",
    shareText: "Share",
    shareButton: "Share case",
    infoTitle: "What is inflation really?",
    infoSubtitle1: "The Old-Timer Nostalgia Effect",
    infoP1: "Inflation is the progressive loss of purchasing power of a currency. Or put another way: with the same 50€ bill, year after year you buy fewer things.",
    infoSubtitle2: "Why should I care?",
    infoP2: "It's not just that prices go up, it's that money is worth less. When the money supply increases or production costs skyrocket, every circulating monetary unit loses a fraction of its exchange capacity.",
    infoSubtitle3: "Keeping money under the mattress",
    infoP3: "Keeping money under the mattress is not a neutral strategy: it is a guaranteed constant loss.",
    infoScienceTitle: "The Science Behind the Magic",
    infoScienceText:
        "This page uses real historical CPI (Consumer Price Index) data to adjust the value of a simulated shopping basket. It is not perfect, but it is a painfully accurate approximation of how our purchasing power has eroded.",
    disclaimerTitle: "Disclaimer",
    disclaimerText:
        "It's easy to fall into the nostalgia trap and think that everything was wonderful. Yes, prices were ridiculously low, but <strong class=\"text-highlight-white\">salaries were low too</strong>. My grandfather didn't earn €2,000 a month; he earned just enough to live.",
    disclaimerEffortTitle: "The Effort",
    disclaimerEffortP1:
        "However, this is where the key variable enters: <strong class=\"text-highlight-green\">The Effort</strong>. Although we earn more 'numbers', the proportion of our salary that we must allocate to basic items (especially housing) has skyrocketed.",
    disclaimerEffortP2:
        "We have gained in technology (today you have a supercomputer in your pocket for 'little' money), but we have lost dramatically in fundamental assets.",
    disclaimerProductivityTitle: "The Productivity Trap",
    disclaimerProductivityText:
        "The most frustrating part of this data is that today we are infinitely more productive than 40 years ago. Technology allows us to do in an hour what used to take a day. Yet, that extra productivity hasn't translated into 'needing to work less to live', but into 'needing to work more to maintain the same standard of living'.",
    effortTitle: "Your Reality",
    effortSubtitle: "Adjust your salary to see your real effort",
    effortPerYear: "/year",
    effortUseAverageBtn: "Use average salary",
    effortGoodEra: "The 'Good' Era",
    effortHarshReality: "The Harsh Reality",
    effortWorkSuffix: "of work",
    effortSalaryLabel: "Salary",
    effortCostLabel: "Cost",
    effortFooterNote: "* Approximate data adjusted to average salaries",
    illusionTitle: "The Money Illusion",
    illusionSubtitle: "Believing you earn more when you actually buy the same (or less).",
    illusionNominalLabel: "Nominal Salary",
    illusionNominalDesc: "Your boss tells you 'We raised your salary to €1,780!'.",
    illusionRealLabel: "Real Purchasing Power",
    illusionRealDesc:
        "You go to the grocery store and discover you buy fewer things than when you made €1,000.",
    illusionLegendNominal: "What you earn",
    illusionLegendReal: "What it actually buys",
    illusionExplanation:
        "If your salary goes up 3% but inflation is 5%, in real terms you are earning 2% less than the previous year.",
    hiddenTypesTitle: "The Traps of Inflation",
    hiddenTypesSubtitle: "Subtle strategies where price is not the only thing that changes.",
    sourcesTitle: "Official Sources and Data",
    sourcesSubtitle: "Institutions and agencies that measure the real impact on the economy.",
    sourcesBadge: "Documentation",
    reportTitle: "Annex I: Macroeconomic Report",
    reportSubtitle:
        "Comparative analysis of price evolution and purchasing power in Spain (1980-2025).",
    table1Title: "Evolution of the Cost of Living",
    table1Ref: "Ref: INE / Press Archives / Ministries",
    thConcept: "Concept",
    thYear: "Year",
    thHistPrice: "Historical Price",
    thPrice2025: "2025 Price",
    thVar: "Var. %",
    thSource: "Source",
    table2Title: "Wage Evolution",
    thAvgSalary: "Annual Average Salary",
    thSmiMonthly: "Monthly Minimum Wage (14p)",
    thSmiTotal: "Total Annual Minimum Wage",
    noteTitle: "Methodological Note",
    noteP1: "The data presented in this report has been normalized to current Euros for ease of comparison, using the fixed exchange rate (1€ = 166.386 ptas).",
    noteP2: 'Important: The "Var. %" column reflects the nominal price increase. To understand the real loss of purchasing power, it must be contrasted with wage evolution (Table A.2). While some basic goods have risen by 900%, average wages have barely tripled over the same period.',
    noteSources:
        "Sources: INE (Historical CPI series), Bank of Spain (Statistical bulletins), Ministry of Housing (m² price series), BOE (Minimum wage decrees), and digital press archives.",
    reportTable1Rows: [
        {
            concept: "Housing (80m² Apartment)",
            year: 1985,
            priceHist: "27,000€ (4.5M ptas)",
            price2025: "287,000€",
            varPercent: "+963%",
            isPositive: false,
            sourceName: "Ministry of Housing",
            sourceUrl: "https://www.boe.es/buscar/doc.php?id=BOE-A-2024-2088",
        },
        {
            concept: "Minimum Wage (SMI)",
            year: 1980,
            priceHist: "154€ (25,620 ptas)",
            price2025: "1,134€",
            varPercent: "+636%",
            isPositive: true,
            sourceName: "BOE (SMI '24)",
            sourceUrl: "https://www.boe.es/buscar/doc.php?id=BOE-A-2024-2088",
        },
        {
            concept: "Bread (250g Loaf)",
            year: 1985,
            priceHist: "0.12€ (20 ptas)",
            price2025: "1.20€",
            varPercent: "+900%",
            isPositive: false,
            sourceName: "INE (CPI)",
            sourceUrl:
                "https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736176802&menu=ultiDatos&idp=1254735976607",
        },
        {
            concept: "Gasoline (Liter)",
            year: 1980,
            priceHist: "0.27€ (45 ptas)",
            price2025: "1.65€",
            varPercent: "+511%",
            isPositive: false,
            sourceName: "Ministry of Energy",
            sourceUrl:
                "https://www.miteco.gob.es/es/energia/hidrocarburos-nuevos-combustibles/petroleo/informes/informes-anuales.html",
        },
        {
            concept: "Cinema Ticket",
            year: 1980,
            priceHist: "1.20€ (200 ptas)",
            price2025: "9.00€",
            varPercent: "+650%",
            isPositive: false,
            sourceName: "Press Archives",
            sourceTitle: "ABC / La Vanguardia Archives",
        },
        {
            concept: "Compact Car",
            year: 1985,
            priceHist: "4,500€ (750k ptas)",
            price2025: "24,000€",
            varPercent: "+433%",
            isPositive: false,
            sourceName: "Automotive Magazines",
            sourceTitle: "Motor Clásico / Autopista Magazines",
        },
        {
            concept: "Newspaper",
            year: 1985,
            priceHist: "0.27€ (45 ptas)",
            price2025: "1.80€",
            varPercent: "+566%",
            isPositive: false,
            sourceName: "Press Archives",
            sourceTitle: "ABC / La Vanguardia Archives",
        },
        {
            concept: "Olive Oil (1L)",
            year: 2000,
            priceHist: "1.20€ (200 ptas)",
            price2025: "10.00€",
            varPercent: "+733%",
            isPositive: false,
            sourceName: "INE (CPI)",
            sourceUrl:
                "https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736176802&menu=ultiDatos&idp=1254735976607",
        },
        {
            concept: "Coffee (Bar)",
            year: 1990,
            priceHist: "0.48€ (80 ptas)",
            price2025: "1.50€",
            varPercent: "+212%",
            isPositive: false,
            sourceName: "Hospitality Assoc.",
            sourceTitle: "Hospitality Associations",
        },
    ],
    hiddenTypesCards: [
        {
            badge: "LESS FOR THE SAME",
            title: "Shrinkflation",
            graphicLabel1: "CHIPS",
            graphicLabel2: "NEW FORMAT",
            graphicLegend1: "243g (Was 295g)",
            graphicLegend2: "Price: +15%",
            tagline: '"They sell you air at food prices."',
            description:
                "The potato chips case is textbook: they dropped from 295g to 275g, and then to 243g, while raising the price. Consumer associations have reported reductions of up to 17% in leading brand products.",
            sourceText: "Source: FACUA Study (12 products detected)",
            shareText:
                "Have you noticed potato chip bags are 60% air? It's called Shrinkflation: selling air at food prices.",
        },
        {
            badge: "WORSE FOR THE SAME",
            title: "Skimpflation",
            graphicLabel1: "IMPROVED RECIPE",
            graphicLabel2: "INGREDIENTS:",
            graphicRemoved1: "Sunflower Oil",
            graphicAdded1: "Palm Fat/Mix",
            graphicRemoved2: "Butter",
            graphicAdded2: "Vegetable Oils",
            tagline: '"They swap good ingredients for cheap substitutes."',
            description:
                "Following supply chain crises, many brands replaced sunflower oil with palm oil or vegetable blends in mayonnaise, cookies, and sauces. The 'Traditional Flavor' label stayed, but nutritional quality plummeted.",
            sourceText: "Source: NPR (Origin of the term Skimpflation)",
            shareText:
                "Does food taste worse but cost the same? It's called Skimpflation: swapping good ingredients for cheap junk.",
        },
        {
            badge: "FLIGHT UPWARDS",
            title: "Premiumization",
            graphicLabel1: "Platinum",
            graphicLabel2: "ULTRA PRO",
            graphicLegend1: "12.99€",
            graphicLegend2: "SOLD OUT!",
            graphicRemoved1: "Basic",
            graphicAdded1: "2.99€",
            tagline: '"They eliminate basic ranges to force you to buy luxury lines."',
            description:
                "The 'High Protein' craze has pushed out basic yogurts. Powdered detergent (cheaper and effective) disappears from shelves to make room for '3-in-1 Pods' costing triple per wash.",
            sourceText: "Source: CESCE (Premiumization Strategy)",
            shareText:
                "Can't find the cheap version of anything anymore? It's called Premiumization: cutting basics to force luxury prices.",
        },
        {
            badge: "YOU ARE THE EMPLOYEE",
            title: "Shadow Inflation",
            graphicLabel1: "ERROR: WAIT FOR ASSISTANCE",
            graphicLabel2: "Your Wage: 0€/hour",
            tagline: '"You work for free for the supermarket and still pay the same."',
            description:
                "The proliferation of self-checkout lanes transfers labor costs to the customer. Market studies show that labor savings (up to 40% in checkout costs) are never passed on as lower consumer prices.",
            sourceText: "Source: The Guardian (Shadow Work & Automation)",
            shareText:
                "Paying the same price and scanning your own groceries? It's called Shadow Inflation: working for free for the store.",
        },
    ],
    personalNoteTitle: "Author's Note",
    personalNoteText:
        '<p>"This page was born out of pure curiosity. I intuited what inflation was, but it was hard to visualize its real impact over the decades."</p><br/><p>"I created this comparison as an exercise to understand it better, to see with my own eyes how our purchasing power has changed. If you find any inaccurate data, I apologize and will be happy to correct it; this is a learning and outreach project that I wanted to share with you."</p>',
    madeForFun: "Made for fun",
    items: [
        { name: "Bread", price: 1.2, minYear: 1950, maxYear: 2025, icon: "bread" },
        { name: "Milk", price: 1.0, minYear: 1950, maxYear: 2025, icon: "milk" },
        { name: "Coffee", price: 1.6, minYear: 1950, maxYear: 2025, icon: "coffee" },
        { name: "Beer", price: 3.0, minYear: 1950, maxYear: 2025, icon: "beer" },
        { name: "Book", price: 22.0, minYear: 1950, maxYear: 2025, icon: "book" },
        { name: "T-Shirt", price: 20.0, minYear: 1950, maxYear: 2025, icon: "shirt" },
        { name: "Shoes", price: 90.0, minYear: 1950, maxYear: 2025, icon: "shoe" },
        { name: "Jewel", price: 500.0, minYear: 1950, maxYear: 2025, icon: "diamond" },
        { name: "Car", price: 22000.0, minYear: 1950, maxYear: 2025, icon: "car" },
        { name: "Apartment", price: 250000.0, minYear: 1950, maxYear: 2025, icon: "house" },
        {
            name: "Restaurant Dinner",
            price: 45.0,
            minYear: 1950,
            maxYear: 2025,
            icon: "restaurant",
        },
        { name: "Newspaper", price: 2.0, minYear: 1950, maxYear: 2025, icon: "newspaper" },
        { name: "Postage Stamp", price: 1.0, minYear: 1950, maxYear: 2025, icon: "mail" },
        { name: "Cinema Ticket", price: 9.5, minYear: 1950, maxYear: 2025, icon: "movie" },
        { name: "Vinyl Record", price: 30.0, minYear: 1950, maxYear: 2025, icon: "vinyl" },
        { name: "Concert Ticket", price: 60.0, minYear: 1950, maxYear: 2025, icon: "concert" },
        { name: "B&W TV", price: 800.0, minYear: 1950, maxYear: 1980, icon: "tv_old" },
        { name: "Wristwatch", price: 80.0, minYear: 1950, maxYear: 2025, icon: "watch" },
        { name: "Theater Ticket", price: 25.0, minYear: 1950, maxYear: 2025, icon: "theater" },
        { name: "Film Roll", price: 12.0, minYear: 1950, maxYear: 2015, icon: "photo_roll" },
        { name: "Camera", price: 300.0, minYear: 1950, maxYear: 2025, icon: "camera" },
        { name: "Cigarettes", price: 5.0, minYear: 1950, maxYear: 2025, icon: "cigarette" },
        { name: "45rpm Single", price: 8.0, minYear: 1960, maxYear: 1995, icon: "single" },
        { name: "Color TV", price: 1200.0, minYear: 1965, maxYear: 2010, icon: "tv_color" },
        { name: "Turntable", price: 150.0, minYear: 1960, maxYear: 2000, icon: "turntable" },
        { name: "Football Ticket", price: 45.0, minYear: 1960, maxYear: 2025, icon: "football" },
        { name: "Burger Meal", price: 11.0, minYear: 1970, maxYear: 2025, icon: "burger" },
        { name: "Pizza", price: 14.0, minYear: 1970, maxYear: 2025, icon: "pizza" },
        { name: "Full Tank of Gas", price: 75.0, minYear: 1970, maxYear: 2025, icon: "fuel" },
        { name: "Digital Alarm", price: 20.0, minYear: 1970, maxYear: 2025, icon: "alarm" },
        { name: "Transistor Radio", price: 40.0, minYear: 1970, maxYear: 2000, icon: "radio" },
        { name: "Walkman", price: 60.0, minYear: 1979, maxYear: 2005, icon: "walkman" },
        { name: "Calculator", price: 15.0, minYear: 1975, maxYear: 2025, icon: "calculator" },
        { name: "Cassette Tape", price: 10.0, minYear: 1980, maxYear: 2005, icon: "cassette" },
        { name: "VHS Tape", price: 20.0, minYear: 1980, maxYear: 2010, icon: "vhs" },
        { name: "VHS Rental", price: 3.0, minYear: 1985, maxYear: 2010, icon: "vhs_rental" },
        { name: "8-bit Console", price: 200.0, minYear: 1985, maxYear: 2000, icon: "console_8bit" },
        { name: "Landline Phone", price: 30.0, minYear: 1980, maxYear: 2025, icon: "phone" },
        { name: "Camcorder", price: 700.0, minYear: 1985, maxYear: 2010, icon: "videocamera" },
        {
            name: "Encyclopedia Set",
            price: 600.0,
            minYear: 1980,
            maxYear: 2005,
            icon: "encyclopedia",
        },
        { name: "Floppy Disk", price: 2.0, minYear: 1980, maxYear: 2005, icon: "floppy" },
        { name: "Audio CD", price: 18.0, minYear: 1990, maxYear: 2015, icon: "cd" },
        { name: "Video Game", price: 70.0, minYear: 1990, maxYear: 2025, icon: "game" },
        { name: "Early Mobile Phone", price: 300.0, minYear: 1995, maxYear: 2010, icon: "mobile" },
        { name: "PC Computer", price: 1200.0, minYear: 1995, maxYear: 2025, icon: "computer" },
        { name: "PlayStation", price: 400.0, minYear: 1995, maxYear: 2025, icon: "playstation" },
        { name: "Game Boy", price: 100.0, minYear: 1990, maxYear: 2010, icon: "gameboy" },
        { name: "Monthly Internet", price: 40.0, minYear: 1995, maxYear: 2025, icon: "internet" },
        {
            name: "Digital Camera",
            price: 250.0,
            minYear: 1995,
            maxYear: 2025,
            icon: "digital_camera",
        },
        {
            name: "Starbucks Coffee",
            price: 4.5,
            minYear: 1999,
            maxYear: 2025,
            icon: "coffee_premium",
        },
        { name: "DVD Movie", price: 15.0, minYear: 2000, maxYear: 2020, icon: "dvd" },
        { name: "iPod", price: 350.0, minYear: 2001, maxYear: 2017, icon: "ipod" },
        { name: "Smartphone", price: 900.0, minYear: 2007, maxYear: 2025, icon: "smartphone" },
        { name: "Tablet", price: 500.0, minYear: 2010, maxYear: 2025, icon: "tablet" },
        { name: "E-Reader", price: 130.0, minYear: 2008, maxYear: 2025, icon: "ereader" },
        { name: "Streaming Plan", price: 15.0, minYear: 2011, maxYear: 2025, icon: "streaming" },
        { name: "Wireless Earbuds", price: 180.0, minYear: 2016, maxYear: 2025, icon: "earbuds" },
        { name: "Smartwatch", price: 300.0, minYear: 2014, maxYear: 2025, icon: "smartwatch" },
        { name: "Electric Scooter", price: 400.0, minYear: 2017, maxYear: 2025, icon: "scooter" },
        { name: "Air Fryer", price: 100.0, minYear: 2018, maxYear: 2025, icon: "airfryer" },
        { name: "AI Subscription", price: 22.0, minYear: 2023, maxYear: 2025, icon: "ai_sub" },
    ],
    cases: [
        {
            year: 1970,
            title: "Seat 600",
            price: "390€",
            description:
                "The dream of Spanish families, costing around 65,000 pesetas at the time.",
            color: "bg-indigo-100 text-indigo-800 border-indigo-200",
            icon: "car",
        },
        {
            year: 1982,
            title: "World Cup Ticket Naranjito",
            price: "4.80€",
            description: "Official ticket for World Cup matches priced at 800 pesetas.",
            color: "bg-emerald-100 text-emerald-800 border-emerald-200",
            icon: "ticket",
        },
        {
            year: 1992,
            title: "Curro Mascot Plush",
            price: "15€",
            description: "Iconic souvenir from Seville Expo '92 priced at 2,500 pesetas.",
            color: "bg-rose-100 text-rose-800 border-rose-200",
            icon: "toy",
        },
        {
            year: 1995,
            title: "PlayStation 1 Launch",
            price: "360€",
            description: "Arrived in Europe costing 59,900 pesetas.",
            color: "bg-amber-100 text-amber-800 border-amber-200",
            icon: "game",
        },
        {
            year: 1998,
            title: "Nokia 5110",
            price: "150€",
            description: "Indestructible phone with Snake game costing 25,000 pesetas.",
            color: "bg-yellow-100 text-yellow-800 border-yellow-200",
            icon: "mobile",
        },
        {
            year: 2002,
            title: "First Euro Coffee",
            price: "0.60€",
            description: "At the moment of euro transition, priced exactly at 100 pesetas.",
            color: "bg-orange-100 text-orange-800 border-orange-200",
            icon: "coffee",
        },
    ],
    effortComparisons: [
        {
            title: "Owned Apartment",
            shareTitle: "an apartment",
            icon: "house",
            then: {
                year: 1985,
                effort: "3 years",
                effortValue: 30,
                salary: "9,000€",
                cost: "27,000€",
            },
            now: {
                year: 2025,
                effort: "11.5 years",
                effortValue: 100,
                salary: "25,000€",
                cost: "287,000€",
            },
        },
        {
            title: "New Car",
            shareTitle: "a new car",
            icon: "car",
            then: {
                year: 1985,
                effort: "6 months",
                effortValue: 25,
                salary: "9,000€",
                cost: "4,500€",
            },
            now: {
                year: 2025,
                effort: "11.5 months",
                effortValue: 48,
                salary: "25,000€",
                cost: "24,000€",
            },
        },
        {
            title: "Cinema Ticket",
            shareTitle: "a cinema ticket",
            icon: "movie",
            then: { year: 1980, effort: "20 min", effortValue: 15, salary: "4€/h", cost: "1.50€" },
            now: { year: 2025, effort: "45 min", effortValue: 35, salary: "12€/h", cost: "9.00€" },
        },
        {
            title: "Liter of Olive Oil",
            shareTitle: "a liter of oil",
            icon: "bottle",
            then: { year: 2000, effort: "12 min", effortValue: 10, salary: "6€/h", cost: "1.20€" },
            now: { year: 2025, effort: "50 min", effortValue: 45, salary: "12€/h", cost: "10.00€" },
        },
        {
            title: "Monthly Rent",
            shareTitle: "one month rent",
            icon: "key",
            then: {
                year: 1995,
                effort: "5 days",
                effortValue: 20,
                salary: "14,000€",
                cost: "250€",
            },
            now: {
                year: 2025,
                effort: "14 days",
                effortValue: 65,
                salary: "25,000€",
                cost: "950€",
            },
        },
        {
            title: "Festival Ticket",
            shareTitle: "a festival pass",
            icon: "ticket",
            then: { year: 1998, effort: "6 hours", effortValue: 8, salary: "5€/h", cost: "30€" },
            now: { year: 2025, effort: "2.5 days", effortValue: 35, salary: "12€/h", cost: "240€" },
        },
        {
            title: "Weekly Grocery Basket",
            shareTitle: "weekly groceries",
            icon: "cart",
            then: { year: 2000, effort: "4 hours", effortValue: 10, salary: "6€/h", cost: "24€" },
            now: { year: 2025, effort: "1.5 days", effortValue: 25, salary: "12€/h", cost: "120€" },
        },
        {
            title: "Electricity/Gas Bill",
            shareTitle: "the electricity bill",
            icon: "bolt",
            then: { year: 1990, effort: "3 hours", effortValue: 5, salary: "4€/h", cost: "12€" },
            now: { year: 2025, effort: "10 hours", effortValue: 18, salary: "12€/h", cost: "120€" },
        },
    ],
};
