import type {
    InflationBasketItem,
    InflationCaseItem,
    InflationEffortItem,
    InflationHiddenTypeItem,
    InflationLocaleData,
    InflationSourceItem,
} from "../types";

export const INFLATION_ES_ITEMS: readonly InflationBasketItem[] = [
    { name: "Pan", price: 1.2, minYear: 1950, maxYear: 2025, icon: "bread" },
    { name: "Leche", price: 1.0, minYear: 1950, maxYear: 2025, icon: "milk" },
    { name: "Café", price: 1.6, minYear: 1950, maxYear: 2025, icon: "coffee" },
    { name: "Caña", price: 3.0, minYear: 1950, maxYear: 2025, icon: "beer" },
    { name: "Libro", price: 22.0, minYear: 1950, maxYear: 2025, icon: "book" },
    { name: "Camiseta", price: 20.0, minYear: 1950, maxYear: 2025, icon: "shirt" },
    { name: "Zapatos", price: 90.0, minYear: 1950, maxYear: 2025, icon: "shoe" },
    { name: "Joya", price: 500.0, minYear: 1950, maxYear: 2025, icon: "diamond" },
    { name: "Coche", price: 22000.0, minYear: 1950, maxYear: 2025, icon: "car" },
    { name: "Piso", price: 250000.0, minYear: 1950, maxYear: 2025, icon: "house" },
    { name: "Cena Restaurante", price: 45.0, minYear: 1950, maxYear: 2025, icon: "restaurant" },
    { name: "Periódico", price: 2.0, minYear: 1950, maxYear: 2025, icon: "newspaper" },
    { name: "Sello Correo", price: 1.0, minYear: 1950, maxYear: 2025, icon: "mail" },
    { name: "Cine", price: 9.5, minYear: 1950, maxYear: 2025, icon: "movie" },
    { name: "Disco Vinilo", price: 30.0, minYear: 1950, maxYear: 2025, icon: "vinyl" },
    { name: "Concierto", price: 60.0, minYear: 1950, maxYear: 2025, icon: "concert" },
    { name: "TV Blanco/Negro", price: 800.0, minYear: 1950, maxYear: 1980, icon: "tv_old" },
    { name: "Reloj de Pulsera", price: 80.0, minYear: 1950, maxYear: 2025, icon: "watch" },
    { name: "Entrada Teatro", price: 25.0, minYear: 1950, maxYear: 2025, icon: "theater" },
    { name: "Rollo Fotos", price: 12.0, minYear: 1950, maxYear: 2015, icon: "photo_roll" },
    { name: "Cámara Fotos", price: 300.0, minYear: 1950, maxYear: 2025, icon: "camera" },
    { name: "Tabaco", price: 5.0, minYear: 1950, maxYear: 2025, icon: "cigarette" },
    { name: "Single 45rpm", price: 8.0, minYear: 1960, maxYear: 1995, icon: "single" },
    { name: "TV Color", price: 1200.0, minYear: 1965, maxYear: 2010, icon: "tv_color" },
    { name: "Tocadiscos", price: 150.0, minYear: 1960, maxYear: 2000, icon: "turntable" },
    { name: "Entrada Fútbol", price: 45.0, minYear: 1960, maxYear: 2025, icon: "football" },
    { name: "Menú Burger", price: 11.0, minYear: 1970, maxYear: 2025, icon: "burger" },
    { name: "Pizza", price: 14.0, minYear: 1970, maxYear: 2025, icon: "pizza" },
    { name: "Llenar Depósito", price: 75.0, minYear: 1970, maxYear: 2025, icon: "fuel" },
    { name: "Despertador Digital", price: 20.0, minYear: 1970, maxYear: 2025, icon: "alarm" },
    { name: "Radio Transistor", price: 40.0, minYear: 1970, maxYear: 2000, icon: "radio" },
    { name: "Walkman", price: 60.0, minYear: 1979, maxYear: 2005, icon: "walkman" },
    { name: "Calculadora", price: 15.0, minYear: 1975, maxYear: 2025, icon: "calculator" },
    { name: "Cassette", price: 10.0, minYear: 1980, maxYear: 2005, icon: "cassette" },
    { name: "VHS", price: 20.0, minYear: 1980, maxYear: 2010, icon: "vhs" },
    { name: "Alquiler VHS", price: 3.0, minYear: 1985, maxYear: 2010, icon: "vhs_rental" },
    { name: "Consola 8-bit", price: 200.0, minYear: 1985, maxYear: 2000, icon: "console_8bit" },
    { name: "Teléfono Fijo", price: 30.0, minYear: 1980, maxYear: 2025, icon: "phone" },
    { name: "Videocámara", price: 700.0, minYear: 1985, maxYear: 2010, icon: "videocamera" },
    { name: "Enciclopedia", price: 600.0, minYear: 1980, maxYear: 2005, icon: "encyclopedia" },
    { name: "Disquete", price: 2.0, minYear: 1980, maxYear: 2005, icon: "floppy" },
    { name: "CD", price: 18.0, minYear: 1990, maxYear: 2015, icon: "cd" },
    { name: "Videojuego", price: 70.0, minYear: 1990, maxYear: 2025, icon: "game" },
    { name: "Móvil Antiguo", price: 300.0, minYear: 1995, maxYear: 2010, icon: "mobile" },
    { name: "Ordenador", price: 1200.0, minYear: 1995, maxYear: 2025, icon: "computer" },
    { name: "PlayStation", price: 400.0, minYear: 1995, maxYear: 2025, icon: "playstation" },
    { name: "Game Boy", price: 100.0, minYear: 1990, maxYear: 2010, icon: "gameboy" },
    { name: "Internet (mes)", price: 40.0, minYear: 1995, maxYear: 2025, icon: "internet" },
    { name: "Cámara Digital", price: 250.0, minYear: 1995, maxYear: 2025, icon: "digital_camera" },
    { name: "Café Starbucks", price: 4.5, minYear: 1999, maxYear: 2025, icon: "coffee_premium" },
    { name: "DVD", price: 15.0, minYear: 2000, maxYear: 2020, icon: "dvd" },
    { name: "iPod", price: 350.0, minYear: 2001, maxYear: 2017, icon: "ipod" },
    { name: "Vuelo Low Cost", price: 80.0, minYear: 2000, maxYear: 2025, icon: "flight" },
    { name: "Suscripción Gym", price: 35.0, minYear: 2000, maxYear: 2025, icon: "gym" },
    { name: "Amazon Prime", price: 50.0, minYear: 2005, maxYear: 2025, icon: "amazon" },
    { name: "Café Premium", price: 5.0, minYear: 2002, maxYear: 2025, icon: "coffee_tag" },
    { name: "Tono Móvil", price: 2.0, minYear: 2000, maxYear: 2015, icon: "ringtone" },
    { name: "Xbox/PS2", price: 300.0, minYear: 2000, maxYear: 2015, icon: "xbox" },
    { name: "SMS", price: 0.15, minYear: 2000, maxYear: 2025, icon: "sms" },
    { name: "TV Plasma", price: 1500.0, minYear: 2000, maxYear: 2015, icon: "tv_plasma" },
    { name: "Descarga MP3", price: 1.0, minYear: 2000, maxYear: 2015, icon: "mp3" },
    { name: "Smartphone", price: 400.0, minYear: 2010, maxYear: 2025, icon: "smartphone" },
    { name: "Tablet", price: 350.0, minYear: 2010, maxYear: 2025, icon: "tablet" },
    { name: "Netflix", price: 13.0, minYear: 2012, maxYear: 2025, icon: "netflix" },
    { name: "Spotify", price: 11.0, minYear: 2011, maxYear: 2025, icon: "spotify" },
    { name: "Delivery", price: 4.0, minYear: 2015, maxYear: 2025, icon: "delivery" },
    { name: "Uber/Cabify", price: 12.0, minYear: 2012, maxYear: 2025, icon: "uber" },
    { name: "Auriculares BT", price: 30.0, minYear: 2010, maxYear: 2025, icon: "headphones" },
    { name: "Smart TV", price: 500.0, minYear: 2010, maxYear: 2025, icon: "smart_tv" },
    { name: "App Móvil (pago)", price: 2.0, minYear: 2010, maxYear: 2025, icon: "app" },
    { name: "YouTube Premium", price: 12.0, minYear: 2015, maxYear: 2025, icon: "youtube" },
    { name: "Suscripción Twitch", price: 4.0, minYear: 2011, maxYear: 2025, icon: "twitch" },
    { name: "ChatGPT Plus", price: 23.0, minYear: 2023, maxYear: 2025, icon: "chatgpt" },
    { name: "Cloud Storage", price: 10.0, minYear: 2020, maxYear: 2025, icon: "cloud" },
    { name: "Disney+", price: 9.0, minYear: 2020, maxYear: 2025, icon: "disney" },
    { name: "HBO Max", price: 10.0, minYear: 2020, maxYear: 2025, icon: "hbo" },
    { name: "Airbnb (noche)", price: 90.0, minYear: 2020, maxYear: 2025, icon: "airbnb" },
    { name: "Discord Nitro", price: 10.0, minYear: 2020, maxYear: 2025, icon: "discord" },
    { name: "Oculus/VR", price: 450.0, minYear: 2020, maxYear: 2025, icon: "vr" },
    { name: "PS5/Xbox X", price: 550.0, minYear: 2020, maxYear: 2025, icon: "ps5" },
    { name: "Zoom Pro", price: 16.0, minYear: 2020, maxYear: 2025, icon: "zoom" },
    { name: "AirPods Pro", price: 279.0, minYear: 2020, maxYear: 2025, icon: "airpods" },
    { name: "Apple Music", price: 11.0, minYear: 2020, maxYear: 2025, icon: "apple_music" },
    { name: "MacBook/Laptop", price: 1200.0, minYear: 2020, maxYear: 2025, icon: "laptop" },
    { name: "OnlyFans (sub)", price: 15.0, minYear: 2020, maxYear: 2025, icon: "onlyfans" },
    { name: "Apple Watch", price: 450.0, minYear: 2020, maxYear: 2025, icon: "apple_watch" },
];

export const INFLATION_ES_CASES: readonly InflationCaseItem[] = [
    {
        title: "Cine de Estreno",
        year: 1970,
        icon: "movie",
        color: "bg-indigo-100 text-indigo-800 border-indigo-200",
        price: "25 pesetas (0,15€)",
        description:
            "En 1970 ibas al cine por lo que hoy te cuesta... <strong>absolutamente nada</strong>. Con 0,15€ hoy en día te dan para una bolsa de plástico en el supermercado",
    },
    {
        title: "Piso en Propiedad",
        year: 1985,
        icon: "house",
        color: "bg-emerald-100 text-emerald-800 border-emerald-200",
        price: "4.000.000 ptas (24.000€)",
        description:
            "Te comprabas una casa entera por lo que hoy cuesta un <strong>coche utilitario básico</strong>. Si vas con 24.000€ a una inmobiliaria hoy, lo único que te alquilan es un trastero",
    },
    {
        title: "Litro de Gasolina",
        year: 1998,
        icon: "fuel",
        color: "bg-rose-100 text-rose-800 border-rose-200",
        price: "100 pesetas (0,60€)",
        description:
            "Echabas un litro de combustible con lo que hoy no te llega ni para <strong>medio café</strong>. Con 60 céntimos hoy, la manguera de la gasolinera ni se desbloquea",
    },
    {
        title: "Carro del Súper",
        year: 2002,
        icon: "cart",
        color: "bg-amber-100 text-amber-800 border-amber-200",
        price: "50€ (Carro Lleno)",
        description:
            "Con 50€ llenabas el carro hasta arriba para toda la semana. Hoy, con ese mismo billete, sales con <strong>dos bolsas medio vacías</strong> y cara de no saber dónde se ha ido el dinero",
    },
    {
        title: "Caña de Cerveza",
        year: 1985,
        icon: "beer",
        color: "bg-yellow-100 text-yellow-800 border-yellow-200",
        price: "25 pesetas (0,15€)",
        description:
            "Con lo que hoy te cuesta una caña mal tirada en una terraza, en el 85 invitabas a <strong>toda la cuadrilla</strong> y te sobraba para el taxi de vuelta a casa",
    },
    {
        title: "Menú del Día",
        year: 1995,
        icon: "restaurant",
        color: "bg-orange-100 text-orange-800 border-orange-200",
        price: "800 pesetas (4,80€)",
        description:
            "Primer plato, segundo, postre, pan, vino y café. Hoy por 4,80€ te dan los buenos días y <strong>un vaso de agua del grifo</strong> si el camarero está de buenas",
    },
    {
        title: "Entrada Concierto",
        year: 1990,
        icon: "concert",
        color: "bg-purple-100 text-purple-800 border-purple-200",
        price: "1.500 pesetas (9€)",
        description:
            "Ver a los grandes del rock costaba menos que dos copas. Hoy, para ver a un artista medio decente desde la última fila, tienes que pedir un <strong>crédito rápido</strong>",
    },
    {
        title: "Barra de Pan",
        year: 1980,
        icon: "bread",
        color: "bg-stone-100 text-stone-800 border-stone-200",
        price: "12 pesetas (0,07€)",
        description:
            'Ibas a por el pan con una moneda que hoy tirarías a la basura. Hoy el pan "artesano" (congelado) cuesta <strong>20 veces más</strong> y dura 20 veces menos tierno',
    },
    {
        title: "Billete de Metro",
        year: 1998,
        icon: "train",
        color: "bg-blue-100 text-blue-800 border-blue-200",
        price: "130 pesetas (0,78€)",
        description:
            "Cruzabas Madrid entero por céntimos. Hoy el transporte público tiene precio de <strong>viaje interplanetario</strong>, y encima vas igual de apretado que entonces",
    },
    {
        title: "Alquiler Centro",
        year: 1999,
        icon: "key",
        color: "bg-teal-100 text-teal-800 border-teal-200",
        price: "40.000 ptas (240€)",
        description:
            "Vivías en el centro por lo que hoy te cuesta la comunidad de vecinos. Ahora por 240€ no alquilas ni una <strong>plaza de garaje</strong> en la periferia",
    },
    {
        title: "Matrícula Uni",
        year: 1995,
        icon: "school",
        color: "bg-cyan-100 text-cyan-800 border-cyan-200",
        price: "60.000 ptas (360€)",
        description:
            "Un año entero de carrera costaba lo que hoy te gastas solo en los libros. Ahora estudiar es un <strong>lujo asiático</strong>, y encima sales directo a la cola del paro",
    },
    {
        title: "Kilo de Patatas",
        year: 1982,
        icon: "basket",
        color: "bg-lime-100 text-lime-800 border-lime-200",
        price: "15 pesetas (0,09€)",
        description:
            "La base de la alimentación costaba céntimos. Hoy hacer una tortilla de patatas es un acto de <strong>ostentación económica</strong> digno de la realeza europea",
    },
    {
        title: "Copa en Discoteca",
        year: 1992,
        icon: "cocktail",
        color: "bg-fuchsia-100 text-fuchsia-800 border-fuchsia-200",
        price: "500 pesetas (3€)",
        description:
            "Salías de fiesta con 2.000 pesetas y eras el rey de la pista. Hoy con 3€ no te dejan ni <strong>oler los hielos</strong> en la barra de un bar de barrio",
    },
    {
        title: "Periódico",
        year: 1988,
        icon: "newspaper",
        color: "bg-gray-100 text-gray-800 border-gray-200",
        price: "50 pesetas (0,30€)",
        description:
            "Informarse costaba una moneda. Hoy el papel es un artículo de <strong>lujo vintage</strong>, y las noticias... bueno, las noticias siguen siendo igual de deprimentes",
    },
    {
        title: "Bolsa de Chuches",
        year: 1990,
        icon: "candy",
        color: "bg-pink-100 text-pink-800 border-pink-200",
        price: "5 pesetas (0,03€)",
        description:
            "Con un duro eras la persona más feliz del barrio. Hoy entras a una tienda de golosinas con 5 céntimos y llaman a seguridad por <strong>insulto a la autoridad</strong>",
    },
    {
        title: "Café en Bar",
        year: 1985,
        icon: "coffee",
        color: "bg-amber-100 text-amber-800 border-amber-200",
        price: "40 pesetas (0,24€)",
        description:
            "Te tomabas un café caliente y bien servido. Hoy por 24 céntimos no te dan ni el <strong>azucarillo</strong> para el café que te haces tú mismo en casa",
    },
    {
        title: "Videojuego Nuevo",
        year: 1998,
        icon: "game",
        color: "bg-violet-100 text-violet-800 border-violet-200",
        price: "8.990 ptas (54€)",
        description:
            "Un juegazo de PS1 costaba 50€. Hoy, la edición estándar digital te sale por 80€ y luego te piden otros 40€ por el <strong>pase de temporada</strong>",
    },
    {
        title: "Paquete Tabaco",
        year: 1990,
        icon: "cigarette",
        color: "bg-red-100 text-red-800 border-red-200",
        price: "125 pesetas (0,75€)",
        description:
            "Fumar era un vicio barato. Hoy, con lo que cuesta un paquete, podrías estar pagando la letra de un <strong>coche pequeño</strong> (de segunda mano, claro)",
    },
    {
        title: "Helado Frigo",
        year: 1995,
        icon: "icecream",
        color: "bg-sky-100 text-sky-800 border-sky-200",
        price: "75 pesetas (0,45€)",
        description:
            "Te comías un Calippo por menos de medio euro. Hoy vas al chiringuito y por un helado te piden la <strong>hipoteca de la casa</strong>",
    },
    {
        title: "Revista Hobby",
        year: 1997,
        icon: "magazine",
        color: "bg-green-100 text-green-800 border-green-200",
        price: "395 pesetas (2,37€)",
        description:
            "Te enterabas de todos los trucos y noticias por dos euros. Hoy, por ese precio, no te dejan ni <strong>leer los titulares</strong> en las webs de suscripción",
    },
    {
        title: "Hora de Ciber",
        year: 2000,
        icon: "computer",
        color: "bg-slate-100 text-slate-800 border-slate-200",
        price: "200 pesetas (1,20€)",
        description:
            "Te conectabas al Messenger y jugabas al Counter por un euro. Hoy, el café del Starbucks donde te conectas al WiFi te cuesta el <strong>triple</strong>",
    },
    {
        title: "Chicle Boomer",
        year: 1995,
        icon: "gum",
        color: "bg-rose-50 text-rose-800 border-rose-200",
        price: "5 pesetas (0,03€)",
        description:
            "El chicle kilométrico costaba un duro. Hoy, por 5 céntimos, no te dan ni el <strong>papel del envoltorio</strong> para tirarlo a la basura",
    },
    {
        title: "Entrada Fútbol",
        year: 1988,
        icon: "football",
        color: "bg-lime-50 text-lime-800 border-lime-200",
        price: "1.000 ptas (6€)",
        description:
            "Ibas al estadio a ver a tu equipo por 6 euros. Hoy, la entrada más barata cuesta más que la <strong>camiseta oficial</strong> (que también es carísima)",
    },
    {
        title: "Botellín Agua",
        year: 1992,
        icon: "water",
        color: "bg-cyan-50 text-cyan-800 border-cyan-200",
        price: "50 pesetas (0,30€)",
        description:
            "El agua costaba lo que vale: poco. Hoy en un aeropuerto te cobran el agua a precio de <strong>sangre de unicornio</strong>",
    },
    {
        title: "Llamada Cabina",
        year: 1990,
        icon: "phone",
        color: "bg-teal-50 text-teal-800 border-teal-200",
        price: "15 pesetas (0,09€)",
        description:
            "Llamabas a casa para que te recogieran por 15 pesetas. Hoy, el establecimiento de llamada te cuesta más que <strong>toda la conversación</strong> de entonces",
    },
    {
        title: "Coche Utilitario",
        year: 1985,
        icon: "car",
        color: "bg-zinc-100 text-zinc-800 border-zinc-200",
        price: "750.000 ptas (4.500€)",
        description:
            "Estrenabas coche por menos de 5.000€. Hoy, por ese precio, te compras un <strong>patinete eléctrico</strong> de gama media-alta",
    },
    {
        title: "Sello Correos",
        year: 1980,
        icon: "mail",
        color: "bg-yellow-50 text-yellow-800 border-yellow-200",
        price: "12 pesetas (0,07€)",
        description:
            "Enviar una carta costaba céntimos. Hoy enviar un burofax te cuesta lo mismo que invitar a cenar al <strong>cartero</strong>",
    },
    {
        title: "Cinta Cassette",
        year: 1988,
        icon: "cassette",
        color: "bg-orange-50 text-orange-800 border-orange-200",
        price: "800 pesetas (4,80€)",
        description:
            'Te comprabas el último disco de Mecano por menos de 5€. Hoy el vinilo "edición coleccionista" te cuesta medio <strong>riñón</strong>',
    },
    {
        title: "Pila Alcalina",
        year: 1995,
        icon: "battery",
        color: "bg-emerald-50 text-emerald-800 border-emerald-200",
        price: "100 pesetas (0,60€)",
        description:
            "Alimentabas tu Game Boy por 60 céntimos. Hoy un paquete de pilas cuesta más que la propia <strong>consola</strong> (de segunda mano)",
    },
    {
        title: "SMS",
        year: 2000,
        icon: "sms",
        color: "bg-blue-50 text-blue-800 border-blue-200",
        price: "25 pesetas (0,15€)",
        description:
            'Mandabas un "tk" para ahorrar caracteres. Hoy tienes WhatsApp gratis, pero pagas con tu <strong>alma y tus datos</strong>',
    },
];

export const INFLATION_ES_HIDDEN_TYPES: readonly InflationHiddenTypeItem[] = [
    {
        title: "Reduflación (Shrinkflation)",
        badge: "El truco del tamaño",
        icon: "shrink",
        desc: "Te cobran exactamente lo mismo, pero el paquete trae menos cantidad. Es la forma más sutil de subir precios sin que la gente proteste en el supermercado.",
        example:
            "Una tableta de chocolate de 100g pasa a ser de 90g al mismo precio. Has sufrido un 11% de inflación sin enterarte.",
        quote: "Mismo envase, más aire, menos producto.",
    },
    {
        title: "Skimpflation (Degradación de Calidad)",
        badge: "El truco del ingrediente",
        icon: "quality",
        desc: "El tamaño y el precio no cambian, pero reemplazan ingredientes o reducen la calidad del servicio para recortar costes de producción.",
        example:
            "Tu aceite de oliva virgen extra en un plato preparado pasa a ser aceite de girasol, o la aerolínea elimina la maleta de mano incluida.",
        quote: "Mismo precio, pero peor experiencia.",
    },
    {
        title: "Greedflation (Inflación por Beneficios)",
        badge: "El margen empresarial",
        icon: "profit",
        desc: "Las empresas aumentan los precios por encima del incremento de sus costes reales aprovechando la narrativa general de 'todo sube' para engordar sus márgenes.",
        example:
            "Los costes de transporte bajan un 20%, pero los precios en estantería se mantienen o siguen subiendo 'por la crisis'.",
        quote: "Excusas macroeconómicas, beneficios récord.",
    },
    {
        title: "Inflación Subyacente",
        badge: "El núcleo duro",
        icon: "core",
        desc: "Mide la variación de los precios excluyendo los alimentos no elaborados y los productos energéticos por ser excesivamente volátiles.",
        example:
            "La inflación general baja porque la gasolina cae, pero la subyacente sigue en un 5% porque la cesta básica no da tregua.",
        quote: "La temperatura real del paciente económico.",
    },
];

export const INFLATION_ES_SOURCES: readonly InflationSourceItem[] = [
    {
        type: "Oficial",
        name: "Índice de Precios de Consumo (IPC)",
        org: "INE (Instituto Nacional de Estadística)",
        freq: "Mensual",
        desc: "La medida oficial de la inflación en España. Evalúa la evolución de los precios de una cesta de bienes y servicios representativa del consumo de los hogares.",
        bestFor: "Datos oficiales históricos y variaciones interanuales.",
        linkText: "Consultar datos del INE",
        url: "https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736176802&menu=ultiDatos&idp=1254735976607",
    },
    {
        type: "Internacional",
        name: "Harmonised Index of Consumer Prices (HICP)",
        org: "Eurostat",
        freq: "Mensual",
        desc: "Estadística homologada para comparar la inflación entre todos los países de la Unión Europea bajo la misma metodología.",
        bestFor: "Comparativas internacionales dentro de la Eurozona.",
        linkText: "Ver datos en Eurostat",
        url: "https://ec.europa.eu/eurostat/web/hicp",
    },
    {
        type: "Banco Central",
        name: "Estadísticas de Inflación y Tipo de Cambio",
        org: "Banco de España / BCE",
        freq: "Continua",
        desc: "Análisis del impacto monetario, tipos de interés y proyecciones macroeconómicas de la inflación a medio y largo plazo.",
        bestFor: "Informes de estabilidad financiera y decisiones del BCE.",
        linkText: "Acceder al Banco de España",
        url: "https://www.bde.es/bde/es/secciones/informes/",
    },
];

export const INFLATION_ES_EFFORT_COMPARISONS: readonly InflationEffortItem[] = [
    {
        title: "Piso en Propiedad",
        shareTitle: "un piso",
        icon: "house",
        then: { year: 1985, effort: "3 años", effortValue: 30, salary: "9.000€", cost: "27.000€" },
        now: {
            year: 2025,
            effort: "11.5 años",
            effortValue: 100,
            salary: "25.000€",
            cost: "287.000€",
        },
    },
    {
        title: "Coche Nuevo",
        shareTitle: "un coche nuevo",
        icon: "car",
        then: { year: 1985, effort: "6 meses", effortValue: 25, salary: "9.000€", cost: "4.500€" },
        now: {
            year: 2025,
            effort: "11.5 meses",
            effortValue: 48,
            salary: "25.000€",
            cost: "24.000€",
        },
    },
    {
        title: "Entrada de Cine",
        shareTitle: "una entrada de cine",
        icon: "movie",
        then: { year: 1980, effort: "20 min", effortValue: 15, salary: "4€/h", cost: "1,50€" },
        now: { year: 2025, effort: "45 min", effortValue: 35, salary: "12€/h", cost: "9,00€" },
    },
    {
        title: "Litro de Aceite",
        shareTitle: "un litro de aceite",
        icon: "bottle",
        then: { year: 2000, effort: "12 min", effortValue: 10, salary: "6€/h", cost: "1,20€" },
        now: { year: 2025, effort: "50 min", effortValue: 45, salary: "12€/h", cost: "10,00€" },
    },
    {
        title: "Alquiler Mensual",
        shareTitle: "un mes de alquiler",
        icon: "key",
        then: { year: 1995, effort: "5 días", effortValue: 20, salary: "14.000€", cost: "250€" },
        now: { year: 2025, effort: "14 días", effortValue: 65, salary: "25.000€", cost: "950€" },
    },
    {
        title: "Abono Festival",
        shareTitle: "un abono de festival",
        icon: "ticket",
        then: { year: 1998, effort: "6 horas", effortValue: 8, salary: "5€/h", cost: "30€" },
        now: { year: 2025, effort: "2.5 días", effortValue: 35, salary: "12€/h", cost: "240€" },
    },
    {
        title: "Carro Semanal",
        shareTitle: "la compra semanal",
        icon: "cart",
        then: { year: 2000, effort: "4 horas", effortValue: 10, salary: "6€/h", cost: "24€" },
        now: { year: 2025, effort: "1.5 días", effortValue: 25, salary: "12€/h", cost: "120€" },
    },
    {
        title: "Factura Luz/Gas",
        shareTitle: "la factura de la luz",
        icon: "bolt",
        then: { year: 1990, effort: "3 horas", effortValue: 5, salary: "4€/h", cost: "12€" },
        now: { year: 2025, effort: "10 horas", effortValue: 18, salary: "12€/h", cost: "120€" },
    },
];

export const INFLATION_ES_TEXTS: InflationLocaleData = {
    cardTitle: "LA INFLACIÓN",
    cardSubtitle: "El Impuesto Invisible",
    cardDescription: "Visualiza cómo el valor del dinero ha cambiado a lo largo del tiempo.",
    title: "Inflación - La memoria es frágil, pero los datos permanecen",
    description:
        "¿Qué es la inflación? Visualiza cómo el valor del dinero ha cambiado a lo largo del tiempo.",
    headerSubtitle: "¿Qué podías comprar con 100€?",
    sliderTitle: "Mueve el deslizador para viajar en el tiempo",
    sliderYearPrefix: "Año",
    sliderValuePrefix: "100€ de entonces equivalen a",
    billTitle: "BILLETE DE 100€",
    billYearLabel: "Año",
    billValueLabel: "Valor equivalente hoy",
    casesTitle: "Desde la barra del bar te digo...",
    casesSubtitle: "(el cuñado que a veces tiene razón)",
    shareText: "Compartir",
    shareButton: "Compartir caso",
    infoTitle: "¿Qué es realmente la inflación?",
    infoSubtitle1: 'El Efecto "Abuelo Cebolleta"',
    infoP1: "La inflación es la pérdida progresiva del poder adquisitivo de la moneda. O dicho de otra forma: con el mismo billete de 50€, año tras año compras menos cosas.",
    infoSubtitle2: "¿Por qué debería importarme?",
    infoP2: "No es solo que los precios suban, es que el dinero vale menos. Cuando la masa monetaria aumenta o los costes de producción se disparan, cada unidad monetaria en circulación pierde una pequeña fracción de su capacidad de intercambio.",
    infoSubtitle3: "Guardar el dinero bajo el colchón",
    infoP3: "Guardar el dinero bajo el colchón no es una estrategia neutra: es una pérdida garantizada constante.",
    infoScienceTitle: "La Ciencia detrás de la Magia",
    infoScienceText:
        'Esta página utiliza datos históricos reales del <strong>IPC (Índice de Precios al Consumo)</strong> para ajustar el valor de una "cesta de la compra" simulada. No es perfecta, pero es una aproximación dolorosamente precisa de cómo se ha erosionado nuestra capacidad de compra.',
    disclaimerTitle: "Disclaimer",
    disclaimerText:
        'Es fácil caer en la trampa de la nostalgia y pensar que todo era maravilloso. Sí, los precios eran ridículos, pero <strong class="text-highlight-white">los sueldos también lo eran</strong>. Mi abuelo no ganaba 2.000€ al mes; ganaba lo justo para vivir.',
    disclaimerEffortTitle: "El Esfuerzo",
    disclaimerEffortP1:
        'Sin embargo, aquí es donde entra la variable clave: <strong class="text-highlight-green">El Esfuerzo</strong>. Aunque ganamos más "números", la proporción de nuestro sueldo que debemos destinar a cosas básicas (especialmente vivienda) se ha disparado.',
    disclaimerEffortP2:
        'Hemos ganado en tecnología (hoy tienes un superordenador en el bolsillo por "poco" dinero), pero hemos perdido dramáticamente en activos fundamentales.',
    disclaimerProductivityTitle: "La Trampa de la Productividad",
    disclaimerProductivityText:
        'Lo más frustrante de estos datos es que hoy somos infinitamente más productivos que hace 40 años. La tecnología nos permite hacer en una hora lo que antes llevaba un día. Y sin embargo, esa productividad extra no se ha traducido en "necesitar trabajar menos para vivir", sino en "necesitar trabajar más para mantener el mismo nivel de vida".',
    effortTitle: "Tu Realidad",
    effortSubtitle: "Ajusta el salario para ver tu esfuerzo real",
    effortPerYear: "/año",
    effortUseAverageBtn: "Usar media española",
    effortGoodEra: 'La "Buena" Época',
    effortHarshReality: "La Cruda Realidad",
    effortWorkSuffix: "de trabajo",
    effortSalaryLabel: "Sueldo",
    effortCostLabel: "Coste",
    effortFooterNote: "* Datos aproximados ajustados a salarios medios",
    illusionTitle: "La Ilusión Monetaria",
    illusionSubtitle: "Creer que ganas más cuando en realidad compras lo mismo (o menos).",
    illusionNominalLabel: "Sueldo Nominal",
    illusionNominalDesc: 'Tu jefe te dice "¡Te hemos subido el sueldo a 1.780€!".',
    illusionRealLabel: "Poder Adquisitivo Real",
    illusionRealDesc: "Vas al súper y descubres que compras menos cosas que cuando ganabas 1.000€.",
    illusionLegendNominal: "Lo que ingresas",
    illusionLegendReal: "Para lo que te da",
    illusionExplanation:
        "Si tu sueldo sube un 3% pero la inflación es del 5%, en términos reales estás cobrando un 2% menos que el año anterior.",
    hiddenTypesTitle: "Las Trampas de la Inflación",
    hiddenTypesSubtitle: "Estrategias sutiles donde el precio no es el único que cambia.",
    sourcesTitle: "Fuentes y Referencias",
    sourcesSubtitle:
        '"La memoria es frágil, pero los datos permanecen." — Recopilación de las fuentes utilizadas para los cálculos y comparativas.',
    sourcesBadge: "Documentación",
    reportTitle: "Anexo I: Informe Macroeconómico",
    reportSubtitle:
        "Análisis comparativo de la evolución de precios y poder adquisitivo en España (1980-2025).",
    table1Title: "Evolución del Coste de la Vida",
    table1Ref: "Ref: INE / Hemeroteca / Ministerios",
    thConcept: "Concepto",
    thYear: "Año",
    thHistPrice: "Precio Histórico",
    thPrice2025: "Precio 2025",
    thVar: "Var. %",
    thSource: "Fuente",
    table2Title: "Evolución Salarial",
    thAvgSalary: "Salario Medio Anual",
    thSmiMonthly: "SMI Mensual 14p",
    thSmiTotal: "SMI Anual Total",
    noteTitle: "Nota Metodológica",
    noteP1: "Los datos presentados en este informe han sido normalizados a Euros corrientes para facilitar la comparación, utilizando el tipo de cambio fijo (1€ = 166,386 ptas).",
    noteP2: 'Importante: La columna "Var. %" refleja el incremento nominal del precio. Para entender la pérdida real de poder adquisitivo, se debe contrastar con la evolución salarial (Tabla A.2). Mientras que algunos bienes básicos han subido un 900%, los salarios medios apenas se han triplicado en el mismo periodo.',
    noteSources:
        "Fuentes: INE (Series históricas IPC), Banco de España (Boletines estadísticos), Ministerio de Vivienda (Series de precios m²), BOE (Decretos SMI) y Hemerotecas digitales (ABC, La Vanguardia, El País).",
    reportTable1Rows: [
        {
            concept: "Vivienda (Piso 80m²)",
            year: 1985,
            priceHist: "27.000€ (4.5M ptas)",
            price2025: "287.000€",
            varPercent: "+963%",
            isPositive: false,
            sourceName: "M. Vivienda",
            sourceUrl: "https://www.boe.es/buscar/doc.php?id=BOE-A-2024-2088",
        },
        {
            concept: "Salario Mínimo (SMI)",
            year: 1980,
            priceHist: "154€ (25.620 ptas)",
            price2025: "1.134€",
            varPercent: "+636%",
            isPositive: true,
            sourceName: "BOE (SMI '24)",
            sourceUrl: "https://www.boe.es/buscar/doc.php?id=BOE-A-2024-2088",
        },
        {
            concept: "Pan (Barra 250g)",
            year: 1985,
            priceHist: "0,12€ (20 ptas)",
            price2025: "1,20€",
            varPercent: "+900%",
            isPositive: false,
            sourceName: "INE (IPC)",
            sourceUrl:
                "https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736176802&menu=ultiDatos&idp=1254735976607",
        },
        {
            concept: "Gasolina (Litro)",
            year: 1980,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,65€",
            varPercent: "+511%",
            isPositive: false,
            sourceName: "M. Energía",
            sourceUrl:
                "https://www.miteco.gob.es/es/energia/hidrocarburos-nuevos-combustibles/petroleo/informes/informes-anuales.html",
        },
        {
            concept: "Cine (Entrada)",
            year: 1980,
            priceHist: "1,20€ (200 ptas)",
            price2025: "9,00€",
            varPercent: "+650%",
            isPositive: false,
            sourceName: "Hemeroteca",
            sourceTitle: "Hemeroteca ABC / La Vanguardia",
        },
        {
            concept: "Coche Utilitario",
            year: 1985,
            priceHist: "4.500€ (750k ptas)",
            price2025: "24.000€",
            varPercent: "+433%",
            isPositive: false,
            sourceName: "Revistas",
            sourceTitle: "Revistas Motor Clásico / Autopista",
        },
        {
            concept: "Periódico",
            year: 1985,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,80€",
            varPercent: "+566%",
            isPositive: false,
            sourceName: "Hemeroteca",
            sourceTitle: "Hemeroteca ABC / La Vanguardia",
        },
        {
            concept: "Aceite Oliva (1L)",
            year: 2000,
            priceHist: "1,20€ (200 ptas)",
            price2025: "10,00€",
            varPercent: "+733%",
            isPositive: false,
            sourceName: "INE (IPC)",
            sourceUrl:
                "https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736176802&menu=ultiDatos&idp=1254735976607",
        },
        {
            concept: "Café (Bar)",
            year: 1990,
            priceHist: "0,48€ (80 ptas)",
            price2025: "1,50€",
            varPercent: "+212%",
            isPositive: false,
            sourceName: "Hostelería",
            sourceTitle: "Asociaciones de Hostelería",
        },
    ],
    hiddenTypesCards: [
        {
            badge: "MENOS POR LO MISMO",
            title: "Reduflación",
            graphicLabel1: "PATATAS",
            graphicLabel2: "NUEVO FORMATO",
            graphicLegend1: "243g (Antes 295g)",
            graphicLegend2: "Precio: +15%",
            tagline: '"Te venden aire a precio de comida."',
            description:
                "El caso de las patatas fritas es de libro: bajaron de 295g a 275g, y luego a 243g, mientras subían el precio. Las asociaciones de consumidores han denunciado reducciones de hasta el 17% en productos de primeras marcas.",
            sourceText: "Fuente: Estudio FACUA (12 productos detectados)",
            shareText:
                "¿Te has dado cuenta de que las bolsas de patatas son 60% aire? Se llama Reduflación: te venden aire a precio de comida.",
        },
        {
            badge: "PEOR POR LO MISMO",
            title: "Cutreflación",
            graphicLabel1: "RECETA MEJORADA",
            graphicLabel2: "INGREDIENTES:",
            graphicRemoved1: "Aceite de Girasol",
            graphicAdded1: "Grasa de Palma/Mix",
            graphicRemoved2: "Mantequilla",
            graphicAdded2: "Aceites Vegetales",
            tagline: '"Te cambian los ingredientes buenos por sucedáneos baratos."',
            description:
                'Tras la crisis de Ucrania, muchas marcas sustituyeron el aceite de girasol por aceites de palma o mezclas vegetales en mayonesas, galletas y salsas. El problema: la etiqueta "Sabor Tradicional" se mantuvo, pero la calidad nutricional cayó en picado.',
            sourceText: "Fuente: NPR (Origen del término Skimpflation)",
            shareText:
                "¿La comida te sabe peor pero cuesta igual? Se llama Cutreflación: cambian ingredientes buenos por basura barata.",
        },
        {
            badge: "LA HUIDA HACIA ARRIBA",
            title: "Premiunización",
            graphicLabel1: "Platinum",
            graphicLabel2: "ULTRA PRO",
            graphicLegend1: "12.99€",
            graphicLegend2: "¡AGOTADO!",
            graphicRemoved1: "Básico",
            graphicAdded1: "2.99€",
            tagline: '"Eliminan la gama básica para obligarte a comprar la gama de lujo."',
            description:
                'La fiebre "High Protein" ha desplazado a los yogures básicos. El detergente en polvo (más barato y eficiente) desaparece de los lineales para dejar sitio a las "Cápsulas 3 en 1" que cuestan el triple por lavado.',
            sourceText: "Fuente: CESCE (Estrategia de Premiumización)",
            shareText:
                "¿Ya no encuentras la versión barata de nada? Se llama Premiunización: eliminan lo básico para obligarte a pagar el lujo.",
        },
        {
            badge: "TÚ ERES EL EMPLEADO",
            title: "Inflación Sombra",
            graphicLabel1: "ERROR: ESPERE ASISTENCIA",
            graphicLabel2: "Tu Sueldo: 0€/hora",
            tagline: '"Trabajas gratis para el supermercado y encima pagas lo mismo."',
            description:
                "La proliferación de cajas de autopago transfiere el coste laboral al cliente. Estudios de mercado indican que el ahorro en personal (hasta un 40% en costes de caja) no se repercute en una bajada de precios para el consumidor.",
            sourceText: "Fuente: The Guardian (Shadow Work & Automation)",
            shareText:
                "¿Pagas lo mismo y encima tienes que escanear tu propia compra? Se llama Inflación Sombra: trabajas gratis para la tienda.",
        },
    ],
    personalNoteTitle: "Nota del Autor",
    personalNoteText:
        '<p>"Esta página nace de la pura curiosidad. Intuía qué era la inflación, pero me costaba visualizar su impacto real a lo largo de las décadas."</p><br/><p>"He creado esta comparativa como un ejercicio para entenderlo mejor, para ver con mis propios ojos cómo ha cambiado nuestro poder adquisitivo. Si encuentras algún dato impreciso, te pido disculpas y estaré encantado de corregirlo; este es un proyecto de aprendizaje y divulgación que he querido compartir contigo."</p>',
    madeForFun: "Hecho por diversión",
    items: INFLATION_ES_ITEMS,
    cases: INFLATION_ES_CASES,
    effortComparisons: INFLATION_ES_EFFORT_COMPARISONS,
};
