import type { InflationLocaleData } from "../types";
import { INFLATION_EN_TEXTS } from "./en";

export const INFLATION_FR_TEXTS: InflationLocaleData = {
    ...INFLATION_EN_TEXTS,
    cardTitle: "INFLATION",
    cardSubtitle: "L'impôt invisible",
    cardDescription: "Visualisez comment la valeur de l'argent a changé au fil du temps.",
    title: "Inflation - La mémoire est fragile, mais les données restent",
    description:
        "Qu'est-ce que l'inflation ? Visualisez comment la valeur de l'argent a changé au fil du temps.",
    headerSubtitle: "Visualisez l'impact réel de l'inflation sur votre pouvoir d'achat.",
    sliderTitle: "Déplacez le curseur pour voyager dans le temps",
    sliderYearPrefix: "Année",
    sliderValuePrefix: "100€ d'alors équivalent à",
    billTitle: "BILLET DE 100€",
    billYearLabel: "Année",
    billValueLabel: "Valeur équivalente aujourd'hui",
    casesTitle: "Nostalgie vs Réalité",
    casesSubtitle: "Faites glisser pour voir des exemples réels de changement de prix",
    shareText: "Partager",
    shareButton: "Partager cas",
    infoTitle: "Qu'est-ce que l'inflation réellement ?",
    infoP1: "L'inflation est la perte progressive du pouvoir d'achat de la monnaie.",
    infoP2: "Ce n'est pas seulement que les prix augmentent, c'est que l'argent vaut moins.",
    infoP3: "Garder de l'argent sous le matelas est une perte garantie constante.",
    illusionTitle: "L'Illusion Monétaire",
    illusionSubtitle: "Croire que vous gagnez plus quand vous achetez la même chose.",
    illusionNominalLabel: "Salaire Nominal",
    illusionRealLabel: "Pouvoir d'Achat Réel",
    illusionExplanation:
        "Si votre salaire augmente de 3% mais l'inflation est de 5%, vous gagnez 2% de moins.",
    hiddenTypesTitle: "Les Pièges de l'Inflation",
    hiddenTypesSubtitle: "Des stratégies subtiles où le prix n'est pas la seule chose qui change.",
    sourcesTitle: "Sources Officieuses et Données",
    sourcesSubtitle: "Institutions qui mesurent l'impact réel sur l'économie.",
    personalNoteTitle: "Note de l'Auteur",
    personalNoteText: "L'inflation est une force silencieuse qui façonne l'avenir.",
    items: [
        { name: "Pain", price: 1.2, minYear: 1950, maxYear: 2025, icon: "bread" },
        { name: "Lait", price: 1.0, minYear: 1950, maxYear: 2025, icon: "milk" },
        { name: "Café", price: 1.6, minYear: 1950, maxYear: 2025, icon: "coffee" },
        { name: "Bière", price: 3.0, minYear: 1950, maxYear: 2025, icon: "beer" },
        { name: "Livre", price: 22.0, minYear: 1950, maxYear: 2025, icon: "book" },
        { name: "T-Shirt", price: 20.0, minYear: 1950, maxYear: 2025, icon: "shirt" },
        { name: "Chaussures", price: 90.0, minYear: 1950, maxYear: 2025, icon: "shoe" },
        { name: "Bijou", price: 500.0, minYear: 1950, maxYear: 2025, icon: "diamond" },
        { name: "Voiture", price: 22000.0, minYear: 1950, maxYear: 2025, icon: "car" },
        { name: "Appartement", price: 250000.0, minYear: 1950, maxYear: 2025, icon: "house" },
        {
            name: "Dîner au Restaurant",
            price: 45.0,
            minYear: 1950,
            maxYear: 2025,
            icon: "restaurant",
        },
        { name: "Journal", price: 2.0, minYear: 1950, maxYear: 2025, icon: "newspaper" },
        { name: "Timbre Postal", price: 1.0, minYear: 1950, maxYear: 2025, icon: "mail" },
        { name: "Place de Cinéma", price: 9.5, minYear: 1950, maxYear: 2025, icon: "movie" },
        { name: "Disque Vinyle", price: 30.0, minYear: 1950, maxYear: 2025, icon: "vinyl" },
        { name: "Billet de Concert", price: 60.0, minYear: 1950, maxYear: 2025, icon: "concert" },
        { name: "Télé Noir et Blanc", price: 800.0, minYear: 1950, maxYear: 1980, icon: "tv_old" },
        { name: "Montre", price: 80.0, minYear: 1950, maxYear: 2025, icon: "watch" },
        { name: "Place de Théâtre", price: 25.0, minYear: 1950, maxYear: 2025, icon: "theater" },
        { name: "Pellicule Photo", price: 12.0, minYear: 1950, maxYear: 2015, icon: "photo_roll" },
        { name: "Appareil Photo", price: 300.0, minYear: 1950, maxYear: 2025, icon: "camera" },
        { name: "Cigarettes", price: 5.0, minYear: 1950, maxYear: 2025, icon: "cigarette" },
        { name: "Single 45t", price: 8.0, minYear: 1960, maxYear: 1995, icon: "single" },
        { name: "Télé Couleur", price: 1200.0, minYear: 1965, maxYear: 2010, icon: "tv_color" },
        { name: "Tourne-disque", price: 150.0, minYear: 1960, maxYear: 2000, icon: "turntable" },
        { name: "Billet de Football", price: 45.0, minYear: 1960, maxYear: 2025, icon: "football" },
        { name: "Menu Burger", price: 11.0, minYear: 1970, maxYear: 2025, icon: "burger" },
        { name: "Pizza", price: 14.0, minYear: 1970, maxYear: 2025, icon: "pizza" },
        { name: "Plein d'Essence", price: 75.0, minYear: 1970, maxYear: 2025, icon: "fuel" },
        { name: "Réveil Digital", price: 20.0, minYear: 1970, maxYear: 2025, icon: "alarm" },
        { name: "Poste de Radio", price: 40.0, minYear: 1970, maxYear: 2000, icon: "radio" },
        { name: "Walkman", price: 60.0, minYear: 1979, maxYear: 2005, icon: "walkman" },
        { name: "Calculatrice", price: 15.0, minYear: 1975, maxYear: 2025, icon: "calculator" },
        { name: "Cassette Audio", price: 10.0, minYear: 1980, maxYear: 2005, icon: "cassette" },
        { name: "Cassette VHS", price: 20.0, minYear: 1980, maxYear: 2010, icon: "vhs" },
        { name: "Location VHS", price: 3.0, minYear: 1985, maxYear: 2010, icon: "vhs_rental" },
        {
            name: "Console 8 bits",
            price: 200.0,
            minYear: 1985,
            maxYear: 2000,
            icon: "console_8bit",
        },
        { name: "Téléphone Fixe", price: 30.0, minYear: 1980, maxYear: 2025, icon: "phone" },
        { name: "Camescope", price: 700.0, minYear: 1985, maxYear: 2010, icon: "videocamera" },
        { name: "Encyclopédie", price: 600.0, minYear: 1980, maxYear: 2005, icon: "encyclopedia" },
        { name: "Disquette", price: 2.0, minYear: 1980, maxYear: 2005, icon: "floppy" },
        { name: "CD Audio", price: 18.0, minYear: 1990, maxYear: 2015, icon: "cd" },
        { name: "Jeu Vidéo", price: 70.0, minYear: 1990, maxYear: 2025, icon: "game" },
        { name: "Ancien Mobile", price: 300.0, minYear: 1995, maxYear: 2010, icon: "mobile" },
        { name: "Ordinateur PC", price: 1200.0, minYear: 1995, maxYear: 2025, icon: "computer" },
        { name: "PlayStation", price: 400.0, minYear: 1995, maxYear: 2025, icon: "playstation" },
        { name: "Game Boy", price: 100.0, minYear: 1990, maxYear: 2010, icon: "gameboy" },
        { name: "Internet Mensuel", price: 40.0, minYear: 1995, maxYear: 2025, icon: "internet" },
        {
            name: "Appareil Photo Numérique",
            price: 250.0,
            minYear: 1995,
            maxYear: 2025,
            icon: "digital_camera",
        },
        {
            name: "Café Starbucks",
            price: 4.5,
            minYear: 1999,
            maxYear: 2025,
            icon: "coffee_premium",
        },
        { name: "Film DVD", price: 15.0, minYear: 2000, maxYear: 2020, icon: "dvd" },
        { name: "iPod", price: 350.0, minYear: 2001, maxYear: 2017, icon: "ipod" },
        { name: "Smartphone", price: 900.0, minYear: 2007, maxYear: 2025, icon: "smartphone" },
        { name: "Tablette", price: 500.0, minYear: 2010, maxYear: 2025, icon: "tablet" },
        { name: "Liseuse Numérique", price: 130.0, minYear: 2008, maxYear: 2025, icon: "ereader" },
        {
            name: "Abonnement Streaming",
            price: 15.0,
            minYear: 2011,
            maxYear: 2025,
            icon: "streaming",
        },
        { name: "Écouteurs Sans Fil", price: 180.0, minYear: 2016, maxYear: 2025, icon: "earbuds" },
        {
            name: "Montre Connectée",
            price: 300.0,
            minYear: 2014,
            maxYear: 2025,
            icon: "smartwatch",
        },
        {
            name: "Trottinette Électrique",
            price: 400.0,
            minYear: 2017,
            maxYear: 2025,
            icon: "scooter",
        },
        {
            name: "Friteuse sans Huile",
            price: 100.0,
            minYear: 2018,
            maxYear: 2025,
            icon: "airfryer",
        },
        { name: "Abonnement IA", price: 22.0, minYear: 2023, maxYear: 2025, icon: "ai_sub" },
    ],
    cases: [
        {
            year: 1970,
            title: "Seat 600",
            price: "390€",
            description: "Le rêve des familles espagnoles coûtait environ 65 000 pesetas.",
            color: "bg-indigo-100 text-indigo-800 border-indigo-200",
            icon: "car",
        },
        {
            year: 1982,
            title: "Billet Mondial Naranjito",
            price: "4,80€",
            description:
                "Un billet officiel pour un match de la Coupe du Monde coûtait 800 pesetas.",
            color: "bg-emerald-100 text-emerald-800 border-emerald-200",
            icon: "ticket",
        },
        {
            year: 1992,
            title: "Peluche Mascotte Curro",
            price: "15€",
            description:
                "Le souvenir emblématique de l'Exposition universelle de Séville coûtait 2 500 pesetas.",
            color: "bg-rose-100 text-rose-800 border-rose-200",
            icon: "toy",
        },
        {
            year: 1995,
            title: "Lancement PlayStation 1",
            price: "360€",
            description: "Arrivée en Europe pour 59 900 pesetas.",
            color: "bg-amber-100 text-amber-800 border-amber-200",
            icon: "game",
        },
        {
            year: 1998,
            title: "Nokia 5110",
            price: "150€",
            description: "Le téléphone indestructible avec Snake coûtait 25 000 pesetas.",
            color: "bg-yellow-100 text-yellow-800 border-yellow-200",
            icon: "mobile",
        },
        {
            year: 2002,
            title: "Premier Café en Euro",
            price: "0,60€",
            description: "Coûtait 100 pesetas au moment précis du passage à l'euro.",
            color: "bg-orange-100 text-orange-800 border-orange-200",
            icon: "coffee",
        },
    ],
};
