import type { InflationLocaleData } from "../types";
import { INFLATION_EN_TEXTS } from "./en";

export const INFLATION_ID_TEXTS: InflationLocaleData = {
    ...INFLATION_EN_TEXTS,
    cardTitle: "Inflasi",
    cardSubtitle: "Apa yang bisa Anda beli dengan 100€ dulu dibanding sekarang?",
    cardDescription:
        "Jelajahi evolusi daya beli melalui perbandingan harga nyata, data gaji, dan catatan sejarah.",
    title: "INFLASI",
    billTitle: "UANG KERTAS 100€",
    billYearLabel: "Tahun",
    billValueLabel: "Nilai setara hari ini",
    casesTitle: "Nostalgia vs Realitas",
    casesSubtitle: "Geser untuk melihat contoh nyata perubahan harga",
    shareButton: "Bagikan",
    infoTitle: "Mengapa 100€ tidak lagi membeli apa yang dulu bisa dibeli?",
    infoP1: "Inflasi adalah kenaikan harga secara umum dan terus-menerus. Seiring waktu, setiap unit mata uang membeli persentase barang atau jasa yang lebih kecil.",
    infoP2: "Kita sering mengingat harga masa lalu dengan nostalgia, tetapi kita lupa bahwa gaji dulu juga jauh lebih rendah.",
    infoP3: "Memahami inflasi membantu Anda membuat keputusan keuangan jangka panjang yang lebih baik dan melindungi daya beli Anda.",
    items: [
        { name: "Roti", price: 1.2, minYear: 1950, maxYear: 2025, icon: "bread" },
        { name: "Susu", price: 1.0, minYear: 1950, maxYear: 2025, icon: "milk" },
        { name: "Kopi", price: 1.6, minYear: 1950, maxYear: 2025, icon: "coffee" },
        { name: "Bir", price: 3.0, minYear: 1950, maxYear: 2025, icon: "beer" },
        { name: "Buku", price: 22.0, minYear: 1950, maxYear: 2025, icon: "book" },
        { name: "Kaos", price: 20.0, minYear: 1950, maxYear: 2025, icon: "shirt" },
        { name: "Sepatu", price: 90.0, minYear: 1950, maxYear: 2025, icon: "shoe" },
        { name: "Perhiasan", price: 500.0, minYear: 1950, maxYear: 2025, icon: "diamond" },
        { name: "Mobil", price: 22000.0, minYear: 1950, maxYear: 2025, icon: "car" },
        { name: "Apartemen", price: 250000.0, minYear: 1950, maxYear: 2025, icon: "house" },
        {
            name: "Makan Malam Restoran",
            price: 45.0,
            minYear: 1950,
            maxYear: 2025,
            icon: "restaurant",
        },
        { name: "Koran", price: 2.0, minYear: 1950, maxYear: 2025, icon: "newspaper" },
        { name: "Prangko Pos", price: 1.0, minYear: 1950, maxYear: 2025, icon: "mail" },
        { name: "Tiket Bioskop", price: 9.5, minYear: 1950, maxYear: 2025, icon: "movie" },
        { name: "Piringan Hitam", price: 30.0, minYear: 1950, maxYear: 2025, icon: "vinyl" },
        { name: "Tiket Konser", price: 60.0, minYear: 1950, maxYear: 2025, icon: "concert" },
        { name: "TV Hitam-Putih", price: 800.0, minYear: 1950, maxYear: 1980, icon: "tv_old" },
        { name: "Jam Tangan", price: 80.0, minYear: 1950, maxYear: 2025, icon: "watch" },
        { name: "Tiket Teater", price: 25.0, minYear: 1950, maxYear: 2025, icon: "theater" },
        { name: "Roll Film", price: 12.0, minYear: 1950, maxYear: 2015, icon: "photo_roll" },
        { name: "Kamera Foto", price: 300.0, minYear: 1950, maxYear: 2025, icon: "camera" },
        { name: "Rokok", price: 5.0, minYear: 1950, maxYear: 2025, icon: "cigarette" },
        { name: "Single 45rpm", price: 8.0, minYear: 1960, maxYear: 1995, icon: "single" },
        { name: "TV Berwarna", price: 1200.0, minYear: 1965, maxYear: 2010, icon: "tv_color" },
        {
            name: "Pemutar Piringan Hitam",
            price: 150.0,
            minYear: 1960,
            maxYear: 2000,
            icon: "turntable",
        },
        { name: "Tiket Sepak Bola", price: 45.0, minYear: 1960, maxYear: 2025, icon: "football" },
        { name: "Paket Burger", price: 11.0, minYear: 1970, maxYear: 2025, icon: "burger" },
        { name: "Pizza", price: 14.0, minYear: 1970, maxYear: 2025, icon: "pizza" },
        { name: "Bensin Penuh", price: 75.0, minYear: 1970, maxYear: 2025, icon: "fuel" },
        { name: "Jam Weker Digital", price: 20.0, minYear: 1970, maxYear: 2025, icon: "alarm" },
        { name: "Radio Transistor", price: 40.0, minYear: 1970, maxYear: 2000, icon: "radio" },
        { name: "Walkman", price: 60.0, minYear: 1979, maxYear: 2005, icon: "walkman" },
        { name: "Kalkulator", price: 15.0, minYear: 1975, maxYear: 2025, icon: "calculator" },
        { name: "Kaset Pita", price: 10.0, minYear: 1980, maxYear: 2005, icon: "cassette" },
        { name: "Kaset VHS", price: 20.0, minYear: 1980, maxYear: 2010, icon: "vhs" },
        { name: "Sewa VHS", price: 3.0, minYear: 1985, maxYear: 2010, icon: "vhs_rental" },
        { name: "Konsol 8-bit", price: 200.0, minYear: 1985, maxYear: 2000, icon: "console_8bit" },
        { name: "Telepon Rumah", price: 30.0, minYear: 1980, maxYear: 2025, icon: "phone" },
        { name: "Handycam", price: 700.0, minYear: 1985, maxYear: 2010, icon: "videocamera" },
        { name: "Ensiklopedia", price: 600.0, minYear: 1980, maxYear: 2005, icon: "encyclopedia" },
        { name: "Disket", price: 2.0, minYear: 1980, maxYear: 2005, icon: "floppy" },
        { name: "CD Audio", price: 18.0, minYear: 1990, maxYear: 2015, icon: "cd" },
        { name: "Game Video", price: 70.0, minYear: 1990, maxYear: 2025, icon: "game" },
        { name: "HP Jadul", price: 300.0, minYear: 1995, maxYear: 2010, icon: "mobile" },
        { name: "Komputer PC", price: 1200.0, minYear: 1995, maxYear: 2025, icon: "computer" },
        { name: "PlayStation", price: 400.0, minYear: 1995, maxYear: 2025, icon: "playstation" },
        { name: "Game Boy", price: 100.0, minYear: 1990, maxYear: 2010, icon: "gameboy" },
        { name: "Internet Bulanan", price: 40.0, minYear: 1995, maxYear: 2025, icon: "internet" },
        {
            name: "Kamera Digital",
            price: 250.0,
            minYear: 1995,
            maxYear: 2025,
            icon: "digital_camera",
        },
        {
            name: "Kopi Starbucks",
            price: 4.5,
            minYear: 1999,
            maxYear: 2025,
            icon: "coffee_premium",
        },
        { name: "Film DVD", price: 15.0, minYear: 2000, maxYear: 2020, icon: "dvd" },
        { name: "iPod", price: 350.0, minYear: 2001, maxYear: 2017, icon: "ipod" },
        { name: "Smartphone", price: 900.0, minYear: 2007, maxYear: 2025, icon: "smartphone" },
        { name: "Tablet", price: 500.0, minYear: 2010, maxYear: 2025, icon: "tablet" },
        { name: "E-Reader", price: 130.0, minYear: 2008, maxYear: 2025, icon: "ereader" },
        {
            name: "Langganan Streaming",
            price: 15.0,
            minYear: 2011,
            maxYear: 2025,
            icon: "streaming",
        },
        { name: "Earphone Nirkabel", price: 180.0, minYear: 2016, maxYear: 2025, icon: "earbuds" },
        { name: "Smartwatch", price: 300.0, minYear: 2014, maxYear: 2025, icon: "smartwatch" },
        { name: "Skuter Listrik", price: 400.0, minYear: 2017, maxYear: 2025, icon: "scooter" },
        { name: "Air Fryer", price: 100.0, minYear: 2018, maxYear: 2025, icon: "airfryer" },
        { name: "Langganan AI", price: 22.0, minYear: 2023, maxYear: 2025, icon: "ai_sub" },
    ],
    cases: [
        {
            year: 1970,
            title: "Seat 600",
            price: "390€",
            description: "Impian keluarga Spanyol berharga sekitar 65.000 peseta.",
            color: "bg-indigo-100 text-indigo-800 border-indigo-200",
            icon: "car",
        },
        {
            year: 1982,
            title: "Tiket Piala Dunia Naranjito",
            price: "4,80€",
            description: "Tiket resmi pertandingan Piala Dunia berharga 800 peseta.",
            color: "bg-emerald-100 text-emerald-800 border-emerald-200",
            icon: "ticket",
        },
        {
            year: 1992,
            title: "Boneka Maskot Curro",
            price: "15€",
            description: "Cinderamata ikonik Expo '92 di Sevilla berharga 2.500 peseta.",
            color: "bg-rose-100 text-rose-800 border-rose-200",
            icon: "toy",
        },
        {
            year: 1995,
            title: "Peluncuran PlayStation 1",
            price: "360€",
            description: "Tiba di Eropa seharga 59.900 peseta.",
            color: "bg-amber-100 text-amber-800 border-amber-200",
            icon: "game",
        },
        {
            year: 1998,
            title: "Nokia 5110",
            price: "150€",
            description: "HP tahan banting dengan game Snake berharga 25.000 peseta.",
            color: "bg-yellow-100 text-yellow-800 border-yellow-200",
            icon: "mobile",
        },
        {
            year: 2002,
            title: "Kopi Euro Pertama",
            price: "0,60€",
            description: "Berharga 100 peseta tepat saat transisi ke euro.",
            color: "bg-orange-100 text-orange-800 border-orange-200",
            icon: "coffee",
        },
    ],
    sourcesTitle: "Sumber Resmi dan Data",
    sourcesSubtitle: "Lembaga yang mengukur dampak nyata terhadap perekonomian.",
    sourcesBadge: "Dokumentasi",
    reportTitle: "Lampiran I: Laporan Makroekonomi",
    reportSubtitle: "Analisis komparatif perkembangan harga dan daya beli di Spanyol (1980-2025).",
    table1Title: "Perkembangan Biaya Hidup",
    table1Ref: "Ref: INE / Arsip Pers / Kementerian",
    thConcept: "Konsep",
    thYear: "Tahun",
    thHistPrice: "Harga Historis",
    thPrice2025: "Harga 2025",
    thVar: "Var. %",
    thSource: "Sumber",
    table2Title: "Perkembangan Gaji",
    thAvgSalary: "Gaji Rata-Rata Tahunan",
    thSmiMonthly: "Gaji Minimum Bulanan (14x)",
    thSmiTotal: "Total Gaji Minimum Tahunan",
    noteTitle: "Catatan Metodologi",
    noteP1: "Data dalam laporan ini dikonversi ke Euro saat ini (1€ = 166.386 ptas).",
    noteP2: 'Penting: Kolom "Var. %" mencerminkan kenaikan harga nominal.',
    noteSources: "Sumber: INE, Bank Spanyol, Kementerian Perumahan dan arsip pers.",
    reportTable1Rows: [
        {
            concept: "Rumah (Apartemen 80m²)",
            year: 1985,
            priceHist: "27.000€ (4,5M ptas)",
            price2025: "287.000€",
            varPercent: "+963%",
            isPositive: false,
            sourceName: "Kementerian Perumahan",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "Gaji Minimum",
            year: 1980,
            priceHist: "154€ (25.620 ptas)",
            price2025: "1.134€",
            varPercent: "+636%",
            isPositive: true,
            sourceName: "BOE",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "Roti (Roti Perancis 250g)",
            year: 1985,
            priceHist: "0,12€ (20 ptas)",
            price2025: "1,20€",
            varPercent: "+900%",
            isPositive: false,
            sourceName: "INE (IHK)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "Bensin (Liter)",
            year: 1980,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,65€",
            varPercent: "+511%",
            isPositive: false,
            sourceName: "Kementerian Energi",
            sourceUrl: "https://www.miteco.gob.es",
        },
        {
            concept: "Tiket Bioskop",
            year: 1980,
            priceHist: "1,20€ (200 ptas)",
            price2025: "9,00€",
            varPercent: "+650%",
            isPositive: false,
            sourceName: "Arsip Pers",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "Mobil Penumpang",
            year: 1985,
            priceHist: "4.500€ (750k ptas)",
            price2025: "24.000€",
            varPercent: "+433%",
            isPositive: false,
            sourceName: "Majalah Otomotif",
            sourceTitle: "Motor Clásico / Autopista",
        },
        {
            concept: "Koran",
            year: 1985,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,80€",
            varPercent: "+566%",
            isPositive: false,
            sourceName: "Arsip Pers",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "Minyak Zaitun (1L)",
            year: 2000,
            priceHist: "1,20€ (200 ptas)",
            price2025: "10,00€",
            varPercent: "+733%",
            isPositive: false,
            sourceName: "INE (IHK)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "Kopi (Kafe)",
            year: 1990,
            priceHist: "0,48€ (80 ptas)",
            price2025: "1,50€",
            varPercent: "+212%",
            isPositive: false,
            sourceName: "Asosiasi Restoran",
            sourceTitle: "Asosiasi Restoran",
        },
    ],
    hiddenTypesCards: [
        {
            badge: "LEBIH SEDIKIT UNTUK HARGA SAMA",
            title: "Shrinkflation",
            graphicLabel1: "KERIPIK",
            graphicLabel2: "FORMAT BARU",
            graphicLegend1: "243g (Sebelumnya 295g)",
            graphicLegend2: "Harga: +15%",
            tagline: '"Mereka menjual udara seharga makanan."',
            description: "Kemasan keripik berkurang dari 295g menjadi 243g saat harga naik.",
            sourceText: "Sumber: Studi FACUA",
            shareText: "Shrinkflation itu nyata!",
        },
        {
            badge: "LEBIH BURUK UNTUK HARGA SAMA",
            title: "Skimpflation",
            graphicLabel1: "RESEP DITINGKATKAN",
            graphicLabel2: "BAHAN-BAHAN:",
            graphicRemoved1: "Minyak Bunga Matahari",
            graphicAdded1: "Minyak Kelapa Sawit/Mix",
            graphicRemoved2: "Mentega",
            graphicAdded2: "Minyak Nabati",
            tagline: '"Mengganti bahan berkualitas dengan bahan murah."',
            description: "Banyak merek mengganti minyak bunga matahari dengan minyak kelapa sawit.",
            sourceText: "Sumber: NPR (Skimpflation)",
            shareText: "Skimpflation menurunkan kualitas!",
        },
        {
            badge: "PELARIAN KE ATAS",
            title: "Premiumisasi",
            graphicLabel1: "Platinum",
            graphicLabel2: "ULTRA PRO",
            graphicLegend1: "12,99€",
            graphicLegend2: "HABIS!",
            graphicRemoved1: "Mendasar",
            graphicAdded1: "2,99€",
            tagline: '"Menghapus varian dasar untuk memaksa membeli varian mewah."',
            description: "Tren produk tinggi protein menggeser yogurt biasa.",
            sourceText: "Sumber: CESCE (Premiumisasi)",
            shareText: "Premiumisasi menghapus produk dasar!",
        },
        {
            badge: "ANDA ADALAH KARYAWAN",
            title: "Inflasi Bayangan",
            graphicLabel1: "ERROR: TUNGGU BANTUAN",
            graphicLabel2: "Gaji Anda: 0€/jam",
            tagline: '"Anda bekerja gratis untuk supermarket dan membayar harga yang sama."',
            description: "Kasir mandiri mengalihkan pekerjaan ke pelanggan tanpa diskon.",
            sourceText: "Sumber: The Guardian (Shadow Work)",
            shareText: "Inflasi bayangan membuat Anda bekerja gratis!",
        },
    ],
};
