import type { InflationLocaleData } from "../types";
import { INFLATION_EN_TEXTS } from "./en";

export const INFLATION_IT_TEXTS: InflationLocaleData = {
    ...INFLATION_EN_TEXTS,
    cardTitle: "L'inflazione",
    cardSubtitle: "Cosa potevi comprare con 100€ prima rispetto ad oggi?",
    cardDescription:
        "Esplora l'evoluzione del potere d'acquisto attraverso confronti reali di prezzi, dati salariali e archivi storici.",
    title: "L'INFLAZIONE",
    billTitle: "BANCONOTA DA 100€",
    billYearLabel: "Anno",
    billValueLabel: "Valore equivalente oggi",
    casesTitle: "Nostalgia vs Realtà",
    casesSubtitle: "Scorri per vedere casi reali di variazione dei prezzi",
    shareButton: "Condividi",
    infoTitle: "Perché 100€ non comprano più quello che compravano una volta?",
    infoP1: "L'inflazione è l'aumento generale e continuo dei prezzi. Con il passare del tempo, ogni unità monetaria acquista una percentuale minore di beni o servizi.",
    infoP2: "Ricordiamo spesso i prezzi del passato con nostalgia, ma dimentichiamo che anche gli stipendi erano molto più bassi.",
    infoP3: "Comprendere l'inflazione ti aiuta a prendere decisioni finanziarie migliori a lungo termine e a proteggere il tuo potere d'acquisto.",
    items: [
        { name: "Pane", price: 1.2, minYear: 1950, maxYear: 2025, icon: "bread" },
        { name: "Latte", price: 1.0, minYear: 1950, maxYear: 2025, icon: "milk" },
        { name: "Caffè", price: 1.6, minYear: 1950, maxYear: 2025, icon: "coffee" },
        { name: "Birra", price: 3.0, minYear: 1950, maxYear: 2025, icon: "beer" },
        { name: "Libro", price: 22.0, minYear: 1950, maxYear: 2025, icon: "book" },
        { name: "Maglietta", price: 20.0, minYear: 1950, maxYear: 2025, icon: "shirt" },
        { name: "Scarpe", price: 90.0, minYear: 1950, maxYear: 2025, icon: "shoe" },
        { name: "Gioiello", price: 500.0, minYear: 1950, maxYear: 2025, icon: "diamond" },
        { name: "Auto", price: 22000.0, minYear: 1950, maxYear: 2025, icon: "car" },
        { name: "Appartamento", price: 250000.0, minYear: 1950, maxYear: 2025, icon: "house" },
        {
            name: "Cena al Ristorante",
            price: 45.0,
            minYear: 1950,
            maxYear: 2025,
            icon: "restaurant",
        },
        { name: "Giornale", price: 2.0, minYear: 1950, maxYear: 2025, icon: "newspaper" },
        { name: "Francobollo", price: 1.0, minYear: 1950, maxYear: 2025, icon: "mail" },
        { name: "Biglietto Cinema", price: 9.5, minYear: 1950, maxYear: 2025, icon: "movie" },
        { name: "Disco in Vinile", price: 30.0, minYear: 1950, maxYear: 2025, icon: "vinyl" },
        { name: "Biglietto Concerto", price: 60.0, minYear: 1950, maxYear: 2025, icon: "concert" },
        { name: "TV Bianco e Nero", price: 800.0, minYear: 1950, maxYear: 1980, icon: "tv_old" },
        { name: "Orologio da Polso", price: 80.0, minYear: 1950, maxYear: 2025, icon: "watch" },
        { name: "Biglietto Teatro", price: 25.0, minYear: 1950, maxYear: 2025, icon: "theater" },
        {
            name: "Rullino Fotografico",
            price: 12.0,
            minYear: 1950,
            maxYear: 2015,
            icon: "photo_roll",
        },
        {
            name: "Macchina Fotografica",
            price: 300.0,
            minYear: 1950,
            maxYear: 2025,
            icon: "camera",
        },
        { name: "Sigarette", price: 5.0, minYear: 1950, maxYear: 2025, icon: "cigarette" },
        { name: "Single 45 giri", price: 8.0, minYear: 1960, maxYear: 1995, icon: "single" },
        { name: "TV a Colori", price: 1200.0, minYear: 1965, maxYear: 2010, icon: "tv_color" },
        { name: "Giradischi", price: 150.0, minYear: 1960, maxYear: 2000, icon: "turntable" },
        { name: "Biglietto Partita", price: 45.0, minYear: 1960, maxYear: 2025, icon: "football" },
        { name: "Menu Burger", price: 11.0, minYear: 1970, maxYear: 2025, icon: "burger" },
        { name: "Pizza", price: 14.0, minYear: 1970, maxYear: 2025, icon: "pizza" },
        { name: "Pieno di Benzina", price: 75.0, minYear: 1970, maxYear: 2025, icon: "fuel" },
        { name: "Sveglia Digitale", price: 20.0, minYear: 1970, maxYear: 2025, icon: "alarm" },
        { name: "Radio Transistor", price: 40.0, minYear: 1970, maxYear: 2000, icon: "radio" },
        { name: "Walkman", price: 60.0, minYear: 1979, maxYear: 2005, icon: "walkman" },
        { name: "Calcolatrice", price: 15.0, minYear: 1975, maxYear: 2025, icon: "calculator" },
        { name: "Cassetta Audio", price: 10.0, minYear: 1980, maxYear: 2005, icon: "cassette" },
        { name: "Cassetta VHS", price: 20.0, minYear: 1980, maxYear: 2010, icon: "vhs" },
        { name: "Noleggio VHS", price: 3.0, minYear: 1985, maxYear: 2010, icon: "vhs_rental" },
        { name: "Console 8-bit", price: 200.0, minYear: 1985, maxYear: 2000, icon: "console_8bit" },
        { name: "Telefono Fisso", price: 30.0, minYear: 1980, maxYear: 2025, icon: "phone" },
        { name: "Videocamera", price: 700.0, minYear: 1985, maxYear: 2010, icon: "videocamera" },
        { name: "Enciclopedia", price: 600.0, minYear: 1980, maxYear: 2005, icon: "encyclopedia" },
        { name: "Floppy Disk", price: 2.0, minYear: 1980, maxYear: 2005, icon: "floppy" },
        { name: "CD Audio", price: 18.0, minYear: 1990, maxYear: 2015, icon: "cd" },
        { name: "Videogioco", price: 70.0, minYear: 1990, maxYear: 2025, icon: "game" },
        { name: "Vecchio Cellulare", price: 300.0, minYear: 1995, maxYear: 2010, icon: "mobile" },
        { name: "Computer PC", price: 1200.0, minYear: 1995, maxYear: 2025, icon: "computer" },
        { name: "PlayStation", price: 400.0, minYear: 1995, maxYear: 2025, icon: "playstation" },
        { name: "Game Boy", price: 100.0, minYear: 1990, maxYear: 2010, icon: "gameboy" },
        { name: "Internet Mensile", price: 40.0, minYear: 1995, maxYear: 2025, icon: "internet" },
        {
            name: "Fotocamera Digitale",
            price: 250.0,
            minYear: 1995,
            maxYear: 2025,
            icon: "digital_camera",
        },
        {
            name: "Caffè Starbucks",
            price: 4.5,
            minYear: 1999,
            maxYear: 2025,
            icon: "coffee_premium",
        },
        { name: "Film DVD", price: 15.0, minYear: 2000, maxYear: 2020, icon: "dvd" },
        { name: "iPod", price: 350.0, minYear: 2001, maxYear: 2017, icon: "ipod" },
        { name: "Smartphone", price: 900.0, minYear: 2007, maxYear: 2025, icon: "smartphone" },
        { name: "Tablet", price: 500.0, minYear: 2010, maxYear: 2025, icon: "tablet" },
        { name: "E-Reader", price: 130.0, minYear: 2008, maxYear: 2025, icon: "ereader" },
        { name: "Piano Streaming", price: 15.0, minYear: 2011, maxYear: 2025, icon: "streaming" },
        {
            name: "Auricolari Bluetooth",
            price: 180.0,
            minYear: 2016,
            maxYear: 2025,
            icon: "earbuds",
        },
        { name: "Smartwatch", price: 300.0, minYear: 2014, maxYear: 2025, icon: "smartwatch" },
        {
            name: "Monopattino Elettrico",
            price: 400.0,
            minYear: 2017,
            maxYear: 2025,
            icon: "scooter",
        },
        {
            name: "Friggitrice ad Aria",
            price: 100.0,
            minYear: 2018,
            maxYear: 2025,
            icon: "airfryer",
        },
        { name: "Abbonamento IA", price: 22.0, minYear: 2023, maxYear: 2025, icon: "ai_sub" },
    ],
    cases: [
        {
            year: 1970,
            title: "Seat 600",
            price: "390€",
            description: "Il sogno delle famiglie spagnole costava circa 65.000 pesetas.",
            color: "bg-indigo-100 text-indigo-800 border-indigo-200",
            icon: "car",
        },
        {
            year: 1982,
            title: "Biglietto Mondiale Naranjito",
            price: "4,80€",
            description: "Un biglietto ufficiale per una partita dei Mondiali costava 800 pesetas.",
            color: "bg-emerald-100 text-emerald-800 border-emerald-200",
            icon: "ticket",
        },
        {
            year: 1992,
            title: "Peluches Mascotte Curro",
            price: "15€",
            description: "L'iconico souvenir dell'Expo '92 di Siviglia costava 2.500 pesetas.",
            color: "bg-rose-100 text-rose-800 border-rose-200",
            icon: "toy",
        },
        {
            year: 1995,
            title: "Lancio PlayStation 1",
            price: "360€",
            description: "Arrivò in Europa a 59.900 pesetas.",
            color: "bg-amber-100 text-amber-800 border-amber-200",
            icon: "game",
        },
        {
            year: 1998,
            title: "Nokia 5110",
            price: "150€",
            description: "L'indistruttibile telefono con Snake costava 25.000 pesetas.",
            color: "bg-yellow-100 text-yellow-800 border-yellow-200",
            icon: "mobile",
        },
        {
            year: 2002,
            title: "Primo Caffè in Euro",
            price: "0,60€",
            description: "Costava 100 pesetas esattamente al momento del passaggio all'euro.",
            color: "bg-orange-100 text-orange-800 border-orange-200",
            icon: "coffee",
        },
    ],
    sourcesTitle: "Fonti Ufficiali e Dati",
    sourcesSubtitle: "Istituzioni ed enti che misurano l'impatto reale sull'economia.",
    sourcesBadge: "Documentazione",
    reportTitle: "Allegato I: Rapporto Macroeconomico",
    reportSubtitle:
        "Analisi comparativa dell'evoluzione dei prezzi e del potere d'acquisto in Spagna (1980-2025).",
    table1Title: "Evoluzione del Costo della Vita",
    table1Ref: "Rif: INE / Emeroteche / Ministeri",
    thConcept: "Concetto",
    thYear: "Anno",
    thHistPrice: "Prezzo Storico",
    thPrice2025: "Prezzo 2025",
    thVar: "Var. %",
    thSource: "Fonte",
    table2Title: "Evoluzione Salariale",
    thAvgSalary: "Stipendio Medio Annuo",
    thSmiMonthly: "Salario Minimo Mensile (14 mensilità)",
    thSmiTotal: "Salario Minimo Annuo Totale",
    noteTitle: "Nota Metodologica",
    noteP1: "I dati presentati in questo rapporto sono stati normalizzati in Euro correnti per facilitare il confronto (1€ = 166,386 ptas).",
    noteP2: 'Importante: La colonna "Var. %" riflette l\'aumento nominale dei prezzi.',
    noteSources: "Fonti: INE, Banca di Spagna, Ministero della Casa e stampa digitale.",
    reportTable1Rows: [
        {
            concept: "Abitazione (80m²)",
            year: 1985,
            priceHist: "27.000€ (4,5M ptas)",
            price2025: "287.000€",
            varPercent: "+963%",
            isPositive: false,
            sourceName: "Ministero Casa",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "Salario Minimo",
            year: 1980,
            priceHist: "154€ (25.620 ptas)",
            price2025: "1.134€",
            varPercent: "+636%",
            isPositive: true,
            sourceName: "BOE",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "Pane (250g)",
            year: 1985,
            priceHist: "0,12€ (20 ptas)",
            price2025: "1,20€",
            varPercent: "+900%",
            isPositive: false,
            sourceName: "INE (IPC)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "Benzina (Latro)",
            year: 1980,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,65€",
            varPercent: "+511%",
            isPositive: false,
            sourceName: "Ministero Energia",
            sourceUrl: "https://www.miteco.gob.es",
        },
        {
            concept: "Biglietto Cinema",
            year: 1980,
            priceHist: "1,20€ (200 ptas)",
            price2025: "9,00€",
            varPercent: "+650%",
            isPositive: false,
            sourceName: "Emeroteca",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "Utilitaria",
            year: 1985,
            priceHist: "4.500€ (750k ptas)",
            price2025: "24.000€",
            varPercent: "+433%",
            isPositive: false,
            sourceName: "Riviste Auto",
            sourceTitle: "Motor Clásico / Autopista",
        },
        {
            concept: "Giornale",
            year: 1985,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,80€",
            varPercent: "+566%",
            isPositive: false,
            sourceName: "Emeroteca",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "Olio d'Oliva (1L)",
            year: 2000,
            priceHist: "1,20€ (200 ptas)",
            price2025: "10,00€",
            varPercent: "+733%",
            isPositive: false,
            sourceName: "INE (IPC)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "Caffè (Bar)",
            year: 1990,
            priceHist: "0,48€ (80 ptas)",
            price2025: "1,50€",
            varPercent: "+212%",
            isPositive: false,
            sourceName: "Assoc. Ristorazione",
            sourceTitle: "Assoc. Ristorazione",
        },
    ],
    hiddenTypesCards: [
        {
            badge: "MENO ALLO STESSO PREZZO",
            title: "Sflazione",
            graphicLabel1: "PATATINE",
            graphicLabel2: "NUOVO FORMATO",
            graphicLegend1: "243g (Prima 295g)",
            graphicLegend2: "Prezzo: +15%",
            tagline: '"Ti vendono aria al prezzo del cibo."',
            description:
                "Le confezioni di patatine sono scese da 295g a 243g mentre il prezzo è aumentato.",
            sourceText: "Fonte: Studio FACUA",
            shareText: "La sflazione è reale!",
        },
        {
            badge: "PEGGIO ALLO STESSO PREZZO",
            title: "Skimpflation",
            graphicLabel1: "RICETTA MIGLIORATA",
            graphicLabel2: "INGREDIENTI:",
            graphicRemoved1: "Olio di Girasole",
            graphicAdded1: "Grasso di Palma/Mix",
            graphicRemoved2: "Burro",
            graphicAdded2: "Olii Vegetali",
            tagline: '"Sostituiscono i buoni ingredienti con surrogati economici."',
            description:
                "Molti marchi hanno sostituito l'olio di girasole con olio di palma o miscele vegetali.",
            sourceText: "Fonte: NPR (Skimpflation)",
            shareText: "La skimpflation peggiora la qualità!",
        },
        {
            badge: "LA FUGA VERSO L'ALTO",
            title: "Premiumizzazione",
            graphicLabel1: "Platinum",
            graphicLabel2: "ULTRA PRO",
            graphicLegend1: "12,99€",
            graphicLegend2: "ESAURITO!",
            graphicRemoved1: "Base",
            graphicAdded1: "2,99€",
            tagline: '"Eliminano la gamma base per costringerti a comprare la linea di lusso."',
            description:
                "La febbre 'High Protein' ha sostituito gli yogurt tradizionali con opzioni costose.",
            sourceText: "Fonte: CESCE (Premiumizzazione)",
            shareText: "La premiumizzazione elimina i prodotti base!",
        },
        {
            badge: "TU SEI IL DIPENDENTE",
            title: "Inflazione Ombra",
            graphicLabel1: "ERRORE: ATTENDERE ASSISTENZA",
            graphicLabel2: "Il tuo Stipendio: 0€/ora",
            tagline: '"Lavori gratis per il supermercato e paghi lo stesso prezzo."',
            description:
                "Le casse automatiche trasferiscono il lavoro al cliente senza sconti sul prezzo finale.",
            sourceText: "Fonte: The Guardian (Shadow Work)",
            shareText: "L'inflazione ombra ti fa lavorare gratis!",
        },
    ],
};
