import type { InflationLocaleData } from "../types";
import { INFLATION_EN_TEXTS } from "./en";

export const INFLATION_JA_TEXTS: InflationLocaleData = {
    ...INFLATION_EN_TEXTS,
    cardTitle: "インフレ",
    cardSubtitle: "100€で昔買えたものと今買えるものの比較",
    cardDescription: "実際の価格比較、賃金データ、歴史的記録を通じて購買力の推移を探索します。",
    title: "インフレ",
    billTitle: "100€紙幣",
    billYearLabel: "年",
    billValueLabel: "今日の相当価値",
    casesTitle: "ノスタルジー vs 現実",
    casesSubtitle: "スワイプして価格変化の実際の事例を見る",
    shareButton: "共有",
    infoTitle: "なぜ100€で昔と同じものが買えなくなったのか？",
    infoP1: "インフレーションとは、物価が sustainable に上昇し続けることです。時間の経過とともに、貨幣1単位で購入できる財やサービスの割合が減少します。",
    infoP2: "昔の価格を懐かしく思い出すことがよくありますが、当時の給与もずっと低かったことを忘れがちです。",
    infoP3: "インフレを理解することで、より良い長期的な財務上の意思決定を行い、購買力を保護することができます。",
    items: [
        { name: "パン", price: 1.2, minYear: 1950, maxYear: 2025, icon: "bread" },
        { name: "牛乳", price: 1.0, minYear: 1950, maxYear: 2025, icon: "milk" },
        { name: "コーヒー", price: 1.6, minYear: 1950, maxYear: 2025, icon: "coffee" },
        { name: "ビール", price: 3.0, minYear: 1950, maxYear: 2025, icon: "beer" },
        { name: "本", price: 22.0, minYear: 1950, maxYear: 2025, icon: "book" },
        { name: "Tシャツ", price: 20.0, minYear: 1950, maxYear: 2025, icon: "shirt" },
        { name: "靴", price: 90.0, minYear: 1950, maxYear: 2025, icon: "shoe" },
        { name: "宝石", price: 500.0, minYear: 1950, maxYear: 2025, icon: "diamond" },
        { name: "車", price: 22000.0, minYear: 1950, maxYear: 2025, icon: "car" },
        { name: "マンション", price: 250000.0, minYear: 1950, maxYear: 2025, icon: "house" },
        {
            name: "レストランのディナー",
            price: 45.0,
            minYear: 1950,
            maxYear: 2025,
            icon: "restaurant",
        },
        { name: "新聞", price: 2.0, minYear: 1950, maxYear: 2025, icon: "newspaper" },
        { name: "切手", price: 1.0, minYear: 1950, maxYear: 2025, icon: "mail" },
        { name: "映画のチケット", price: 9.5, minYear: 1950, maxYear: 2025, icon: "movie" },
        { name: "レコード盤", price: 30.0, minYear: 1950, maxYear: 2025, icon: "vinyl" },
        { name: "コンサートチケット", price: 60.0, minYear: 1950, maxYear: 2025, icon: "concert" },
        { name: "白黒テレビ", price: 800.0, minYear: 1950, maxYear: 1980, icon: "tv_old" },
        { name: "腕時計", price: 80.0, minYear: 1950, maxYear: 2025, icon: "watch" },
        { name: "劇場のチケット", price: 25.0, minYear: 1950, maxYear: 2025, icon: "theater" },
        { name: "写真フィルム", price: 12.0, minYear: 1950, maxYear: 2015, icon: "photo_roll" },
        { name: "カメラ", price: 300.0, minYear: 1950, maxYear: 2025, icon: "camera" },
        { name: "タバコ", price: 5.0, minYear: 1950, maxYear: 2025, icon: "cigarette" },
        { name: "45回転シングル", price: 8.0, minYear: 1960, maxYear: 1995, icon: "single" },
        { name: "カラーテレビ", price: 1200.0, minYear: 1965, maxYear: 2010, icon: "tv_color" },
        {
            name: "レコードプレーヤー",
            price: 150.0,
            minYear: 1960,
            maxYear: 2000,
            icon: "turntable",
        },
        { name: "サッカーのチケット", price: 45.0, minYear: 1960, maxYear: 2025, icon: "football" },
        { name: "バーガーセット", price: 11.0, minYear: 1970, maxYear: 2025, icon: "burger" },
        { name: "ピザ", price: 14.0, minYear: 1970, maxYear: 2025, icon: "pizza" },
        { name: "ガソリン満タン", price: 75.0, minYear: 1970, maxYear: 2025, icon: "fuel" },
        { name: "デジタル目覚まし時計", price: 20.0, minYear: 1970, maxYear: 2025, icon: "alarm" },
        { name: "トランジスタラジオ", price: 40.0, minYear: 1970, maxYear: 2000, icon: "radio" },
        { name: "ウォークマン", price: 60.0, minYear: 1979, maxYear: 2005, icon: "walkman" },
        { name: "電卓", price: 15.0, minYear: 1975, maxYear: 2025, icon: "calculator" },
        { name: "カセットテープ", price: 10.0, minYear: 1980, maxYear: 2005, icon: "cassette" },
        { name: "VHSテープ", price: 20.0, minYear: 1980, maxYear: 2010, icon: "vhs" },
        { name: "VHSレンタル", price: 3.0, minYear: 1985, maxYear: 2010, icon: "vhs_rental" },
        {
            name: "8ビットゲーム機",
            price: 200.0,
            minYear: 1985,
            maxYear: 2000,
            icon: "console_8bit",
        },
        { name: "固定電話", price: 30.0, minYear: 1980, maxYear: 2025, icon: "phone" },
        { name: "ビデオカメラ", price: 700.0, minYear: 1985, maxYear: 2010, icon: "videocamera" },
        {
            name: "百科事典セット",
            price: 600.0,
            minYear: 1980,
            maxYear: 2005,
            icon: "encyclopedia",
        },
        { name: "フロッピーディスク", price: 2.0, minYear: 1980, maxYear: 2005, icon: "floppy" },
        { name: "音楽CD", price: 18.0, minYear: 1990, maxYear: 2015, icon: "cd" },
        { name: "ビデオゲーム", price: 70.0, minYear: 1990, maxYear: 2025, icon: "game" },
        { name: "昔の携帯電話", price: 300.0, minYear: 1995, maxYear: 2010, icon: "mobile" },
        { name: "パソコン", price: 1200.0, minYear: 1995, maxYear: 2025, icon: "computer" },
        { name: "PlayStation", price: 400.0, minYear: 1995, maxYear: 2025, icon: "playstation" },
        { name: "ゲームボーイ", price: 100.0, minYear: 1990, maxYear: 2010, icon: "gameboy" },
        { name: "月額インターネット", price: 40.0, minYear: 1995, maxYear: 2025, icon: "internet" },
        {
            name: "デジタルカメラ",
            price: 250.0,
            minYear: 1995,
            maxYear: 2025,
            icon: "digital_camera",
        },
        {
            name: "スターバックスのコーヒー",
            price: 4.5,
            minYear: 1999,
            maxYear: 2025,
            icon: "coffee_premium",
        },
        { name: "DVD映画", price: 15.0, minYear: 2000, maxYear: 2020, icon: "dvd" },
        { name: "iPod", price: 350.0, minYear: 2001, maxYear: 2017, icon: "ipod" },
        { name: "スマートフォン", price: 900.0, minYear: 2007, maxYear: 2025, icon: "smartphone" },
        { name: "タブレット", price: 500.0, minYear: 2010, maxYear: 2025, icon: "tablet" },
        { name: "電子書籍リーダー", price: 130.0, minYear: 2008, maxYear: 2025, icon: "ereader" },
        { name: "配信サブスク", price: 15.0, minYear: 2011, maxYear: 2025, icon: "streaming" },
        { name: "ワイヤレスイヤホン", price: 180.0, minYear: 2016, maxYear: 2025, icon: "earbuds" },
        {
            name: "スマートウォッチ",
            price: 300.0,
            minYear: 2014,
            maxYear: 2025,
            icon: "smartwatch",
        },
        { name: "電動キックボード", price: 400.0, minYear: 2017, maxYear: 2025, icon: "scooter" },
        { name: "ノンフライヤー", price: 100.0, minYear: 2018, maxYear: 2025, icon: "airfryer" },
        { name: "AIサブスク", price: 22.0, minYear: 2023, maxYear: 2025, icon: "ai_sub" },
    ],
    cases: [
        {
            year: 1970,
            title: "Seat 600",
            price: "390€",
            description: "スペインの家族の夢は約65,000ペセタでした。",
            color: "bg-indigo-100 text-indigo-800 border-indigo-200",
            icon: "car",
        },
        {
            year: 1982,
            title: "W杯ナランヒートのチケット",
            price: "4.80€",
            description: "ワールドカップ試合の公式チケットは800ペセタでした。",
            color: "bg-emerald-100 text-emerald-800 border-emerald-200",
            icon: "ticket",
        },
        {
            year: 1992,
            title: "マスコット「クッロ」のぬいぐるみ",
            price: "15€",
            description: "セビリア万博'92の象徴的なお土産は2,500ペセタでした。",
            color: "bg-rose-100 text-rose-800 border-rose-200",
            icon: "toy",
        },
        {
            year: 1995,
            title: "PlayStation 1発売",
            price: "360€",
            description: "59,900ペセタで欧州に上陸しました。",
            color: "bg-amber-100 text-amber-800 border-amber-200",
            icon: "game",
        },
        {
            year: 1998,
            title: "Nokia 5110",
            price: "150€",
            description: "スネークゲーム搭載の頑丈な携帯電話は25,000ペセタでした。",
            color: "bg-yellow-100 text-yellow-800 border-yellow-200",
            icon: "mobile",
        },
        {
            year: 2002,
            title: "ユーロ導入後初のコーヒー",
            price: "0.60€",
            description: "ユーロ移行のまさにその時、100ペセタでした。",
            color: "bg-orange-100 text-orange-800 border-orange-200",
            icon: "coffee",
        },
    ],
    sourcesTitle: "公式情報源とデータ",
    sourcesSubtitle: "経済への影響を測定する公的機関。",
    sourcesBadge: "ドキュメント",
    reportTitle: "付録 I: マクロ経済レポート",
    reportSubtitle: "スペインにおける価格動向と購買力の比較分析 (1980-2025)。",
    table1Title: "生活費の動向",
    table1Ref: "参照: INE / 新聞アーカイブ / 各省庁",
    thConcept: "項目",
    thYear: "年",
    thHistPrice: "過去の価格",
    thPrice2025: "2025年の価格",
    thVar: "変動率 %",
    thSource: "情報源",
    table2Title: "賃金の動向",
    thAvgSalary: "平均年収",
    thSmiMonthly: "月額最低賃金 (14回払い)",
    thSmiTotal: "年間最低賃金合計",
    noteTitle: "方法論に関する注記",
    noteP1: "本レポートのデータは比較を容易にするため、固定為替レート (1€ = 166.386 ptas) を使用して現在のユーロに換算されています。",
    noteP2: "重要: 「変動率 %」は名目価格の上昇を示しています。",
    noteSources: "情報源: INE、スペイン銀行、住宅省、新聞アーカイブ。",
    reportTable1Rows: [
        {
            concept: "住宅 (80m²マンション)",
            year: 1985,
            priceHist: "27.000€ (4.5M ptas)",
            price2025: "287.000€",
            varPercent: "+963%",
            isPositive: false,
            sourceName: "住宅省",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "最低賃金 (SMI)",
            year: 1980,
            priceHist: "154€ (25.620 ptas)",
            price2025: "1.134€",
            varPercent: "+636%",
            isPositive: true,
            sourceName: "BOE",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "パン (250g)",
            year: 1985,
            priceHist: "0,12€ (20 ptas)",
            price2025: "1,20€",
            varPercent: "+900%",
            isPositive: false,
            sourceName: "INE (CPI)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "ガソリン (1L)",
            year: 1980,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,65€",
            varPercent: "+511%",
            isPositive: false,
            sourceName: "エネルギー省",
            sourceUrl: "https://www.miteco.gob.es",
        },
        {
            concept: "映画チケット",
            year: 1980,
            priceHist: "1,20€ (200 ptas)",
            price2025: "9,00€",
            varPercent: "+650%",
            isPositive: false,
            sourceName: "新聞アーカイブ",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "小型車",
            year: 1985,
            priceHist: "4.500€ (750k ptas)",
            price2025: "24.000€",
            varPercent: "+433%",
            isPositive: false,
            sourceName: "自動車雑誌",
            sourceTitle: "Motor Clásico / Autopista",
        },
        {
            concept: "新聞",
            year: 1985,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,80€",
            varPercent: "+566%",
            isPositive: false,
            sourceName: "新聞アーカイブ",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "オリーブオイル (1L)",
            year: 2000,
            priceHist: "1,20€ (200 ptas)",
            price2025: "10,00€",
            varPercent: "+733%",
            isPositive: false,
            sourceName: "INE (CPI)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "カフェのコーヒー",
            year: 1990,
            priceHist: "0,48€ (80 ptas)",
            price2025: "1,50€",
            varPercent: "+212%",
            isPositive: false,
            sourceName: "飲食協会",
            sourceTitle: "飲食協会",
        },
    ],
    hiddenTypesCards: [
        {
            badge: "同じ価格で容量減少",
            title: "シュリンクフレーション",
            graphicLabel1: "ポテトチップス",
            graphicLabel2: "新パッケージ",
            graphicLegend1: "243g (以前は295g)",
            graphicLegend2: "価格: +15%",
            tagline: '"食品の価格で空気が売られる。"',
            description: "ポテトチップスは295gから243gへと容量が減り価格が上昇しました。",
            sourceText: "情報源: FACUA調査",
            shareText: "シュリンクフレーションは現実です！",
        },
        {
            badge: "同じ価格で品質低下",
            title: "スキンプフレーション",
            graphicLabel1: "リニューアルレシピ",
            graphicLabel2: "原材料:",
            graphicRemoved1: "ひまわり油",
            graphicAdded1: "パーム油/ミックス",
            graphicRemoved2: "バター",
            graphicAdded2: "植物油",
            tagline: '"良い原材料が安価な代替品に置き換えられる。"',
            description: "ひまわり油がパーム油や植物油に置き換えられました。",
            sourceText: "情報源: NPR (スキンプフレーション)",
            shareText: "スキンプフレーションで品質が低下！",
        },
        {
            badge: "ハイエンド化への逃避",
            title: "プレミアム化",
            graphicLabel1: "Platinum",
            graphicLabel2: "ULTRA PRO",
            graphicLegend1: "12.99€",
            graphicLegend2: "売り切れ！",
            graphicRemoved1: "ベーシック",
            graphicAdded1: "2.99€",
            tagline: '"高級ラインの購入を強いられるため基本モデルが消える。"',
            description: "高タンパクブームが通常のヨーグルトを追いやっています。",
            sourceText: "情報源: CESCE (プレミアム化)",
            shareText: "プレミアム化で定番商品が消滅！",
        },
        {
            badge: "あなたが従業員",
            title: "シャドウインフレ",
            graphicLabel1: "エラー: 係員をお待ちください",
            graphicLabel2: "あなたの時給: 0€/時間",
            tagline: '"スーパーのために無給で働き、同じ価格を支払う。"',
            description: "セルフレジの導入で労働コストが客に転嫁されています。",
            sourceText: "情報源: The Guardian (シャドウワーク)",
            shareText: "シャドウインフレで無給労働！",
        },
    ],
};
