import type { InflationLocaleData } from "../types";
import { INFLATION_EN_TEXTS } from "./en";

export const INFLATION_KO_TEXTS: InflationLocaleData = {
    ...INFLATION_EN_TEXTS,
    cardTitle: "인플레이션",
    cardSubtitle: "과거 100€로 살 수 있었던 것 vs 현재 살 수 있는 것",
    cardDescription:
        "실제 가격 비교, 임금 데이터 및 역사적 기록을 통해 구매력의 변화를 탐색해 보세요.",
    title: "인플레이션",
    billTitle: "100€ 지폐",
    billYearLabel: "연도",
    billValueLabel: "현재 상응하는 가치",
    casesTitle: "향수 vs 현실",
    casesSubtitle: "스와이프하여 실제 가격 변화 사례를 확인하세요",
    shareButton: "공유하기",
    infoTitle: "왜 100€로 예전만큼 살 수 없을까요?",
    infoP1: "인플레이션은 물가가 지속적이고 general하게 상승하는 현상입니다. 시간이 지남에 따라 통화 1단위로 구매할 수 있는 재화나 서비스의 비율이 줄어듭니다.",
    infoP2: "우리는 과거의 물가를 향수로 기억하곤 하지만, 당시 임금 역시 훨씬 낮았다는 점을 잊기 쉽습니다.",
    infoP3: "인플레이션을 이해하면 장기적으로 더 나은 재정적 의사결정을 내리고 구매력을 보호하는 데 도움이 됩니다.",
    items: [
        { name: "빵", price: 1.2, minYear: 1950, maxYear: 2025, icon: "bread" },
        { name: "우유", price: 1.0, minYear: 1950, maxYear: 2025, icon: "milk" },
        { name: "커피", price: 1.6, minYear: 1950, maxYear: 2025, icon: "coffee" },
        { name: "맥주", price: 3.0, minYear: 1950, maxYear: 2025, icon: "beer" },
        { name: "책", price: 22.0, minYear: 1950, maxYear: 2025, icon: "book" },
        { name: "티셔츠", price: 20.0, minYear: 1950, maxYear: 2025, icon: "shirt" },
        { name: "신발", price: 90.0, minYear: 1950, maxYear: 2025, icon: "shoe" },
        { name: "보석", price: 500.0, minYear: 1950, maxYear: 2025, icon: "diamond" },
        { name: "자동차", price: 22000.0, minYear: 1950, maxYear: 2025, icon: "car" },
        { name: "아파트", price: 250000.0, minYear: 1950, maxYear: 2025, icon: "house" },
        {
            name: "레스토랑 저녁식사",
            price: 45.0,
            minYear: 1950,
            maxYear: 2025,
            icon: "restaurant",
        },
        { name: "신문", price: 2.0, minYear: 1950, maxYear: 2025, icon: "newspaper" },
        { name: "우표", price: 1.0, minYear: 1950, maxYear: 2025, icon: "mail" },
        { name: "영화 티켓", price: 9.5, minYear: 1950, maxYear: 2025, icon: "movie" },
        { name: "바이닐 LP판", price: 30.0, minYear: 1950, maxYear: 2025, icon: "vinyl" },
        { name: "콘서트 티켓", price: 60.0, minYear: 1950, maxYear: 2025, icon: "concert" },
        { name: "흑백 텔레비전", price: 800.0, minYear: 1950, maxYear: 1980, icon: "tv_old" },
        { name: "손목시계", price: 80.0, minYear: 1950, maxYear: 2025, icon: "watch" },
        { name: "연극 티켓", price: 25.0, minYear: 1950, maxYear: 2025, icon: "theater" },
        { name: "필름 롤", price: 12.0, minYear: 1950, maxYear: 2015, icon: "photo_roll" },
        { name: "카메라", price: 300.0, minYear: 1950, maxYear: 2025, icon: "camera" },
        { name: "담배", price: 5.0, minYear: 1950, maxYear: 2025, icon: "cigarette" },
        { name: "45rpm 싱글판", price: 8.0, minYear: 1960, maxYear: 1995, icon: "single" },
        { name: "컬러 텔레비전", price: 1200.0, minYear: 1965, maxYear: 2010, icon: "tv_color" },
        { name: "턴테이블", price: 150.0, minYear: 1960, maxYear: 2000, icon: "turntable" },
        { name: "축구 티켓", price: 45.0, minYear: 1960, maxYear: 2025, icon: "football" },
        { name: "버거 세트", price: 11.0, minYear: 1970, maxYear: 2025, icon: "burger" },
        { name: "피자", price: 14.0, minYear: 1970, maxYear: 2025, icon: "pizza" },
        { name: "휘발유 가득", price: 75.0, minYear: 1970, maxYear: 2025, icon: "fuel" },
        { name: "디지털 탁상시계", price: 20.0, minYear: 1970, maxYear: 2025, icon: "alarm" },
        { name: "트랜지스터 라디오", price: 40.0, minYear: 1970, maxYear: 2000, icon: "radio" },
        { name: "워크맨", price: 60.0, minYear: 1979, maxYear: 2005, icon: "walkman" },
        { name: "계산기", price: 15.0, minYear: 1975, maxYear: 2025, icon: "calculator" },
        { name: "카세트 테이프", price: 10.0, minYear: 1980, maxYear: 2005, icon: "cassette" },
        { name: "VHS 테이프", price: 20.0, minYear: 1980, maxYear: 2010, icon: "vhs" },
        { name: "VHS 대여", price: 3.0, minYear: 1985, maxYear: 2010, icon: "vhs_rental" },
        { name: "8비트 콘솔", price: 200.0, minYear: 1985, maxYear: 2000, icon: "console_8bit" },
        { name: "유선 전화기", price: 30.0, minYear: 1980, maxYear: 2025, icon: "phone" },
        { name: "캠코더", price: 700.0, minYear: 1985, maxYear: 2010, icon: "videocamera" },
        { name: "백과사전 전집", price: 600.0, minYear: 1980, maxYear: 2005, icon: "encyclopedia" },
        { name: "플로피 디스크", price: 2.0, minYear: 1980, maxYear: 2005, icon: "floppy" },
        { name: "음악 CD", price: 18.0, minYear: 1990, maxYear: 2015, icon: "cd" },
        { name: "비디오 게임", price: 70.0, minYear: 1990, maxYear: 2025, icon: "game" },
        { name: "구형 휴대폰", price: 300.0, minYear: 1995, maxYear: 2010, icon: "mobile" },
        { name: "PC 컴퓨터", price: 1200.0, minYear: 1995, maxYear: 2025, icon: "computer" },
        { name: "PlayStation", price: 400.0, minYear: 1995, maxYear: 2025, icon: "playstation" },
        { name: "Game Boy", price: 100.0, minYear: 1990, maxYear: 2010, icon: "gameboy" },
        { name: "월간 인터넷", price: 40.0, minYear: 1995, maxYear: 2025, icon: "internet" },
        {
            name: "디지털 카메라",
            price: 250.0,
            minYear: 1995,
            maxYear: 2025,
            icon: "digital_camera",
        },
        { name: "스타벅스 커피", price: 4.5, minYear: 1999, maxYear: 2025, icon: "coffee_premium" },
        { name: "DVD 영화", price: 15.0, minYear: 2000, maxYear: 2020, icon: "dvd" },
        { name: "iPod", price: 350.0, minYear: 2001, maxYear: 2017, icon: "ipod" },
        { name: "스마트폰", price: 900.0, minYear: 2007, maxYear: 2025, icon: "smartphone" },
        { name: "태블릿", price: 500.0, minYear: 2010, maxYear: 2025, icon: "tablet" },
        { name: "전자책 리더기", price: 130.0, minYear: 2008, maxYear: 2025, icon: "ereader" },
        { name: "스트리밍 구독", price: 15.0, minYear: 2011, maxYear: 2025, icon: "streaming" },
        { name: "무선 이어폰", price: 180.0, minYear: 2016, maxYear: 2025, icon: "earbuds" },
        { name: "스마트워치", price: 300.0, minYear: 2014, maxYear: 2025, icon: "smartwatch" },
        { name: "전동 킥보드", price: 400.0, minYear: 2017, maxYear: 2025, icon: "scooter" },
        { name: "에어프라이어", price: 100.0, minYear: 2018, maxYear: 2025, icon: "airfryer" },
        { name: "AI 구독", price: 22.0, minYear: 2023, maxYear: 2025, icon: "ai_sub" },
    ],
    cases: [
        {
            year: 1970,
            title: "Seat 600",
            price: "390€",
            description: "스페인 가정의 꿈이었던 이 차는 약 65,000페세타였습니다.",
            color: "bg-indigo-100 text-indigo-800 border-indigo-200",
            icon: "car",
        },
        {
            year: 1982,
            title: "월드컵 나란히토 티켓",
            price: "4.80€",
            description: "월드컵 경기 공식 티켓은 800페세타였습니다.",
            color: "bg-emerald-100 text-emerald-800 border-emerald-200",
            icon: "ticket",
        },
        {
            year: 1992,
            title: "마스코트 쿠로 봉제인형",
            price: "15€",
            description: "세비야 엑스포 '92의 상징적인 기념품은 2,500페세타였습니다.",
            color: "bg-rose-100 text-rose-800 border-rose-200",
            icon: "toy",
        },
        {
            year: 1995,
            title: "PlayStation 1 출시",
            price: "360€",
            description: "59,900페세타 가격으로 유럽에 상륙했습니다.",
            color: "bg-amber-100 text-amber-800 border-amber-200",
            icon: "game",
        },
        {
            year: 1998,
            title: "Nokia 5110",
            price: "150€",
            description: "뱀 게임이 내장된 튼튼한 휴대전화는 25,000페세타였습니다.",
            color: "bg-yellow-100 text-yellow-800 border-yellow-200",
            icon: "mobile",
        },
        {
            year: 2002,
            title: "유로화 전환 후 첫 커피",
            price: "0.60€",
            description: "유로 전환 당시 정확히 100페세타였습니다.",
            color: "bg-orange-100 text-orange-800 border-orange-200",
            icon: "coffee",
        },
    ],
    sourcesTitle: "공식 출처 및 데이터",
    sourcesSubtitle: "경제에 미치는 실질적 영향을 측정하는 기관.",
    sourcesBadge: "문서",
    reportTitle: "부록 I: 거시경제 보고서",
    reportSubtitle: "스페인의 가격 변동 및 구매력 비교 분석 (1980-2025).",
    table1Title: "생활비 변동",
    table1Ref: "참조: INE / 신문 아카이브 / 각 부처",
    thConcept: "항목",
    thYear: "연도",
    thHistPrice: "과거 가격",
    thPrice2025: "2025년 가격",
    thVar: "변동률 %",
    thSource: "출처",
    table2Title: "임금 변동",
    thAvgSalary: "연평균 임금",
    thSmiMonthly: "월 최저임금 (14회 지급)",
    thSmiTotal: "연간 총 최저임금",
    noteTitle: "방법론 참고사항",
    noteP1: "본 보고서의 데이터는 비교를 돕기 위해 고정 환율(1€ = 166.386 ptas)을 적용하여 현재 유로화로 환산되었습니다.",
    noteP2: '중요: "변동률 %"는 명목 가격 상승을 나타냅니다.',
    noteSources: "출처: INE, 스페인 은행, 주택부 및 디지털 신문 아카이브.",
    reportTable1Rows: [
        {
            concept: "주택 (80m² 아파트)",
            year: 1985,
            priceHist: "27.000€ (4.5M ptas)",
            price2025: "287.000€",
            varPercent: "+963%",
            isPositive: false,
            sourceName: "주택부",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "최저임금 (SMI)",
            year: 1980,
            priceHist: "154€ (25.620 ptas)",
            price2025: "1.134€",
            varPercent: "+636%",
            isPositive: true,
            sourceName: "BOE",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "빵 (250g 바게트)",
            year: 1985,
            priceHist: "0,12€ (20 ptas)",
            price2025: "1,20€",
            varPercent: "+900%",
            isPositive: false,
            sourceName: "INE (CPI)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "휘발유 (1리터)",
            year: 1980,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,65€",
            varPercent: "+511%",
            isPositive: false,
            sourceName: "에너지부",
            sourceUrl: "https://www.miteco.gob.es",
        },
        {
            concept: "영화 관람권",
            year: 1980,
            priceHist: "1,20€ (200 ptas)",
            price2025: "9,00€",
            varPercent: "+650%",
            isPositive: false,
            sourceName: "신문 아카이브",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "소형 승용차",
            year: 1985,
            priceHist: "4.500€ (750k ptas)",
            price2025: "24.000€",
            varPercent: "+433%",
            isPositive: false,
            sourceName: "자동차 잡지",
            sourceTitle: "Motor Clásico / Autopista",
        },
        {
            concept: "신문",
            year: 1985,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,80€",
            varPercent: "+566%",
            isPositive: false,
            sourceName: "신문 아카이브",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "올리브유 (1L)",
            year: 2000,
            priceHist: "1,20€ (200 ptas)",
            price2025: "10,00€",
            varPercent: "+733%",
            isPositive: false,
            sourceName: "INE (CPI)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "카페 커피",
            year: 1990,
            priceHist: "0,48€ (80 ptas)",
            price2025: "1,50€",
            varPercent: "+212%",
            isPositive: false,
            sourceName: "요식업 협회",
            sourceTitle: "요식업 협회",
        },
    ],
    hiddenTypesCards: [
        {
            badge: "같은 가격에 더 적게",
            title: "슈링크플레이션",
            graphicLabel1: "감자칩",
            graphicLabel2: "새 포장",
            graphicLegend1: "243g (기존 295g)",
            graphicLegend2: "가격: +15%",
            tagline: '"음식 가격으로 공기를 팝니다."',
            description: "감자칩 용량이 295g에서 243g으로 줄어들면서 가격은 올랐습니다.",
            sourceText: "출처: FACUA 조사",
            shareText: "슈링크플레이션은 실제 현상입니다!",
        },
        {
            badge: "같은 가격에 품질 저하",
            title: "스킴플레이션",
            graphicLabel1: "개선된 레시피",
            graphicLabel2: "원재료:",
            graphicRemoved1: "해바라기유",
            graphicAdded1: "팜유/혼합유",
            graphicRemoved2: "버터",
            graphicAdded2: "식물성 유지",
            tagline: '"좋은 원재료를 저렴한 대체제로 바꿉니다."',
            description: "해바라기유를 팜유나 식물성 유지로 대체했습니다.",
            sourceText: "출처: NPR (스킴플레이션)",
            shareText: "스킴플레이션으로 품질이 떨어집니다!",
        },
        {
            badge: "고급화로의 도피",
            title: "프리미엄화",
            graphicLabel1: "Platinum",
            graphicLabel2: "ULTRA PRO",
            graphicLegend1: "12.99€",
            graphicLegend2: "품절!",
            graphicRemoved1: "기본형",
            graphicAdded1: "2.99€",
            tagline: '"고급 라인 구매를 강제하기 위해 기본 제품을 없앱니다."',
            description: "고단백 열풍이 일반 요거트를 밀어내고 고가 제품을 늘렸습니다.",
            sourceText: "출처: CESCE (프리미엄화 전략)",
            shareText: "프리미엄화로 기본 선택지가 사라집니다!",
        },
        {
            badge: "당신이 직원입니다",
            title: "섀도 인플레이션",
            graphicLabel1: "오류: 직원을 기다려주세요",
            graphicLabel2: "당신의 시급: 0€/시간",
            tagline: '"마트를 위해 무급으로 일하면서 가격은 똑같이 냅니다."',
            description: "셀프 계산대가 인건비를 고객에게 전가하면서 가격은 내리지 않습니다.",
            sourceText: "출처: The Guardian (섀도 워크)",
            shareText: "섀도 인플레이션이 무료 노동을 시킵니다!",
        },
    ],
};
