import type { InflationLocaleData } from "../types";
import { INFLATION_EN_TEXTS } from "./en";

export const INFLATION_NL_TEXTS: InflationLocaleData = {
    ...INFLATION_EN_TEXTS,
    cardTitle: "De Inflatie",
    cardSubtitle: "Wat kon u vroeger met €100 kopen vergeleken met vandaag?",
    cardDescription:
        "Ontdek de evolutie van koopkracht via echte prijsvergelijkingen, loongegevens en historische archieven.",
    title: "DE INFLATIE",
    billTitle: "100€ BANKBILJET",
    billYearLabel: "Jaar",
    billValueLabel: "Gelijkwaardige waarde vandaag",
    casesTitle: "Nostalgie vs Realiteit",
    casesSubtitle: "Veeg om echte voorbeelden van prijsveranderingen te zien",
    shareButton: "Delen",
    infoTitle: "Waarom koopt u met €100 niet meer wat u vroeger kon kopen?",
    infoP1: "Inflatie is de algemene en sustained stijging van de prijzen. Naarmate de tijd vordert, koopt elke geldeenheid een kleiner percentage van een goed of dienst.",
    infoP2: "We herinneren ons vaak oude prijzen met nostalgie, maar we vergeten dat de lonen toen ook veel lager waren.",
    infoP3: "Het begrijpen van inflatie helpt u betere financiële beslissingen op lange termijn te nemen en uw koopkracht te beschermen.",
    items: [
        { name: "Brood", price: 1.2, minYear: 1950, maxYear: 2025, icon: "bread" },
        { name: "Melk", price: 1.0, minYear: 1950, maxYear: 2025, icon: "milk" },
        { name: "Koffie", price: 1.6, minYear: 1950, maxYear: 2025, icon: "coffee" },
        { name: "Bier", price: 3.0, minYear: 1950, maxYear: 2025, icon: "beer" },
        { name: "Boek", price: 22.0, minYear: 1950, maxYear: 2025, icon: "book" },
        { name: "T-Shirt", price: 20.0, minYear: 1950, maxYear: 2025, icon: "shirt" },
        { name: "Schoenen", price: 90.0, minYear: 1950, maxYear: 2025, icon: "shoe" },
        { name: "Juweel", price: 500.0, minYear: 1950, maxYear: 2025, icon: "diamond" },
        { name: "Auto", price: 22000.0, minYear: 1950, maxYear: 2025, icon: "car" },
        { name: "Appartement", price: 250000.0, minYear: 1950, maxYear: 2025, icon: "house" },
        {
            name: "Diner in Restaurant",
            price: 45.0,
            minYear: 1950,
            maxYear: 2025,
            icon: "restaurant",
        },
        { name: "Krant", price: 2.0, minYear: 1950, maxYear: 2025, icon: "newspaper" },
        { name: "Postzegel", price: 1.0, minYear: 1950, maxYear: 2025, icon: "mail" },
        { name: "Bioscoopkaartje", price: 9.5, minYear: 1950, maxYear: 2025, icon: "movie" },
        { name: "Vinylplaat", price: 30.0, minYear: 1950, maxYear: 2025, icon: "vinyl" },
        { name: "Concertkaartje", price: 60.0, minYear: 1950, maxYear: 2025, icon: "concert" },
        { name: "Zwart-Wit TV", price: 800.0, minYear: 1950, maxYear: 1980, icon: "tv_old" },
        { name: "Polshorloge", price: 80.0, minYear: 1950, maxYear: 2025, icon: "watch" },
        { name: "Theaterkaartje", price: 25.0, minYear: 1950, maxYear: 2025, icon: "theater" },
        { name: "Fotorolletje", price: 12.0, minYear: 1950, maxYear: 2015, icon: "photo_roll" },
        { name: "Fotocamera", price: 300.0, minYear: 1950, maxYear: 2025, icon: "camera" },
        { name: "Sigaretten", price: 5.0, minYear: 1950, maxYear: 2025, icon: "cigarette" },
        { name: "45-toeren Single", price: 8.0, minYear: 1960, maxYear: 1995, icon: "single" },
        { name: "Kleuren-TV", price: 1200.0, minYear: 1965, maxYear: 2010, icon: "tv_color" },
        { name: "Platenspeler", price: 150.0, minYear: 1960, maxYear: 2000, icon: "turntable" },
        { name: "Voetbalkaartje", price: 45.0, minYear: 1960, maxYear: 2025, icon: "football" },
        { name: "Burgermenu", price: 11.0, minYear: 1970, maxYear: 2025, icon: "burger" },
        { name: "Pizza", price: 14.0, minYear: 1970, maxYear: 2025, icon: "pizza" },
        { name: "Volle Tank Benzine", price: 75.0, minYear: 1970, maxYear: 2025, icon: "fuel" },
        { name: "Digitale Wekker", price: 20.0, minYear: 1970, maxYear: 2025, icon: "alarm" },
        { name: "Transistorradio", price: 40.0, minYear: 1970, maxYear: 2000, icon: "radio" },
        { name: "Walkman", price: 60.0, minYear: 1979, maxYear: 2005, icon: "walkman" },
        { name: "Rekenmachine", price: 15.0, minYear: 1975, maxYear: 2025, icon: "calculator" },
        { name: "Cassettebandje", price: 10.0, minYear: 1980, maxYear: 2005, icon: "cassette" },
        { name: "VHS-Band", price: 20.0, minYear: 1980, maxYear: 2010, icon: "vhs" },
        { name: "VHS-Huur", price: 3.0, minYear: 1985, maxYear: 2010, icon: "vhs_rental" },
        { name: "8-bit Console", price: 200.0, minYear: 1985, maxYear: 2000, icon: "console_8bit" },
        { name: "Vaste Telefoon", price: 30.0, minYear: 1980, maxYear: 2025, icon: "phone" },
        { name: "Videocamera", price: 700.0, minYear: 1985, maxYear: 2010, icon: "videocamera" },
        { name: "Encyclopedie", price: 600.0, minYear: 1980, maxYear: 2005, icon: "encyclopedia" },
        { name: "Disquette", price: 2.0, minYear: 1980, maxYear: 2005, icon: "floppy" },
        { name: "Audio-CD", price: 18.0, minYear: 1990, maxYear: 2015, icon: "cd" },
        { name: "Videospiel", price: 70.0, minYear: 1990, maxYear: 2025, icon: "game" },
        { name: "Oude Mobiel", price: 300.0, minYear: 1995, maxYear: 2010, icon: "mobile" },
        { name: "PC Computer", price: 1200.0, minYear: 1995, maxYear: 2025, icon: "computer" },
        { name: "PlayStation", price: 400.0, minYear: 1995, maxYear: 2025, icon: "playstation" },
        { name: "Game Boy", price: 100.0, minYear: 1990, maxYear: 2010, icon: "gameboy" },
        {
            name: "Maandelijks Internet",
            price: 40.0,
            minYear: 1995,
            maxYear: 2025,
            icon: "internet",
        },
        {
            name: "Digitale Camera",
            price: 250.0,
            minYear: 1995,
            maxYear: 2025,
            icon: "digital_camera",
        },
        {
            name: "Starbucks Koffie",
            price: 4.5,
            minYear: 1999,
            maxYear: 2025,
            icon: "coffee_premium",
        },
        { name: "DVD-Film", price: 15.0, minYear: 2000, maxYear: 2020, icon: "dvd" },
        { name: "iPod", price: 350.0, minYear: 2001, maxYear: 2017, icon: "ipod" },
        { name: "Smartphone", price: 900.0, minYear: 2007, maxYear: 2025, icon: "smartphone" },
        { name: "Tablet", price: 500.0, minYear: 2010, maxYear: 2025, icon: "tablet" },
        { name: "E-Reader", price: 130.0, minYear: 2008, maxYear: 2025, icon: "ereader" },
        {
            name: "Streaming-Abonnement",
            price: 15.0,
            minYear: 2011,
            maxYear: 2025,
            icon: "streaming",
        },
        { name: "Draadloze Oortjes", price: 180.0, minYear: 2016, maxYear: 2025, icon: "earbuds" },
        { name: "Smartwatch", price: 300.0, minYear: 2014, maxYear: 2025, icon: "smartwatch" },
        { name: "Elektrische Step", price: 400.0, minYear: 2017, maxYear: 2025, icon: "scooter" },
        { name: "Air Fryer", price: 100.0, minYear: 2018, maxYear: 2025, icon: "airfryer" },
        { name: "AI-Abonnement", price: 22.0, minYear: 2023, maxYear: 2025, icon: "ai_sub" },
    ],
    cases: [
        {
            year: 1970,
            title: "Seat 600",
            price: "390€",
            description: "De droom van Spaanse gezinnen kostte ongeveer 65.000 peseta's.",
            color: "bg-indigo-100 text-indigo-800 border-indigo-200",
            icon: "car",
        },
        {
            year: 1982,
            title: "WK-Ticket Naranjito",
            price: "4,80€",
            description: "Een officieel ticket voor een WK-wedstrijd kostte 800 peseta's.",
            color: "bg-emerald-100 text-emerald-800 border-emerald-200",
            icon: "ticket",
        },
        {
            year: 1992,
            title: "Curro Mascotte Knuffel",
            price: "15€",
            description: "Het iconische souvenir van Expo '92 in Sevilla kostte 2.500 peseta's.",
            color: "bg-rose-100 text-rose-800 border-rose-200",
            icon: "toy",
        },
        {
            year: 1995,
            title: "PlayStation 1 Lancement",
            price: "360€",
            description: "Kwam naar Europa voor 59.900 peseta's.",
            color: "bg-amber-100 text-amber-800 border-amber-200",
            icon: "game",
        },
        {
            year: 1998,
            title: "Nokia 5110",
            price: "150€",
            description: "De onverwoestbare telefoon met Snake kostte 25.000 peseta's.",
            color: "bg-yellow-100 text-yellow-800 border-yellow-200",
            icon: "mobile",
        },
        {
            year: 2002,
            title: "Eerste Euro-Koffie",
            price: "0,60€",
            description: "Kostte precies 100 peseta's bij de euro-overgang.",
            color: "bg-orange-100 text-orange-800 border-orange-200",
            icon: "coffee",
        },
    ],
    sourcesTitle: "Officiële Bronnen en Gegevens",
    sourcesSubtitle: "Instellingen en bureaus die de reële impact op de economie meten.",
    sourcesBadge: "Documentatie",
    reportTitle: "Bijlage I: Macro-economisch Rapport",
    reportSubtitle:
        "Vergelijkende analyse van prijsontwikkeling en koopkracht in Spanje (1980-2025).",
    table1Title: "Ontwikkeling van de Lebenskosten",
    table1Ref: "Ref: INE / Krantenarchieven / Ministeries",
    thConcept: "Concept",
    thYear: "Jaar",
    thHistPrice: "Historische Prijs",
    thPrice2025: "Prijs 2025",
    thVar: "Verand. %",
    thSource: "Bron",
    table2Title: "Loonontwikkeling",
    thAvgSalary: "Gemiddeld Jaarsalaris",
    thSmiMonthly: "Maandelijks Minimumloon (14x)",
    thSmiTotal: "Totaal Minimumloon per Jaar",
    noteTitle: "Methodologische Opmerking",
    noteP1: "De gegevens in dit rapport zijn omgerekend naar huidige euro's (1€ = 166.386 ptas).",
    noteP2: 'Belangrijk: De kolom "Verand. %" toont de nominale prijsstijging.',
    noteSources: "Bronnen: INE, Bank van Spanje, Ministerie van Huisvesting en krantenarchieven.",
    reportTable1Rows: [
        {
            concept: "Woning (80m² Appartement)",
            year: 1985,
            priceHist: "27.000€ (4,5M ptas)",
            price2025: "287.000€",
            varPercent: "+963%",
            isPositive: false,
            sourceName: "Ministerie Huisvesting",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "Minimumloon",
            year: 1980,
            priceHist: "154€ (25.620 ptas)",
            price2025: "1.134€",
            varPercent: "+636%",
            isPositive: true,
            sourceName: "BOE",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "Brood (250g Stokbrood)",
            year: 1985,
            priceHist: "0,12€ (20 ptas)",
            price2025: "1,20€",
            varPercent: "+900%",
            isPositive: false,
            sourceName: "INE (CPI)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "Benzine (Liter)",
            year: 1980,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,65€",
            varPercent: "+511%",
            isPositive: false,
            sourceName: "Ministerie Energie",
            sourceUrl: "https://www.miteco.gob.es",
        },
        {
            concept: "Bioscoopkaartje",
            year: 1980,
            priceHist: "1,20€ (200 ptas)",
            price2025: "9,00€",
            varPercent: "+650%",
            isPositive: false,
            sourceName: "Krantenarchief",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "Personenauto",
            year: 1985,
            priceHist: "4.500€ (750k ptas)",
            price2025: "24.000€",
            varPercent: "+433%",
            isPositive: false,
            sourceName: "Autotijdschriften",
            sourceTitle: "Motor Clásico / Autopista",
        },
        {
            concept: "Krant",
            year: 1985,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,80€",
            varPercent: "+566%",
            isPositive: false,
            sourceName: "Krantenarchief",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "Olijfolie (1L)",
            year: 2000,
            priceHist: "1,20€ (200 ptas)",
            price2025: "10,00€",
            varPercent: "+733%",
            isPositive: false,
            sourceName: "INE (CPI)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "Koffie (Horeca)",
            year: 1990,
            priceHist: "0,48€ (80 ptas)",
            price2025: "1,50€",
            varPercent: "+212%",
            isPositive: false,
            sourceName: "Horecabond",
            sourceTitle: "Horecabonden",
        },
    ],
    hiddenTypesCards: [
        {
            badge: "MINDER VOOR HETZELFDE",
            title: "Krimpflatie",
            graphicLabel1: "CHIPS",
            graphicLabel2: "NIEUW FORMAT",
            graphicLegend1: "243g (Voorheen 295g)",
            graphicLegend2: "Prijs: +15%",
            tagline: '"Ze verkopen je lucht voor de prijs van eten."',
            description: "Chipsverpakkingen krompen van 295g naar 243g terwijl de prijs steeg.",
            sourceText: "Bron: FACUA Studie",
            shareText: "Krimpflatie is echt!",
        },
        {
            badge: "SLCHTER VOOR HETZELFDE",
            title: "Skimpflatie",
            graphicLabel1: "VERBETERD RECEPT",
            graphicLabel2: "INGREDIËNTEN:",
            graphicRemoved1: "Zonnebloemolie",
            graphicAdded1: "Palmvacht/Mix",
            graphicRemoved2: "Boter",
            graphicAdded2: "Plantaardige oliën",
            tagline: '"Goede ingrediënten worden vervangen door goedkope alternatieven."',
            description: "Zonnebloemolie werd vervangen door palmolie.",
            sourceText: "Bron: NPR (Skimpflatie)",
            shareText: "Skimpflatie verslechtert de kwaliteit!",
        },
        {
            badge: "VLUCHT NAAR BOVEN",
            title: "Premiumisering",
            graphicLabel1: "Platinum",
            graphicLabel2: "ULTRA PRO",
            graphicLegend1: "12,99€",
            graphicLegend2: "UITVERKOCHT!",
            graphicRemoved1: "Basis",
            graphicAdded1: "2,99€",
            tagline: '"Het basisaanbod verdwijnt om luxe-opties af te dwingen."',
            description: "Eenvoudige yoghurt maakt plaats voor dure eiwitvarianten.",
            sourceText: "Bron: CESCE (Premiumisering)",
            shareText: "Premiumisering verwijdert basisproducten!",
        },
        {
            badge: "JIJ BENT DE WERKNEMER",
            title: "Schaduwinflatie",
            graphicLabel1: "FOUT: WACHT OP ASSISTENTIE",
            graphicLabel2: "Jouw Loon: 0€/uur",
            tagline: '"Je werkt gratis voor de supermarkt en betaalt dezelfde prijs."',
            description: "Zelfscankassa's verleggen de arbeid naar de klant zonder korting.",
            sourceText: "Bron: The Guardian (Shadow Work)",
            shareText: "Schaduwinflatie laat je gratis werken!",
        },
    ],
};
