import type { InflationLocaleData } from "../types";
import { INFLATION_EN_TEXTS } from "./en";

export const INFLATION_PL_TEXTS: InflationLocaleData = {
    ...INFLATION_EN_TEXTS,
    cardTitle: "Inflacja",
    cardSubtitle: "Co można było kupić za 100€ kiedyś a co dzisiaj?",
    cardDescription:
        "Odkryj ewolucję siły nabywczej poprzez porównania rzeczywistych cen, dane o wynagrodzeniach i archiwa historyczne.",
    title: "INFLACJA",
    billTitle: "BANKNOT 100€",
    billYearLabel: "Rok",
    billValueLabel: "Równoważna wartość dzisiaj",
    casesTitle: "Nostalgia vs Rzeczywistość",
    casesSubtitle: "Przesuń, aby zobaczyć realne przykłady zmian cen",
    shareButton: "Udostępnij",
    infoTitle: "Dlaczego za 100€ nie kupimy już tego, co kiedyś?",
    infoP1: "Inflacja to ogólny i ciągły wzrost cen. Z upływem czasu każda jednostka waluty kupuje mniejszy procent dóbr lub usług.",
    infoP2: "Często wspominamy dawne ceny z nostalgijką, ale zapominamy, że pensje były wtedy również znacznie niższe.",
    infoP3: "Zrozumienie inflacji pomaga podejmować lepsze długoterminowe decyzje finansowe i chronić swoją siłę nabywczą.",
    items: [
        { name: "Chleb", price: 1.2, minYear: 1950, maxYear: 2025, icon: "bread" },
        { name: "Mleko", price: 1.0, minYear: 1950, maxYear: 2025, icon: "milk" },
        { name: "Kawa", price: 1.6, minYear: 1950, maxYear: 2025, icon: "coffee" },
        { name: "Piwo", price: 3.0, minYear: 1950, maxYear: 2025, icon: "beer" },
        { name: "Książka", price: 22.0, minYear: 1950, maxYear: 2025, icon: "book" },
        { name: "Koszulka", price: 20.0, minYear: 1950, maxYear: 2025, icon: "shirt" },
        { name: "Buty", price: 90.0, minYear: 1950, maxYear: 2025, icon: "shoe" },
        { name: "Biżuteria", price: 500.0, minYear: 1950, maxYear: 2025, icon: "diamond" },
        { name: "Samochód", price: 22000.0, minYear: 1950, maxYear: 2025, icon: "car" },
        { name: "Mieszkanie", price: 250000.0, minYear: 1950, maxYear: 2025, icon: "house" },
        {
            name: "Kolacja w Restauracji",
            price: 45.0,
            minYear: 1950,
            maxYear: 2025,
            icon: "restaurant",
        },
        { name: "Gazeta", price: 2.0, minYear: 1950, maxYear: 2025, icon: "newspaper" },
        { name: "Znaczek Pocztowy", price: 1.0, minYear: 1950, maxYear: 2025, icon: "mail" },
        { name: "Bilet do Kina", price: 9.5, minYear: 1950, maxYear: 2025, icon: "movie" },
        { name: "Płyta Winylowa", price: 30.0, minYear: 1950, maxYear: 2025, icon: "vinyl" },
        { name: "Bilet na Koncert", price: 60.0, minYear: 1950, maxYear: 2025, icon: "concert" },
        { name: "TV Czarno-Biały", price: 800.0, minYear: 1950, maxYear: 1980, icon: "tv_old" },
        { name: "Zegarek na Rękę", price: 80.0, minYear: 1950, maxYear: 2025, icon: "watch" },
        { name: "Bilet do Teatru", price: 25.0, minYear: 1950, maxYear: 2025, icon: "theater" },
        { name: "Rolka Filmu", price: 12.0, minYear: 1950, maxYear: 2015, icon: "photo_roll" },
        {
            name: "Aparat Fotograficzny",
            price: 300.0,
            minYear: 1950,
            maxYear: 2025,
            icon: "camera",
        },
        { name: "Papierosy", price: 5.0, minYear: 1950, maxYear: 2025, icon: "cigarette" },
        { name: "Single 45 obr./min", price: 8.0, minYear: 1960, maxYear: 1995, icon: "single" },
        { name: "TV Kolorowy", price: 1200.0, minYear: 1965, maxYear: 2010, icon: "tv_color" },
        { name: "Gramofon", price: 150.0, minYear: 1960, maxYear: 2000, icon: "turntable" },
        { name: "Bilet na Mecz", price: 45.0, minYear: 1960, maxYear: 2025, icon: "football" },
        { name: "Zestaw Burger", price: 11.0, minYear: 1970, maxYear: 2025, icon: "burger" },
        { name: "Pizza", price: 14.0, minYear: 1970, maxYear: 2025, icon: "pizza" },
        { name: "Pełny Bak Paliwa", price: 75.0, minYear: 1970, maxYear: 2025, icon: "fuel" },
        { name: "Cyfrowy Budzik", price: 20.0, minYear: 1970, maxYear: 2025, icon: "alarm" },
        { name: "Radio Tranzystorowe", price: 40.0, minYear: 1970, maxYear: 2000, icon: "radio" },
        { name: "Walkman", price: 60.0, minYear: 1979, maxYear: 2005, icon: "walkman" },
        { name: "Kalkulator", price: 15.0, minYear: 1975, maxYear: 2025, icon: "calculator" },
        {
            name: "Kaseta Magnetofonowa",
            price: 10.0,
            minYear: 1980,
            maxYear: 2005,
            icon: "cassette",
        },
        { name: "Kaseta VHS", price: 20.0, minYear: 1980, maxYear: 2010, icon: "vhs" },
        { name: "Wypożyczenie VHS", price: 3.0, minYear: 1985, maxYear: 2010, icon: "vhs_rental" },
        { name: "Konsola 8-bit", price: 200.0, minYear: 1985, maxYear: 2000, icon: "console_8bit" },
        { name: "Telefon Stacjonarny", price: 30.0, minYear: 1980, maxYear: 2025, icon: "phone" },
        { name: "Kamera Wideo", price: 700.0, minYear: 1985, maxYear: 2010, icon: "videocamera" },
        { name: "Encyklopedia", price: 600.0, minYear: 1980, maxYear: 2005, icon: "encyclopedia" },
        { name: "Dyskietka", price: 2.0, minYear: 1980, maxYear: 2005, icon: "floppy" },
        { name: "Płyta CD", price: 18.0, minYear: 1990, maxYear: 2015, icon: "cd" },
        { name: "Gra Wideo", price: 70.0, minYear: 1990, maxYear: 2025, icon: "game" },
        { name: "Stary Telefon", price: 300.0, minYear: 1995, maxYear: 2010, icon: "mobile" },
        { name: "Komputer PC", price: 1200.0, minYear: 1995, maxYear: 2025, icon: "computer" },
        { name: "PlayStation", price: 400.0, minYear: 1995, maxYear: 2025, icon: "playstation" },
        { name: "Game Boy", price: 100.0, minYear: 1990, maxYear: 2010, icon: "gameboy" },
        {
            name: "Miesięczny Internet",
            price: 40.0,
            minYear: 1995,
            maxYear: 2025,
            icon: "internet",
        },
        {
            name: "Aparat Cyfrowy",
            price: 250.0,
            minYear: 1995,
            maxYear: 2025,
            icon: "digital_camera",
        },
        {
            name: "Kawa Starbucks",
            price: 4.5,
            minYear: 1999,
            maxYear: 2025,
            icon: "coffee_premium",
        },
        { name: "Film DVD", price: 15.0, minYear: 2000, maxYear: 2020, icon: "dvd" },
        { name: "iPod", price: 350.0, minYear: 2001, maxYear: 2017, icon: "ipod" },
        { name: "Smartfon", price: 900.0, minYear: 2007, maxYear: 2025, icon: "smartphone" },
        { name: "Tablet", price: 500.0, minYear: 2010, maxYear: 2025, icon: "tablet" },
        { name: "Czytnik e-Book", price: 130.0, minYear: 2008, maxYear: 2025, icon: "ereader" },
        {
            name: "Abonament Streaming",
            price: 15.0,
            minYear: 2011,
            maxYear: 2025,
            icon: "streaming",
        },
        {
            name: "Słuchawki Bezprzewodowe",
            price: 180.0,
            minYear: 2016,
            maxYear: 2025,
            icon: "earbuds",
        },
        { name: "Smartwatch", price: 300.0, minYear: 2014, maxYear: 2025, icon: "smartwatch" },
        {
            name: "Hulajnoga Elektryczna",
            price: 400.0,
            minYear: 2017,
            maxYear: 2025,
            icon: "scooter",
        },
        { name: "Air Fryer", price: 100.0, minYear: 2018, maxYear: 2025, icon: "airfryer" },
        { name: "Subskrypcja AI", price: 22.0, minYear: 2023, maxYear: 2025, icon: "ai_sub" },
    ],
    cases: [
        {
            year: 1970,
            title: "Seat 600",
            price: "390€",
            description: "Marzenie hiszpańskich rodzin kosztowało około 65 000 peset.",
            color: "bg-indigo-100 text-indigo-800 border-indigo-200",
            icon: "car",
        },
        {
            year: 1982,
            title: "Bilet na Mundial Naranjito",
            price: "4,80€",
            description: "Oficjalny bilet na mecz Mistrzostw Świata kosztował 800 peset.",
            color: "bg-emerald-100 text-emerald-800 border-emerald-200",
            icon: "ticket",
        },
        {
            year: 1992,
            title: "Maskotka Curro",
            price: "15€",
            description: "Kultowa pamiątka z Expo '92 w Sewilli kosztowała 2 500 peset.",
            color: "bg-rose-100 text-rose-800 border-rose-200",
            icon: "toy",
        },
        {
            year: 1995,
            title: "Premiera PlayStation 1",
            price: "360€",
            description: "Trafiła do Europy za 59 900 peset.",
            color: "bg-amber-100 text-amber-800 border-amber-200",
            icon: "game",
        },
        {
            year: 1998,
            title: "Nokia 5110",
            price: "150€",
            description: "Niezniszczalny telefon z grą Snake kosztował 25 000 peset.",
            color: "bg-yellow-100 text-yellow-800 border-yellow-200",
            icon: "mobile",
        },
        {
            year: 2002,
            title: "Pierwsza Kawa w Euro",
            price: "0,60€",
            description: "Kosztowała 100 peset dokładnie w momencie przejścia na euro.",
            color: "bg-orange-100 text-orange-800 border-orange-200",
            icon: "coffee",
        },
    ],
    sourcesTitle: "Oficjalne Źródła i Dane",
    sourcesSubtitle: "Instytucje mierzące rzeczywisty wpływ na gospodarkę.",
    sourcesBadge: "Dokumentacja",
    reportTitle: "Załącznik I: Raport Makroekonomiczny",
    reportSubtitle: "Analiza porównawcza ewolucji cen i siły nabywczej w Hiszpanii (1980-2025).",
    table1Title: "Ewolucja Kosztów Życia",
    table1Ref: "Ref: INE / Archiwa Prasowe / Ministerstwa",
    thConcept: "Koncepcja",
    thYear: "Rok",
    thHistPrice: "Cena Historyczna",
    thPrice2025: "Cena 2025",
    thVar: "Zmiana %",
    thSource: "Źródło",
    table2Title: "Ewolucja Wynagrodzeń",
    thAvgSalary: "Średnie Wynagrodzenie Roczne",
    thSmiMonthly: "Miesięczne Wynagrodzenie Minimalne (14 wypłat)",
    thSmiTotal: "Roczne Wynagrodzenie Minimalne Ogółem",
    noteTitle: "Uwaga Metodologiczna",
    noteP1: "Dane w tym raporcie przeliczono na obecne euro (1€ = 166.386 ptas).",
    noteP2: 'Ważne: Kolumna "Zmiana %" odzwierciedla nominalny wzrost cen.',
    noteSources: "Źródła: INE, Bank Hiszpanii, Ministerstwo Mieszkalnictwa i archiwum prasowe.",
    reportTable1Rows: [
        {
            concept: "Mieszkanie (80m²)",
            year: 1985,
            priceHist: "27.000€ (4.5M ptas)",
            price2025: "287.000€",
            varPercent: "+963%",
            isPositive: false,
            sourceName: "Ministerstwo Mieszkalnictwa",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "Wynagrodzenie Minimalne",
            year: 1980,
            priceHist: "154€ (25.620 ptas)",
            price2025: "1.134€",
            varPercent: "+636%",
            isPositive: true,
            sourceName: "BOE",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "Chleb (Bagietka 250g)",
            year: 1985,
            priceHist: "0,12€ (20 ptas)",
            price2025: "1,20€",
            varPercent: "+900%",
            isPositive: false,
            sourceName: "INE (CPI)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "Benzyna (Litr)",
            year: 1980,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,65€",
            varPercent: "+511%",
            isPositive: false,
            sourceName: "Ministerstwo Energii",
            sourceUrl: "https://www.miteco.gob.es",
        },
        {
            concept: "Bilet do Kina",
            year: 1980,
            priceHist: "1,20€ (200 ptas)",
            price2025: "9,00€",
            varPercent: "+650%",
            isPositive: false,
            sourceName: "Archiwum Prasowe",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "Samochód Osobowy",
            year: 1985,
            priceHist: "4.500€ (750k ptas)",
            price2025: "24.000€",
            varPercent: "+433%",
            isPositive: false,
            sourceName: "Czasopisma Auto",
            sourceTitle: "Motor Clásico / Autopista",
        },
        {
            concept: "Gazeta",
            year: 1985,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,80€",
            varPercent: "+566%",
            isPositive: false,
            sourceName: "Archiwum Prasowe",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "Oliwa z Oliwek (1L)",
            year: 2000,
            priceHist: "1,20€ (200 ptas)",
            price2025: "10,00€",
            varPercent: "+733%",
            isPositive: false,
            sourceName: "INE (CPI)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "Kawa (Kawiarnia)",
            year: 1990,
            priceHist: "0,48€ (80 ptas)",
            price2025: "1,50€",
            varPercent: "+212%",
            isPositive: false,
            sourceName: "Związek Gastronomii",
            sourceTitle: "Związki Gastronomii",
        },
    ],
    hiddenTypesCards: [
        {
            badge: "MNIEJ ZA TYLE SAMO",
            title: "Shrinkflacja",
            graphicLabel1: "CHIPSY",
            graphicLabel2: "NOWY FORMAT",
            graphicLegend1: "243g (Wcześniej 295g)",
            graphicLegend2: "Cena: +15%",
            tagline: '"Sprzedają ci powietrze w cenie jedzenia."',
            description: "Paczki chipsów zmniejszyły się z 295g do 243g przy wzroście ceny.",
            sourceText: "Źródło: Badanie FACUA",
            shareText: "Shrinkflacja jest faktem!",
        },
        {
            badge: "GORZEJ ZA TYLE SAMO",
            title: "Skimpflacja",
            graphicLabel1: "ULEPSZONA RECEPTURA",
            graphicLabel2: "SKŁADNIKI:",
            graphicRemoved1: "Olej Słonecznikowy",
            graphicAdded1: "Tłuszcz Palmowy/Mix",
            graphicRemoved2: "Masło",
            graphicAdded2: "Oleje Roślinne",
            tagline: '"Zastępują dobre składniki tanimi zamiennikami."',
            description: "Olej słonecznikowy zastąpiono olejem palmowym.",
            sourceText: "Źródło: NPR (Skimpflacja)",
            shareText: "Skimpflacja pogarsza jakość!",
        },
        {
            badge: "UCIECZKA W GÓRĘ",
            title: "Premiumizacja",
            graphicLabel1: "Platinum",
            graphicLabel2: "ULTRA PRO",
            graphicLegend1: "12,99€",
            graphicLegend2: "WYSPRZEDANE!",
            graphicRemoved1: "Podstawowy",
            graphicAdded1: "2.99€",
            tagline: '"Usuwają podstawową ofertę, aby wymusić zakup opcji luksusowych."',
            description: "Moda na warianty wysokobiałkowe wyparła zwykłe jogurty.",
            sourceText: "Źródło: CESCE (Premiumizacja)",
            shareText: "Premiumizacja likwiduje podstawowe produkty!",
        },
        {
            badge: "TY JESTEŚ PRACOWNIKIEM",
            title: "Inflacja Cienia",
            graphicLabel1: "BŁĄD: CZEKAJ NA ASYSTĘ",
            graphicLabel2: "Twoja Stawka: 0€/godz.",
            tagline: '"Pracujesz za darmo dla marketu i płacisz tę samą cenę."',
            description: "Kasy samoobsługowe przerzucają pracę na klienta bez obniżki ceny.",
            sourceText: "Źródło: The Guardian (Shadow Work)",
            shareText: "Inflacja cienia zmusza do darmowej pracy!",
        },
    ],
};
