import type { InflationLocaleData } from "../types";
import { INFLATION_EN_TEXTS } from "./en";

export const INFLATION_PT_TEXTS: InflationLocaleData = {
    ...INFLATION_EN_TEXTS,
    cardTitle: "A Inflação",
    cardSubtitle: "O que podia comprar com 100€ antes em comparação com hoje?",
    cardDescription:
        "Explore a evolução do poder de compra através de comparações reais de preços, dados salariais e registos históricos.",
    title: "A INFLAÇÃO",
    billTitle: "NOTA DE 100€",
    billYearLabel: "Ano",
    billValueLabel: "Valor equivalente hoje",
    casesTitle: "Nostalgia vs Realidade",
    casesSubtitle: "Deslize para ver casos reais de mudança de preços",
    shareButton: "Partilhar",
    infoTitle: "Por que motivo 100€ já não compram o mesmo que compravam?",
    infoP1: "A inflação é o aumento geral e contínuo dos preços. Com o passar do tempo, cada unidade monetária compra uma percentagem menor de um bem ou serviço.",
    infoP2: "Lembramo-nos frequentemente dos preços do passado com nostalgia, mas esquecemo-nos de que os salários também eram muito mais baixos.",
    infoP3: "Compreender a inflação ajuda a tomar melhores decisões financeiras a longo prazo e a proteger o seu poder de compra.",
    items: [
        { name: "Pão", price: 1.2, minYear: 1950, maxYear: 2025, icon: "bread" },
        { name: "Leite", price: 1.0, minYear: 1950, maxYear: 2025, icon: "milk" },
        { name: "Café", price: 1.6, minYear: 1950, maxYear: 2025, icon: "coffee" },
        { name: "Cerveja", price: 3.0, minYear: 1950, maxYear: 2025, icon: "beer" },
        { name: "Livro", price: 22.0, minYear: 1950, maxYear: 2025, icon: "book" },
        { name: "T-Shirt", price: 20.0, minYear: 1950, maxYear: 2025, icon: "shirt" },
        { name: "Sapatos", price: 90.0, minYear: 1950, maxYear: 2025, icon: "shoe" },
        { name: "Jóia", price: 500.0, minYear: 1950, maxYear: 2025, icon: "diamond" },
        { name: "Carro", price: 22000.0, minYear: 1950, maxYear: 2025, icon: "car" },
        { name: "Apartamento", price: 250000.0, minYear: 1950, maxYear: 2025, icon: "house" },
        {
            name: "Jantar em Restaurante",
            price: 45.0,
            minYear: 1950,
            maxYear: 2025,
            icon: "restaurant",
        },
        { name: "Jornal", price: 2.0, minYear: 1950, maxYear: 2025, icon: "newspaper" },
        { name: "Selo Correio", price: 1.0, minYear: 1950, maxYear: 2025, icon: "mail" },
        { name: "Bilhete de Cinema", price: 9.5, minYear: 1950, maxYear: 2025, icon: "movie" },
        { name: "Disco de Vinil", price: 30.0, minYear: 1950, maxYear: 2025, icon: "vinyl" },
        { name: "Bilhete de Concerto", price: 60.0, minYear: 1950, maxYear: 2025, icon: "concert" },
        { name: "TV Preto e Branco", price: 800.0, minYear: 1950, maxYear: 1980, icon: "tv_old" },
        { name: "Relógio de Pulso", price: 80.0, minYear: 1950, maxYear: 2025, icon: "watch" },
        { name: "Entrada Teatro", price: 25.0, minYear: 1950, maxYear: 2025, icon: "theater" },
        { name: "Rolo Fotográfico", price: 12.0, minYear: 1950, maxYear: 2015, icon: "photo_roll" },
        { name: "Câmara Fotográfica", price: 300.0, minYear: 1950, maxYear: 2025, icon: "camera" },
        { name: "Tabaco", price: 5.0, minYear: 1950, maxYear: 2025, icon: "cigarette" },
        { name: "Single 45rpm", price: 8.0, minYear: 1960, maxYear: 1995, icon: "single" },
        { name: "TV a Cores", price: 1200.0, minYear: 1965, maxYear: 2010, icon: "tv_color" },
        { name: "Gira-discos", price: 150.0, minYear: 1960, maxYear: 2000, icon: "turntable" },
        { name: "Bilhete de Futebol", price: 45.0, minYear: 1960, maxYear: 2025, icon: "football" },
        { name: "Menu Burger", price: 11.0, minYear: 1970, maxYear: 2025, icon: "burger" },
        { name: "Pizza", price: 14.0, minYear: 1970, maxYear: 2025, icon: "pizza" },
        {
            name: "Depósito de Combustível",
            price: 75.0,
            minYear: 1970,
            maxYear: 2025,
            icon: "fuel",
        },
        { name: "Despertador Digital", price: 20.0, minYear: 1970, maxYear: 2025, icon: "alarm" },
        { name: "Rádio Transístor", price: 40.0, minYear: 1970, maxYear: 2000, icon: "radio" },
        { name: "Walkman", price: 60.0, minYear: 1979, maxYear: 2005, icon: "walkman" },
        { name: "Calculadora", price: 15.0, minYear: 1975, maxYear: 2025, icon: "calculator" },
        { name: "Cassete", price: 10.0, minYear: 1980, maxYear: 2005, icon: "cassette" },
        { name: "Cassete VHS", price: 20.0, minYear: 1980, maxYear: 2010, icon: "vhs" },
        { name: "Aluguer VHS", price: 3.0, minYear: 1985, maxYear: 2010, icon: "vhs_rental" },
        { name: "Consola 8-bit", price: 200.0, minYear: 1985, maxYear: 2000, icon: "console_8bit" },
        { name: "Telefone Fixo", price: 30.0, minYear: 1980, maxYear: 2025, icon: "phone" },
        {
            name: "Câmara de Vídeo",
            price: 700.0,
            minYear: 1985,
            maxYear: 2010,
            icon: "videocamera",
        },
        { name: "Enciclopédia", price: 600.0, minYear: 1980, maxYear: 2005, icon: "encyclopedia" },
        { name: "Disquete", price: 2.0, minYear: 1980, maxYear: 2005, icon: "floppy" },
        { name: "CD Audio", price: 18.0, minYear: 1990, maxYear: 2015, icon: "cd" },
        { name: "Videojogo", price: 70.0, minYear: 1990, maxYear: 2025, icon: "game" },
        { name: "Telemóvel Antigo", price: 300.0, minYear: 1995, maxYear: 2010, icon: "mobile" },
        { name: "Computador PC", price: 1200.0, minYear: 1995, maxYear: 2025, icon: "computer" },
        { name: "PlayStation", price: 400.0, minYear: 1995, maxYear: 2025, icon: "playstation" },
        { name: "Game Boy", price: 100.0, minYear: 1990, maxYear: 2010, icon: "gameboy" },
        { name: "Internet Mensal", price: 40.0, minYear: 1995, maxYear: 2025, icon: "internet" },
        {
            name: "Câmara Digital",
            price: 250.0,
            minYear: 1995,
            maxYear: 2025,
            icon: "digital_camera",
        },
        {
            name: "Café Starbucks",
            price: 4.5,
            minYear: 1999,
            maxYear: 2025,
            icon: "coffee_premium",
        },
        { name: "Filme DVD", price: 15.0, minYear: 2000, maxYear: 2020, icon: "dvd" },
        { name: "iPod", price: 350.0, minYear: 2001, maxYear: 2017, icon: "ipod" },
        { name: "Smartphone", price: 900.0, minYear: 2007, maxYear: 2025, icon: "smartphone" },
        { name: "Tablet", price: 500.0, minYear: 2010, maxYear: 2025, icon: "tablet" },
        { name: "Leitor e-Book", price: 130.0, minYear: 2008, maxYear: 2025, icon: "ereader" },
        { name: "Plano Streaming", price: 15.0, minYear: 2011, maxYear: 2025, icon: "streaming" },
        {
            name: "Auriculares Sem Fios",
            price: 180.0,
            minYear: 2016,
            maxYear: 2025,
            icon: "earbuds",
        },
        { name: "Smartwatch", price: 300.0, minYear: 2014, maxYear: 2025, icon: "smartwatch" },
        { name: "Trotinete Elétrica", price: 400.0, minYear: 2017, maxYear: 2025, icon: "scooter" },
        {
            name: "Fritadeira sem Óleo",
            price: 100.0,
            minYear: 2018,
            maxYear: 2025,
            icon: "airfryer",
        },
        { name: "Subscrição IA", price: 22.0, minYear: 2023, maxYear: 2025, icon: "ai_sub" },
    ],
    cases: [
        {
            year: 1970,
            title: "Seat 600",
            price: "390€",
            description: "O sonho das famílias espanholas custava cerca de 65.000 pesetas.",
            color: "bg-indigo-100 text-indigo-800 border-indigo-200",
            icon: "car",
        },
        {
            year: 1982,
            title: "Bilhete Mundial Naranjito",
            price: "4,80€",
            description: "Um bilhete oficial para um jogo do Mundial custava 800 pesetas.",
            color: "bg-emerald-100 text-emerald-800 border-emerald-200",
            icon: "ticket",
        },
        {
            year: 1992,
            title: "Peluche Mascote Curro",
            price: "15€",
            description: "A recordação emblemática da Expo '92 em Sevilha custava 2.500 pesetas.",
            color: "bg-rose-100 text-rose-800 border-rose-200",
            icon: "toy",
        },
        {
            year: 1995,
            title: "Lançamento PlayStation 1",
            price: "360€",
            description: "Chegou à Europa por 59.900 pesetas.",
            color: "bg-amber-100 text-amber-800 border-amber-200",
            icon: "game",
        },
        {
            year: 1998,
            title: "Nokia 5110",
            price: "150€",
            description: "O telemóvel indestrutível com Snake custava 25.000 pesetas.",
            color: "bg-yellow-100 text-yellow-800 border-yellow-200",
            icon: "mobile",
        },
        {
            year: 2002,
            title: "Primeiro Café em Euro",
            price: "0,60€",
            description: "Custava 100 pesetas exatamente na transição para o euro.",
            color: "bg-orange-100 text-orange-800 border-orange-200",
            icon: "coffee",
        },
    ],
    sourcesTitle: "Fontes Oficiais e Dados",
    sourcesSubtitle: "Instituições e organismos que medem o impacto real na economia.",
    sourcesBadge: "Documentação",
    reportTitle: "Anexo I: Relatório Macroeconómico",
    reportSubtitle:
        "Análise comparativa da evolução de preços e poder de compra em Espanha (1980-2025).",
    table1Title: "Evolução do Custo de Vida",
    table1Ref: "Ref: INE / Hemerotecas / Ministérios",
    thConcept: "Conceito",
    thYear: "Ano",
    thHistPrice: "Preço Histórico",
    thPrice2025: "Preço 2025",
    thVar: "Var. %",
    thSource: "Fonte",
    table2Title: "Evolução Salarial",
    thAvgSalary: "Salário Médio Anual",
    thSmiMonthly: "Salário Mínimo Mensal (14m)",
    thSmiTotal: "Salário Mínimo Anual Total",
    noteTitle: "Nota Metodológica",
    noteP1: "Os dados apresentados neste relatório foram normalizados em Euros correntes para facilitar a comparação (1€ = 166,386 ptas).",
    noteP2: 'Importante: A coluna "Var. %" reflete o aumento nominal de preços.',
    noteSources: "Fontes: INE, Banco de Espanha, Ministério da Habitação e imprensa digital.",
    reportTable1Rows: [
        {
            concept: "Habitação (80m²)",
            year: 1985,
            priceHist: "27.000€ (4,5M ptas)",
            price2025: "287.000€",
            varPercent: "+963%",
            isPositive: false,
            sourceName: "Ministério Habitação",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "Salário Mínimo",
            year: 1980,
            priceHist: "154€ (25.620 ptas)",
            price2025: "1.134€",
            varPercent: "+636%",
            isPositive: true,
            sourceName: "BOE",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "Pão (Carcaça 250g)",
            year: 1985,
            priceHist: "0,12€ (20 ptas)",
            price2025: "1,20€",
            varPercent: "+900%",
            isPositive: false,
            sourceName: "INE (IPC)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "Gasolina (Litro)",
            year: 1980,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,65€",
            varPercent: "+511%",
            isPositive: false,
            sourceName: "Ministério Energia",
            sourceUrl: "https://www.miteco.gob.es",
        },
        {
            concept: "Bilhete de Cinema",
            year: 1980,
            priceHist: "1,20€ (200 ptas)",
            price2025: "9,00€",
            varPercent: "+650%",
            isPositive: false,
            sourceName: "Hemeroteca",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "Carro Utilitário",
            year: 1985,
            priceHist: "4.500€ (750k ptas)",
            price2025: "24.000€",
            varPercent: "+433%",
            isPositive: false,
            sourceName: "Revistas Auto",
            sourceTitle: "Motor Clásico / Autopista",
        },
        {
            concept: "Jornal",
            year: 1985,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,80€",
            varPercent: "+566%",
            isPositive: false,
            sourceName: "Hemeroteca",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "Azeite (1L)",
            year: 2000,
            priceHist: "1,20€ (200 ptas)",
            price2025: "10,00€",
            varPercent: "+733%",
            isPositive: false,
            sourceName: "INE (IPC)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "Café (Bar)",
            year: 1990,
            priceHist: "0,48€ (80 ptas)",
            price2025: "1,50€",
            varPercent: "+212%",
            isPositive: false,
            sourceName: "Assoc. Restauração",
            sourceTitle: "Assoc. Restauração",
        },
    ],
    hiddenTypesCards: [
        {
            badge: "MENOS PELO MESMO",
            title: "Reduflação",
            graphicLabel1: "BATATAS",
            graphicLabel2: "NOVO FORMATO",
            graphicLegend1: "243g (Antes 295g)",
            graphicLegend2: "Preço: +15%",
            tagline: '"Vendem-lhe ar a preço de comida."',
            description:
                "O caso das batatas fritas baixou de 295g para 243g enquanto o preço aumentou.",
            sourceText: "Fonte: Estudo FACUA",
            shareText: "A reduflação é real!",
        },
        {
            badge: "PIOR PELO MESMO",
            title: "Skimpflation",
            graphicLabel1: "RECEITA MELHORADA",
            graphicLabel2: "INGREDIENTES:",
            graphicRemoved1: "Óleo de Girassol",
            graphicAdded1: "Gordura de Palma/Mix",
            graphicRemoved2: "Manteiga",
            graphicAdded2: "Óleos Vegetais",
            tagline: '"Trocam os bons ingredientes por substitutos baratos."',
            description:
                "Muitas marcas substituíram o óleo de girassol por óleo de palma ou misturas vegetais.",
            sourceText: "Fonte: NPR (Skimpflation)",
            shareText: "A skimpflation reduz a qualidade!",
        },
        {
            badge: "A FUGA PARA CIMA",
            title: "Premiunização",
            graphicLabel1: "Platinum",
            graphicLabel2: "ULTRA PRO",
            graphicLegend1: "12,99€",
            graphicLegend2: "ESGOTADO!",
            graphicRemoved1: "Básico",
            graphicAdded1: "2,99€",
            tagline: '"Eliminam a gama básica para forçar a compra da gama de luxo."',
            description: "A febre 'High Protein' substituiu os iogurtes básicos por opções caras.",
            sourceText: "Fonte: CESCE (Premiunização)",
            shareText: "A premiunização elimina o básico!",
        },
        {
            badge: "VOCÊ É O EMPREGADO",
            title: "Inflação Sombra",
            graphicLabel1: "ERRO: AGUARDE ASSISTÊNCIA",
            graphicLabel2: "O seu Salário: 0€/hora",
            tagline: '"Trabalha de graça para o supermercado e paga o mesmo preço."',
            description:
                "As caixas automáticas transferem custos de trabalho para o cliente sem descontos.",
            sourceText: "Fonte: The Guardian (Shadow Work)",
            shareText: "A inflação sombra põe-no a trabalhar de graça!",
        },
    ],
};
