import type { InflationLocaleData } from "../types";
import { INFLATION_EN_TEXTS } from "./en";

export const INFLATION_RU_TEXTS: InflationLocaleData = {
    ...INFLATION_EN_TEXTS,
    cardTitle: "Инфляция",
    cardSubtitle: "Что можно было купить на 100€ раньше по сравнению с сегодняшним днем?",
    cardDescription:
        "Изучите эволюцию покупательной способности с помощью сравнения реальных цен, данных о зарплатах и исторических архивов.",
    title: "ИНФЛЯЦИЯ",
    billTitle: "БАНКНОТА 100€",
    billYearLabel: "Год",
    billValueLabel: "Эквивалентная стоимость сегодня",
    casesTitle: "Ностальгия против Реальности",
    casesSubtitle: "Смахните, чтобы увидеть реальные примеры изменения цен",
    shareButton: "Поделиться",
    infoTitle: "Почему на 100€ больше нельзя купить то, что раньше?",
    infoP1: "Инфляция — это общее и устойчивое повышение цен. Со временем каждая денежная единица покупает меньший процент товаров или услуг.",
    infoP2: "Мы часто с ностальгией вспоминаем прошлые цены, но забываем, что зарплаты тогда также были значительно ниже.",
    infoP3: "Понимание инфляции помогает принимать более грамотные долгосрочные финансовые решения и защищать свою покупательную способность.",
    items: [
        { name: "Хлеб", price: 1.2, minYear: 1950, maxYear: 2025, icon: "bread" },
        { name: "Молоко", price: 1.0, minYear: 1950, maxYear: 2025, icon: "milk" },
        { name: "Кофе", price: 1.6, minYear: 1950, maxYear: 2025, icon: "coffee" },
        { name: "Пиво", price: 3.0, minYear: 1950, maxYear: 2025, icon: "beer" },
        { name: "Книга", price: 22.0, minYear: 1950, maxYear: 2025, icon: "book" },
        { name: "Футболка", price: 20.0, minYear: 1950, maxYear: 2025, icon: "shirt" },
        { name: "Обувь", price: 90.0, minYear: 1950, maxYear: 2025, icon: "shoe" },
        {
            name: "Ювелирное украшение",
            price: 500.0,
            minYear: 1950,
            maxYear: 2025,
            icon: "diamond",
        },
        { name: "Машина", price: 22000.0, minYear: 1950, maxYear: 2025, icon: "car" },
        { name: "Квартира", price: 250000.0, minYear: 1950, maxYear: 2025, icon: "house" },
        { name: "Ужин в ресторане", price: 45.0, minYear: 1950, maxYear: 2025, icon: "restaurant" },
        { name: "Газета", price: 2.0, minYear: 1950, maxYear: 2025, icon: "newspaper" },
        { name: "Почтовая марка", price: 1.0, minYear: 1950, maxYear: 2025, icon: "mail" },
        { name: "Билет в кино", price: 9.5, minYear: 1950, maxYear: 2025, icon: "movie" },
        { name: "Виниловая пластинка", price: 30.0, minYear: 1950, maxYear: 2025, icon: "vinyl" },
        { name: "Билет на концерт", price: 60.0, minYear: 1950, maxYear: 2025, icon: "concert" },
        {
            name: "Черно-белый телевизор",
            price: 800.0,
            minYear: 1950,
            maxYear: 1980,
            icon: "tv_old",
        },
        { name: "Наручные часы", price: 80.0, minYear: 1950, maxYear: 2025, icon: "watch" },
        { name: "Билет в театр", price: 25.0, minYear: 1950, maxYear: 2025, icon: "theater" },
        { name: "Фотопленка", price: 12.0, minYear: 1950, maxYear: 2015, icon: "photo_roll" },
        { name: "Фотоаппарат", price: 300.0, minYear: 1950, maxYear: 2025, icon: "camera" },
        { name: "Сигареты", price: 5.0, minYear: 1950, maxYear: 2025, icon: "cigarette" },
        { name: "Сингл 45 об/мин", price: 8.0, minYear: 1960, maxYear: 1995, icon: "single" },
        {
            name: "Цветной телевизор",
            price: 1200.0,
            minYear: 1965,
            maxYear: 2010,
            icon: "tv_color",
        },
        {
            name: "Проигрыватель винила",
            price: 150.0,
            minYear: 1960,
            maxYear: 2000,
            icon: "turntable",
        },
        { name: "Футбольный билет", price: 45.0, minYear: 1960, maxYear: 2025, icon: "football" },
        { name: "Бургер-меню", price: 11.0, minYear: 1970, maxYear: 2025, icon: "burger" },
        { name: "Пицца", price: 14.0, minYear: 1970, maxYear: 2025, icon: "pizza" },
        { name: "Полный бак бензина", price: 75.0, minYear: 1970, maxYear: 2025, icon: "fuel" },
        { name: "Цифровой будильник", price: 20.0, minYear: 1970, maxYear: 2025, icon: "alarm" },
        {
            name: "Транзисторный приемник",
            price: 40.0,
            minYear: 1970,
            maxYear: 2000,
            icon: "radio",
        },
        { name: "Плеер Walkman", price: 60.0, minYear: 1979, maxYear: 2005, icon: "walkman" },
        { name: "Калькулятор", price: 15.0, minYear: 1975, maxYear: 2025, icon: "calculator" },
        { name: "Аудиокассета", price: 10.0, minYear: 1980, maxYear: 2005, icon: "cassette" },
        { name: "Видеокассета VHS", price: 20.0, minYear: 1980, maxYear: 2010, icon: "vhs" },
        { name: "Прокат VHS", price: 3.0, minYear: 1985, maxYear: 2010, icon: "vhs_rental" },
        {
            name: "8-битная приставка",
            price: 200.0,
            minYear: 1985,
            maxYear: 2000,
            icon: "console_8bit",
        },
        { name: "Домашний телефон", price: 30.0, minYear: 1980, maxYear: 2025, icon: "phone" },
        { name: "Видеокамера", price: 700.0, minYear: 1985, maxYear: 2010, icon: "videocamera" },
        { name: "Энциклопедия", price: 600.0, minYear: 1980, maxYear: 2005, icon: "encyclopedia" },
        { name: "Дискета", price: 2.0, minYear: 1980, maxYear: 2005, icon: "floppy" },
        { name: "Музыкальный CD", price: 18.0, minYear: 1990, maxYear: 2015, icon: "cd" },
        { name: "Видеоигра", price: 70.0, minYear: 1990, maxYear: 2025, icon: "game" },
        { name: "Старый мобильный", price: 300.0, minYear: 1995, maxYear: 2010, icon: "mobile" },
        { name: "Компьютер ПК", price: 1200.0, minYear: 1995, maxYear: 2025, icon: "computer" },
        { name: "PlayStation", price: 400.0, minYear: 1995, maxYear: 2025, icon: "playstation" },
        { name: "Game Boy", price: 100.0, minYear: 1990, maxYear: 2010, icon: "gameboy" },
        {
            name: "Ежемесячный интернет",
            price: 40.0,
            minYear: 1995,
            maxYear: 2025,
            icon: "internet",
        },
        {
            name: "Цифровой фотоаппарат",
            price: 250.0,
            minYear: 1995,
            maxYear: 2025,
            icon: "digital_camera",
        },
        {
            name: "Кофе Starbucks",
            price: 4.5,
            minYear: 1999,
            maxYear: 2025,
            icon: "coffee_premium",
        },
        { name: "DVD-фильм", price: 15.0, minYear: 2000, maxYear: 2020, icon: "dvd" },
        { name: "iPod", price: 350.0, minYear: 2001, maxYear: 2017, icon: "ipod" },
        { name: "Смартфон", price: 900.0, minYear: 2007, maxYear: 2025, icon: "smartphone" },
        { name: "Планшет", price: 500.0, minYear: 2010, maxYear: 2025, icon: "tablet" },
        { name: "Электронная книга", price: 130.0, minYear: 2008, maxYear: 2025, icon: "ereader" },
        {
            name: "Стриминговая подписка",
            price: 15.0,
            minYear: 2011,
            maxYear: 2025,
            icon: "streaming",
        },
        {
            name: "Беспроводные наушники",
            price: 180.0,
            minYear: 2016,
            maxYear: 2025,
            icon: "earbuds",
        },
        { name: "Умные часы", price: 300.0, minYear: 2014, maxYear: 2025, icon: "smartwatch" },
        { name: "Электросамокат", price: 400.0, minYear: 2017, maxYear: 2025, icon: "scooter" },
        { name: "Аэрогриль", price: 100.0, minYear: 2018, maxYear: 2025, icon: "airfryer" },
        { name: "Подписка на ИИ", price: 22.0, minYear: 2023, maxYear: 2025, icon: "ai_sub" },
    ],
    cases: [
        {
            year: 1970,
            title: "Seat 600",
            price: "390€",
            description: "Мечта испанских семей стоила около 65 000 песет.",
            color: "bg-indigo-100 text-indigo-800 border-indigo-200",
            icon: "car",
        },
        {
            year: 1982,
            title: "Билет на ЧМ Naranjito",
            price: "4,80€",
            description: "Официальный билет на матч Чемпионата мира стоил 800 песет.",
            color: "bg-emerald-100 text-emerald-800 border-emerald-200",
            icon: "ticket",
        },
        {
            year: 1992,
            title: "Плюшевый талисман Curro",
            price: "15€",
            description:
                "Культовый сувенир Всемирной выставки 92 года в Севилье стоил 2 500 песет.",
            color: "bg-rose-100 text-rose-800 border-rose-200",
            icon: "toy",
        },
        {
            year: 1995,
            title: "Запуск PlayStation 1",
            price: "360€",
            description: "Поступила в продажу в Европе за 59 900 песет.",
            color: "bg-amber-100 text-amber-800 border-amber-200",
            icon: "game",
        },
        {
            year: 1998,
            title: "Nokia 5110",
            price: "150€",
            description: "Неубиваемый телефон со Змейкой стоил 25 000 песет.",
            color: "bg-yellow-100 text-yellow-800 border-yellow-200",
            icon: "mobile",
        },
        {
            year: 2002,
            title: "Первый кофе в евро",
            price: "0,60€",
            description: "Стоил 100 песет ровно в момент перехода на евро.",
            color: "bg-orange-100 text-orange-800 border-orange-200",
            icon: "coffee",
        },
    ],
    sourcesTitle: "Официальные источники и данные",
    sourcesSubtitle: "Учреждения и агентства, измеряющие реальное влияние на экономику.",
    sourcesBadge: "Документация",
    reportTitle: "Приложение I: Макроэкономический отчет",
    reportSubtitle:
        "Сравнительный анализ динамики цен и покупательной способности в Испании (1980-2025).",
    table1Title: "Динамика стоимости жизни",
    table1Ref: "Ref: INE / Архивы прессы / Министерства",
    thConcept: "Концепция",
    thYear: "Год",
    thHistPrice: "Историческая цена",
    thPrice2025: "Цена 2025",
    thVar: "Изм. %",
    thSource: "Источник",
    table2Title: "Динамика зарплат",
    thAvgSalary: "Средняя годовая зарплата",
    thSmiMonthly: "Мин. зарплата в месяц (14 выплат)",
    thSmiTotal: "Мин. зарплата в год всего",
    noteTitle: "Методологическая note",
    noteP1: "Данные приведены к текущему евро для удобства сравнения (1€ = 166,386 ptas).",
    noteP2: 'Важно: Колонка "Изм. %" отражает номинальный рост цен.',
    noteSources: "Источники: INE, Банк Испании, Министерство жилья и архивы прессы.",
    reportTable1Rows: [
        {
            concept: "Жилье (Квартира 80м²)",
            year: 1985,
            priceHist: "27 000€ (4,5M ptas)",
            price2025: "287 000€",
            varPercent: "+963%",
            isPositive: false,
            sourceName: "Мин. жилья",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "Мин. зарплата",
            year: 1980,
            priceHist: "154€ (25 620 ptas)",
            price2025: "1 134€",
            varPercent: "+636%",
            isPositive: true,
            sourceName: "BOE",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "Хлеб (Батон 250г)",
            year: 1985,
            priceHist: "0,12€ (20 ptas)",
            price2025: "1,20€",
            varPercent: "+900%",
            isPositive: false,
            sourceName: "INE (ИПЦ)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "Бензин (Литр)",
            year: 1980,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,65€",
            varPercent: "+511%",
            isPositive: false,
            sourceName: "Мин. энергетики",
            sourceUrl: "https://www.miteco.gob.es",
        },
        {
            concept: "Билет в кино",
            year: 1980,
            priceHist: "1,20€ (200 ptas)",
            price2025: "9,00€",
            varPercent: "+650%",
            isPositive: false,
            sourceName: "Архив прессы",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "Автомобиль",
            year: 1985,
            priceHist: "4 500€ (750k ptas)",
            price2025: "24 000€",
            varPercent: "+433%",
            isPositive: false,
            sourceName: "Автожурналы",
            sourceTitle: "Motor Clásico / Autopista",
        },
        {
            concept: "Газета",
            year: 1985,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,80€",
            varPercent: "+566%",
            isPositive: false,
            sourceName: "Архив прессы",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "Оливковое масло (1L)",
            year: 2000,
            priceHist: "1,20€ (200 ptas)",
            price2025: "10,00€",
            varPercent: "+733%",
            isPositive: false,
            sourceName: "INE (ИПЦ)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "Кофе (В баре)",
            year: 1990,
            priceHist: "0,48€ (80 ptas)",
            price2025: "1,50€",
            varPercent: "+212%",
            isPositive: false,
            sourceName: "Общепит",
            sourceTitle: "Ассоциации общепита",
        },
    ],
    hiddenTypesCards: [
        {
            badge: "МЕНЬШЕ ЗА ТУ ЖЕ ЦЕНУ",
            title: "Шринкфляция",
            graphicLabel1: "ЧИПСЫ",
            graphicLabel2: "НОВЫЙ ФОРМАТ",
            graphicLegend1: "243г (Раньше 295г)",
            graphicLegend2: "Цена: +15%",
            tagline: '"Вам продают воздух по цене еды."',
            description: "Упаковки чипсов уменьшились с 295г до 243г при росте цены.",
            sourceText: "Источник: Исследование FACUA",
            shareText: "Шринкфляция реальна!",
        },
        {
            badge: "ХУЖЕ ЗА ТУ ЖЕ ЦЕНУ",
            title: "Скимпфляция",
            graphicLabel1: "УЛУЧШЕННАЯ РЕЦЕПТУРА",
            graphicLabel2: "СОСТАВ:",
            graphicRemoved1: "Подсолнечное масло",
            graphicAdded1: "Пальмовое масло/Микс",
            graphicRemoved2: "Сливочное масло",
            graphicAdded2: "Растительные масла",
            tagline: '"Качественные ингредиенты заменяют дешевыми аналогами."',
            description: "Производители заменяют подсолнечное масло пальмовым.",
            sourceText: "Источник: NPR (Скимпфляция)",
            shareText: "Скимпфляция ухудшает качество!",
        },
        {
            badge: "ПОБЕГ ВВЕРХ",
            title: "Премиумизация",
            graphicLabel1: "Platinum",
            graphicLabel2: "ULTRA PRO",
            graphicLegend1: "12,99€",
            graphicLegend2: "ПРОДАНО!",
            graphicRemoved1: "Базовый",
            graphicAdded1: "2,99€",
            tagline: '"Убирают базовую линейку, чтобы заставить купить премиум."',
            description: "Простой йогурт вытесняется дорогими протеиновыми вариантами.",
            sourceText: "Источник: CESCE (Премиумизация)",
            shareText: "Премиумизация убирает бюджетные товары!",
        },
        {
            badge: "ВЫ — СОТРУДНИК",
            title: "Теневая инфляция",
            graphicLabel1: "ОШИБКА: ЖДИТЕ АССИСТЕНТА",
            graphicLabel2: "Ваша зарплата: 0€/час",
            tagline: '"Вы бесплатно работаете на супермаркет и платите ту же цену."',
            description: "Кассы самообслуживания перекладывают работу на клиента без скидок.",
            sourceText: "Источник: The Guardian (Shadow Work)",
            shareText: "Теневая инфляция заставляет работать бесплатно!",
        },
    ],
};
