import type { InflationLocaleData } from "../types";
import { INFLATION_EN_TEXTS } from "./en";

export const INFLATION_SV_TEXTS: InflationLocaleData = {
    ...INFLATION_EN_TEXTS,
    cardTitle: "Inflationen",
    cardSubtitle: "Vad kunde du köpa för 100€ förr jämfört med idag?",
    cardDescription:
        "Utforska köpkraftens utveckling genom verkliga prisjämförelser, lönedata och historiska arkiv.",
    title: "INFLATIONEN",
    billTitle: "100€ SEDEL",
    billYearLabel: "År",
    billValueLabel: "Motsvarande värde idag",
    casesTitle: "Nostalgi vs Verklighet",
    casesSubtitle: "Svep för att se verkliga exempel på prisändringar",
    shareButton: "Dela",
    infoTitle: "Varför räcker inte 100€ lika långt som förr?",
    infoP1: "Inflammation är den allmänna och ihållande ökningen av priserna. Med tiden köper varje myntenhet en mindre procentandel av en vara eller tjänst.",
    infoP2: "Vi kommer ofta ihåg gamla priser med nostalgi, men vi glömmer att lönerna också var mycket lägre då.",
    infoP3: "Att förstå inflation hjälper dig att ta bättre långsiktiga ekonomiska beslut och skydda din köpkraft.",
    items: [
        { name: "Bröd", price: 1.2, minYear: 1950, maxYear: 2025, icon: "bread" },
        { name: "Mjölk", price: 1.0, minYear: 1950, maxYear: 2025, icon: "milk" },
        { name: "Kaffe", price: 1.6, minYear: 1950, maxYear: 2025, icon: "coffee" },
        { name: "Öl", price: 3.0, minYear: 1950, maxYear: 2025, icon: "beer" },
        { name: "Bok", price: 22.0, minYear: 1950, maxYear: 2025, icon: "book" },
        { name: "T-Shirt", price: 20.0, minYear: 1950, maxYear: 2025, icon: "shirt" },
        { name: "Skor", price: 90.0, minYear: 1950, maxYear: 2025, icon: "shoe" },
        { name: "Smycke", price: 500.0, minYear: 1950, maxYear: 2025, icon: "diamond" },
        { name: "Bil", price: 22000.0, minYear: 1950, maxYear: 2025, icon: "car" },
        { name: "Lägenhet", price: 250000.0, minYear: 1950, maxYear: 2025, icon: "house" },
        {
            name: "Middag på Restaurang",
            price: 45.0,
            minYear: 1950,
            maxYear: 2025,
            icon: "restaurant",
        },
        { name: "Tidning", price: 2.0, minYear: 1950, maxYear: 2025, icon: "newspaper" },
        { name: "Frimärke", price: 1.0, minYear: 1950, maxYear: 2025, icon: "mail" },
        { name: "Biobiljett", price: 9.5, minYear: 1950, maxYear: 2025, icon: "movie" },
        { name: "Vinylskiva", price: 30.0, minYear: 1950, maxYear: 2025, icon: "vinyl" },
        { name: "Konsertbiljett", price: 60.0, minYear: 1950, maxYear: 2025, icon: "concert" },
        { name: "Svartvit TV", price: 800.0, minYear: 1950, maxYear: 1980, icon: "tv_old" },
        { name: "Armbandsur", price: 80.0, minYear: 1950, maxYear: 2025, icon: "watch" },
        { name: "Teaterbiljett", price: 25.0, minYear: 1950, maxYear: 2025, icon: "theater" },
        { name: "Filmrulle", price: 12.0, minYear: 1950, maxYear: 2015, icon: "photo_roll" },
        { name: "Kamera", price: 300.0, minYear: 1950, maxYear: 2025, icon: "camera" },
        { name: "Cigaretter", price: 5.0, minYear: 1950, maxYear: 2025, icon: "cigarette" },
        { name: "45rpm Single", price: 8.0, minYear: 1960, maxYear: 1995, icon: "single" },
        { name: "Färg-TV", price: 1200.0, minYear: 1965, maxYear: 2010, icon: "tv_color" },
        { name: "Grammofon", price: 150.0, minYear: 1960, maxYear: 2000, icon: "turntable" },
        { name: "Fotbollsbiljett", price: 45.0, minYear: 1960, maxYear: 2025, icon: "football" },
        { name: "Burgermeny", price: 11.0, minYear: 1970, maxYear: 2025, icon: "burger" },
        { name: "Pizza", price: 14.0, minYear: 1970, maxYear: 2025, icon: "pizza" },
        { name: "Full Tank Bensin", price: 75.0, minYear: 1970, maxYear: 2025, icon: "fuel" },
        { name: "Digital Väckarklocka", price: 20.0, minYear: 1970, maxYear: 2025, icon: "alarm" },
        { name: "Transistorradio", price: 40.0, minYear: 1970, maxYear: 2000, icon: "radio" },
        { name: "Walkman", price: 60.0, minYear: 1979, maxYear: 2005, icon: "walkman" },
        { name: "Miniräknare", price: 15.0, minYear: 1975, maxYear: 2025, icon: "calculator" },
        { name: "Kassettband", price: 10.0, minYear: 1980, maxYear: 2005, icon: "cassette" },
        { name: "VHS-Band", price: 20.0, minYear: 1980, maxYear: 2010, icon: "vhs" },
        { name: "VHS-Hyrning", price: 3.0, minYear: 1985, maxYear: 2010, icon: "vhs_rental" },
        {
            name: "8-bitars Konsol",
            price: 200.0,
            minYear: 1985,
            maxYear: 2000,
            icon: "console_8bit",
        },
        { name: "Fast Telefon", price: 30.0, minYear: 1980, maxYear: 2025, icon: "phone" },
        { name: "Videokamera", price: 700.0, minYear: 1985, maxYear: 2010, icon: "videocamera" },
        {
            name: "Encyklopedi-Set",
            price: 600.0,
            minYear: 1980,
            maxYear: 2005,
            icon: "encyclopedia",
        },
        { name: "Diskett", price: 2.0, minYear: 1980, maxYear: 2005, icon: "floppy" },
        { name: "Ljud-CD", price: 18.0, minYear: 1990, maxYear: 2015, icon: "cd" },
        { name: "TV-Spel", price: 70.0, minYear: 1990, maxYear: 2025, icon: "game" },
        { name: "Gammal Mobil", price: 300.0, minYear: 1995, maxYear: 2010, icon: "mobile" },
        { name: "PC-Dator", price: 1200.0, minYear: 1995, maxYear: 2025, icon: "computer" },
        { name: "PlayStation", price: 400.0, minYear: 1995, maxYear: 2025, icon: "playstation" },
        { name: "Game Boy", price: 100.0, minYear: 1990, maxYear: 2010, icon: "gameboy" },
        { name: "Månads-Internet", price: 40.0, minYear: 1995, maxYear: 2025, icon: "internet" },
        {
            name: "Digitalkamera",
            price: 250.0,
            minYear: 1995,
            maxYear: 2025,
            icon: "digital_camera",
        },
        {
            name: "Starbucks Kaffe",
            price: 4.5,
            minYear: 1999,
            maxYear: 2025,
            icon: "coffee_premium",
        },
        { name: "DVD-Film", price: 15.0, minYear: 2000, maxYear: 2020, icon: "dvd" },
        { name: "iPod", price: 350.0, minYear: 2001, maxYear: 2017, icon: "ipod" },
        { name: "Smartphone", price: 900.0, minYear: 2007, maxYear: 2025, icon: "smartphone" },
        { name: "Surfplatta", price: 500.0, minYear: 2010, maxYear: 2025, icon: "tablet" },
        { name: "Läsplatta", price: 130.0, minYear: 2008, maxYear: 2025, icon: "ereader" },
        {
            name: "Streamingabonnemang",
            price: 15.0,
            minYear: 2011,
            maxYear: 2025,
            icon: "streaming",
        },
        { name: "Trådlösa Hörlurar", price: 180.0, minYear: 2016, maxYear: 2025, icon: "earbuds" },
        { name: "Smartwatch", price: 300.0, minYear: 2014, maxYear: 2025, icon: "smartwatch" },
        { name: "Elsparkcykel", price: 400.0, minYear: 2017, maxYear: 2025, icon: "scooter" },
        { name: "Air Fryer", price: 100.0, minYear: 2018, maxYear: 2025, icon: "airfryer" },
        { name: "AI-Abonnemang", price: 22.0, minYear: 2023, maxYear: 2025, icon: "ai_sub" },
    ],
    cases: [
        {
            year: 1970,
            title: "Seat 600",
            price: "390€",
            description: "Spanska familjers dröm kostade cirka 65 000 pesetas.",
            color: "bg-indigo-100 text-indigo-800 border-indigo-200",
            icon: "car",
        },
        {
            year: 1982,
            title: "VM-Biljett Naranjito",
            price: "4,80€",
            description: "En officiell biljett till en VM-match kostade 800 pesetas.",
            color: "bg-emerald-100 text-emerald-800 border-emerald-200",
            icon: "ticket",
        },
        {
            year: 1992,
            title: "Curro Maskot Gosedjur",
            price: "15€",
            description: "Den ikoniska souvenir från Expo '92 i Sevilla kostade 2 500 pesetas.",
            color: "bg-rose-100 text-rose-800 border-rose-200",
            icon: "toy",
        },
        {
            year: 1995,
            title: "PlayStation 1 Lansering",
            price: "360€",
            description: "Anlände till Europa för 59 900 pesetas.",
            color: "bg-amber-100 text-amber-800 border-amber-200",
            icon: "game",
        },
        {
            year: 1998,
            title: "Nokia 5110",
            price: "150€",
            description: "Den oförstörbara telefonen med Snake kostade 25 000 pesetas.",
            color: "bg-yellow-100 text-yellow-800 border-yellow-200",
            icon: "mobile",
        },
        {
            year: 2002,
            title: "Första Euro-Kaffet",
            price: "0,60€",
            description: "Kostade exakt 100 pesetas vid euro-övergången.",
            color: "bg-orange-100 text-orange-800 border-orange-200",
            icon: "coffee",
        },
    ],
    sourcesTitle: "Officiella Källor och Data",
    sourcesSubtitle: "Institutioner som mäter den verkliga påverkan på ekonomin.",
    sourcesBadge: "Dokumentation",
    reportTitle: "Bilaga I: Makroekonomisk Rapport",
    reportSubtitle: "Jämförande analys av prisutveckling och köpkraft i Spanien (1980-2025).",
    table1Title: "Levnadskostnadsutveckling",
    table1Ref: "Ref: INE / Pressarkiv / Ministerier",
    thConcept: "Koncept",
    thYear: "År",
    thHistPrice: "Historiskt Pris",
    thPrice2025: "2025 Pris",
    thVar: "Förändr. %",
    thSource: "Källa",
    table2Title: "Löneutveckling",
    thAvgSalary: "Årlig Genomsnittslön",
    thSmiMonthly: "Månadslägstalön (14utbet.)",
    thSmiTotal: "Total Årlig Lägstalön",
    noteTitle: "Metodologisk Not",
    noteP1: "Data i denna rapport har omvandlats till nuvarande euro (1€ = 166.386 ptas).",
    noteP2: 'Viktigt: Kolumnen "Förändr. %" visar den nominella prisökningen.',
    noteSources: "Källor: INE, Spaniens Riksbank, Bostadsministeriet och pressarkiv.",
    reportTable1Rows: [
        {
            concept: "Bostad (80m² Lägenhet)",
            year: 1985,
            priceHist: "27.000€ (4.5M ptas)",
            price2025: "287.000€",
            varPercent: "+963%",
            isPositive: false,
            sourceName: "Bostadsministeriet",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "Lägstalön",
            year: 1980,
            priceHist: "154€ (25.620 ptas)",
            price2025: "1.134€",
            varPercent: "+636%",
            isPositive: true,
            sourceName: "BOE",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "Bröd (250g)",
            year: 1985,
            priceHist: "0,12€ (20 ptas)",
            price2025: "1,20€",
            varPercent: "+900%",
            isPositive: false,
            sourceName: "INE (KPI)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "Bensin (Liter)",
            year: 1980,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,65€",
            varPercent: "+511%",
            isPositive: false,
            sourceName: "Energiministeriet",
            sourceUrl: "https://www.miteco.gob.es",
        },
        {
            concept: "Biobiljett",
            year: 1980,
            priceHist: "1,20€ (200 ptas)",
            price2025: "9,00€",
            varPercent: "+650%",
            isPositive: false,
            sourceName: "Pressarkiv",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "Personbil",
            year: 1985,
            priceHist: "4.500€ (750k ptas)",
            price2025: "24.000€",
            varPercent: "+433%",
            isPositive: false,
            sourceName: "Biltidningar",
            sourceTitle: "Motor Clásico / Autopista",
        },
        {
            concept: "Tidning",
            year: 1985,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,80€",
            varPercent: "+566%",
            isPositive: false,
            sourceName: "Pressarkiv",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "Olivolja (1L)",
            year: 2000,
            priceHist: "1,20€ (200 ptas)",
            price2025: "10,00€",
            varPercent: "+733%",
            isPositive: false,
            sourceName: "INE (KPI)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "Kaffe (Kafé)",
            year: 1990,
            priceHist: "0,48€ (80 ptas)",
            price2025: "1,50€",
            varPercent: "+212%",
            isPositive: false,
            sourceName: "Restaurangförbund",
            sourceTitle: "Restaurangförbund",
        },
    ],
    hiddenTypesCards: [
        {
            badge: "MINDRE FÖR SAMMA",
            title: "Krympflation",
            graphicLabel1: "CHIPS",
            graphicLabel2: "NYTT FORMAT",
            graphicLegend1: "243g (Före 295g)",
            graphicLegend2: "Pris: +15%",
            tagline: '"De säljer luft till matpris."',
            description: "Chipsförpackningar minskade från 295g till 243g medan priset steg.",
            sourceText: "Källa: FACUA-studie",
            shareText: "Krympflation är på riktigt!",
        },
        {
            badge: "SÄMRE FÖR SAMMA",
            title: "Skimpflation",
            graphicLabel1: "FÖRBÄTTRAT RECEPT",
            graphicLabel2: "INGREDIENSER:",
            graphicRemoved1: "Solrosolja",
            graphicAdded1: "Palmolja/Mix",
            graphicRemoved2: "Smör",
            graphicAdded2: "Vegetabiliska oljor",
            tagline: '"De byter ut bra ingredienser mot billiga ersättningar."',
            description: "Många varumärken ersatte solrosolja med palmolja.",
            sourceText: "Källa: NPR (Skimpflation)",
            shareText: "Skimpflation försämrar kvaliteten!",
        },
        {
            badge: "FLYKTEN UPPÅT",
            title: "Premiumisering",
            graphicLabel1: "Platinum",
            graphicLabel2: "ULTRA PRO",
            graphicLegend1: "12,99€",
            graphicLegend2: "SLUTSÅLT!",
            graphicRemoved1: "Bas",
            graphicAdded1: "2,99€",
            tagline: '"De tar bort bassortimentet för att tvinga fram köp av lyxserier."',
            description: "High Protein-trenden har trängt undan vanlig yoghurt.",
            sourceText: "Källa: CESCE (Premiumisering)",
            shareText: "Premiumisering tar bort basvaror!",
        },
        {
            badge: "DU ÄR ANSTÄLLD",
            title: "Skugginflation",
            graphicLabel1: "FEL: VÄNTA PÅ ASSISTANS",
            graphicLabel2: "Din Lön: 0€/timme",
            tagline: '"Du arbetar gratis för stormarknaden och betalar samma pris."',
            description: "Självskanningskassor överför arbetskostnaden på kunden.",
            sourceText: "Källa: The Guardian (Shadow Work)",
            shareText: "Skugginflation tvingar dig att arbeta gratis!",
        },
    ],
};
