import type { InflationLocaleData } from "../types";
import { INFLATION_EN_TEXTS } from "./en";

export const INFLATION_TR_TEXTS: InflationLocaleData = {
    ...INFLATION_EN_TEXTS,
    cardTitle: "Enflasyon",
    cardSubtitle: "Eskiden 100€ ile ne alabiliyordunuz, bugün ne alabiliyorsunuz?",
    cardDescription:
        "Gerçek fiyat karşılaştırmaları, maaş verileri ve tarihi kayıtlar aracılığıyla alım gücünün evrimini keşfedin.",
    title: "ENFLASYON",
    billTitle: "100€ BANKNOTU",
    billYearLabel: "Yıl",
    billValueLabel: "Bugünkü eşdeğer değer",
    casesTitle: "Nostalji vs Gerçeklik",
    casesSubtitle: "Fiyat değişimlerinin gerçek örneklerini görmek için kaydırın",
    shareButton: "Paylaş",
    infoTitle: "Neden 100€ artık eskiden aldığı şeyleri almıyor?",
    infoP1: "Enflasyon, fiyatların genel ve sürekli artışıdır. Zaman geçtikçe, her para birimi bir mal veya hizmetin daha küçük bir yüzdesini satın alır.",
    infoP2: "Geçmişteki fiyatları sık sık nostaljiyle hatırlıyoruz, ancak o zamanlar maaşların da çok daha düşük olduğunu unutuyoruz.",
    infoP3: "Enflasyonu anlamak, daha iyi uzun vadeli finansal kararlar almanıza ve alım gücünüzü korumanıza yardımcı olur.",
    items: [
        { name: "Ekmek", price: 1.2, minYear: 1950, maxYear: 2025, icon: "bread" },
        { name: "Süt", price: 1.0, minYear: 1950, maxYear: 2025, icon: "milk" },
        { name: "Kahve", price: 1.6, minYear: 1950, maxYear: 2025, icon: "coffee" },
        { name: "Bira", price: 3.0, minYear: 1950, maxYear: 2025, icon: "beer" },
        { name: "Kitap", price: 22.0, minYear: 1950, maxYear: 2025, icon: "book" },
        { name: "T-Shirt", price: 20.0, minYear: 1950, maxYear: 2025, icon: "shirt" },
        { name: "Ayakkabı", price: 90.0, minYear: 1950, maxYear: 2025, icon: "shoe" },
        { name: "Mücevher", price: 500.0, minYear: 1950, maxYear: 2025, icon: "diamond" },
        { name: "Araba", price: 22000.0, minYear: 1950, maxYear: 2025, icon: "car" },
        { name: "Daire", price: 250000.0, minYear: 1950, maxYear: 2025, icon: "house" },
        {
            name: "Restoran Akşam Yemeği",
            price: 45.0,
            minYear: 1950,
            maxYear: 2025,
            icon: "restaurant",
        },
        { name: "Gazete", price: 2.0, minYear: 1950, maxYear: 2025, icon: "newspaper" },
        { name: "Posta Pulu", price: 1.0, minYear: 1950, maxYear: 2025, icon: "mail" },
        { name: "Sinema Bileti", price: 9.5, minYear: 1950, maxYear: 2025, icon: "movie" },
        { name: "Plak", price: 30.0, minYear: 1950, maxYear: 2025, icon: "vinyl" },
        { name: "Konser Bileti", price: 60.0, minYear: 1950, maxYear: 2025, icon: "concert" },
        { name: "Siyah Beyaz TV", price: 800.0, minYear: 1950, maxYear: 1980, icon: "tv_old" },
        { name: "Kol Saati", price: 80.0, minYear: 1950, maxYear: 2025, icon: "watch" },
        { name: "Tiyatro Bileti", price: 25.0, minYear: 1950, maxYear: 2025, icon: "theater" },
        {
            name: "Fotoğraf Makinesi Filmi",
            price: 12.0,
            minYear: 1950,
            maxYear: 2015,
            icon: "photo_roll",
        },
        { name: "Fotoğraf Makinesi", price: 300.0, minYear: 1950, maxYear: 2025, icon: "camera" },
        { name: "Sigara", price: 5.0, minYear: 1950, maxYear: 2025, icon: "cigarette" },
        { name: "45'lik Plak", price: 8.0, minYear: 1960, maxYear: 1995, icon: "single" },
        { name: "Renkli TV", price: 1200.0, minYear: 1965, maxYear: 2010, icon: "tv_color" },
        { name: "Pikap", price: 150.0, minYear: 1960, maxYear: 2000, icon: "turntable" },
        { name: "Futbol Bileti", price: 45.0, minYear: 1960, maxYear: 2025, icon: "football" },
        { name: "Burger Menü", price: 11.0, minYear: 1970, maxYear: 2025, icon: "burger" },
        { name: "Pizza", price: 14.0, minYear: 1970, maxYear: 2025, icon: "pizza" },
        { name: "Depo Benzin", price: 75.0, minYear: 1970, maxYear: 2025, icon: "fuel" },
        { name: "Dijital Çalar Saat", price: 20.0, minYear: 1970, maxYear: 2025, icon: "alarm" },
        { name: "Transistörlü Radyo", price: 40.0, minYear: 1970, maxYear: 2000, icon: "radio" },
        { name: "Walkman", price: 60.0, minYear: 1979, maxYear: 2005, icon: "walkman" },
        { name: "Hesap Makinesi", price: 15.0, minYear: 1975, maxYear: 2025, icon: "calculator" },
        { name: "Kaset", price: 10.0, minYear: 1980, maxYear: 2005, icon: "cassette" },
        { name: "VHS Kaset", price: 20.0, minYear: 1980, maxYear: 2010, icon: "vhs" },
        { name: "VHS Kiralama", price: 3.0, minYear: 1985, maxYear: 2010, icon: "vhs_rental" },
        { name: "8-bit Konsol", price: 200.0, minYear: 1985, maxYear: 2000, icon: "console_8bit" },
        { name: "Sabit Telefon", price: 30.0, minYear: 1980, maxYear: 2025, icon: "phone" },
        { name: "Video Kamera", price: 700.0, minYear: 1985, maxYear: 2010, icon: "videocamera" },
        {
            name: "Ansiklopedi Seti",
            price: 600.0,
            minYear: 1980,
            maxYear: 2005,
            icon: "encyclopedia",
        },
        { name: "Disket", price: 2.0, minYear: 1980, maxYear: 2005, icon: "floppy" },
        { name: "Müzik CD'si", price: 18.0, minYear: 1990, maxYear: 2015, icon: "cd" },
        { name: "Video Oyunu", price: 70.0, minYear: 1990, maxYear: 2025, icon: "game" },
        { name: "Eski Cep Telefonu", price: 300.0, minYear: 1995, maxYear: 2010, icon: "mobile" },
        {
            name: "Masaüstü Bilgisayar",
            price: 1200.0,
            minYear: 1995,
            maxYear: 2025,
            icon: "computer",
        },
        { name: "PlayStation", price: 400.0, minYear: 1995, maxYear: 2025, icon: "playstation" },
        { name: "Game Boy", price: 100.0, minYear: 1990, maxYear: 2010, icon: "gameboy" },
        { name: "Aylık İnternet", price: 40.0, minYear: 1995, maxYear: 2025, icon: "internet" },
        {
            name: "Dijital Kamera",
            price: 250.0,
            minYear: 1995,
            maxYear: 2025,
            icon: "digital_camera",
        },
        {
            name: "Starbucks Kahvesi",
            price: 4.5,
            minYear: 1999,
            maxYear: 2025,
            icon: "coffee_premium",
        },
        { name: "DVD Film", price: 15.0, minYear: 2000, maxYear: 2020, icon: "dvd" },
        { name: "iPod", price: 350.0, minYear: 2001, maxYear: 2017, icon: "ipod" },
        { name: "Akıllı Telefon", price: 900.0, minYear: 2007, maxYear: 2025, icon: "smartphone" },
        { name: "Tablet", price: 500.0, minYear: 2010, maxYear: 2025, icon: "tablet" },
        { name: "E-Kitap Okuyucu", price: 130.0, minYear: 2008, maxYear: 2025, icon: "ereader" },
        { name: "Streaming Üyeliği", price: 15.0, minYear: 2011, maxYear: 2025, icon: "streaming" },
        { name: "Kablosuz Kulaklık", price: 180.0, minYear: 2016, maxYear: 2025, icon: "earbuds" },
        { name: "Akıllı Saat", price: 300.0, minYear: 2014, maxYear: 2025, icon: "smartwatch" },
        { name: "Elektrikli Skuter", price: 400.0, minYear: 2017, maxYear: 2025, icon: "scooter" },
        {
            name: "Sıcak Hava Fritözü",
            price: 100.0,
            minYear: 2018,
            maxYear: 2025,
            icon: "airfryer",
        },
        { name: "Yapay Zeka Aboneliği", price: 22.0, minYear: 2023, maxYear: 2025, icon: "ai_sub" },
    ],
    cases: [
        {
            year: 1970,
            title: "Seat 600",
            price: "390€",
            description: "İspanyol ailelerin hayali yaklaşık 65.000 pesetaya mal oluyordu.",
            color: "bg-indigo-100 text-indigo-800 border-indigo-200",
            icon: "car",
        },
        {
            year: 1982,
            title: "Naranjito Dünya Kupası Bileti",
            price: "4,80€",
            description: "Dünya Kupası maçı için resmi bilet 800 pesetaya mal oluyordu.",
            color: "bg-emerald-100 text-emerald-800 border-emerald-200",
            icon: "ticket",
        },
        {
            year: 1992,
            title: "Curro Maskot Peluşu",
            price: "15€",
            description: "Sevilla Expo '92'nin simge hediyeliği 2.500 pesetaya mal oluyordu.",
            color: "bg-rose-100 text-rose-800 border-rose-200",
            icon: "toy",
        },
        {
            year: 1995,
            title: "PlayStation 1 Çıkışı",
            price: "360€",
            description: "Avrupa'ya 59.900 pesetaya geldi.",
            color: "bg-amber-100 text-amber-800 border-amber-200",
            icon: "game",
        },
        {
            year: 1998,
            title: "Nokia 5110",
            price: "150€",
            description: "Snake oyunlu kırılmaz telefon 25.000 pesetaya mal oluyordu.",
            color: "bg-yellow-100 text-yellow-800 border-yellow-200",
            icon: "mobile",
        },
        {
            year: 2002,
            title: "İlk Euro Kahvesi",
            price: "0,60€",
            description: "Euro geçişi anında tam olarak 100 pesetaya mal oluyordu.",
            color: "bg-orange-100 text-orange-800 border-orange-200",
            icon: "coffee",
        },
    ],
    sourcesTitle: "Resmi Kaynaklar ve Veriler",
    sourcesSubtitle: "Ekonomi üzerindeki gerçek etkiyi ölçen kurumlar.",
    sourcesBadge: "Dokümantasyon",
    reportTitle: "Ek I: Makroekonomik Rapor",
    reportSubtitle:
        "İspanya'da fiyat gelişimi ve satın alma gücü karşılaştırmalı analizi (1980-2025).",
    table1Title: "Yaşam Maliyeti Gelişimi",
    table1Ref: "Ref: INE / Gazete Arşivleri / Bakanlıklar",
    thConcept: "Kavram",
    thYear: "Yıl",
    thHistPrice: "Tarihsel Fiyat",
    thPrice2025: "2025 Fiyatı",
    thVar: "Değişim %",
    thSource: "Kaynak",
    table2Title: "Maaş Gelişimi",
    thAvgSalary: "Yıllık Ortalama Maaş",
    thSmiMonthly: "Aylık Asgari Ücret (14 Maaş)",
    thSmiTotal: "Yıllık Toplam Asgari Ücret",
    noteTitle: "Metodolojik Not",
    noteP1: "Bu raporda sunulan veriler, sabit döviz kuru (1€ = 166.386 ptas) kullanılarak Euro'ya dönüştürülmüştür.",
    noteP2: 'Önemli: "Değişim %" sütunu nominal fiyat artışını yansıtır.',
    noteSources:
        "Kaynaklar: INE, İspanya Merkez Bankası, Konut Bakanlığı ve dijital basın arşivleri.",
    reportTable1Rows: [
        {
            concept: "Konut (80m² Daire)",
            year: 1985,
            priceHist: "27.000€ (4.5M ptas)",
            price2025: "287.000€",
            varPercent: "+963%",
            isPositive: false,
            sourceName: "Konut Bakanlığı",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "Asgari Ücret",
            year: 1980,
            priceHist: "154€ (25.620 ptas)",
            price2025: "1.134€",
            varPercent: "+636%",
            isPositive: true,
            sourceName: "BOE",
            sourceUrl: "https://www.boe.es",
        },
        {
            concept: "Ekmek (250g Somun)",
            year: 1985,
            priceHist: "0,12€ (20 ptas)",
            price2025: "1,20€",
            varPercent: "+900%",
            isPositive: false,
            sourceName: "INE (TÜFE)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "Benzin (Litre)",
            year: 1980,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,65€",
            varPercent: "+511%",
            isPositive: false,
            sourceName: "Enerji Bakanlığı",
            sourceUrl: "https://www.miteco.gob.es",
        },
        {
            concept: "Sinema Bileti",
            year: 1980,
            priceHist: "1,20€ (200 ptas)",
            price2025: "9,00€",
            varPercent: "+650%",
            isPositive: false,
            sourceName: "Basın Arşivi",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "Binek Araba",
            year: 1985,
            priceHist: "4.500€ (750k ptas)",
            price2025: "24.000€",
            varPercent: "+433%",
            isPositive: false,
            sourceName: "Otomobil Dergileri",
            sourceTitle: "Motor Clásico / Autopista",
        },
        {
            concept: "Gazete",
            year: 1985,
            priceHist: "0,27€ (45 ptas)",
            price2025: "1,80€",
            varPercent: "+566%",
            isPositive: false,
            sourceName: "Basın Arşivi",
            sourceTitle: "ABC / La Vanguardia",
        },
        {
            concept: "Zeytinyağı (1L)",
            year: 2000,
            priceHist: "1,20€ (200 ptas)",
            price2025: "10,00€",
            varPercent: "+733%",
            isPositive: false,
            sourceName: "INE (TÜFE)",
            sourceUrl: "https://www.ine.es",
        },
        {
            concept: "Kahve (Kafe)",
            year: 1990,
            priceHist: "0,48€ (80 ptas)",
            price2025: "1,50€",
            varPercent: "+212%",
            isPositive: false,
            sourceName: "Restoran Birliği",
            sourceTitle: "Restoran Birlikleri",
        },
    ],
    hiddenTypesCards: [
        {
            badge: "AYNI FİYATA DAHA AZ",
            title: "Büzülme Enflasyonu",
            graphicLabel1: "CİPS",
            graphicLabel2: "YENİ FORMAT",
            graphicLegend1: "243g (Önce 295g)",
            graphicLegend2: "Fiyat: +15%",
            tagline: '"Yemek fiyatına hava satıyorlar."',
            description: "Cips paketleri fiyat artarken 295g'dan 243g'a düştü.",
            sourceText: "Kaynak: FACUA Çalışması",
            shareText: "Büzülme enflasyonu gerçektir!",
        },
        {
            badge: "AYNI FİYATA DAHA KÖTÜ",
            title: "Kalite Düşüşü Enflasyonu",
            graphicLabel1: "GELİŞTİRİLMİŞ TARİF",
            graphicLabel2: "İÇİNDEKİLER:",
            graphicRemoved1: "Ayçiçek Yağı",
            graphicAdded1: "Palmiye Yağı/Karışım",
            graphicRemoved2: "Tereyağı",
            graphicAdded2: "Bitkisel Yağlar",
            tagline: '"İyi malzemeleri ucuz ikamelerle değiştiriyorlar."',
            description: "Markalar ayçiçek yağını palmiye yağı ile değiştirdi.",
            sourceText: "Kaynak: NPR (Skimpflation)",
            shareText: "Kalite düşüşü enflasyonu kaliteyi düşürüyor!",
        },
        {
            badge: "YUKARI KAÇIŞ",
            title: "Premiumlaşma",
            graphicLabel1: "Platinum",
            graphicLabel2: "ULTRA PRO",
            graphicLegend1: "12.99€",
            graphicLegend2: "TÜKENDİ!",
            graphicRemoved1: "Temel",
            graphicAdded1: "2.99€",
            tagline: '"Lüks serileri almaya zorlamak için temel serileri kaldırıyorlar."',
            description: "Yüksek protein çılgınlığı sade yoğurtları raflardan kaldırdı.",
            sourceText: "Kaynak: CESCE (Premiumlaşma)",
            shareText: "Premiumlaşma temel ürünleri yok ediyor!",
        },
        {
            badge: "ÇALIŞAN SİZSİNİZ",
            title: "Gölge Enflasyon",
            graphicLabel1: "HATA: YARDIM BEKLEYİN",
            graphicLabel2: "Maaşınız: 0€/saat",
            tagline: '"Süpermarket için ücretsiz çalışıyorsunuz ve aynı parayı ödüyorsunuz."',
            description: "Self-servis kasalar iş gücü maliyetini müşteriye yüklüyor.",
            sourceText: "Kaynak: The Guardian (Shadow Work)",
            shareText: "Gölge enflasyon sizi ücretsiz çalıştırıyor!",
        },
    ],
};
