export const BOREDOM_EN_TEXTS = {
    title: "Ode to boredom",
    subtitle:
        "STATUTORY COMPENDIUM FOR THE RECOGNITION AND PRESERVATION OF BOREDOM AS AN INTRINSIC STATE OF OPERATIVE CONSCIOUSNESS AND A CATALYST FOR UNSOLICITED PRODUCTION",
    tocTitle: "EXHAUSTIVE ANALYTICAL INDEX",
    tocLoading: "Calculating boredom levels...",
    art1Title:
        "ARTICLE I. Conceptual delimitation and phenomenological record of the state of Boredom.",
    sub11Title: "Subarticle 1.1. Definition and Scope.",
    sec111Title: "Section 1.1.1. Operational Definition.",
    sec111Text:
        "Boredom is defined, for the purposes of this statute, as a psychological state characterized by a substantial, verifiable, and sustained decrease in the reception of significant external stimuli. Such decrease invariably results in an internal perception of monotony, accompanied by a low expectation of immediate novelty. It is imperative to note that this condition does not constitute a clinical pathology or an attentional deficit, but rather an evolutionary signaling mechanism indicating the temporary inefficiency of the environment in capturing the subject's executive attention.",
    sec112Title: "Section 1.1.2. Exclusion of Synonyms.",
    sec112Text:
        'Colloquial terms such as "weariness", "disinclination" or "apathy" are expressly excluded from this definition, insofar as they imply a negative emotional load that is not consubstantial with pure Boredom. Boredom, in its normative form, is neutral, sterile, and devoid of affective valence.',
    sub12Title: "Subarticle 1.2. Phenomenological Taxonomy.",
    sec121Title: "Section 1.2.1. Situational Boredom.",
    sec121Text:
        "Situational Boredom is understood as that variant generated by forced exposure to a specific, repetitive, and redundant task, or by forced inaction in contexts of non-productive waiting (e.g., waiting rooms, bureaucratic procedures, reading this document). Its duration is strictly linked to the persistence of the stimulus (or lack thereof) that originates it.",
    sec122Title: "Section 1.2.2. Existential Boredom.",
    sec122Text:
        "It is defined as a more diffuse, omnipresent condition not linked to an immediate external event. It arises from a perception of a lack of purpose in the broad context of daily activity and manifests as a temporary disconnection from pre-established vital goals. Both types must be cataloged not as a deficiency, but as an unassigned availability of high-level cognitive resources.",
    sub13Title: "Subarticle 1.3. The Principle of Quietism.",
    sec131Title: "Section 1.3.1. Valuation of Quietism.",
    sec131Text:
        "It is fundamental for the correct application of this statute to recognize that Boredom requires, for its full effectiveness, a passive acceptance of quietism. Any attempt of immediate escape from this state compromises its intrinsic value.",
    sec132Title: "Section 1.3.2. Persistence.",
    sec132Text:
        "The value of Boredom resides precisely in the persistence of the imposed mental inactivity. Resistance to the urge to seek relief is the first test of compliance with this regulation.",
    art2Title: "ARTICLE II. The Necessary Nature of Boredom as a Precursor to Creative Structure.",
    sub21Title: "Subarticle 2.1. Mechanisms of Activation.",
    sec211Title: "Section 2.1.1. Secondary Activation Thesis.",
    sec211Text:
        "Contrary to popular belief, Boredom is not the antithesis of Entertainment, but its primary structural ally. Prolonged and uninterrupted exposure to low stimulation forces the cognitive system to initiate a process of endogenous reorientation, progressively ceasing dependency on external sensory inputs.",
    sec212Title: "Section 2.1.2. The Fertile Void.",
    sec212Text:
        'This cessation of inputs creates a "fertile void" where the mind, deprived of distractions, is forced to resort to its own memory files and synthesis capacity to maintain cognitive homeostasis.',
    sub22Title: "Subarticle 2.2. Unsolicited Internal Production.",
    sec221Title: "Section 2.2.1. Generation of Projects.",
    sec221Text:
        "The dissatisfaction derived from Boredom acts as a motor for a forced search for novelty, but on a purely internal plane. The bored subject enters a state of functional pre-creativity.",
    sec222Title: "Section 2.2.2. Hypotheses and Narratives.",
    sec222Text:
        "In this state, the mind begins to generate hypotheses, complex narratives, and solutions to unposed (and often non-existent) problems to occupy the perceived void. Ergo, it is concluded that Entertainment is simply the commercialized solution that the mind offers to the fundamental problem of Boredom.",
    sub23Title: "Subarticle 2.3. Cognitive Economy.",
    sec231Title: "Section 2.3.1. Priority Allocation of Funds.",
    sec231Text:
        "The lack of urgent stimuli allows the reallocation of neural resources to low-priority or long-term cognitive tasks (strategic planning, introspection, philosophical wandering) that, under conditions of high stimulation, would be systematically ignored or postponed indefinitely.",
    sec232Title: "Section 2.3.2. Mandatory Investment.",
    sec232Text:
        "Boredom is, therefore, a policy of mandatory investment in the reserve mental infrastructure, ensuring the maintenance of cognitive capacities that would atrophy in an environment of perpetual entertainment.",
    art3Title:
        "ARTICLE III. Loss of the Capacity to Be Bored: The Tolerance Deficit to the Absence of Stimulus.",
    sub31Title: "Subarticle 3.1. The Saturated Environment.",
    sec311Title: "Section 3.1.1. Proliferation of Stimuli.",
    sec311Text:
        "Contemporary society exhibits a programmed and systematic saturation of information and entertainment channels. These channels are specifically designed to eradicate any temporal interval of low stimulation, colonizing every second of waking life with content of low cognitive nutritional value.",
    sec312Title: "Section 3.1.2. Physiological Dependency.",
    sec312Text:
        "This saturation has generated a physiological dependency on constant novelty (dopamine), creating a feedback loop where tolerance to silence and inaction decreases exponentially.",
    sub32Title: "Subarticle 3.2. Psychological Atrophy.",
    sec321Title: "Section 3.2.1. Erosion of Resilience.",
    sec321Text:
        "The modern subject has lost the psychological resilience necessary to sustain Boredom for periods exceeding thirty seconds.",
    sec322Title: "Section 3.2.2. Withdrawal Symptoms.",
    sec322Text:
        "The reflex impulse to check the mobile device or to generate immediate interaction at the slightest temporal void is irrefutable proof of the atrophy in the capacity for static self-regulation and of the inability to inhabit one's own mental space without external assistance.",
    sub33Title: "Subarticle 3.3. Cognitive Impact.",
    sec331Title: "Section 3.3.1. Consequences on Depth.",
    sec331Text:
        "The systematic prevention of Boredom prevents the consolidation of productive mind-wandering. Since the mind is constantly busy processing superficial and ephemeral stimuli, the capacity for deep reflection is severely compromised.",
    sec332Title: "Section 3.3.2. Need for Detoxification.",
    sec332Text:
        "Therefore, the urgent implementation of a policy of gradual detoxification from excess inputs is required to restore basal cognitive faculties.",
    art4Title: "ARTICLE IV. Protocols for the Maintenance and Cultivation of Boredom.",
    sub41Title: "Subarticle 4.1. Programmed Inaction.",
    sec411Title: "Section 4.1.1. Recommendation of S.U.I.",
    sec411Text:
        "The inclusion of periods of Strictly Unstructured Inaction (S.U.I.) in the subject's weekly calendar is strongly advised.",
    sec412Title: "Section 4.1.2. Prohibitions during S.U.I.",
    sec412Text:
        "During the periods designated as S.U.I., interaction with electronic devices, audiovisual media, recreational reading material, or the performance of domestic tasks with a defined purpose is strictly prohibited. The only permitted activity is passive existence.",
    sub42Title: "Subarticle 4.2. Environmental Control.",
    sec421Title: "Section 4.2.1. Adoption of Neutral Environments.",
    sec421Text:
        "Remaining in visually and auditorily neutral environments should be encouraged. The use of rooms painted in monochromatic tones and the total absence of incidental music is recommended.",
    sec422Title: "Section 4.2.2. Noise Reduction.",
    sec422Text:
        'The goal is to reduce cognitive "background noise" to the absolute minimum. Environmental uniformity facilitates the emergence of non-directed internal thought, a sine qua non condition for quality boredom.',
    sub43Title: "Subarticle 4.3. Final Provisions.",
    sec431Title: "Section 4.3.1. The Seeker's Paradox.",
    sec431Text:
        'Boredom is not an activity that can be actively pursued; it is a permission that one grants to oneself. Anyone actively looking for "how to get bored" is, by definition, entertaining themselves in the search and, therefore, fails in the attempt.',
    sec432Title: "Section 4.3.2. Resignation Clause.",
    sec432Text: "The only path of access is resignation to the passage of time without content.",
    art5Title: "ARTICLE V. The Causal Agent of Tedium (Active Subject).",
    sub51Title: "Subarticle 5.1. Legal Definition of the Bore.",
    sec511Title: "Section 5.1.1. The Active Subject.",
    sec511Text:
        'The "Causal Agent of Tedio" or "Active Subject" is defined as that natural person who, through speech, conduct, or inaction, induces in third parties the state of boredom described in Article I.',
    sub52Title: "Subarticle 5.2. Classification of Offending Conducts.",
    sub52Intro:
        "For the purposes of citation and notification of infraction in social interactions, the following Classified Paragraphs are established, the complete reading of which is mandatory for the correct understanding of the magnitude of the problem:",
    paragraphs: [
        {
            title: "Paragraph 1. The Narrator of Other People's Dreams.",
            text: "It constitutes a cause of first-degree boredom to describe in detail, slowly, and without omissions one's own or third parties' dream experiences, given that such narratives intrinsically lack narrative logic, real consequences in the physical plane, or any interest for anyone other than the dreamer, who often forgets the dream in the middle of the story but persists in their attempt at reconstruction.",
        },
        {
            title: "Paragraph 2. The Irrelevant Detailer.",
            text: "One who interrupts the flow of their own narrative, or worse, that of another, to correct data absolutely irrelevant to the conclusion of the story, such as the exact date (debating with themselves whether it was Tuesday or Wednesday), the precise name of a secondary street, or the price to the cent of an already purchased item, dilating the exposure time without adding semantic value.",
        },
        {
            title: "Paragraph 3. The Word Monopolist.",
            text: "Subject who deliberately or unconsciously ignores the non-verbal signs of disinterest emitted by their interlocutor, such as furtive glances at the watch, suppressed yawns, body orientation towards the exit, or failed attempts at interjection, and continues their monologued exposition without allowing the alternation of the turn to speak under any circumstances.",
        },
        {
            title: "Paragraph 4. The Photo Gallery Displayer.",
            text: "Person who forces the extensive, sequential, and commented viewing of the entirety of their photo gallery on mobile devices, including bursts of identical photos, accidental screenshots, and out-of-focus videos of fireworks, sleeping pets, or infants performing basic motor activities, without applying any selection filter or prior curation.",
        },
        {
            title: "Paragraph 5. The Explainer of the Obvious.",
            text: "Individual who details basic concepts, social norms, or elementary mechanical operations that are already well known by the interlocutor with pedagogical meticulousness, assuming non-existent ignorance on the other part and slowing down efficient communication to levels of absolute cognitive stagnation.",
        },
        {
            title: "Paragraph 6. The Anecdote Repeater.",
            text: 'One who relates a story, joke, or event that is already known by those present, ignoring explicit verbal warnings of "you\'ve already told me that" or "yes, I remember", under the pretext that "it\'s very good" or "but wait, you don\'t remember the end", proceeding to narrate it with the exact same words and dramatic pauses as on the five previous occasions.',
        },
        {
            title: "Paragraph 7. The Unsolicited Grammar Corrector.",
            text: "Subject who prioritizes syntactic, phonetic, or lexical correction of another's speech over the content of the message, interrupting communication to point out minor errors of agreement or pronunciation, thus destroying any possibility of conversational fluidity and generating an environment of non-consensual academic examination.",
        },
        {
            title: "Paragraph 8. The Traffic Route Expert.",
            text: "Person who describes in great detail the itinerary followed to move from a point A to a point B, including names of roads, roundabouts taken, red lights, roadworks, and strategic lane change decisions, assuming that the logistics of their displacement possess some kind of epic narrative value.",
        },
        {
            title: "Paragraph 9. The Past Weather Detailer.",
            text: "Individual who recalls the weather conditions of previous days, weeks, or years with unnecessary precision, comparing temperatures, humidity levels, and thermal sensations of different periods without it having any relevance to the present or future moment.",
        },
        {
            title: "Paragraph 10. The Genealogist of Strangers.",
            text: "One who explains the complex family relationships, relatives, divorces, and second marriages of people the interlocutor does not know, has never seen, and probably will never see, drawing invisible family trees in the air that nobody requested.",
        },
        {
            title: "Paragraph 11. The Menu of the Day Food Critic.",
            text: "Subject who performs an exhaustive and unqualified organoleptic analysis of each dish of an economic menu, commenting on the texture of the sauce, the temperature of the side dish, and the presumed origin of the ingredients with the gravity of a sanitary audit.",
        },
        {
            title: "Paragraph 12. The Bill Analyst.",
            text: "Person who publicly breaks down the concepts of their utility, insurance, or banking services bills, comparing rates, kilowatt hours, and maintenance fees with a passion that should be reserved for life-or-death issues.",
        },
        {
            title: "Paragraph 13. The Chronicler of Mild Illnesses.",
            text: "Individual who relates the minute-by-minute evolution of minor ailments, colds, seasonal allergies, or small muscle discomforts, including graphic descriptions of symptoms, administered medication, and intake schedules.",
        },
        {
            title: "Paragraph 14. The Recreational Excel User.",
            text: 'One who transfers the logic of spreadsheets to daily life, organizing vacations, dinners with friends, or shopping lists with pivot tables and conditional formulas, and who insists on showing the "beauty" of their organization system to those who just wanted to buy bread.',
        },
        {
            title: "Paragraph 15. The Dubbed Movie Quotes Spouter.",
            text: "Subject who communicates mainly through catchphrases extracted from 90s movie dubs, repeating them out of context and expecting a complicit laugh that, by pure statistics and wear, stopped occurring decades ago.",
        },
        {
            title: "Paragraph 16. The Pineapple Pizza Defender.",
            text: "Or its contrary. Person who starts polarized and sterile culinary debates about pizza ingredients, omelets with or without onion, or the order of ingredients in cereal, treating them as matters of state when they are actually irrelevant preferences.",
        },
        {
            title: "Paragraph 17. The Commercial Commentator.",
            text: "Individual who feels the imperious need to verbalize what is happening on the television screen during commercial breaks, reading slogans or criticizing the actors, preventing the restorative silence that should accompany advertising.",
        },
        {
            title: "Paragraph 18. The Label Reader.",
            text: "One who reads aloud the nutritional composition, ingredients, or instructions for use of any product that falls into their hands in a supermarket, informing their companion about the percentage of saturated fats without the companion having shown any interest in their cardiovascular health.",
        },
        {
            title: "Paragraph 19. The Writer of Infinite Paragraphs.",
            text: "Subject who writes texts lacking proper punctuation, deliberately ignoring the use of periods or semicolons and linking subordinate clauses one after another through the abusive use of copulative or relative conjunctions, generating a syntactic structure that resembles a messy stream of consciousness more than a logical exposition of ideas, causing the reader a feeling of mental and visual suffocation by not finding a place to rest their eyes or take metaphorical breath while trying to decipher the subject of the main clause that was probably lost ten lines above in unnecessary parentheses and clarifications that clarify nothing but rather confuse even more the original meaning of the text if it ever had one beyond the mere accumulation of words.",
        },
        {
            title: "Paragraph 20. The Notary of Visual Obviousness.",
            text: 'Person who points out and verbalizes the presence of objects, animals, or phenomena that are clearly in the visual field of all present, exclaiming "look, a dog!" or "it\'s raining!" when the dog is barking a meter away and the water is wetting everyone.',
        },
        {
            title: "Paragraph 21. The Renovation Historian.",
            text: "Individual who knows and relates the history of works, contributions, and aesthetic changes of their neighborhood community of the last thirty years, detailing which neighbor voted against changing the elevator in 1998.",
        },
        {
            title: "Paragraph 22. The Price Comparator.",
            text: "One who memorizes the prices of basic products in different supermarket chains and recites the differences of cents between the liter of milk in one establishment and another as if they were revealing state secrets.",
        },
        {
            title: "Paragraph 23. The Bureaucratic Procedure Narrator.",
            text: "Subject who describes step by step the process of renewing their identity card, applying for a scholarship, or claiming a fine, including waiting times, the civil servant's attitude, and the forms filled out.",
        },
        {
            title: "Paragraph 24. The Shared Expense Detailer.",
            text: "One who insists on the manual and public reconciliation of accounts for small group expenses, using a basic calculator and verbalizing each addition and subtraction, instead of using automatic management applications, lengthening the settlement of small debts to the limit of patience.",
        },
        {
            title: "Paragraph 25. The Retroactive Weather Consultant.",
            text: "Individual who, in the face of any conversation about the current weather, feels the imperious need to consult and cite the exact historical temperature and precipitation data of the previous year, to establish an irrelevant point of comparison.",
        },
        {
            title: "Paragraph 26. The Reader of Legal Conditions Aloud.",
            text: "Person who, when registering for a service or buying a product, begins to read aloud the Terms and Conditions of Use (TCU) or the Privacy Policy, assuming that their interlocutors share the same level of legal-contractual interest.",
        },
        {
            title: "Paragraph 27. The Timekeeper of Other People's Routines.",
            text: "Subject who describes in detail the exact times it takes them to perform domestic or personal tasks (e.g., how long it takes to boil water, to get to work, to get dressed), generating an efficiency record that was not requested.",
        },
        {
            title: "Paragraph 28. The Toponymic Detail Fan.",
            text: "One who insists on correcting the pronunciation or the full name of places of remote geographical interest (provinces, rivers, mountains) that are tangential to the central theme of the conversation, interrupting the narrative flow.",
        },
        {
            title: "Paragraph 29. The Basic Flavor Describer.",
            text: 'Individual who, after consuming any mass-market and well-known food or drink, takes time to analyze and describe its obvious organoleptic qualities (e.g., "the coffee tastes like coffee," "the apple is sweet and crunchy").',
        },
        {
            title: "Paragraph 30. The Redundant Feedback Seeker.",
            text: "Person who, after completing a minor task (e.g., sending an email, uploading a photo), repeatedly asks if the action was received, seen, or approved by the interlocutor, demonstrating unnecessary operational insecurity.",
        },
        {
            title: "Paragraph 31. The Housing Price Historian.",
            text: "Subject who, when passing through any neighborhood or street, begins to relate the price that property or plot had ten, fifteen, or twenty years ago, lamenting the real estate situation with unverified data.",
        },
        {
            title: "Paragraph 32. The Supermarket Queue Analyst.",
            text: "One who, while waiting at the checkout, analyzes and quietly criticizes the quantity and type of products purchased by the person ahead of them, making judgments about their diet or lifestyle.",
        },
        {
            title: "Paragraph 33. The Excessive Email Scribe.",
            text: "Person who uses email as an activity log, sending messages to notify that they have sent another message, or to ask if the previous message has been read, duplicating the flow of information unnecessarily.",
        },
        {
            title: "Paragraph 34. The Arcane Spelling Defender.",
            text: "Individual who uses extremely rare or archaic words in daily speech, forcing the search for their meaning or the interruption to ask for clarification, under the pretext of lexical richness.",
        },
        {
            title: "Paragraph 35. The Explainer of Simple Jokes.",
            text: 'Subject who, after telling a joke or a mildly humorous anecdote, feels the need to break down the comic mechanism or the cultural allusion, ensuring that everyone has understood the "deep layer" of humor.',
        },
        {
            title: "Paragraph 36. The Loyalty Card Collector.",
            text: "Person who insists on showing and explaining the operation of each loyalty card of supermarkets, gas stations, or cafes they own, detailing the points accumulated and potential discounts, even if nobody asked.",
        },
        {
            title: "Paragraph 37. The Technological Process Describer.",
            text: "One who explains minutely how they used a software or an application to perform a common task (e.g., how they created a folder, how they uploaded a file), as if they were giving a master lecture.",
        },
        {
            title: "Paragraph 38. The Bureaucratic Process Comparator.",
            text: "Individual who compares two administrative processes (e.g., renewing passport vs. ID), pointing out minor differences in forms or waiting times, without the comparison having a practical utility.",
        },
        {
            title: "Paragraph 39. The Meticulous Menu Reader.",
            text: "Person who reads aloud each section of the menu in a restaurant, pondering each option and asking the waiter about the origin of each ingredient, before finally ordering the simplest or already known dish.",
        },
        {
            title: "Paragraph 40. The Expert in Other People's Corporate Affairs.",
            text: "Subject who relates the complex hierarchies, dismissals, and staff changes of a company in which neither they nor their interlocutor work, treating the information as if it were a Shakespearean drama.",
        },
        {
            title: "Paragraph 41. The Phone Coverage Analyst.",
            text: "One who, in any new place, checks and verbalizes the strength of their Wi-Fi or mobile data signal, announcing the megabits per second or coverage bars, as if it were a notable geographical find.",
        },
        {
            title: "Paragraph 42. The Live Social Media Commentator.",
            text: "Person who reads aloud other people's posts or comments on social networks, without summarizing or contextualizing, forcing the interlocutor to follow an irrelevant thread of speech from a third party.",
        },
        {
            title: "Paragraph 43. The Redundant Summary Writer.",
            text: 'Individual who, after finishing a conversation or a meeting, insists on making an exhaustive summary of the points already agreed and understood, under the pretext of "clarity", but with the effect of duplicating the interaction time.',
        },
        {
            title: "Paragraph 44. The Unsolicited Link Distributor.",
            text: "Subject who compulsively shares hyperlinks to extreme niche articles, videos, or websites in messaging groups, without accompanying them with context or summary, erroneously assuming that the rest of the members have the time and interest to consume such content.",
        },
        {
            title: "Paragraph 45. The Alternative Diet Evangelist.",
            text: "Subject who adopts a dietary regime that diverges from the statistical norm (intermittent fasting, paleo diet, raw veganism) and feels the moral obligation to detail their intake schedules, caloric restrictions, and supposed metabolic benefits to interlocutors who are in the middle of consuming refined carbohydrates.",
        },
        {
            title: "Paragraph 46. The Sports Discipline Novice.",
            text: "Individual who has recently started practicing a fashionable physical activity (paddle tennis, crossfit, bouldering) and monopolizes the conversation describing technical equipment, specific stiffness, and the discipline's own terminology, assuming that their personal discovery constitutes a universal novelty.",
        },
        {
            title: "Paragraph 47. The Unnecessary Audio Sender.",
            text: "Subject who systematically uses the voice message function to transmit information that could have been efficiently condensed into three lines of text, forcing the receiver to linear playback of the audio without the possibility of visual scanning.",
        },
        {
            title: "Paragraph 48. The Obvious Response Anticipator.",
            text: "Person who asks rhetorical queries or questions whose answer is a logical and inevitable conclusion of the information already shared, compromising the efficiency of the question-answer cycle.",
        },
        {
            title: "Paragraph 49. The Font Analyst.",
            text: "Individual who, upon receiving a document, prioritizes exhaustive comment on the font, size, spacing, or margins of the text, over the semantic content that the document contains.",
        },
        {
            title: "Paragraph 50. The Inflexible Schedule Quoter.",
            text: 'Individual who communicates only by mentioning the exact time of an event or task, refusing to use relative time terms ("afternoon", "soon") and forcing unnecessary chronometric precision in informal contexts.',
        },
        {
            title: "Paragraph 51. The Antiquated Audio Quality Defender.",
            text: 'Subject who, despite the availability of modern technology, insists on playing audio files or music in low-fidelity formats or insufficient volume, and then defends the supposed "warm tonal qualities" of poor quality.',
        },
        {
            title: "Paragraph 52. The Price with VAT Commentator.",
            text: "One who, when mentioning a price or expense, feels obliged to specify whether the figure includes or excludes Value Added Tax (VAT), although such detail is fiscally irrelevant to casual conversation.",
        },
        {
            title: "Paragraph 53. The Low Battery Analyst.",
            text: "Individual who interrupts an interaction to notify the low battery level of their mobile device, explaining the imminent need to find a charger and describing its charge percentage with alarming regularity.",
        },
        {
            title: "Paragraph 54. The Next Tasks Reminder.",
            text: 'Person who, in the middle of a pleasant or leisure activity, inserts unsolicited and timely reminders about future obligations ("remember tomorrow we have to go to the bank", "don\'t forget the dentist next week"), undermining the enjoyment of the present moment.',
        },
        {
            title: "Paragraph 55. The Acronym Inquisitor.",
            text: 'Subject who insists on stopping the conversation to ask about the meaning of acronyms or abbreviations that their interlocutor assumes as common (e.g., asking "what is LOL", "what does CEO mean"), interrupting the rhythm of the speech due to lack of tolerance for context.',
        },
    ],
    art6Title:
        "ARTICLE VI. On Sanctions, Therapeutic Measures, and Administrative Appeals of Tedium",
    sub61Title: "Subarticle 6.1. Guiding Principles of the Sanction.",
    sec611Title: "Section 6.1.1. Nature of the Penalty.",
    sec611Text:
        "The sanctions imposed for the violation of the provisions of Article V shall not be of a pecuniary nature nor involve deprivation of physical liberty. Their primary objective is the behavioral re-education of the Active Subject through the imposition of a Mandatory Consumption of Tedium (MCT), thus restoring their tolerance to low stimulation.",
    sec612Title: "Section 6.1.2. Graduation of the Infraction.",
    sec612Text: "Infractions shall be classified as:",
    infLeveTitle: "Minor Infraction:",
    infLeveText:
        "Incurring in up to three (3) Classified Paragraphs in a single social interaction.",
    infGraveTitle: "Major Infraction:",
    infGraveText:
        "Incurring in more than three (3) Classified Paragraphs or the recurrence of Minor Infractions.",
    infMuyGraveTitle: "Very Major Infraction:",
    infMuyGraveText:
        "Incurring in Paragraph 19 (The Writer of Infinite Paragraphs) or in any conduct that results in the physical abandonment of the interlocutor.",
    sub62Title: "Subarticle 6.2. Therapeutic Measures of Mandatory Consumption of Tedium (MCT).",
    sec621Title: "Section 6.2.1. Sanctions for Minor Infraction.",
    sec621Text:
        "The Active Subject must undergo a Non-Recreational Reading (NRR) session. This implies the mandatory reading of one (1) excerpt from an appliance instruction manual, the legal notice of a corporate website, or a random chapter of this Ode to Boredom.",
    sec622Title: "Section 6.2.2. Sanctions for Major Infraction.",
    sec622Text:
        "A Mandatory Documentary Viewing (MDV) is imposed. The Active Subject must consume thirty (30) minutes of audiovisual material consisting of recordings of security cameras without incidents, the reading of a telephone directory on a static screen, or the monitoring of a surveillance video of a repetitive industrial process.",
    sec623Title: "Section 6.2.3. Sanctions for Very Major Infraction.",
    sec623Text:
        "Reflective and Contemplative Seclusion (RCS) is required. The Active Subject must spend one hour without interacting with any digital device or printed material, forced to contemplate a wall painted in a neutral color or a blank page. The duration of the seclusion shall be increased by ten (10) minutes for each attempt to initiate a narrative about the chemical composition of the paint or paper.",
    sub63Title: "Subarticle 6.3. On the Administrative Procedure and Appeal.",
    sec631Title: "Section 6.3.1. Formalization of the Complaint.",
    sec631Text:
        'The complaint must be formalized by the Affected Interlocutor (the "Passive Subject") through the verbal and precise citation of the Classified Paragraph number and the concise description of the sanctionable conduct. The conciseness of the Passive Subject shall serve as proof of their communication efficiency.',
    sec632Title: "Section 6.3.2. Right of Appeal.",
    sec632Text:
        "The Active Subject has a period of five (5) minutes, counted from the notification of the sanction, to present an appeal. Said appeal must be written in the form of a haiku (a poem of three lines of 5, 7, and 5 syllables) and must explain the intrinsic need for their boredom. Any appeal that does not comply with the metric structure will be automatically dismissed for lack of formal rigor.",
    sec633Title: "Section 6.3.3. Compliance and Closing of the File.",
    sec633Text:
        'The file shall only be considered closed once the Active Subject has presented a certification of compliance with the MCT or NRR sanction. This certification must be a black and white photograph of the Active Subject during the performance of the imposed measure, accompanied by a sworn statement of having experienced "a feeling of deep, serene, and unalterable lack of emotion".',
    docInfo:
        "Official document issued under the protocol of Boredom focused on the Austerity of Design V.1.0.",
    warningTitle: "COMPLIANCE WARNING:",
    warningP1:
        "Pardon if this presentation of motives has generated, accidentally or involuntarily, any trace of interest, novelty, or entertainment in the reader. It was not my intention",
    warningP2:
        "In case you consider that the Legislator has erred or that there is an omission of some vital point for the defense of boredom, you can send your request to @jjlmoya.",
    warningP3:
        "IMPORTANT: Please proceed only if you are in a state of genuine boredom. Any indication of fun, wit, or enthusiasm in your communication will lead to the automatic and irrevocable dismissal of the petition.",
};
