import type { WheatTexts } from "../types";

export const WHEAT_ZH_TEXTS: WheatTexts = {
    common: {
        conceptName: "小麦",
        shareIdea: "分享想法",
        close: "关闭",
        millionsSuffix: "百万",
    },
    header: {
        light: "光明",
        title: "小麦的故事",
        details: "细节：光与影",
        shadow: "阴影",
    },
    deepTime: {
        chapter: "深邃时光",
        title: "20万年的寂静",
        firstParagraph:
            "在人类历史的99%时间里，我们都是游牧者（采集狩猎者）。世界不属于我们；我们属于世界。",
        secondParagraph: "我们狩猎、采集并不断前行。生活虽然危险，但却轻松自如。",
        quote: "我们没有主人，没有城墙，也没有愤怒的神灵。",
    },
    rachis: {
        chapter: "穗轴",
        title: "隐形的结构",
        lead: "一个微观的意外",
        explanationBeforeName: "人类文明的历史建立在一个生物学细节之上：",
        name: "穗轴（Rachis）",
        explanationAfterName:
            "。野生小麦的穗轴非常脆弱，以便种子散播；而驯化小麦的穗轴则十分坚硬，种子只能等待人类收割。",
        consequence:
            "正是这1毫米的生物学差异创造了“劳动的必要”。小麦不再能独立生长，我们也无法不播种而食。",
        quote: "一项血契由此签订：我们赋予它生命，它赋予 us 能量。",
    },
    trap: {
        chapter: "陷阱",
        title: "带毒的礼物",
        description: "这看似是一份礼物：稳定的食物。但小麦要求持续的服务——除草、浇水、驱赶害虫。",
        quote: "是我们驯化了小麦……还是小麦驯化了我们？",
        figureCaption: "> “这一连接点支撑着地球上的每一座城市。”",
    },
    grinding: {
        chapter: "日常",
        title: "痛苦的黎明",
        firstParagraph: "小麦需要磨碎才能食用。我们无法生吃，于是发明了石磨。",
        secondParagraph:
            "随之而来的是慢性背痛、膝关节炎和腰椎间盘突出。每天数小时跪在地板上，用一块石头推压另一块石头。",
        conclusion: "为攀爬和奔跑而进化的人体，在地面上折断了。",
    },
    skeleton: {
        imageAlt: "骨骼对比：狩猎者与农夫",
        chapter: "生物学代价",
        title: "残破的身躯",
        description:
            "农业的采用带来了一系列新的疾病：疝气、关节炎和脊柱变形。最糟糕的印记刻在骨头里。",
        quote: "人体经过200万年的进化是为了攀爬、奔跑和狩猎，而不是为了弯腰、掘地和搬运石头。",
        figureCaption: "图2：比较古病理学 (Cohen & Armelagos, 1984)",
    },
    calorieHunter: {
        chapter: "能量陷阱",
        title: "卡路里 vs 自由",
        introduction: "狩猎者工作时间更少，吃得更好。农夫工作时间更长，吃得更差。我们为什么改变？",
        figureTitle: "狩猎者的自由",
        workLabel: "每天工作时间",
        workValue: "4小时",
        nutritionLabel: "营养质量",
        nutritionValue: "高（多样化）",
        densityLabel: "人口密度",
        densityValue: "低（0.1人/km²）",
    },
    calorieFarmer: {
        chapter: "能量陷阱 II",
        title: "应付的代价",
        introduction: "小麦使得供养更多人口成为可能，即使人们过得更加悲惨。",
        figureTitle: "农夫的负担",
        workLabel: "每天工作时间",
        workValue: "10小时以上",
        nutritionLabel: "营养质量",
        nutritionValue: "低（单一作物）",
        densityLabel: "人口密度",
        densityValue: "爆发式（50人/km²）",
        conclusion:
            "进化追求的不是个人的幸福，而仅仅是更多的DNA复制品。小麦是繁衍人类的完美工具，却不是让人类幸福的工具。",
    },
    surplus: {
        figureLabel: "图4：积累",
        chapter: "剩余",
        title: "贫困的诞生",
        storageLead: "小麦具有肉类所不具备的特性：",
        storageEmphasis: "它可以储存",
        storageConclusion: "。干燥的谷物可以保存数年。人类的悲剧正由此诞生。",
        povertyQuote: "小麦发明了贫困。",
        inequality: "因为历史第一次，有人可以拥有“一切”，而另一些人可以“一无所有”。",
        power: "如果你能积聚食物，你就能积聚权力。粮仓出现了，保护粮仓的城墙出现了，守卫城墙的士兵出现了，计算谷物的国王出现了。",
        doubtTitle: "疑问",
        doubtText:
            "在小麦出现之前，我们在饥饿面前人人平等。谷物永远打破了社会平衡。我们建立城市是为了保护自己，还是为了防止他人抢夺小麦？",
    },
    socialContract: {
        chapter: "社会契约",
        title: "谷物法律",
        firstParagraph: "当你拥有粮仓时，你需要保护它。当你有饥饿的邻居时，你需要法律。",
        secondParagraph:
            "《汉谟拉比法典》是最早的成文法典之一，它谈论的不是自由，而是债务、谷物盗窃和灌溉渠。",
        quote: "正义的诞生是为了管理收成。",
        lawQuote: "“如果一人欠下谷物债务而无钱偿还，他应将儿子或女儿交出充当奴隶。”",
        lawAttribution: "— 《汉谟拉比法典》，约公元前1750年",
        tabletTitle: "行政泥板",
        tabletPlace: "乌鲁克，公元前3100年",
    },
    population: {
        chapter: "人口统计",
        title: "大爆发",
        description: "在20万年里，我们人口稀少。随后小麦降临了。",
        chartLabel: "全球人口（百万）",
        chartDates: [
            "公元前20万年",
            "公元前10万年",
            "公元前1万年",
            "0年",
            "公元1000年",
            "公元1800年",
            "2025年",
        ],
        paleolithic: { value: "约500万人", label: "旧石器时代人口" },
        romanEmpire: { value: "约2亿人", label: "罗马帝国" },
        present: { value: "82亿人", label: "2025年人口" },
    },
    workHours: {
        chapter: "进步的代价",
        title: "工作日",
        description: "与流行观点相反，“原始”生活并非一场永无休止的挣扎。",
        quote: "农业的承诺是安全，但代价是自由时间。",
        hunterHours: "约3-5小时",
        hunterMeasure: "维持生计",
        hunterTitle: "采集狩猎者",
        hunterDescription: "充裕的休闲时间。间歇性工作。",
        farmerHours: "约9-10小时",
        farmerMeasure: "日出而作，日落而息",
        farmerTitle: "新石器时代农夫",
        farmerDescription: "繁重的日常劳作。耕地、播种、收割和磨粉。",
        sourceNote: "数据基于马歇尔·萨林斯（《石器时代经济学》）的研究以及!Kung部落的人类学记录。",
    },
    modernMap: {
        chapter: "长时段",
        title: "今天的地图",
        firstParagraph: "时光流逝。帝国塌陷。宗教变迁。但小麦依然屹立。",
        secondParagraph:
            "看看今天的地图。不要只看政治边界；那是近代的发明。看看“结构”：养活80亿灵魂的辽阔单一作物平原。我们已经把地球改造变成了一个巨大的农场。",
        conclusion: "小麦赢得了进化的游戏。它占领的土地比任何自然森林都要多。",
    },
    future: {
        chapter: "未来",
        title: "无限的小麦",
        geneEditingTitle: "基因编辑",
        geneEditingText:
            "我们不再等待偶然的突变。现在我们重写小麦的基因代码，使其能抵御干旱、盐碱和酷热。未来的小麦将不再是天然的。",
        verticalFarmsTitle: "垂直农场",
        verticalFarmsText:
            "解放土地。在城市中心的高耸玻璃塔中向上种植。农夫的终结，农业工程师的开端。",
        conclusion: "“我们从驯化一株野草开始，最终驯化了整个地球来为它服务。”",
    },
    epilogue: {
        chapter: "结语",
        text: "“你手里拿着一块面包。这是100个世纪的选择、痛苦、工程和信仰的结晶。它是人类的电池。但疑问依然存在，像历史本身一样沉默：我们征服了饥饿……但在不再自由的路上，我们失去了什么？”",
    },
    documentation: {
        title: "文档与参考文献",
        references: [
            {
                category: "第一手资料",
                authors: "尤瓦尔·赫拉利",
                year: "(2011).",
                title: "人类简史：从动物到上帝",
                publisher: "中信出版社.",
                description: "“史上最大骗局”一章。分析小麦如何驯化了人类。",
            },
            {
                category: "人类学",
                authors: "詹姆斯·C·斯科特",
                year: "(2017).",
                title: "造法自然：早期国家的深层历史",
                publisher: "耶鲁大学出版社.",
                description: "关于早期农业国家的形成及余粮控制的研究。",
            },
            {
                category: "古病理学",
                authors: "Cohen, M. N., & Armelagos, G. J.",
                year: "(1984).",
                title: "Paleopathology at the Origins of Agriculture.",
                publisher: "Academic Press.",
                description: "骨骼研究汇编，展示身高降低及重复性劳损。",
            },
            {
                category: "经济学",
                authors: "马歇尔·萨林斯",
                year: "(1972).",
                title: "石器时代经济学",
                publisher: "生活·读书·新知三联书店.",
                description: "采集狩猎社会与农业社会工作时间的对比研究。",
            },
            {
                category: "植物学",
                authors: "Zohary, D., & Hopf, M.",
                year: "(2000).",
                title: "Domestication of Plants in the Old World.",
                publisher: "Oxford University Press.",
                description: "双粒小麦和单粒小麦穗轴突变的技术细节。",
            },
        ],
        projectLabel: "jjlmoya / 概念 / 小麦",
        updatedAt: "最后更新：2025年11月",
        status: "状态：已完成",
        identifier: "ID: CPT-003-WHEAT",
    },
    positiveDocumentation: {
        title: "参考文献：光明",
        references: [
            {
                category: "文明",
                authors: "雅各布·布洛诺夫斯基",
                year: "(1973).",
                title: "人类的升华",
                publisher: "BBC Books.",
                description: "分析定居农业如何使建筑和数学成为可能。",
            },
            {
                category: "啤酒",
                authors: "Katz, S. H., & Voigt, M. M.",
                year: "(1986).",
                title: "Bread and Beer: The Early Use of Cereals in the Human Diet.",
                publisher: "Expedition.",
                description: "关于谷物驯化的主要动机是酿造啤酒的假说。",
            },
            {
                category: "经济学",
                authors: "大卫·格雷伯",
                year: "(2011).",
                title: "债务：第一个5000年",
                publisher: "中信出版社.",
                description: "论苏美尔神庙中作为基于谷物的信用的货币起源。",
            },
        ],
    },
    choice: {
        heading: "选择你的阵营",
        shadowTitle: "阴影阵营",
        shadowDescription: "“农业是一个陷阱。我选择自由。”",
        shadowAction: "加入阴影",
        shadowShareText: "我看清了陷阱。小麦驯化了我们。我选择阴影的自由。 #小麦的故事 #阴影阵营",
        lightTitle: "光明阵营",
        lightDescription: "“文明是值得的。我选择进步。”",
        lightAction: "加入光明",
        lightShareText: "代价是高昂的，但文明是值得的。我选择进步的光明。 #小麦的故事 #光明阵营",
    },
    positiveExpansion: {
        chapter: "扩张",
        title: "不可阻挡的物种",
        description:
            "得益于小麦的高热量密度，我们得以在猎物稀少的地区定居。我们征服了沙漠、山脉和苔原。",
        dates: ["公元前10000年", "公元前8000年", "公元前5000年", "公元前3000年"],
        populations: ["100万人", "500万人", "5000万人"],
        chartLabel: "人口增长",
        metrics: [
            {
                value: "7大洲",
                label: "已定居",
                description: "小麦使在地球上每个宜居气候区建立永久定居点成为可能。",
            },
            {
                value: "50倍",
                label: "增长",
                description: "在农业的前7000年里，人类人口增长了50倍。",
            },
            {
                value: "∞",
                label: "潜力",
                description: "不受地理限制，人类成为了真正意义上的全球物种。",
            },
        ],
    },
    positiveKnowledge: {
        chapter: "科学",
        title: "时间的科学",
        firstParagraph: "狩猎者生活在永恒的当下。农夫需要预测未来。",
        secondParagraph:
            "为了知道何时播种，我们必须理解太阳和月亮的周期。我们发明了天文学、数学和几何学来测量农田。小麦是抽象科学之父。",
    },
    positiveSpecialization: {
        chapter: "天才",
        title: "天才的诞生",
        roles: [
            {
                title: "工匠",
                description:
                    "从寻找食物中解放出来的双手可以精制黏土、金属和布料。“大师”的概念诞生了。",
                skills: "制陶 • 冶金 • 纺织",
            },
            {
                title: "医者",
                description:
                    "闲暇时间使观察成为可能。我们不仅将植物视为食物，还将它们视为药物。药理学诞生了。",
                skills: "草药学 • 外科 • 诊断",
            },
            {
                title: "天文学家",
                description:
                    "我们需要预测收成。于是我们抬头仰望，绘制星空图。我们发明了日历和数学。",
                skills: "天文学 • 历法 • 几何学",
            },
        ],
        beforeValue: "100%",
        beforeLabel: "狩猎者",
        beforeCaption: "小麦之前",
        afterValue: "10%",
        afterLabel: "农夫",
        afterCaption: "小麦之后",
        conclusion:
            "剩余物资解放了90%的人口，使其致力于创新、艺术和科学。历史第一次，人类实现了专业化分工。",
        quote: "在狩猎部落中，所有人都在狩猎。在小麦之城，一人耕作，九人可以做梦。",
    },
    positiveLaw: {
        chapter: "法律",
        title: "混沌中的秩序",
        quote: "野生生活是自由的，但正义是任意的（丛林法则）。小麦迫使我们发明了客观正义。",
        conflictTitle: "冲突解决",
        conflictText:
            "当两个邻居为土地边界争执时，他们不再杀死对方，而是去找中立的第三方。法官和成文法诞生了。城墙内的暴力急剧下降。",
        propertyTitle: "产权",
        propertyText:
            "知道播种的成果归自己所有，使长期投资成为可能。如果认为明天房屋就会被抢走，就没有人会建造石屋。法律带来了稳定性。",
        beforeValue: "∞",
        beforeLabel: "之前",
        afterValue: "-90%",
        afterLabel: "之后",
        reductionLabel: "人际暴力的减少",
    },
    positiveBeer: {
        formula: "C₂H₅OH",
        formulaName: "乙醇",
        chapter: "庆典",
        title: "液态狂欢",
        theoryLead: "有一个严肃的理论指出，",
        theoryQuote: "我们驯化小麦不是为了做面包，而是为了酿造啤酒。",
        description:
            "发酵为我们提供了安全（无菌）且高热量的饮料。但更重要的是：它为我们带来了庆典、仪式和社会凝聚力。啤酒缓和了群居生活的摩擦。",
    },
    positiveTrade: {
        chapter: "贸易",
        title: "最早的货币",
        firstParagraph: "在黄金之前，是谷物。最初的舍克尔（shekel）不是硬币；它是大麦的重量单位。",
        secondParagraph:
            "小麦剩余使远距离贸易成为可能。它连接了孤立的部落，将安纳托利亚的黑曜石带到杰里科，将地中海的海壳带到沙漠。",
        conclusion:
            "小麦织就了人类合作的第一张全球网络。它不仅滋养了身体，还开辟了连接文明的第一条贸易路线。",
        shekelValue: "1舍克尔",
        shekelLabel: "≈ 180粒谷物",
        distanceValue: "3000 km",
        distanceLabel: "贸易路线",
        wheatLabel: "小麦",
        places: [
            "安纳托利亚",
            "杰里科",
            "乌鲁克",
            "埃及",
            "苏美尔",
            "黎凡特",
            "克里特",
            "塞浦路斯",
        ],
        goods: [
            { value: "黑曜石", label: "从安纳托利亚到美索不达米亚" },
            { value: "青金石", label: "从阿富汗到地中海" },
            { value: "贝壳", label: "从地中海到沙漠" },
        ],
    },
    positiveWriting: {
        binary: "10101010101010101010101010101010 01010101010101010101010101010101 11001100110011001100110011001100 ...",
        symbol: "阿列夫",
        symbolCaption: "历史的开端",
        chapter: "文字",
        title: "永恒的记忆",
        quote: "我们发明文字不是为了写诗，而是为了计算小麦的袋数。",
        firstParagraph:
            "但那个记账工具演变成了某种更伟大的东西。它使我们能够与死者对话，并给未出生的人留下讯息。小麦迫使我们创造了：",
        historyWord: "历史",
        secondParagraph:
            "没有谷物剩余，我们的记忆就会随着每一代人而抹去。有了小麦，我们的经验得以积累。我们在纸上永生。",
    },
    positiveCity: {
        chapter: "城市",
        title: "庇护之城",
        quote: "小麦要求我们停下脚步。作为交换，它给予我们城墙。",
        cities: [
            { value: "杰里科", label: "公元前8000年 — 第一座有城墙的城市" },
            { value: "恰塔霍裕克", label: "公元前7500年 — 10000人共存" },
            { value: "乌鲁克", label: "公元前4000年 — 第一座大都市" },
        ],
        description:
            "历史第一次，人类不再听凭风暴或野兽的摆布。我们创造了受控、安全的空间。“家”不再是一个临时概念，而成为了遗产。",
        centerLabel: "中心",
    },
    positiveSecurity: {
        chapter: "安全",
        title: "恐惧的终结",
        firstParagraph:
            "游牧生活是一场每日的赌博。如果不去狩猎，就没有食物。小麦带来了全新的东西：",
        emphasis: "未来。",
        secondParagraph:
            "历史第一次，人类能够满怀确信地面对明天。满载的粮仓意味着寒冬不再是死刑判决。",
        quote: "我们用野性的自由换取了内心的平静。",
        metrics: [
            { value: "365天", label: "安全的日子" },
            { value: "0次", label: "饥荒" },
            { value: "100%", label: "确信" },
        ],
        capacityLabel: "容量",
        reserveLabel: "战略储备",
        granaryLabel: "粮仓",
    },
    tableOfContents: {
        navigationLabel: "目录",
        openLabel: "打开目录",
        closeLabel: "关闭目录",
        title: "目录",
        sections: [
            { id: "positive-documentation", label: "参考文献", theme: "emerald" },
            { id: "dilema-luz", label: "选择阵营", theme: "emerald" },
            { id: "positive-expansion", label: "IX. 扩张", theme: "emerald" },
            { id: "positive-knowledge", label: "VIII. 科学", theme: "emerald" },
            { id: "positive-specialization", label: "VII. 天才", theme: "emerald" },
            { id: "positive-law", label: "VI. 法律", theme: "emerald" },
            { id: "positive-beer", label: "V. 庆典", theme: "emerald" },
            { id: "positive-trade", label: "IV. 贸易", theme: "emerald" },
            { id: "positive-writing", label: "III. 文字", theme: "emerald" },
            { id: "positive-city", label: "II. 城市", theme: "emerald" },
            { id: "positive-security", label: "I. 安全", theme: "emerald" },
            { id: "intro", label: "开始", theme: "neutral" },
            { id: "tiempo-profundo", label: "I. 深邃时光", theme: "amber" },
            { id: "raquis", label: "II. 穗轴", theme: "amber" },
            { id: "trampa", label: "III. 陷阱", theme: "amber" },
            { id: "rutina", label: "IV. 日常", theme: "amber" },
            { id: "cuerpos-rotos", label: "V. 残破的身躯", theme: "amber" },
            { id: "calorias-cazador", label: "VI. 卡路里（狩猎者）", theme: "amber" },
            { id: "calorias-agricultor", label: "VII. 卡路里（农夫）", theme: "amber" },
            { id: "excedente", label: "VIII. 剩余", theme: "amber" },
            { id: "contrato-social", label: "IX. 社会契约", theme: "amber" },
            { id: "demografia", label: "X. 人口统计", theme: "amber" },
            { id: "jornada-laboral", label: "XI. 工作日", theme: "amber" },
            { id: "mapa-moderno", label: "XII. 今天的地图", theme: "amber" },
            { id: "futuro", label: "XIII. 未来", theme: "amber" },
            { id: "epilogo", label: "结语", theme: "neutral" },
            { id: "documentacion", label: "参考文献", theme: "neutral" },
            { id: "dilema-sombra", label: "选择阵营", theme: "neutral" },
        ],
    },
};
