import { createNuanceTexts } from "./create";

export const NUANCE_DE_TEXTS = createNuanceTexts(
    {
        hud: {
            defaultLeft: "Links",
            defaultRight: "Rechts",
            hint: "Schieben, um zu entdecken",
            sliderLabel: "Gleichgewicht zwischen den Extremen",
        },
        intro: {
            labelLeft: "LEERE",
            labelRight: "DUNKELHEIT",
            title: "NUANCE",
            descriptionFirst: "Die wirkliche Welt ist voller Farben.",
            descriptionSecond: "Die Extreme sind deren Abwesenheit.",
            leftTitle: "WEISS",
            leftDescription: "Keine Schatten. Keine Zweifel.",
            rightTitle: "SCHWARZ",
            rightDescription: "Kein Licht. Keine Hoffnung.",
        },
        outro: {
            firstLine: "Die Welt will, dass du dich für eine Seite entscheidest.",
            secondLine: "Die wahre Revolution besteht darin, sich zu weigern.",
            exit: "Schleife verlassen",
            left: "LEERE",
            right: "DUNKELHEIT",
        },
    },
    [
        [
            "MÄNNERHASS",
            "MACHISMO",
            "Gleichheit",
            "GESCHLECHT",
            "Biologische Unterschiede anzuerkennen rechtfertigt keine ungleichen Rechte. Sie völlig zu leugnen ignoriert die materielle Realität. Gleichheit ist rechtlich und moralisch, nicht biologisch.",
            "SIE SIND ALLE<br />SCHULDIG",
            "MÄNNLICHKEIT IST KREBS.",
            "ZURÜCK IN DIE<br />KÜCHE",
            "DIE NATÜRLICHE ORDNUNG IST HEILIG.",
        ],
        [
            "TOXISCH",
            "REINE VERBINDUNG",
            "Soziales",
            "ALGORITHMUS",
            "Soziale Netzwerke können marginalisierten Stimmen Gehör verschaffen und Wissen demokratisieren, doch ihr heutiges Geschäftsmodell macht Polarisierung und Angst zu Geld.",
            "LÖSCH<br />ALLES",
            "WIR LEBEN IN EINER SIMULATION DES EGOS.",
            "POSTE<br />DEINE SEELE",
            "WENN DU ES NICHT TEILST, EXISTIERST DU NICHT.",
        ],
        [
            "UNVERMEIDLICHER KOLLAPS",
            "LEUGNUNG",
            "Planet",
            "ÖKO-LOGIK",
            "Panik lähmt und Leugnung verdammt. Wir brauchen entschlossene technologische Innovation und gezieltes Schrumpfen, keine Rückkehr in die Höhlen und kein Vortäuschen, dass nichts geschieht.",
            "ROHSTOFFABBAU<br />IST MORD",
            "DER MENSCH IST DIE PLAGE.",
            "DAS KLIMA<br />ÄNDERT SICH IMMER",
            "DIE WIRTSCHAFT IST UNANTASTBAR.",
        ],
        [
            "MITTELMASS",
            "ARBEITSSUCHT",
            "Leben",
            "ERFOLG",
            "Erfolg ist nicht nur Geld oder Ruhm, sondern ein sinnvolles Leben. Den Bedarf an materiellen Mitteln in einer kapitalistischen Gesellschaft zu ignorieren ist jedoch naiv, nicht tugendhaft.",
            "GIB DICH ZUFRIEDEN",
            "EHRGEIZ IST ETWAS FÜR PSYCHOPATHEN.",
            "SCHLAF<br />NIE",
            "ERHOLUNG IST FÜR SCHWACHE.",
        ],
        [
            "MILITANTER VEGANISMUS",
            "REINER KARNIVORISMUS",
            "Ernährung",
            "KULTURELLE ERNÄHRUNG",
            "Essen ist ein ethischer und biologischer Akt. Wir können Tierleid verringern, ohne unsere omnivore Evolutionsgeschichte zu leugnen. Es gibt keine heilige Ernährung.",
            "DU ISST<br />LEICHEN",
            "DU BIST EIN SPEZIESISTISCHER MÖRDER.",
            "SCHWACHER<br />SOYBOY",
            "NUR BLUT GIBT KRAFT.",
        ],
        [
            "RADIKALER ATHEISMUS",
            "FANATISMUS",
            "Spiritualität",
            "GLAUBE UND VERNUNFT",
            "Die Wissenschaft erklärt das Wie, Spiritualität sucht das Warum. Wir können die wissenschaftliche Methode annehmen, ohne das Staunen über das Geheimnis der Existenz zu verlieren.",
            "GOTT IST<br />TOT",
            "WIR SIND ZUFÄLLIGE SÄCKE AUS FLEISCH.",
            "ZAHL DEN ZEHNTEN<br />ODER BRENNE",
            "ZWEIFEL IST EINE TODSÜNDE.",
        ],
        [
            "REINES PONZI-SYSTEM",
            "NEUE ORDNUNG",
            "Geld",
            "DIGITALER WERT",
            "Blockchain ist eine revolutionäre Technologie voller Betrüger. Zentralbanken bestehlen uns durch Inflation, doch vollständige Dezentralisierung ist ein Dschungel.",
            "SCHNEEBALL-<br />SYSTEM",
            "ALLES IST RAUCH UND GELDWÄSCHE.",
            "HODL<br />BIS ZUM TOD",
            "FIAT IST MORGEN NULL WERT.",
        ],
        [
            "FREMDENFEINDLICHKEIT",
            "STAATENLOS",
            "Zugehörigkeit",
            "NATIONALE IDENTITÄT",
            "Die eigene Kultur zu lieben heißt nicht, die des Nachbarn zu hassen. Weltbürger zu sein ist ein leeres Privileg, wenn man sich nicht zuerst um die lokale Gemeinschaft kümmert.",
            "GRENZEN<br />SCHLIESSEN",
            "DIE EIGENEN ZUERST.",
            "NATIONEN<br />SIND GEFÄNGNISSE",
            "KEIN MENSCH IST ILLEGAL.",
        ],
        [
            "CHAOTISCHE POLYAMORIE",
            "BESITZ",
            "Beziehungen",
            "BINDUNG",
            "Individuelle Freiheit sollte tiefe Bindung nicht verhindern. Lieben heißt, auf die Möglichkeit anderer Welten zu verzichten, um eine gemeinsame und beständige zu errichten.",
            "NICHTS GEHÖRT<br />IRGENDWEM",
            "BINDUNG IST EIN GEFÄNGNIS.",
            "DU BIST<br />MEIN EIGENTUM",
            "EIFERSUCHT IST LIEBE.",
        ],
        [
            "HAUSBESETZUNG",
            "SPEKULATION",
            "Zuhause",
            "EIN WÜRDIGES DACH",
            "Wohnen ist ein Recht, nicht bloß ein Finanzwert. Doch Rechtssicherheit und private Investitionen sind nötig, um dieses Recht aufzubauen.",
            "ENTEIGNET<br />ALLES",
            "VERMIETER SIND PARASITEN.",
            "DER MARKT<br />REGELT SICH SELBST",
            "WENN DU ARM BIST, BIST DU SELBST SCHULD.",
        ],
        [
            "SNOBISMUS",
            "AUTOMATISIERUNG",
            "Kreativität",
            "SYNTHETISCHE SEELE",
            "Kunst ist nicht nur das Ergebnis, sondern der menschliche Prozess, Sinn zu schaffen. KI demokratisiert Technik, doch Schmerz und Erfahrung kann sie niemals demokratisieren.",
            "DAS IST KEINE<br />KUNST",
            "NUR ÖLFARBE HAT EINE SEELE.",
            "PASS DICH AN<br />ODER STIRB",
            "DER KÜNSTLER IST VERZICHTBAR.",
        ],
        [
            "INDOKTRINATION",
            "VERWILDERUNG",
            "Bildung",
            "LERNEN",
            "Schule soll lehren, wie man denkt, nicht was man denkt. Strukturiertes und geteiltes Wissen ist jedoch die Grundlage der Zivilisation, keine Unterdrückung.",
            "ZIEGEL-<br />FABRIK",
            "SIE TÖTEN DEINE KREATIVITÄT.",
            "FREIE<br />UNWISSENHEIT",
            "MEIN KIND LERNT BEIM TIKTOK-SCHAUEN.",
        ],
        [
            "POLIZEISTAAT",
            "ANARCHIE",
            "Sicherheit",
            "ZUSAMMENLEBEN",
            "Wir wollen ohne Angst durch die Straßen gehen, aber nicht um den Preis ständiger Überwachung. Echte Sicherheit entsteht aus sozialem Zusammenhalt, nicht aus Kameras.",
            "KAMERAS<br />IM BAD",
            "WER NICHTS ZU VERBERGEN HAT, HAT NICHTS ZU BEFÜRCHTEN.",
            "RECHT DES<br />STÄRKEREN",
            "KAUF DIR EINE WAFFE ODER STIRB.",
        ],
        [
            "PROHIBITION",
            "DROGENSTAAT",
            "Öffentliche Gesundheit",
            "ALTER EGO",
            "Der Krieg gegen Drogen ist gescheitert, doch unkontrollierter Konsum zerstört Leben. Wir brauchen Bildung, Regulierung und Verantwortung, keinen Moralismus und kein Chaos.",
            "DEIN KÖRPER<br />GEHÖRT DEM STAAT",
            "SAG NEIN ZUM LEBEN.",
            "ZOMBIES<br />AUF DER STRASSE",
            "ALLES IST ERLAUBT, WENN ES HIGH MACHT.",
        ],
        [
            "ANTINATALISMUS",
            "BRUTKASTEN",
            "Familie",
            "VERMÄCHTNIS",
            "Kinder in die Welt zu setzen ist ein Akt radikaler Hoffnung, keine patriotische Pflicht und kein ökologisches Verbrechen. Bewusste Erziehung ist unser größter Beitrag zur Zukunft.",
            "LEBEN IST<br />LEIDEN",
            "FREIWILLIGES AUSSTERBEN JETZT.",
            "GEBÄR ODER<br />STIRB",
            "FRAUEN SIND FABRIKEN.",
        ],
        [
            "TRANSPARENZ",
            "PHANTOM",
            "Daten",
            "PRIVATSPHÄRE",
            "Privatsphäre ist für Freiheit notwendig. Vollständige Anonymität schützt aber auch grausame Verbrechen. Wo liegt die Grenze zwischen Sicherheit und dem Recht auf Geheimhaltung?",
            "GEHEIMNIS<br />IST SCHULD",
            "VERÖFFENTLICHE DEINEN GANZEN CHAT.",
            "DARK<br />WEB",
            "KRYPTOGRAFISCHE STRAFLOSIGKEIT.",
        ],
        [
            "BIG PHARMA",
            "PSEUDOWISSENSCHAFT",
            "Gesundheit",
            "HEILUNG",
            "Moderne Medizin rettet Leben, heilt aber nicht immer die Seele und verhindert nicht jede Krankheit. Auf den Körper zu hören heißt nicht, Antibiotika abzulehnen.",
            "EINE PILLE<br />FÜR ALLES",
            "DEIN SCHMERZ IST EIN MARKT.",
            "KREBS<br />IST MENTAL",
            "HOHE SCHWINGUNGEN UND ZUCKERWASSER.",
        ],
        [
            "GERONTOKRATIE",
            "ALTERSDISKRIMINIERUNG",
            "Zeit",
            "REIFE",
            "Alt zu werden ist ein Privileg, keine Krankheit. Wir müssen für jene sorgen, die für uns sorgten, ohne die Zukunft der Jungen zu verpfänden.",
            "UNSTERBLICHKEIT<br />UM JEDEN PREIS",
            "DIE JUGEND WEISS GAR NICHTS.",
            "DU BIST<br />ÜBERFLÜSSIG, OPA",
            "FLUCHT INS 23. JAHRHUNDERT WAR EINE DOKU.",
        ],
        [
            "GRUNDEINKOMMEN",
            "LUDDISMUS",
            "Zukunft",
            "SINN",
            "Wenn Maschinen arbeiten, was tun dann wir? Arbeit gibt Würde, Ausbeutung nicht. Wir müssen menschlichen Wert jenseits der Produktivität neu bestimmen.",
            "GRATIS-<br />GELD",
            "NIEMAND SOLLTE JE ARBEITEN MÜSSEN.",
            "VERBRENNT DIE<br />MASCHINEN",
            "TECHNOLOGIE IST DER TEUFEL.",
        ],
        [
            "SKALPELL",
            "VERWAHRLOSUNG",
            "Ästhetik",
            "SELBSTWERT",
            "Gut aussehen zu wollen ist menschlich; Selbsthass ist profitabel. Gesundheit sollte der Maßstab sein, doch vielfältige Schönheit ist die Realität.",
            "DAUER-<br />FILTER",
            "DEIN ECHTES GESICHT IST EIN MAKEL.",
            "FETTLEIBIGKEIT<br />IST GESUND",
            "BIOLOGIE ZU LEUGNEN IST EMPOWERMENT.",
        ],
        [
            "DIKTATUR",
            "POBELHERRSCHAFT",
            "Macht",
            "REGIERUNG",
            "Der starke Führer verspricht Ordnung, bringt aber Tyrannei. Die Masse verspricht Mitsprache, bringt aber Chaos. Langweilige Institutionen sind unser einziger Schutz vor uns selbst.",
            "HARTE HAND",
            "FREIHEIT WIRD ÜBERBEWERTET.",
            "BRENN DAS<br />PARLAMENT NIEDER",
            "DAS VOLK HAT IMMER RECHT.",
        ],
        [
            "TODESSTRAFE",
            "STRAFLOSIGKEIT",
            "Gerechtigkeit",
            "WIEDERGUTMACHUNG",
            "Auge um Auge macht uns blind, doch Opfer zu ignorieren schafft Monster. Wiedereingliederung ist das Ideal, der Schutz der Gesellschaft die Pflicht.",
            "TÖTET SIE<br />ALLE",
            "RACHE IST SÜSS.",
            "SCHAFFT<br />GEFÄNGNISSE AB",
            "KEIN VERBRECHEN VERDIENT STRAFE.",
        ],
        [
            "SCHWARZE LEGENDE",
            "ROSAROTE LEGENDE",
            "Erinnerung",
            "VERGANGENHEIT",
            "Wir können das 15. Jahrhundert weder mit der Moral des 21. beurteilen noch Völkermorde beschönigen. Geschichte ist kein Märchen von Helden und Schurken, sondern eine Lektion in Komplexität.",
            "ALLES WAR<br />VÖLKERMORD",
            "DEINE KULTUR IST SCHULD.",
            "RUHMREICHES<br />REICH",
            "WIR HABEN NIE ETWAS FALSCH GEMACHT.",
        ],
        [
            "WISSENSCHAFTSRELIGION",
            "VERSCHWÖRUNG",
            "Wahrheit",
            "EVIDENZ",
            "Wissenschaft ist eine Methode, Fehler zu verringern, kein unveränderliches Dogma. Fragen ist gesund, doch die beobachtbare Realität zu leugnen führt in den Abgrund des Wahns.",
            "DER EXPERTE<br />IST GOTT",
            "DENK NICHT, VERTRAU.",
            "DIE ERDE<br />IST FLACH",
            "ALLES IST MANIPULIERT.",
        ],
        [
            "FELLKINDER",
            "VERDINGLICHUNG",
            "Natur",
            "ARTEN",
            "Tiere fühlen und verdienen Respekt, doch sie zu vermenschlichen ist eine andere Form der Misshandlung. Sie zu lieben heißt, ihre Natur zu verstehen, nicht sie als Babys zu verkleiden.",
            "MEHR ALS<br />MENSCHEN",
            "RETTE DEN HUND, TÖTE DAS KIND.",
            "SIE SIND NUR<br />DINGE",
            "BENUTZ SIE UND WIRF SIE WEG.",
        ],
        [
            "UNIFORM",
            "FAST FASHION",
            "Erscheinung",
            "AUSDRUCK",
            "Kleidung ist Sprache, doch zwanghafter Konsum ist Zerstörung. Wir können Stil haben, ohne den Planeten auszubeuten oder selbst zu Werbetafeln zu werden.",
            "TRAG<br />GRAU",
            "AUFFALLEN IST EITELKEIT.",
            "KAUFEN<br />UND WEGWERFEN",
            "NEUE SACHEN MACHEN GLÜCKLICH.",
        ],
        [
            "VERBOT",
            "SPIELSUCHT",
            "Laster",
            "ZUFALL",
            "Glücksspiel ist Unterhaltung für Erwachsene, doch eine räuberische Industrie zerstört Familien. Aggressive Werbung zu regulieren schützt die freie Wahl vor Fallen.",
            "ILLEGALER<br />SPASS",
            "VERGNÜGEN IST SÜNDE.",
            "VERWETTE<br />DAS HAUS",
            "DIE NÄCHSTE RUNDE RETTET DICH.",
        ],
        [
            "TOURIST GO HOME",
            "FREIZEITPARK",
            "Reisen",
            "ERKUNDUNG",
            "Reisen öffnet den Geist, doch Massentourismus verdrängt ganze Viertel. Wir wollen die Welt kennenlernen, ohne sie in eine Kulisse aus Pappmaché zu verwandeln.",
            "VERSCHWINDE<br />VON HIER",
            "AUSLÄNDER STÖREN.",
            "VERKAUF DEIN<br />VIERTEL",
            "ALLES IST EIN AIRBNB.",
        ],
        [
            "INKLUSIVE SPRACHE",
            "SPRACHPURISMUS",
            "Kommunikation",
            "WÖRTER",
            "Sprache entwickelt sich mit der Gesellschaft, doch künstlich erzwungene Änderungen erzeugen Ablehnung. Reden wir, um einander zu verstehen, nicht um politische Tugend zu demonstrieren.",
            "SPRICH RICHTIG,<br />VERDAMMT",
            "DAS GENDERN ZERSTÖRT DIE FAMILIE.",
            "DER DUDEN IST<br />SEXISTISCH",
            "ÄNDERE DICH ODER DU BIST DER FEIND.",
        ],
        [
            "SIEGEN IST ALLES",
            "TEILNAHME",
            "Wettkampf",
            "ANSTRENGUNG",
            "Exzellenz verlangt Opfer, und es gibt Gewinner und Verlierer. Breitensport sollte aber Werte fördern, nicht verfrühten Frust.",
            "DER ZWEITE<br />IST DER ERSTE VERLIERER",
            "DEMÜTIGE DEINEN GEGNER.",
            "ALLE SIND<br />SIEGER",
            "VERLIEREN TRAUMATISIERT FÜRS LEBEN.",
        ],
        [
            "HIKIKOMORI",
            "ERZWUNGENE GESELLIGKEIT",
            "Gemeinschaft",
            "VERBINDUNG",
            "Allein sein zu können ist lebenswichtig, doch Isolation ist krankhaft. Wir sind soziale Tiere und brauchen den Stamm, auch wenn er manchmal erdrückt.",
            "ICH HASSE<br />MENSCHEN",
            "MEIN ZIMMER IST MEINE WELT.",
            "LÄCHLE UND<br />MACH MIT",
            "INTROVERSION IST HEILBAR.",
        ],
    ]
);
