import { createNuanceTexts } from "./create";

export const NUANCE_EN_TEXTS = createNuanceTexts(
    {
        hud: {
            defaultLeft: "Left",
            defaultRight: "Right",
            hint: "Slide to discover",
            sliderLabel: "Balance between extremes",
        },
        intro: {
            labelLeft: "EMPTINESS",
            labelRight: "DARKNESS",
            title: "NUANCE",
            descriptionFirst: "The real world is full of colour.",
            descriptionSecond: "Extremes are its absence.",
            leftTitle: "WHITE",
            leftDescription: "No shadows. No doubts.",
            rightTitle: "BLACK",
            rightDescription: "No light. No hope.",
        },
        outro: {
            firstLine: "The world wants you to pick a side.",
            secondLine: "The true revolution is refusing to.",
            exit: "Exit the Loop",
            left: "EMPTINESS",
            right: "DARKNESS",
        },
    },
    [
        [
            "MISANDRY",
            "MACHISMO",
            "Equality",
            "GENDER",
            "Recognising biological differences does not justify unequal rights. Denying them altogether ignores material reality. Equality is legal and moral, not biological.",
            "THEY ARE ALL<br />GUILTY",
            "MASCULINITY IS A CANCER.",
            "GET BACK IN THE<br />KITCHEN",
            "THE NATURAL ORDER IS SACRED.",
        ],
        [
            "TOXIC",
            "PURE CONNECTION",
            "Social",
            "ALGORITHM",
            "Social media can amplify marginalised voices and democratise knowledge, but its current business model monetises polarisation and anxiety.",
            "DELETE IT<br />ALL",
            "WE LIVE IN A SIMULATION OF EGO.",
            "POST<br />YOUR SOUL",
            "IF YOU DO NOT SHARE IT, YOU DO NOT EXIST.",
        ],
        [
            "INEVITABLE COLLAPSE",
            "DENIAL",
            "Planet",
            "ECO-LOGIC",
            "Panic paralyses and denial condemns. We need aggressive technological innovation and selective degrowth, not a return to the caves or the pretence that nothing is happening.",
            "EXTRACTION<br />IS MURDER",
            "HUMANKIND IS THE PLAGUE.",
            "THE CLIMATE<br />ALWAYS CHANGES",
            "THE ECONOMY IS UNTOUCHABLE.",
        ],
        [
            "MEDIOCRITY",
            "WORKAHOLIC",
            "Life",
            "SUCCESS",
            "Success is not merely money or fame; it is living with purpose. Yet ignoring the need for material resources in a capitalist society is naïveté, not virtue.",
            "SETTLE",
            "AMBITION IS FOR PSYCHOPATHS.",
            "NEVER<br />SLEEP",
            "REST IS FOR THE WEAK.",
        ],
        [
            "MILITANT VEGANISM",
            "PURE CARNIVORISM",
            "Nutrition",
            "CULTURAL NUTRITION",
            "Eating is both an ethical and a biological act. We can reduce animal suffering without denying our omnivorous evolutionary history. There is no holy diet.",
            "YOU EAT<br />CORPSES",
            "YOU ARE A SPECIESIST MURDERER.",
            "WEAK<br />SOY BOY",
            "ONLY BLOOD GIVES STRENGTH.",
        ],
        [
            "RADICAL ATHEISM",
            "FANATICISM",
            "Spirituality",
            "FAITH AND REASON",
            "Science explains how; spirituality seeks why. We can embrace the scientific method without losing our wonder at the mystery of existence.",
            "GOD IS<br />DEAD",
            "WE ARE RANDOM BAGS OF MEAT.",
            "TITHE OR<br />BURN",
            "DOUBT IS A MORTAL SIN.",
        ],
        [
            "TOTAL PONZI",
            "NEW ORDER",
            "Money",
            "DIGITAL VALUE",
            "Blockchain is a revolutionary technology crowded with scammers. Central banks rob us through inflation, but total decentralisation is a jungle.",
            "PYRAMID<br />SCHEME",
            "IT IS ALL SMOKE AND MONEY LAUNDERING.",
            "HODL<br />UNTIL DEATH",
            "FIAT GOES TO ZERO TOMORROW.",
        ],
        [
            "XENOPHOBIA",
            "STATELESS",
            "Belonging",
            "NATIONAL IDENTITY",
            "Loving your culture does not mean hating your neighbour’s. Being a citizen of the world is an empty privilege if you do not care for your local community first.",
            "CLOSE THE<br />BORDERS",
            "OUR OWN PEOPLE FIRST.",
            "NATIONS<br />ARE PRISONS",
            "NO HUMAN BEING IS ILLEGAL.",
        ],
        [
            "CHAOTIC POLYAMORY",
            "POSSESSION",
            "Relationships",
            "BOND",
            "Individual freedom should not prevent deep commitment. To love is to relinquish the possibility of other worlds in order to build one that is shared and solid.",
            "NOTHING BELONGS<br />TO ANYONE",
            "COMMITMENT IS A PRISON.",
            "YOU ARE<br />MY PROPERTY",
            "JEALOUSY IS LOVE.",
        ],
        [
            "SQUATTING",
            "SPECULATION",
            "Home",
            "A DECENT ROOF",
            "Housing is a right, not merely a financial asset. But legal certainty and private investment are necessary to build that right.",
            "EXPROPRIATE<br />EVERYTHING",
            "LANDLORDS ARE PARASITES.",
            "THE MARKET<br />REGULATES ITSELF",
            "IF YOU ARE POOR, IT IS YOUR FAULT.",
        ],
        [
            "SNOBBERY",
            "AUTOMATION",
            "Creativity",
            "SYNTHETIC SOUL",
            "Art is not only the result; it is the human process of making meaning. AI democratises technique, but it can never democratise pain or experience.",
            "THAT IS NOT<br />ART",
            "ONLY OIL PAINT HAS A SOUL.",
            "ADAPT<br />OR DIE",
            "THE ARTIST IS DISPENSABLE.",
        ],
        [
            "INDOCTRINATION",
            "SAVAGERY",
            "Education",
            "LEARNING",
            "School should teach us how to think, not what to think. Yet structured, shared knowledge is the foundation of civilisation, not a form of oppression.",
            "BRICK<br />FACTORY",
            "THEY KILL YOUR CREATIVITY.",
            "FREE<br />IGNORANCE",
            "MY CHILD LEARNS BY WATCHING TIKTOK.",
        ],
        [
            "POLICE STATE",
            "ANARCHY",
            "Safety",
            "COEXISTENCE",
            "We want to walk the streets without fear, but not at the cost of being watched around the clock. Real safety grows from social cohesion, not cameras.",
            "CAMERAS IN<br />THE BATHROOM",
            "IF YOU HAVE NOTHING TO HIDE, YOU HAVE NOTHING TO FEAR.",
            "SURVIVAL OF<br />THE STRONGEST",
            "BUY A GUN OR DIE.",
        ],
        [
            "PROHIBITION",
            "NARCO-STATE",
            "Public Health",
            "ALTER EGO",
            "The war on drugs has failed, but uncontrolled consumption destroys lives. We need education, regulation and responsibility, not moralism or chaos.",
            "YOUR BODY<br />BELONGS TO THE STATE",
            "JUST SAY NO TO LIFE.",
            "ZOMBIES<br />IN THE STREET",
            "ANYTHING GOES IF IT GETS YOU HIGH.",
        ],
        [
            "ANTINATALISM",
            "INCUBATOR",
            "Family",
            "LEGACY",
            "Bringing children into the world is an act of radical hope, not a patriotic duty or an ecological crime. Conscious parenting is our greatest contribution to the future.",
            "LIFE IS<br />SUFFERING",
            "VOLUNTARY EXTINCTION NOW.",
            "BREED OR<br />DIE",
            "WOMEN ARE FACTORIES.",
        ],
        [
            "TRANSPARENCY",
            "GHOST",
            "Data",
            "PRIVACY",
            "Privacy is necessary for freedom. Yet total anonymity also shields atrocious crimes. Where is the boundary between safety and the right to secrecy?",
            "SECRECY<br />MEANS GUILT",
            "PUBLISH YOUR ENTIRE CHAT.",
            "DARK<br />WEB",
            "CRYPTOGRAPHIC IMPUNITY.",
        ],
        [
            "BIG PHARMA",
            "PSEUDOSCIENCE",
            "Health",
            "HEALING",
            "Modern medicine saves lives, but it does not always heal the soul or prevent disease. Listening to the body does not mean rejecting antibiotics.",
            "A PILL<br />FOR EVERYTHING",
            "YOUR PAIN IS A MARKET.",
            "CANCER<br />IS MENTAL",
            "HIGH VIBES AND SUGAR WATER.",
        ],
        [
            "GERONTOCRACY",
            "AGEISM",
            "Time",
            "MATURITY",
            "Growing old is a privilege, not a disease. We must care for those who cared for us without mortgaging the future of the young.",
            "IMMORTALITY<br />AT ANY COST",
            "YOUNG PEOPLE KNOW NOTHING.",
            "YOU ARE<br />SURPLUS, GRANDPA",
            "LOGAN’S RUN WAS A DOCUMENTARY.",
        ],
        [
            "BASIC INCOME",
            "LUDDISM",
            "Future",
            "PURPOSE",
            "If machines do the work, what do we do? Work dignifies, but exploitation does not. We must redefine human value beyond productivity.",
            "FREE<br />MONEY",
            "NO ONE SHOULD EVER HAVE TO WORK.",
            "BURN THE<br />MACHINES",
            "TECHNOLOGY IS THE DEVIL.",
        ],
        [
            "SCALPEL",
            "NEGLECT",
            "Aesthetics",
            "SELF-ESTEEM",
            "Wanting to look good is human; making us hate ourselves is profitable. Health should be the standard, but diverse beauty is reality.",
            "PERMANENT<br />FILTER",
            "YOUR REAL FACE IS A DEFECT.",
            "OBESITY<br />IS HEALTH",
            "DENYING BIOLOGY IS EMPOWERING.",
        ],
        [
            "DICTATORSHIP",
            "MOB RULE",
            "Power",
            "GOVERNMENT",
            "The strong leader promises order but brings tyranny. The crowd promises a voice but brings chaos. Boring institutions are all that protects us from ourselves.",
            "IRON FIST",
            "FREEDOM IS OVERRATED.",
            "BURN DOWN<br />PARLIAMENT",
            "THE PEOPLE ARE ALWAYS RIGHT.",
        ],
        [
            "DEATH PENALTY",
            "IMPUNITY",
            "Justice",
            "REPARATION",
            "An eye for an eye leaves us blind, but ignoring victims creates monsters. Reintegration is the ideal, yet protecting society is the duty.",
            "KILL THEM<br />ALL",
            "REVENGE IS SWEET.",
            "ABOLISH<br />PRISONS",
            "NO CRIME DESERVES PUNISHMENT.",
        ],
        [
            "BLACK LEGEND",
            "PINK LEGEND",
            "Memory",
            "THE PAST",
            "We cannot judge the fifteenth century by twenty-first-century morals, nor can we whitewash genocide. History is not a tale of heroes and villains; it is a lesson in complexity.",
            "IT WAS ALL<br />GENOCIDE",
            "YOUR CULTURE IS GUILTY.",
            "GLORIOUS<br />EMPIRE",
            "WE NEVER DID ANYTHING WRONG.",
        ],
        [
            "SCIENTIFIC RELIGION",
            "CONSPIRACY",
            "Truth",
            "EVIDENCE",
            "Science is a method for reducing error, not an immutable dogma. Questioning is healthy, but denying observable reality is to fall into the abyss of delusion.",
            "THE EXPERT<br />IS GOD",
            "DO NOT THINK. TRUST.",
            "THE EARTH<br />IS FLAT",
            "EVERYTHING IS RIGGED.",
        ],
        [
            "FUR BABIES",
            "OBJECTIFICATION",
            "Nature",
            "SPECIES",
            "Animals feel and deserve respect, but humanising them is another form of mistreatment. Loving them means understanding their nature, not dressing them up as babies.",
            "MORE THAN<br />HUMAN",
            "SAVE THE DOG, KILL THE CHILD.",
            "THEY ARE JUST<br />THINGS",
            "USE THEM AND THROW THEM AWAY.",
        ],
        [
            "UNIFORM",
            "FAST FASHION",
            "Image",
            "EXPRESSION",
            "Clothing is language, but compulsive consumption is destruction. We can have style without exploiting the planet or turning ourselves into billboards.",
            "WEAR<br />GREY",
            "STANDING OUT IS VANITY.",
            "BUY<br />AND BIN",
            "NEW CLOTHES ARE HAPPINESS.",
        ],
        [
            "PROHIBITION",
            "GAMBLING ADDICTION",
            "Vice",
            "CHANCE",
            "Gambling is adult entertainment, but a predatory industry destroys families. Regulating aggressive advertising protects the freedom to choose without traps.",
            "ILLEGAL<br />FUN",
            "PLEASURE IS A SIN.",
            "BET<br />THE HOUSE",
            "THE NEXT SPIN WILL SAVE YOU.",
        ],
        [
            "TOURIST GO HOME",
            "THEME PARK",
            "Travel",
            "EXPLORATION",
            "Travel broadens the mind, but mass tourism closes neighbourhoods. We want to discover the world without turning it into a cardboard stage set.",
            "GET OUT<br />OF HERE",
            "FOREIGNERS ARE A NUISANCE.",
            "SELL YOUR<br />NEIGHBOURHOOD",
            "EVERYTHING IS AN AIRBNB.",
        ],
        [
            "INCLUSIVE LANGUAGE",
            "LINGUISTIC PURISM",
            "Communication",
            "WORDS",
            "Language evolves with society, but imposing artificial changes breeds rejection. Let us speak to understand one another, not to signal political virtue.",
            "SPEAK PROPERLY,<br />DAMN IT",
            "THE ‘E’ DESTROYS THE FAMILY.",
            "THE ACADEMY IS<br />SEXIST",
            "CHANGE OR YOU ARE THE ENEMY.",
        ],
        [
            "WINNING IS EVERYTHING",
            "PARTICIPATION",
            "Competition",
            "EFFORT",
            "Excellence requires sacrifice, and there are winners and losers. But grassroots sport should foster values, not premature frustration.",
            "SECOND PLACE<br />IS THE FIRST LOSER",
            "HUMILIATE YOUR RIVAL.",
            "EVERYONE IS<br />A CHAMPION",
            "LOSING TRAUMATISES YOU FOR LIFE.",
        ],
        [
            "HIKIKOMORI",
            "FORCED SOCIALISING",
            "Community",
            "CONNECTION",
            "Knowing how to be alone is vital, but isolation is pathological. We are social animals that need the tribe, even when the tribe can be overwhelming.",
            "I HATE<br />PEOPLE",
            "MY ROOM IS MY WORLD.",
            "SMILE AND<br />JOIN IN",
            "INTROVERSION CAN BE CURED.",
        ],
    ]
);
