import { createNuanceTexts } from "./create";

export const NUANCE_FR_TEXTS = createNuanceTexts(
    {
        hud: {
            defaultLeft: "Gauche",
            defaultRight: "Droite",
            hint: "Faites glisser pour découvrir",
            sliderLabel: "Équilibre entre les extrêmes",
        },
        intro: {
            labelLeft: "VIDE",
            labelRight: "OBSCURITÉ",
            title: "NUANCE",
            descriptionFirst: "Le monde réel est plein de couleurs.",
            descriptionSecond: "Les extrêmes en sont l’absence.",
            leftTitle: "BLANC",
            leftDescription: "Sans ombres. Sans doutes.",
            rightTitle: "NOIR",
            rightDescription: "Sans lumière. Sans espoir.",
        },
        outro: {
            firstLine: "Le monde veut que vous choisissiez un camp.",
            secondLine: "La véritable révolution, c’est de refuser.",
            exit: "Sortir de la boucle",
            left: "VIDE",
            right: "OBSCURITÉ",
        },
    },
    [
        [
            "MISANDRIE",
            "MACHISME",
            "Égalité",
            "GENRE",
            "Reconnaître les différences biologiques ne justifie pas l’inégalité des droits. Les nier entièrement revient à ignorer la réalité matérielle. L’égalité est juridique et morale, non biologique.",
            "ILS SONT TOUS<br />COUPABLES",
            "LA MASCULINITÉ EST UN CANCER.",
            "RETOURNE À LA<br />CUISINE",
            "L’ORDRE NATUREL EST SACRÉ.",
        ],
        [
            "TOXIQUE",
            "CONNEXION PURE",
            "Société",
            "ALGORITHME",
            "Les réseaux sociaux peuvent amplifier les voix marginalisées et démocratiser le savoir, mais leur modèle économique actuel monétise la polarisation et l’anxiété.",
            "EFFACE<br />TOUT",
            "NOUS VIVONS DANS UNE SIMULATION DE L’EGO.",
            "PUBLIE<br />TON ÂME",
            "SI TU NE LE PARTAGES PAS, TU N’EXISTES PAS.",
        ],
        [
            "EFFONDREMENT INÉVITABLE",
            "DÉNI",
            "Planète",
            "ÉCO-LOGIQUE",
            "La panique paralyse et le déni condamne. Il nous faut une innovation technologique vigoureuse et une décroissance sélective, pas retourner dans les cavernes ni prétendre que rien ne se passe.",
            "EXTRAIRE,<br />C’EST TUER",
            "L’ÊTRE HUMAIN EST LE FLÉAU.",
            "LE CLIMAT<br />A TOUJOURS CHANGÉ",
            "ON NE TOUCHE PAS À L’ÉCONOMIE.",
        ],
        [
            "MÉDIOCRITÉ",
            "BOURREAU DE TRAVAIL",
            "Vie",
            "RÉUSSITE",
            "La réussite ne se résume ni à l’argent ni à la célébrité : c’est vivre avec un but. Mais ignorer le besoin de ressources matérielles dans une société capitaliste relève de la naïveté, pas de la vertu.",
            "CONTENTE-TOI",
            "L’AMBITION, C’EST POUR LES PSYCHOPATHES.",
            "NE DORS<br />JAMAIS",
            "LE REPOS, C’EST POUR LES FAIBLES.",
        ],
        [
            "VÉGANISME MILITANT",
            "CARNIVORISME PUR",
            "Nutrition",
            "NUTRITION CULTURELLE",
            "Manger est un acte éthique et biologique. Nous pouvons réduire la souffrance animale sans nier notre histoire évolutive omnivore. Aucun régime n’est sacré.",
            "TU MANGES DES<br />CADAVRES",
            "TU ES UN ASSASSIN SPÉCISTE.",
            "SOYBOY<br />FAIBLE",
            "SEUL LE SANG DONNE DE LA FORCE.",
        ],
        [
            "ATHÉISME RADICAL",
            "FANATISME",
            "Spiritualité",
            "FOI ET RAISON",
            "La science explique le comment, la spiritualité cherche le pourquoi. Nous pouvons embrasser la méthode scientifique sans perdre notre émerveillement devant le mystère de l’existence.",
            "DIEU EST<br />MORT",
            "NOUS SOMMES DES SACS DE VIANDE ALÉATOIRES.",
            "PAIE LA DÎME<br />OU BRÛLE",
            "LE DOUTE EST UN PÉCHÉ MORTEL.",
        ],
        [
            "PONZI TOTAL",
            "NOUVEL ORDRE",
            "Argent",
            "VALEUR NUMÉRIQUE",
            "La blockchain est une technologie révolutionnaire envahie d’escrocs. Les banques centrales nous volent par l’inflation, mais la décentralisation totale est une jungle.",
            "SYSTÈME<br />PYRAMIDAL",
            "TOUT N’EST QUE FUMÉE ET BLANCHIMENT.",
            "HODL<br />JUSQU’À LA MORT",
            "LA MONNAIE FIAT VAUT ZÉRO DEMAIN.",
        ],
        [
            "XÉNOPHOBIE",
            "APATRIDE",
            "Appartenance",
            "IDENTITÉ NATIONALE",
            "Aimer sa culture n’implique pas de haïr celle du voisin. Être citoyen du monde est un privilège vide de sens si l’on ne prend pas d’abord soin de sa communauté locale.",
            "FERMEZ LES<br />FRONTIÈRES",
            "LES NÔTRES D’ABORD.",
            "LES NATIONS<br />SONT DES PRISONS",
            "AUCUN ÊTRE HUMAIN N’EST ILLÉGAL.",
        ],
        [
            "POLYAMOUR CHAOTIQUE",
            "POSSESSION",
            "Relations",
            "LIEN",
            "La liberté individuelle ne devrait pas empêcher l’engagement profond. Aimer, c’est renoncer à la possibilité d’autres mondes pour en construire un, commun et solide.",
            "RIEN N’EST<br />À PERSONNE",
            "L’ENGAGEMENT EST UNE PRISON.",
            "TU ES<br />MA PROPRIÉTÉ",
            "LA JALOUSIE, C’EST L’AMOUR.",
        ],
        [
            "SQUAT",
            "SPÉCULATION",
            "Foyer",
            "TOIT DIGNE",
            "Le logement est un droit, pas seulement un actif financier. Mais la sécurité juridique et l’investissement privé sont nécessaires pour bâtir ce droit.",
            "EXPROPRIEZ<br />TOUT",
            "LES PROPRIÉTAIRES SONT DES PARASITES.",
            "LE MARCHÉ<br />S’AUTORÉGULE",
            "SI TU ES PAUVRE, C’EST TA FAUTE.",
        ],
        [
            "SNOBISME",
            "AUTOMATISATION",
            "Créativité",
            "ÂME SYNTHÉTIQUE",
            "L’art n’est pas seulement le résultat : c’est le processus humain qui consiste à donner du sens. L’IA démocratise la technique, mais elle ne pourra jamais démocratiser la douleur ni l’expérience.",
            "CE N’EST PAS<br />DE L’ART",
            "SEULE LA PEINTURE À L’HUILE A UNE ÂME.",
            "ADAPTE-TOI<br />OU MEURS",
            "L’ARTISTE EST SUPERFLU.",
        ],
        [
            "ENDOCTRINEMENT",
            "SAUVAGERIE",
            "Éducation",
            "APPRENTISSAGE",
            "L’école doit apprendre à penser, non dicter quoi penser. Mais le savoir structuré et partagé est le fondement de la civilisation, pas une oppression.",
            "USINE À<br />BRIQUES",
            "ILS TUENT TA CRÉATIVITÉ.",
            "IGNORANCE<br />LIBRE",
            "MON ENFANT APPREND EN REGARDANT TIKTOK.",
        ],
        [
            "ÉTAT POLICIER",
            "ANARCHIE",
            "Sécurité",
            "VIVRE-ENSEMBLE",
            "Nous voulons marcher tranquillement dans la rue, mais pas au prix d’une surveillance permanente. La véritable sécurité naît de la cohésion sociale, pas des caméras.",
            "DES CAMÉRAS<br />AUX TOILETTES",
            "QUI N’A RIEN À SE REPROCHER N’A RIEN À CRAINDRE.",
            "LOI DU<br />PLUS FORT",
            "ACHÈTE UNE ARME OU MEURS.",
        ],
        [
            "PROHIBITION",
            "NARCO-ÉTAT",
            "Santé publique",
            "ALTER EGO",
            "La guerre contre la drogue a échoué, mais la consommation sans contrôle détruit des vies. Il nous faut éducation, régulation et responsabilité, pas moralisme ni chaos.",
            "TON CORPS<br />APPARTIENT À L’ÉTAT",
            "DIS NON À LA VIE.",
            "DES ZOMBIES<br />DANS LA RUE",
            "TOUT EST PERMIS SI ÇA DÉFONCE.",
        ],
        [
            "ANTINATALISME",
            "INCUBATEUR",
            "Famille",
            "HÉRITAGE",
            "Mettre des enfants au monde est un acte d’espoir radical, ni un devoir patriotique ni un crime écologique. Une parentalité consciente est notre plus grande contribution à l’avenir.",
            "LA VIE EST<br />SOUFFRANCE",
            "EXTINCTION VOLONTAIRE MAINTENANT.",
            "ENFANTE OU<br />MEURS",
            "LES FEMMES SONT DES USINES.",
        ],
        [
            "TRANSPARENCE",
            "FANTÔME",
            "Données",
            "INTIMITÉ",
            "La vie privée est nécessaire à la liberté. Mais l’anonymat total protège aussi des crimes atroces. Où se situe la limite entre sécurité et droit au secret ?",
            "LE SECRET,<br />C’EST LA CULPABILITÉ",
            "PUBLIE TOUTE TA CONVERSATION.",
            "DARK<br />WEB",
            "IMPUNITÉ CRYPTOGRAPHIQUE.",
        ],
        [
            "BIG PHARMA",
            "PSEUDOSCIENCE",
            "Santé",
            "GUÉRISON",
            "La médecine moderne sauve des vies, mais ne guérit pas toujours l’âme et ne prévient pas toujours la maladie. Écouter son corps ne signifie pas rejeter les antibiotiques.",
            "UNE PILULE<br />POUR TOUT",
            "TA DOULEUR EST UN MARCHÉ.",
            "LE CANCER<br />EST MENTAL",
            "BONNES VIBRATIONS ET EAU SUCRÉE.",
        ],
        [
            "GÉRONTOCRATIE",
            "ÂGISME",
            "Temps",
            "MATURITÉ",
            "Vieillir est un privilège, pas une maladie. Nous devons prendre soin de ceux qui ont pris soin de nous sans hypothéquer l’avenir des jeunes.",
            "L’IMMORTALITÉ<br />À TOUT PRIX",
            "LES JEUNES NE SAVENT RIEN.",
            "TU ES DE TROP,<br />PAPY",
            "L’ÂGE DE CRISTAL ÉTAIT UN DOCUMENTAIRE.",
        ],
        [
            "REVENU DE BASE",
            "LUDDISME",
            "Avenir",
            "RAISON D’ÊTRE",
            "Si les machines travaillent, que faisons-nous ? Le travail donne de la dignité, pas l’exploitation. Nous devons redéfinir la valeur humaine au-delà de la productivité.",
            "ARGENT<br />GRATUIT",
            "PERSONNE NE DEVRAIT JAMAIS TRAVAILLER.",
            "BRÛLEZ LES<br />MACHINES",
            "LA TECHNOLOGIE EST LE DÉMON.",
        ],
        [
            "BISTOURI",
            "ABANDON",
            "Esthétique",
            "ESTIME DE SOI",
            "Vouloir être beau est humain ; se détester est rentable. La santé doit être la référence, mais la diversité de la beauté est la réalité.",
            "FILTRE<br />PERMANENT",
            "TON VRAI VISAGE EST UN DÉFAUT.",
            "L’OBÉSITÉ,<br />C’EST LA SANTÉ",
            "NIER LA BIOLOGIE EST ÉMANCIPATEUR.",
        ],
        [
            "DICTATURE",
            "RÈGNE DE LA FOULE",
            "Pouvoir",
            "GOUVERNEMENT",
            "Le chef fort promet l’ordre mais apporte la tyrannie. La foule promet une voix mais apporte le chaos. Les institutions ennuyeuses sont notre seule protection contre nous-mêmes.",
            "POIGNE DE FER",
            "LA LIBERTÉ EST SURESTIMÉE.",
            "BRÛLEZ LE<br />PARLEMENT",
            "LE PEUPLE A TOUJOURS RAISON.",
        ],
        [
            "PEINE DE MORT",
            "IMPUNITÉ",
            "Justice",
            "RÉPARATION",
            "Œil pour œil nous rend aveugles, mais ignorer les victimes crée des monstres. La réinsertion est l’idéal ; protéger la société est le devoir.",
            "TUEZ-LES<br />TOUS",
            "LA VENGEANCE EST DOUCE.",
            "ABOLISSEZ<br />LES PRISONS",
            "AUCUN CRIME NE MÉRITE DE CHÂTIMENT.",
        ],
        [
            "LÉGENDE NOIRE",
            "LÉGENDE ROSE",
            "Mémoire",
            "PASSÉ",
            "Nous ne pouvons juger le XVe siècle avec la morale du XXIe, ni blanchir les génocides. L’histoire n’est pas un conte de héros et de méchants, mais une leçon de complexité.",
            "TOUT ÉTAIT<br />GÉNOCIDE",
            "TA CULTURE EST COUPABLE.",
            "GLORIEUX<br />EMPIRE",
            "NOUS N’AVONS JAMAIS RIEN FAIT DE MAL.",
        ],
        [
            "RELIGION SCIENTIFIQUE",
            "COMPLOT",
            "Vérité",
            "PREUVE",
            "La science est une méthode pour réduire l’erreur, pas un dogme immuable. Questionner est sain ; nier la réalité observable, c’est sombrer dans le délire.",
            "L’EXPERT<br />EST DIEU",
            "NE PENSE PAS, FAIS CONFIANCE.",
            "LA TERRE<br />EST PLATE",
            "TOUT EST MANIPULÉ.",
        ],
        [
            "ANIMAUX-ENFANTS",
            "RÉIFICATION",
            "Nature",
            "ESPÈCES",
            "Les animaux ressentent et méritent le respect, mais les humaniser est une autre forme de maltraitance. Les aimer, c’est comprendre leur nature, pas les déguiser en bébés.",
            "PLUS QUE<br />DES HUMAINS",
            "SAUVE LE CHIEN, TUE L’ENFANT.",
            "CE NE SONT QUE<br />DES OBJETS",
            "UTILISE-LES ET JETTE-LES.",
        ],
        [
            "UNIFORME",
            "FAST FASHION",
            "Image",
            "EXPRESSION",
            "Le vêtement est un langage, mais la consommation compulsive est une destruction. Nous pouvons avoir du style sans exploiter la planète ni devenir des panneaux publicitaires.",
            "HABILLE-TOI<br />EN GRIS",
            "SE DISTINGUER EST VANITEUX.",
            "ACHÈTE<br />ET JETTE",
            "PORTER DU NEUF, C’EST LE BONHEUR.",
        ],
        [
            "INTERDICTION",
            "ADDICTION AU JEU",
            "Vice",
            "HASARD",
            "Le jeu est un divertissement pour adultes, mais une industrie prédatrice détruit des familles. Encadrer la publicité agressive, c’est protéger la liberté de choisir sans pièges.",
            "PLAISIR<br />ILLÉGAL",
            "LE PLAISIR EST UN PÉCHÉ.",
            "PARIE<br />LA MAISON",
            "LE PROCHAIN TOUR TE SAUVERA.",
        ],
        [
            "TOURIST GO HOME",
            "PARC D’ATTRACTIONS",
            "Voyages",
            "EXPLORATION",
            "Voyager ouvre l’esprit, mais le tourisme de masse ferme les quartiers. Nous voulons découvrir le monde sans le transformer en décor de carton-pâte.",
            "HORS<br />D’ICI",
            "LES ÉTRANGERS DÉRANGENT.",
            "VENDS TON<br />QUARTIER",
            "TOUT DEVIENT UN AIRBNB.",
        ],
        [
            "LANGAGE INCLUSIF",
            "PURISME LINGUISTIQUE",
            "Communication",
            "MOTS",
            "La langue évolue avec la société, mais imposer des changements artificiels suscite le rejet. Parlons pour nous comprendre, pas pour afficher une vertu politique.",
            "PARLE CORRECTEMENT,<br />BORDEL",
            "LE « E » DÉTRUIT LA FAMILLE.",
            "L’ACADÉMIE EST<br />SEXISTE",
            "CHANGE OU TU ES L’ENNEMI.",
        ],
        [
            "GAGNER À TOUT PRIX",
            "PARTICIPATION",
            "Compétition",
            "EFFORT",
            "L’excellence exige des sacrifices, et il y a des gagnants et des perdants. Mais le sport amateur doit transmettre des valeurs, pas des frustrations précoces.",
            "LE DEUXIÈME<br />EST LE PREMIER PERDANT",
            "HUMILIE TON ADVERSAIRE.",
            "TOUS SONT<br />CHAMPIONS",
            "PERDRE TRAUMATISE À VIE.",
        ],
        [
            "HIKIKOMORI",
            "SOCIALISATION FORCÉE",
            "Communauté",
            "CONNEXION",
            "Savoir être seul est vital, mais s’isoler est pathologique. Nous sommes des animaux sociaux qui ont besoin de la tribu, même si elle devient parfois étouffante.",
            "JE DÉTESTE<br />LES GENS",
            "MA CHAMBRE EST MON MONDE.",
            "SOURIS ET<br />PARTICIPE",
            "L’INTROVERSION SE SOIGNE.",
        ],
    ]
);
