import { createNuanceTexts } from "./create";

export const NUANCE_ID_TEXTS = createNuanceTexts(
    {
        hud: {
            defaultLeft: "Kiri",
            defaultRight: "Kanan",
            hint: "Geser untuk menemukan",
            sliderLabel: "Keseimbangan di antara kutub",
        },
        intro: {
            labelLeft: "KEHAMPAAN",
            labelRight: "KEGELAPAN",
            title: "NUANSA",
            descriptionFirst: "Dunia nyata penuh warna.",
            descriptionSecond: "Kutub-kutub ekstrem adalah ketiadaannya.",
            leftTitle: "PUTIH",
            leftDescription: "Tanpa bayangan. Tanpa keraguan.",
            rightTitle: "HITAM",
            rightDescription: "Tanpa cahaya. Tanpa harapan.",
        },
        outro: {
            firstLine: "Dunia ingin kamu memilih kubu.",
            secondLine: "Revolusi sejati adalah menolak memilih.",
            exit: "Keluar dari putaran",
            left: "KEHAMPAAN",
            right: "KEGELAPAN",
        },
    },
    [
        [
            "KEBENCIAN TERHADAP PRIA",
            "MACHISMO",
            "Kesetaraan",
            "GENDER",
            "Mengakui perbedaan biologis tidak membenarkan ketimpangan hak. Menyangkalnya sepenuhnya berarti mengabaikan kenyataan material. Kesetaraan bersifat hukum dan moral, bukan biologis.",
            "MEREKA SEMUA<br />BERSALAH",
            "MASKULINITAS ADALAH KANKER.",
            "KEMBALI KE<br />DAPUR",
            "TATANAN ALAM ITU SUCI.",
        ],
        [
            "TOKSIK",
            "KONEKSI MURNI",
            "Sosial",
            "ALGORITMA",
            "Media sosial dapat menguatkan suara kelompok terpinggirkan dan mendemokratisasi pengetahuan, tetapi model bisnisnya saat ini mengubah polarisasi dan kecemasan menjadi uang.",
            "HAPUS<br />SEMUANYA",
            "KITA HIDUP DALAM SIMULASI EGO.",
            "UNGGAH<br />JIWAMU",
            "KALAU TIDAK DIBAGIKAN, KAMU TIDAK ADA.",
        ],
        [
            "KERUNTUHAN TAK TERELAKKAN",
            "PENYANGKALAN",
            "Planet",
            "EKO-LOGIKA",
            "Kepanikan melumpuhkan dan penyangkalan membawa petaka. Kita memerlukan inovasi teknologi yang agresif dan pengurangan pertumbuhan secara selektif, bukan kembali ke gua atau berpura-pura tidak terjadi apa-apa.",
            "EKSTRAKSI<br />ADALAH PEMBUNUHAN",
            "MANUSIA ADALAH WABAH.",
            "IKLIM<br />SELALU BERUBAH",
            "EKONOMI TIDAK BOLEH DISENTUH.",
        ],
        [
            "MEDIOKRITAS",
            "GILA KERJA",
            "Hidup",
            "SUKSES",
            "Sukses bukan sekadar uang atau ketenaran, melainkan hidup dengan tujuan. Namun mengabaikan kebutuhan akan sumber daya material dalam masyarakat kapitalis adalah kenaifan, bukan kebajikan.",
            "TERIMA SAJA",
            "AMBISI HANYA UNTUK PSIKOPAT.",
            "JANGAN PERNAH<br />TIDUR",
            "ISTIRAHAT HANYA UNTUK YANG LEMAH.",
        ],
        [
            "VEGANISME MILITAN",
            "KARNIVORISME MURNI",
            "Nutrisi",
            "NUTRISI BUDAYA",
            "Makan adalah tindakan etis sekaligus biologis. Kita dapat mengurangi penderitaan hewan tanpa menyangkal sejarah evolusi kita sebagai omnivor. Tidak ada pola makan yang suci.",
            "KAMU MAKAN<br />BANGKAI",
            "KAMU PEMBUNUH SPESIESIS.",
            "SOYBOY<br />LEMAH",
            "HANYA DARAH YANG MEMBERI KEKUATAN.",
        ],
        [
            "ATEISME RADIKAL",
            "FANATISME",
            "Spiritualitas",
            "IMAN DAN NALAR",
            "Sains menjelaskan bagaimana, spiritualitas mencari mengapa. Kita dapat merangkul metode ilmiah tanpa kehilangan rasa takjub terhadap misteri keberadaan.",
            "TUHAN TELAH<br />MATI",
            "KITA HANYALAH KANTONG DAGING ACAK.",
            "BAYAR PERSEPULUHAN<br />ATAU TERBAKAR",
            "KERAGUAN ADALAH DOSA BESAR.",
        ],
        [
            "PONZI TOTAL",
            "TATANAN BARU",
            "Uang",
            "NILAI DIGITAL",
            "Blockchain adalah teknologi revolusioner yang dipenuhi penipu. Bank sentral merampok kita melalui inflasi, tetapi desentralisasi total adalah rimba belantara.",
            "SKEMA<br />PIRAMIDA",
            "SEMUANYA ASAP DAN PENCUCIAN UANG.",
            "HODL<br />SAMPAI MATI",
            "UANG FIAT JADI NOL BESOK.",
        ],
        [
            "XENOFOBIA",
            "TANPA NEGARA",
            "Rasa memiliki",
            "IDENTITAS NASIONAL",
            "Mencintai budayamu tidak berarti membenci budaya tetangga. Menjadi warga dunia adalah privilese kosong jika kamu tidak lebih dahulu merawat komunitas setempatmu.",
            "TUTUP<br />PERBATASAN",
            "DAHULUKAN ORANG KITA.",
            "NEGARA<br />ADALAH PENJARA",
            "TIDAK ADA MANUSIA YANG ILEGAL.",
        ],
        [
            "POLIAMORI KACAU",
            "KEPEMILIKAN",
            "Relasi",
            "IKATAN",
            "Kebebasan individu seharusnya tidak menghalangi komitmen yang mendalam. Mencintai berarti melepaskan kemungkinan dunia-dunia lain demi membangun satu dunia yang kokoh dan dimiliki bersama.",
            "TIDAK ADA YANG<br />MEMILIKI APA PUN",
            "KOMITMEN ADALAH PENJARA.",
            "KAMU ADALAH<br />MILIKKU",
            "CEMBURU ADALAH CINTA.",
        ],
        [
            "PENDUDUKAN LIAR",
            "SPEKULASI",
            "Rumah",
            "ATAP YANG LAYAK",
            "Hunian adalah hak, bukan sekadar aset keuangan. Namun kepastian hukum dan investasi swasta diperlukan untuk mewujudkan hak itu.",
            "AMBIL ALIH<br />SEMUANYA",
            "PEMILIK SEWA ADALAH PARASIT.",
            "PASAR<br />MENGATUR DIRINYA",
            "KALAU KAMU MISKIN, ITU SALAHMU.",
        ],
        [
            "SNOBISME",
            "OTOMATISASI",
            "Kreativitas",
            "JIWA SINTETIS",
            "Seni bukan hanya hasil, melainkan proses manusia dalam memberi makna. AI mendemokratisasi teknik, tetapi tidak akan pernah mendemokratisasi rasa sakit maupun pengalaman.",
            "ITU BUKAN<br />SENI",
            "HANYA CAT MINYAK YANG PUNYA JIWA.",
            "BERADAPTASI<br />ATAU MATI",
            "SENIMAN DAPAT DISINGKIRKAN.",
        ],
        [
            "INDOKTRINASI",
            "KEBIADABAN",
            "Pendidikan",
            "PEMBELAJARAN",
            "Sekolah harus mengajarkan cara berpikir, bukan apa yang harus dipikirkan. Namun pengetahuan yang terstruktur dan dibagikan adalah fondasi peradaban, bukan penindasan.",
            "PABRIK<br />BATA",
            "MEREKA MEMBUNUH KREATIVITASMU.",
            "KEBODOHAN<br />BEBAS",
            "ANAKKU BELAJAR DARI TIKTOK.",
        ],
        [
            "NEGARA POLISI",
            "ANARKI",
            "Keamanan",
            "HIDUP BERSAMA",
            "Kita ingin berjalan tenang di jalan, tetapi bukan dengan harga pengawasan dua puluh empat jam. Keamanan sejati lahir dari kohesi sosial, bukan kamera.",
            "KAMERA DI<br />KAMAR MANDI",
            "YANG TIDAK PUNYA RAHASIA TAK PERLU TAKUT.",
            "HUKUM<br />YANG TERKUAT",
            "BELI SENJATA ATAU MATI.",
        ],
        [
            "PELARANGAN",
            "NEGARA NARKO",
            "Kesehatan publik",
            "ALTER EGO",
            "Perang melawan narkoba telah gagal, tetapi konsumsi tanpa kendali menghancurkan hidup. Kita membutuhkan pendidikan, regulasi, dan tanggung jawab, bukan moralisme atau kekacauan.",
            "TUBUHMU<br />MILIK NEGARA",
            "KATAKAN TIDAK PADA HIDUP.",
            "ZOMBI DI<br />JALANAN",
            "APA SAJA BOLEH ASAL BIKIN TINGGI.",
        ],
        [
            "ANTINATALISME",
            "INKUBATOR",
            "Keluarga",
            "WARISAN",
            "Menghadirkan anak ke dunia adalah tindakan harapan yang radikal, bukan kewajiban patriotik atau kejahatan ekologis. Pengasuhan sadar adalah sumbangan terbesar kita bagi masa depan.",
            "HIDUP ADALAH<br />PENDERITAAN",
            "KEPUNAHAN SUKARELA SEKARANG.",
            "BERANAK ATAU<br />MATI",
            "PEREMPUAN ADALAH PABRIK.",
        ],
        [
            "TRANSPARANSI",
            "HANTU",
            "Data",
            "PRIVASI",
            "Privasi diperlukan untuk kebebasan. Namun anonimitas total juga melindungi kejahatan keji. Di mana batas antara keamanan dan hak untuk menyimpan rahasia?",
            "RAHASIA<br />BERARTI BERSALAH",
            "PUBLIKASIKAN SELURUH OBROLANMU.",
            "DARK<br />WEB",
            "KEKEBALAN KRIPTOGRAFIS.",
        ],
        [
            "BIG PHARMA",
            "PSEUDOSAINS",
            "Kesehatan",
            "PENYEMBUHAN",
            "Kedokteran modern menyelamatkan nyawa, tetapi tidak selalu menyembuhkan jiwa atau mencegah penyakit. Mendengarkan tubuh bukan berarti menolak antibiotik.",
            "PIL<br />UNTUK SEGALANYA",
            "RASA SAKITMU ADALAH PASAR.",
            "KANKER<br />HANYA DI PIKIRAN",
            "GETARAN TINGGI DAN AIR GULA.",
        ],
        [
            "GERONTOKRASI",
            "DISKRIMINASI USIA",
            "Waktu",
            "KEDEWASAAN",
            "Menjadi tua adalah privilese, bukan penyakit. Kita harus merawat mereka yang dahulu merawat kita tanpa menggadaikan masa depan kaum muda.",
            "KEABADIAN<br />BERAPA PUN HARGANYA",
            "ANAK MUDA TIDAK TAHU APA-APA.",
            "KAU TAK BERGUNA,<br />KAKEK",
            "LOGAN’S RUN ADALAH FILM DOKUMENTER.",
        ],
        [
            "PENGHASILAN DASAR",
            "LUDDISME",
            "Masa depan",
            "TUJUAN",
            "Jika mesin yang bekerja, lalu apa yang kita lakukan? Kerja memberi martabat, eksploitasi tidak. Kita perlu mendefinisikan ulang nilai manusia melampaui produktivitas.",
            "UANG<br />GRATIS",
            "TAK SEORANG PUN SEHARUSNYA BEKERJA.",
            "BAKAR<br />MESIN-MESIN",
            "TEKNOLOGI ADALAH SETAN.",
        ],
        [
            "PISAU BEDAH",
            "PENELANTARAN",
            "Estetika",
            "HARGA DIRI",
            "Ingin terlihat baik itu manusiawi; membenci diri sendiri itu menguntungkan. Kesehatan harus menjadi standar, tetapi keragaman keindahan adalah kenyataan.",
            "FILTER<br />PERMANEN",
            "WAJAH ASLIMU ADALAH CACAT.",
            "OBESITAS<br />ADALAH SEHAT",
            "MENYANGKAL BIOLOGI ITU MEMBERDAYAKAN.",
        ],
        [
            "KEDIKTATORAN",
            "KEKUASAAN MASSA",
            "Kekuasaan",
            "PEMERINTAHAN",
            "Pemimpin kuat menjanjikan ketertiban tetapi membawa tirani. Massa menjanjikan suara tetapi membawa kekacauan. Lembaga-lembaga yang membosankan adalah satu-satunya pelindung kita dari diri sendiri.",
            "TANGAN BESI",
            "KEBEBASAN TERLALU DIAGUNGKAN.",
            "BAKAR<br />PARLEMEN",
            "RAKYAT SELALU BENAR.",
        ],
        [
            "HUKUMAN MATI",
            "KEKEBALAN HUKUM",
            "Keadilan",
            "PEMULIHAN",
            "Mata dibalas mata membuat kita buta, tetapi mengabaikan korban menciptakan monster. Reintegrasi adalah cita-cita; melindungi masyarakat adalah kewajiban.",
            "BUNUH MEREKA<br />SEMUA",
            "BALAS DENDAM ITU MANIS.",
            "HAPUSKAN<br />PENJARA",
            "TAK ADA KEJAHATAN YANG PANTAS DIHUKUM.",
        ],
        [
            "LEGENDA HITAM",
            "LEGENDA MERAH MUDA",
            "Ingatan",
            "MASA LALU",
            "Kita tidak bisa menghakimi abad ke-15 dengan moral abad ke-21, maupun memutihkan genosida. Sejarah bukan dongeng tentang pahlawan dan penjahat, melainkan pelajaran tentang kompleksitas.",
            "SEMUANYA<br />GENOSIDA",
            "BUDAYAMU BERSALAH.",
            "KEKAISARAN<br />GEMILANG",
            "KAMI TIDAK PERNAH BERBUAT SALAH.",
        ],
        [
            "AGAMA SAINS",
            "KONSPIRASI",
            "Kebenaran",
            "BUKTI",
            "Sains adalah metode untuk mengurangi kesalahan, bukan dogma yang tak berubah. Bertanya itu sehat, tetapi menyangkal kenyataan yang dapat diamati berarti jatuh ke jurang delusi.",
            "PAKAR<br />ADALAH TUHAN",
            "JANGAN BERPIKIR, PERCAYA SAJA.",
            "BUMI<br />DATAR",
            "SEMUANYA DIMANIPULASI.",
        ],
        [
            "ANAK BULU",
            "OBJEKTIFIKASI",
            "Alam",
            "SPESIES",
            "Hewan dapat merasakan dan layak dihormati, tetapi memanusiakan mereka adalah bentuk lain penganiayaan. Mencintai mereka berarti memahami sifatnya, bukan mendandani mereka seperti bayi.",
            "LEBIH DARI<br />MANUSIA",
            "SELAMATKAN ANJING, BUNUH ANAK.",
            "MEREKA HANYA<br />BENDA",
            "PAKAI LALU BUANG.",
        ],
        [
            "SERAGAM",
            "FAST FASHION",
            "Citra",
            "EKSPRESI",
            "Pakaian adalah bahasa, tetapi konsumsi kompulsif adalah kehancuran. Kita dapat bergaya tanpa mengeksploitasi planet atau mengubah diri menjadi papan iklan.",
            "KENAKAN<br />ABU-ABU",
            "MENONJOL ITU KESOMBONGAN.",
            "BELI<br />LALU BUANG",
            "PAKAIAN BARU ADALAH KEBAHAGIAAN.",
        ],
        [
            "PELARANGAN",
            "KECANDUAN JUDI",
            "Candu",
            "KEBETULAN",
            "Judi adalah hiburan orang dewasa, tetapi industri predator menghancurkan keluarga. Mengatur iklan agresif berarti melindungi kebebasan memilih tanpa jebakan.",
            "HIBURAN<br />ILEGAL",
            "KENIKMATAN ADALAH DOSA.",
            "PERTARUHKAN<br />RUMAH",
            "PUTARAN BERIKUTNYA AKAN MENYELAMATKANMU.",
        ],
        [
            "TOURIST GO HOME",
            "TAMAN HIBURAN",
            "Perjalanan",
            "PENJELAJAHAN",
            "Bepergian membuka pikiran, tetapi pariwisata massal menutup lingkungan warga. Kita ingin mengenal dunia tanpa mengubahnya menjadi panggung kardus.",
            "PERGI<br />DARI SINI",
            "ORANG ASING MENGGANGGU.",
            "JUAL<br />LINGKUNGANMU",
            "SEMUANYA JADI AIRBNB.",
        ],
        [
            "BAHASA INKLUSIF",
            "PURISME BAHASA",
            "Komunikasi",
            "KATA-KATA",
            "Bahasa berkembang bersama masyarakat, tetapi memaksakan perubahan buatan menimbulkan penolakan. Mari berbicara untuk saling memahami, bukan untuk memamerkan kebajikan politik.",
            "BICARA YANG BENAR,<br />SIALAN",
            "BAHASA NETRAL MERUSAK KELUARGA.",
            "LEMBAGA BAHASA<br />SEKSIS",
            "BERUBAH ATAU KAMU MUSUH.",
        ],
        [
            "MENANG ADALAH SEGALANYA",
            "PARTISIPASI",
            "Kompetisi",
            "USAHA",
            "Keunggulan menuntut pengorbanan, dan ada pemenang serta pecundang. Namun olahraga akar rumput harus menanamkan nilai, bukan frustrasi sejak dini.",
            "JUARA DUA<br />ADALAH PECUNDANG PERTAMA",
            "PERMALUKAN LAWANMU.",
            "SEMUA ORANG<br />JUARA",
            "KALAH MENIMBULKAN TRAUMA SEUMUR HIDUP.",
        ],
        [
            "HIKIKOMORI",
            "SOSIALISASI PAKSA",
            "Komunitas",
            "KONEKSI",
            "Mampu menyendiri itu penting, tetapi mengisolasi diri bersifat patologis. Kita adalah makhluk sosial yang membutuhkan kelompok, meski kelompok terkadang menyesakkan.",
            "AKU BENCI<br />ORANG",
            "KAMARKU ADALAH DUNIAKU.",
            "TERSENYUM DAN<br />IKUTLAH",
            "INTROVERSI BISA DISEMBUHKAN.",
        ],
    ]
);
