import { createNuanceTexts } from "./create";

export const NUANCE_IT_TEXTS = createNuanceTexts(
    {
        hud: {
            defaultLeft: "Sinistra",
            defaultRight: "Destra",
            hint: "Scorri per scoprire",
            sliderLabel: "Equilibrio tra gli estremi",
        },
        intro: {
            labelLeft: "VUOTO",
            labelRight: "OSCURITÀ",
            title: "SFUMATURA",
            descriptionFirst: "Il mondo reale è pieno di colori.",
            descriptionSecond: "Gli estremi sono la loro assenza.",
            leftTitle: "BIANCO",
            leftDescription: "Senza ombre. Senza dubbi.",
            rightTitle: "NERO",
            rightDescription: "Senza luce. Senza speranza.",
        },
        outro: {
            firstLine: "Il mondo vuole che tu scelga da che parte stare.",
            secondLine: "La vera rivoluzione è rifiutarsi.",
            exit: "Esci dal ciclo",
            left: "VUOTO",
            right: "OSCURITÀ",
        },
    },
    [
        [
            "MISANDRIA",
            "MASCHILISMO",
            "Uguaglianza",
            "GENERE",
            "Riconoscere le differenze biologiche non giustifica la disuguaglianza dei diritti. Negarle del tutto significa ignorare la realtà materiale. L’uguaglianza è giuridica e morale, non biologica.",
            "SONO TUTTI<br />COLPEVOLI",
            "LA MASCOLINITÀ È UN CANCRO.",
            "TORNA IN<br />CUCINA",
            "L’ORDINE NATURALE È SACRO.",
        ],
        [
            "TOSSICO",
            "CONNESSIONE PURA",
            "Società",
            "ALGORITMO",
            "I social network possono amplificare le voci emarginate e democratizzare la conoscenza, ma il loro attuale modello di business monetizza la polarizzazione e l’ansia.",
            "CANCELLA<br />TUTTO",
            "VIVIAMO IN UNA SIMULAZIONE DELL’EGO.",
            "POSTA<br />LA TUA ANIMA",
            "SE NON LO CONDIVIDI, NON ESISTI.",
        ],
        [
            "COLLASSO INEVITABILE",
            "NEGAZIONISMO",
            "Pianeta",
            "ECO-LOGICA",
            "Il panico paralizza e il negazionismo condanna. Servono innovazione tecnologica aggressiva e decrescita selettiva, non tornare nelle caverne né fingere che non stia accadendo nulla.",
            "ESTRARRE<br />È UCCIDERE",
            "L’ESSERE UMANO È LA PIAGA.",
            "IL CLIMA<br />CAMBIA DA SEMPRE",
            "L’ECONOMIA NON SI TOCCA.",
        ],
        [
            "MEDIOCRITÀ",
            "DIPENDENZA DAL LAVORO",
            "Vita",
            "SUCCESSO",
            "Il successo non è soltanto denaro o fama: è vivere con uno scopo. Ma ignorare la necessità di risorse materiali in una società capitalista è ingenuità, non virtù.",
            "ACCONTENTATI",
            "L’AMBIZIONE È DA PSICOPATICI.",
            "NON DORMIRE<br />MAI",
            "IL RIPOSO È PER I DEBOLI.",
        ],
        [
            "VEGANISMO MILITANTE",
            "CARNIVORISMO PURO",
            "Nutrizione",
            "NUTRIZIONE CULTURALE",
            "Mangiare è un atto etico e biologico. Possiamo ridurre la sofferenza animale senza negare la nostra storia evolutiva onnivora. Non esiste una dieta santa.",
            "MANGI<br />CADAVERI",
            "SEI UN ASSASSINO SPECISTA.",
            "SOYBOY<br />DEBOLE",
            "SOLO IL SANGUE DÀ FORZA.",
        ],
        [
            "ATEISMO RADICALE",
            "FANATISMO",
            "Spiritualità",
            "FEDE E RAGIONE",
            "La scienza spiega il come, la spiritualità cerca il perché. Possiamo abbracciare il metodo scientifico senza perdere lo stupore davanti al mistero dell’esistenza.",
            "DIO È<br />MORTO",
            "SIAMO SACCHI DI CARNE CASUALI.",
            "PAGA LA DECIMA<br />O BRUCIA",
            "IL DUBBIO È UN PECCATO MORTALE.",
        ],
        [
            "PONZI TOTALE",
            "NUOVO ORDINE",
            "Denaro",
            "VALORE DIGITALE",
            "La blockchain è una tecnologia rivoluzionaria piena di truffatori. Le banche centrali ci derubano con l’inflazione, ma la decentralizzazione totale è una giungla.",
            "SCHEMA<br />PIRAMIDALE",
            "È TUTTO FUMO E RICICLAGGIO.",
            "HODL<br />FINO ALLA MORTE",
            "DOMANI LA MONETA FIAT VA A ZERO.",
        ],
        [
            "XENOFOBIA",
            "APOLIDE",
            "Appartenenza",
            "IDENTITÀ NAZIONALE",
            "Amare la propria cultura non significa odiare quella del vicino. Essere cittadini del mondo è un privilegio vuoto se prima non ci si prende cura della comunità locale.",
            "CHIUDI LE<br />FRONTIERE",
            "PRIMA I NOSTRI.",
            "LE NAZIONI<br />SONO PRIGIONI",
            "NESSUN ESSERE UMANO È ILLEGALE.",
        ],
        [
            "POLIAMORE CAOTICO",
            "POSSESSO",
            "Relazioni",
            "LEGAME",
            "La libertà individuale non dovrebbe impedire un impegno profondo. Amare significa rinunciare alla possibilità di altri mondi per costruirne uno condiviso e solido.",
            "NIENTE È<br />DI NESSUNO",
            "L’IMPEGNO È UNA PRIGIONE.",
            "SEI DI<br />MIA PROPRIETÀ",
            "LA GELOSIA È AMORE.",
        ],
        [
            "OCCUPAZIONE",
            "SPECULAZIONE",
            "Casa",
            "UN TETTO DIGNITOSO",
            "La casa è un diritto, non soltanto un bene finanziario. Ma la certezza del diritto e l’investimento privato sono necessari per costruire quel diritto.",
            "ESPROPRIA<br />TUTTO",
            "I PROPRIETARI SONO PARASSITI.",
            "IL MERCATO<br />SI REGOLA DA SÉ",
            "SE SEI POVERO È COLPA TUA.",
        ],
        [
            "SNOBISMO",
            "AUTOMAZIONE",
            "Creatività",
            "ANIMA SINTETICA",
            "L’arte non è soltanto il risultato: è il processo umano di dare senso. L’IA democratizza la tecnica, ma non potrà mai democratizzare il dolore né l’esperienza.",
            "QUESTA NON È<br />ARTE",
            "SOLO L’OLIO HA UN’ANIMA.",
            "ADATTATI<br />O MUORI",
            "L’ARTISTA È SUPERFLUO.",
        ],
        [
            "INDOTTRINAMENTO",
            "SELVAGGISMO",
            "Istruzione",
            "APPRENDIMENTO",
            "La scuola deve insegnare a pensare, non cosa pensare. Ma la conoscenza strutturata e condivisa è la base della civiltà, non un’oppressione.",
            "FABBRICA DI<br />MATTONI",
            "UCCIDONO LA TUA CREATIVITÀ.",
            "IGNORANZA<br />LIBERA",
            "MIO FIGLIO IMPARA GUARDANDO TIKTOK.",
        ],
        [
            "STATO DI POLIZIA",
            "ANARCHIA",
            "Sicurezza",
            "CONVIVENZA",
            "Vogliamo camminare tranquilli per strada, ma non al prezzo di essere sorvegliati ventiquattr’ore su ventiquattro. La vera sicurezza nasce dalla coesione sociale, non dalle telecamere.",
            "TELECAMERE<br />IN BAGNO",
            "CHI NON HA NULLA DA NASCONDERE NON HA NULLA DA TEMERE.",
            "LEGGE DEL<br />PIÙ FORTE",
            "COMPRATI UN’ARMA O MUORI.",
        ],
        [
            "PROIBIZIONISMO",
            "NARCO-STATO",
            "Salute pubblica",
            "ALTER EGO",
            "La guerra alla droga ha fallito, ma il consumo senza controllo distrugge vite. Servono educazione, regolamentazione e responsabilità, non moralismo né caos.",
            "IL TUO CORPO<br />È DELLO STATO",
            "DI’ NO ALLA VITA.",
            "ZOMBI<br />PER STRADA",
            "TUTTO VALE SE SBALLA.",
        ],
        [
            "ANTINATALISMO",
            "INCUBATRICE",
            "Famiglia",
            "EREDITÀ",
            "Mettere al mondo dei figli è un atto di speranza radicale, non un dovere patriottico né un crimine ecologico. Una genitorialità consapevole è il contributo più grande al futuro.",
            "LA VITA È<br />SOFFERENZA",
            "ESTINZIONE VOLONTARIA SUBITO.",
            "PARTORISCI O<br />MUORI",
            "LE DONNE SONO FABBRICHE.",
        ],
        [
            "TRASPARENZA",
            "FANTASMA",
            "Dati",
            "INTIMITÀ",
            "La privacy è necessaria alla libertà. Ma l’anonimato totale protegge anche crimini atroci. Dov’è il confine tra sicurezza e diritto al segreto?",
            "IL SEGRETO<br />È COLPA",
            "PUBBLICA TUTTA LA TUA CHAT.",
            "DARK<br />WEB",
            "IMPUNITÀ CRITTOGRAFICA.",
        ],
        [
            "BIG PHARMA",
            "PSEUDOSCIENZA",
            "Salute",
            "GUARIGIONE",
            "La medicina moderna salva vite, ma non sempre cura l’anima né previene le malattie. Ascoltare il corpo non significa negare gli antibiotici.",
            "UNA PILLOLA<br />PER TUTTO",
            "IL TUO DOLORE È UN MERCATO.",
            "IL CANCRO<br />È MENTALE",
            "VIBRAZIONI ALTE E ACQUA ZUCCHERATA.",
        ],
        [
            "GERONTOCRAZIA",
            "DISCRIMINAZIONE PER ETÀ",
            "Tempo",
            "MATURITÀ",
            "Invecchiare è un privilegio, non una malattia. Dobbiamo prenderci cura di chi si è preso cura di noi senza ipotecare il futuro dei giovani.",
            "IMMORTALITÀ<br />A OGNI COSTO",
            "I GIOVANI NON SANNO NULLA.",
            "SEI DI TROPPO,<br />NONNO",
            "LA FUGA DI LOGAN ERA UN DOCUMENTARIO.",
        ],
        [
            "REDDITO DI BASE",
            "LUDDISMO",
            "Futuro",
            "SCOPO",
            "Se lavorano le macchine, noi che cosa facciamo? Il lavoro dà dignità, lo sfruttamento no. Dobbiamo ridefinire il valore umano oltre la produttività.",
            "DENARO<br />GRATIS",
            "NESSUNO DOVREBBE MAI LAVORARE.",
            "BRUCIA LE<br />MACCHINE",
            "LA TECNOLOGIA È IL DEMONIO.",
        ],
        [
            "BISTURI",
            "ABBANDONO",
            "Estetica",
            "AUTOSTIMA",
            "Voler apparire bene è umano; odiarsi è redditizio. La salute dovrebbe essere lo standard, ma la bellezza plurale è la realtà.",
            "FILTRO<br />PERMANENTE",
            "IL TUO VERO VISO È UN DIFETTO.",
            "L’OBESITÀ<br />È SALUTE",
            "NEGARE LA BIOLOGIA È EMANCIPANTE.",
        ],
        [
            "DITTATURA",
            "GOVERNO DELLA FOLLA",
            "Potere",
            "GOVERNO",
            "Il leader forte promette ordine ma porta tirannia. La massa promette voce ma porta caos. Le istituzioni noiose sono l’unica cosa che ci protegge da noi stessi.",
            "PUGNO DI FERRO",
            "LA LIBERTÀ È SOPRAVVALUTATA.",
            "BRUCIATE IL<br />PARLAMENTO",
            "IL POPOLO HA SEMPRE RAGIONE.",
        ],
        [
            "PENA DI MORTE",
            "IMPUNITÀ",
            "Giustizia",
            "RIPARAZIONE",
            "Occhio per occhio ci rende ciechi, ma ignorare le vittime crea mostri. Il reinserimento è l’ideale, proteggere la società è il dovere.",
            "UCCIDETELI<br />TUTTI",
            "LA VENDETTA È DOLCE.",
            "ABOLITE LE<br />CARCERI",
            "NESSUN CRIMINE MERITA UNA PENA.",
        ],
        [
            "LEGGENDA NERA",
            "LEGGENDA ROSA",
            "Memoria",
            "PASSATO",
            "Non possiamo giudicare il XV secolo con la morale del XXI, né imbiancare i genocidi. La storia non è una favola di eroi e cattivi, ma una lezione di complessità.",
            "FU TUTTO<br />GENOCIDIO",
            "LA TUA CULTURA È COLPEVOLE.",
            "GLORIOSO<br />IMPERO",
            "NON ABBIAMO MAI FATTO NULLA DI MALE.",
        ],
        [
            "RELIGIONE SCIENTIFICA",
            "COMPLOTTO",
            "Verità",
            "EVIDENZA",
            "La scienza è un metodo per ridurre l’errore, non un dogma immutabile. Dubitare è sano, ma negare la realtà osservabile significa cadere nell’abisso del delirio.",
            "L’ESPERTO<br />È DIO",
            "NON PENSARE, FIDATI.",
            "LA TERRA<br />È PIATTA",
            "È TUTTO MANIPOLATO.",
        ],
        [
            "FIGLI PELOSI",
            "REIFICAZIONE",
            "Natura",
            "SPECIE",
            "Gli animali provano emozioni e meritano rispetto, ma umanizzarli è un’altra forma di maltrattamento. Amarli significa capirne la natura, non travestirli da bambini.",
            "PIÙ CHE<br />UMANI",
            "SALVA IL CANE, UCCIDI IL BAMBINO.",
            "SONO SOLO<br />COSE",
            "USALI E BUTTALI.",
        ],
        [
            "UNIFORME",
            "FAST FASHION",
            "Immagine",
            "ESPRESSIONE",
            "L’abbigliamento è linguaggio, ma il consumo compulsivo è distruzione. Possiamo avere stile senza sfruttare il pianeta né trasformarci in cartelloni pubblicitari.",
            "VESTITI<br />DI GRIGIO",
            "DISTINGUERSI È VANITÀ.",
            "COMPRA<br />E BUTTA",
            "VESTIRE NUOVO È FELICITÀ.",
        ],
        [
            "DIVIETO",
            "LUDOPATIA",
            "Vizio",
            "AZZARDO",
            "Il gioco d’azzardo è intrattenimento per adulti, ma un’industria predatoria distrugge le famiglie. Regolare la pubblicità aggressiva significa proteggere la libertà di scegliere senza trappole.",
            "DIVERTIMENTO<br />ILLEGALE",
            "IL PIACERE È PECCATO.",
            "SCOMMETTI<br />LA CASA",
            "IL PROSSIMO GIRO TI SALVERÀ.",
        ],
        [
            "TOURIST GO HOME",
            "PARCO TEMATICO",
            "Viaggi",
            "ESPLORAZIONE",
            "Viaggiare apre la mente, ma il turismo di massa chiude i quartieri. Vogliamo conoscere il mondo senza trasformarlo in una scenografia di cartapesta.",
            "VATTENE<br />DA QUI",
            "GLI STRANIERI DANNO FASTIDIO.",
            "VENDI IL TUO<br />QUARTIERE",
            "TUTTO È UN AIRBNB.",
        ],
        [
            "LINGUAGGIO INCLUSIVO",
            "PURISMO LINGUISTICO",
            "Comunicazione",
            "PAROLE",
            "La lingua evolve con la società, ma imporre cambiamenti artificiali genera rifiuto. Parliamo per capirci, non per esibire virtù politica.",
            "PARLA BENE,<br />MALEDIZIONE",
            "LA SCHWA DISTRUGGE LA FAMIGLIA.",
            "L’ACCADEMIA È<br />SESSISTA",
            "CAMBIA O SEI IL NEMICO.",
        ],
        [
            "VINCERE È TUTTO",
            "PARTECIPAZIONE",
            "Competizione",
            "IMPEGNO",
            "L’eccellenza richiede sacrificio e ci sono vincitori e sconfitti. Ma lo sport di base deve promuovere valori, non frustrazioni premature.",
            "IL SECONDO<br />È IL PRIMO DEGLI SCONFITTI",
            "UMILIA IL TUO AVVERSARIO.",
            "SONO TUTTI<br />CAMPIONI",
            "PERDERE TRAUMATIZZA PER SEMPRE.",
        ],
        [
            "HIKIKOMORI",
            "SOCIALIZZAZIONE FORZATA",
            "Comunità",
            "CONNESSIONE",
            "Saper stare soli è vitale, ma isolarsi è patologico. Siamo animali sociali che hanno bisogno della tribù, anche se a volte la tribù soffoca.",
            "ODIO LA<br />GENTE",
            "LA MIA STANZA È IL MIO MONDO.",
            "SORRIDI E<br />PARTECIPA",
            "L’INTROVERSIONE SI CURA.",
        ],
    ]
);
