import { createNuanceTexts } from "./create";

export const NUANCE_NL_TEXTS = createNuanceTexts(
    {
        hud: {
            defaultLeft: "Links",
            defaultRight: "Rechts",
            hint: "Schuif om te ontdekken",
            sliderLabel: "Evenwicht tussen uitersten",
        },
        intro: {
            labelLeft: "LEEGTE",
            labelRight: "DUISTERNIS",
            title: "NUANCE",
            descriptionFirst: "De echte wereld zit vol kleur.",
            descriptionSecond: "Uitersten zijn de afwezigheid daarvan.",
            leftTitle: "WIT",
            leftDescription: "Geen schaduwen. Geen twijfel.",
            rightTitle: "ZWART",
            rightDescription: "Geen licht. Geen hoop.",
        },
        outro: {
            firstLine: "De wereld wil dat je partij kiest.",
            secondLine: "De ware revolutie is weigeren.",
            exit: "Verlaat de lus",
            left: "LEEGTE",
            right: "DUISTERNIS",
        },
    },
    [
        [
            "MANNENHAAT",
            "MACHISMO",
            "Gelijkheid",
            "GENDER",
            "Biologische verschillen erkennen rechtvaardigt geen ongelijke rechten. Ze volledig ontkennen negeert de materiële werkelijkheid. Gelijkheid is juridisch en moreel, niet biologisch.",
            "ZE ZIJN ALLEMAAL<br />SCHULDIG",
            "MANNELIJKHEID IS KANKER.",
            "TERUG NAAR DE<br />KEUKEN",
            "DE NATUURLIJKE ORDE IS HEILIG.",
        ],
        [
            "GIFTIG",
            "ZUIVERE VERBINDING",
            "Sociaal",
            "ALGORITME",
            "Sociale media kunnen gemarginaliseerde stemmen versterken en kennis democratiseren, maar hun huidige verdienmodel maakt geld van polarisatie en angst.",
            "VERWIJDER<br />ALLES",
            "WE LEVEN IN EEN SIMULATIE VAN HET EGO.",
            "POST<br />JE ZIEL",
            "ALS JE HET NIET DEELT, BESTA JE NIET.",
        ],
        [
            "ONVERMIJDELIJKE INSTORTING",
            "ONTKENNING",
            "Planeet",
            "ECO-LOGICA",
            "Paniek verlamt en ontkenning veroordeelt. We hebben krachtige technologische innovatie en selectieve krimp nodig, geen terugkeer naar grotten en geen doen alsof er niets gebeurt.",
            "WINNING<br />IS MOORD",
            "DE MENS IS DE PLAAG.",
            "HET KLIMAAT<br />VERANDERT ALTIJD",
            "VAN DE ECONOMIE BLIJF JE AF.",
        ],
        [
            "MIDDELMATIGHEID",
            "WERKVERSLAVING",
            "Leven",
            "SUCCES",
            "Succes is niet alleen geld of roem, maar leven met een doel. De behoefte aan materiële middelen in een kapitalistische samenleving negeren is echter naïef, niet deugdzaam.",
            "NEEM ER GENOEGEN MEE",
            "AMBITIE IS VOOR PSYCHOPATEN.",
            "SLAAP<br />NOOIT",
            "RUST IS VOOR ZWAKKELINGEN.",
        ],
        [
            "MILITANT VEGANISME",
            "PUUR CARNIVORISME",
            "Voeding",
            "CULTURELE VOEDING",
            "Eten is een ethische en biologische daad. We kunnen dierenleed verminderen zonder onze omnivore evolutiegeschiedenis te ontkennen. Er bestaat geen heilig dieet.",
            "JE EET<br />LIJKEN",
            "JE BENT EEN SPECIESISTISCHE MOORDENAAR.",
            "ZWAKKE<br />SOYBOY",
            "ALLEEN BLOED GEEFT KRACHT.",
        ],
        [
            "RADICAAL ATHEÏSME",
            "FANATISME",
            "Spiritualiteit",
            "GELOOF EN REDE",
            "De wetenschap verklaart het hoe, spiritualiteit zoekt het waarom. We kunnen de wetenschappelijke methode omarmen zonder onze verwondering over het mysterie van het bestaan te verliezen.",
            "GOD IS<br />DOOD",
            "WE ZIJN WILLEKEURIGE ZAKKEN VLEES.",
            "GEEF JE TIENDEN<br />OF BRAND",
            "TWIJFEL IS EEN DOODZONDE.",
        ],
        [
            "PUUR PONZISPEL",
            "NIEUWE ORDE",
            "Geld",
            "DIGITALE WAARDE",
            "Blockchain is een revolutionaire technologie vol oplichters. Centrale banken bestelen ons via inflatie, maar volledige decentralisatie is een jungle.",
            "PIRAMIDE-<br />SPEL",
            "ALLES IS LUCHT EN WITWASSERIJ.",
            "HODL<br />TOT DE DOOD",
            "FIAT IS MORGEN NIETS MEER WAARD.",
        ],
        [
            "XENOFOBIE",
            "STAATLOOS",
            "Verbondenheid",
            "NATIONALE IDENTITEIT",
            "Van je eigen cultuur houden betekent niet dat je die van je buur moet haten. Wereldburger zijn is een leeg voorrecht als je niet eerst voor je lokale gemeenschap zorgt.",
            "SLUIT DE<br />GRENZEN",
            "EIGEN VOLK EERST.",
            "NATIES<br />ZIJN GEVANGENISSEN",
            "GEEN MENS IS ILLEGAAL.",
        ],
        [
            "CHAOTISCHE POLYAMORIE",
            "BEZIT",
            "Relaties",
            "BAND",
            "Individuele vrijheid mag diepe verbondenheid niet verhinderen. Liefhebben is afzien van andere mogelijke werelden om er samen één te bouwen die stevig staat.",
            "NIETS IS<br />VAN IEMAND",
            "VERBINTENIS IS EEN GEVANGENIS.",
            "JIJ BENT<br />MIJN BEZIT",
            "JALOEZIE IS LIEFDE.",
        ],
        [
            "KRAKEN",
            "SPECULATIE",
            "Thuis",
            "EEN WAARDIG DAK",
            "Wonen is een recht, niet alleen een financieel bezit. Maar rechtszekerheid en particuliere investeringen zijn nodig om dat recht op te bouwen.",
            "ONTEIGEN<br />ALLES",
            "VERHUURDERS ZIJN PARASIETEN.",
            "DE MARKT<br />REGELT ZICHZELF",
            "ALS JE ARM BENT, IS DAT JE EIGEN SCHULD.",
        ],
        [
            "SNOBISME",
            "AUTOMATISERING",
            "Creativiteit",
            "SYNTHETISCHE ZIEL",
            "Kunst is niet alleen het resultaat, maar het menselijke proces van betekenis geven. AI democratiseert techniek, maar zal pijn en ervaring nooit kunnen democratiseren.",
            "DAT IS GEEN<br />KUNST",
            "ALLEEN OLIEVERF HEEFT EEN ZIEL.",
            "PAS JE AAN<br />OF STERF",
            "DE KUNSTENAAR IS OVERBODIG.",
        ],
        [
            "INDOCTRINATIE",
            "VERWILDERING",
            "Onderwijs",
            "LEREN",
            "School moet leren hoe je denkt, niet wat je moet denken. Gestructureerde, gedeelde kennis is echter de basis van de beschaving, geen onderdrukking.",
            "BAKSTENEN-<br />FABRIEK",
            "ZE DODEN JE CREATIVITEIT.",
            "VRIJE<br />ONWETENDHEID",
            "MIJN KIND LEERT DOOR TIKTOK TE KIJKEN.",
        ],
        [
            "POLITIESTAAT",
            "ANARCHIE",
            "Veiligheid",
            "SAMENLEVEN",
            "We willen rustig over straat kunnen, maar niet ten koste van permanente bewaking. Echte veiligheid ontstaat uit sociale samenhang, niet uit camera’s.",
            "CAMERA’S<br />IN DE BADKAMER",
            "WIE NIETS TE VERBERGEN HEEFT, HEEFT NIETS TE VREZEN.",
            "RECHT VAN<br />DE STERKSTE",
            "KOOP EEN WAPEN OF STERF.",
        ],
        [
            "VERBODSPOLITIEK",
            "NARCO-STAAT",
            "Volksgezondheid",
            "ALTER EGO",
            "De oorlog tegen drugs is mislukt, maar ongecontroleerd gebruik verwoest levens. We hebben voorlichting, regulering en verantwoordelijkheid nodig, geen moralisme of chaos.",
            "JE LICHAAM<br />IS VAN DE STAAT",
            "ZEG NEE TEGEN HET LEVEN.",
            "ZOMBIES<br />OP STRAAT",
            "ALLES MAG ALS HET JE HIGH MAAKT.",
        ],
        [
            "ANTINATALISME",
            "BROEDMACHINE",
            "Familie",
            "NALATENSCHAP",
            "Kinderen op de wereld zetten is een daad van radicale hoop, geen vaderlandse plicht of ecologische misdaad. Bewust ouderschap is onze grootste bijdrage aan de toekomst.",
            "LEVEN IS<br />LIJDEN",
            "VRIJWILLIG UITSTERVEN, NU.",
            "BAAR OF<br />STERF",
            "VROUWEN ZIJN FABRIEKEN.",
        ],
        [
            "TRANSPARANTIE",
            "SPOOK",
            "Gegevens",
            "PRIVACY",
            "Privacy is noodzakelijk voor vrijheid. Maar volledige anonimiteit beschermt ook gruwelijke misdaden. Waar ligt de grens tussen veiligheid en het recht op geheimhouding?",
            "GEHEIM<br />BETEKENT SCHULD",
            "PUBLICEER JE HELE CHAT.",
            "DARK<br />WEB",
            "CRYPTOGRAFISCHE STRAFFELOOSHEID.",
        ],
        [
            "BIG PHARMA",
            "PSEUDOWETENSCHAP",
            "Gezondheid",
            "GENEZING",
            "De moderne geneeskunde redt levens, maar geneest niet altijd de ziel en voorkomt niet iedere ziekte. Naar je lichaam luisteren betekent niet dat je antibiotica afwijst.",
            "EEN PIL<br />VOOR ALLES",
            "JOUW PIJN IS EEN MARKT.",
            "KANKER<br />ZIT IN JE HOOFD",
            "HOGE VIBRATIES EN SUIKERWATER.",
        ],
        [
            "GERONTOCRATIE",
            "LEEFTIJDSDISCRIMINATIE",
            "Tijd",
            "VOLWASSENHEID",
            "Ouder worden is een voorrecht, geen ziekte. We moeten zorgen voor wie voor ons zorgde zonder de toekomst van jongeren te verpanden.",
            "ONSTERFELIJKHEID<br />TEGEN ELKE PRIJS",
            "JONGEREN WETEN NIETS.",
            "JE BENT<br />OVERBODIG, OPA",
            "LOGAN’S RUN WAS EEN DOCUMENTAIRE.",
        ],
        [
            "BASISINKOMEN",
            "LUDDISME",
            "Toekomst",
            "DOEL",
            "Als machines werken, wat doen wij dan? Werk geeft waardigheid, uitbuiting niet. We moeten menselijke waarde opnieuw definiëren, voorbij productiviteit.",
            "GRATIS<br />GELD",
            "NIEMAND ZOU OOIT HOEVEN WERKEN.",
            "VERBRAND DE<br />MACHINES",
            "TECHNOLOGIE IS DE DUIVEL.",
        ],
        [
            "SCALPEL",
            "VERWAARLOZING",
            "Esthetiek",
            "ZELFWAARDERING",
            "Er goed uit willen zien is menselijk; jezelf haten is winstgevend. Gezondheid moet de norm zijn, maar uiteenlopende schoonheid is de werkelijkheid.",
            "PERMANENT<br />FILTER",
            "JE ECHTE GEZICHT IS EEN GEBREK.",
            "OBESITAS<br />IS GEZOND",
            "BIOLOGIE ONTKENNEN GEEFT KRACHT.",
        ],
        [
            "DICTATUUR",
            "MASSAHEERSCHAPPIJ",
            "Macht",
            "BESTUUR",
            "De sterke leider belooft orde maar brengt tirannie. De massa belooft inspraak maar brengt chaos. Saaie instituties zijn het enige wat ons tegen onszelf beschermt.",
            "HARDE HAND",
            "VRIJHEID WORDT OVERSCHAT.",
            "STEEK HET<br />PARLEMENT IN BRAND",
            "HET VOLK HEEFT ALTIJD GELIJK.",
        ],
        [
            "DOODSTRAF",
            "STRAFFELOOSHEID",
            "Rechtvaardigheid",
            "HERSTEL",
            "Oog om oog maakt ons blind, maar slachtoffers negeren schept monsters. Re-integratie is het ideaal; de samenleving beschermen is de plicht.",
            "DOOD ZE<br />ALLEMAAL",
            "WRAAK IS ZOET.",
            "SCHAFT<br />GEVANGENISSEN AF",
            "GEEN MISDAAD VERDIENT STRAF.",
        ],
        [
            "ZWARTE LEGENDE",
            "ROZE LEGENDE",
            "Herinnering",
            "VERLEDEN",
            "We kunnen de vijftiende eeuw niet beoordelen met de moraal van de eenentwintigste, noch genocides vergoelijken. Geschiedenis is geen verhaal van helden en schurken, maar een les in complexiteit.",
            "ALLES WAS<br />GENOCIDE",
            "JOUW CULTUUR IS SCHULDIG.",
            "GLORIEUS<br />RIJK",
            "WE HEBBEN NOOIT IETS FOUT GEDAAN.",
        ],
        [
            "WETENSCHAPSRELIGIE",
            "SAMENZWERING",
            "Waarheid",
            "BEWIJS",
            "Wetenschap is een methode om fouten te verkleinen, geen onveranderlijk dogma. Vragen stellen is gezond, maar de waarneembare werkelijkheid ontkennen is wegzinken in waanzin.",
            "DE EXPERT<br />IS GOD",
            "DENK NIET, VERTROUW.",
            "DE AARDE<br />IS PLAT",
            "ALLES IS GEMANIPULEERD.",
        ],
        [
            "VACHTKINDEREN",
            "VERDINGLIJKING",
            "Natuur",
            "SOORTEN",
            "Dieren voelen en verdienen respect, maar ze vermenselijken is ook mishandeling. Van ze houden betekent hun aard begrijpen, niet ze als baby’s verkleden.",
            "MEER DAN<br />MENSEN",
            "RED DE HOND, DOOD HET KIND.",
            "HET ZIJN MAAR<br />DINGEN",
            "GEBRUIK ZE EN GOOI ZE WEG.",
        ],
        [
            "UNIFORM",
            "FAST FASHION",
            "Imago",
            "UITDRUKKING",
            "Kleding is taal, maar dwangmatige consumptie is vernietiging. We kunnen stijl hebben zonder de planeet uit te buiten of zelf reclameborden te worden.",
            "DRAAG<br />GRIJS",
            "OPVALLEN IS IJDELHEID.",
            "KOOP<br />EN GOOI WEG",
            "IETS NIEUWS DRAGEN IS GELUK.",
        ],
        [
            "VERBOD",
            "GOKVERSLAVING",
            "Ondeugd",
            "TOEVAL",
            "Gokken is vermaak voor volwassenen, maar een roofzuchtige industrie verwoest gezinnen. Agressieve reclame reguleren beschermt de vrije keuze tegen valstrikken.",
            "ILLEGAAL<br />PLEZIER",
            "GENOT IS ZONDE.",
            "VERGOK<br />JE HUIS",
            "DE VOLGENDE DRAAI REDT JE.",
        ],
        [
            "TOURIST GO HOME",
            "THEMAPARK",
            "Reizen",
            "ONTDEKKING",
            "Reizen verruimt de geest, maar massatoerisme sluit buurten. We willen de wereld leren kennen zonder er een kartonnen decor van te maken.",
            "WEG<br />HIER",
            "BUITENLANDERS ZIJN LASTIG.",
            "VERKOOP JE<br />BUURT",
            "ALLES IS EEN AIRBNB.",
        ],
        [
            "INCLUSIEVE TAAL",
            "TAALPURISME",
            "Communicatie",
            "WOORDEN",
            "Taal evolueert met de samenleving, maar kunstmatige veranderingen opleggen roept weerstand op. Laten we spreken om elkaar te begrijpen, niet om politieke deugd te etaleren.",
            "PRAAT NORMAAL,<br />VERDOMME",
            "GENDERNEUTRALE TAAL VERNIETIGT HET GEZIN.",
            "DE TAALUNIE IS<br />SEKSISTISCH",
            "VERANDER OF JE BENT DE VIJAND.",
        ],
        [
            "WINNEN IS ALLES",
            "DEELNAME",
            "Competitie",
            "INSPANNING",
            "Uitmuntendheid vereist offers en er zijn winnaars en verliezers. Maar breedtesport moet waarden bevorderen, geen vroege frustratie.",
            "DE TWEEDE<br />IS DE EERSTE VERLIEZER",
            "VERNEDER JE TEGENSTANDER.",
            "IEDEREEN IS<br />KAMPIOEN",
            "VERLIEZEN TRAUMATISEERT VOOR ALTIJD.",
        ],
        [
            "HIKIKOMORI",
            "GEDWONGEN SOCIALISEREN",
            "Gemeenschap",
            "VERBINDING",
            "Alleen kunnen zijn is essentieel, maar afzondering is ziekelijk. We zijn sociale dieren die de groep nodig hebben, ook als die soms benauwt.",
            "IK HAAT<br />MENSEN",
            "MIJN KAMER IS MIJN WERELD.",
            "GLIMLACH EN<br />DOE MEE",
            "INTROVERSIE IS TE GENEZEN.",
        ],
    ]
);
