import { createNuanceTexts } from "./create";

export const NUANCE_PL_TEXTS = createNuanceTexts(
    {
        hud: {
            defaultLeft: "Lewo",
            defaultRight: "Prawo",
            hint: "Przesuń, aby odkryć",
            sliderLabel: "Równowaga między skrajnościami",
        },
        intro: {
            labelLeft: "PUSTKA",
            labelRight: "CIEMNOŚĆ",
            title: "NIUANS",
            descriptionFirst: "Prawdziwy świat jest pełen barw.",
            descriptionSecond: "Skrajności są ich brakiem.",
            leftTitle: "BIEL",
            leftDescription: "Bez cieni. Bez wątpliwości.",
            rightTitle: "CZERŃ",
            rightDescription: "Bez światła. Bez nadziei.",
        },
        outro: {
            firstLine: "Świat chce, żebyś opowiedział się po jednej ze stron.",
            secondLine: "Prawdziwa rewolucja polega na odmowie.",
            exit: "Wyjdź z pętli",
            left: "PUSTKA",
            right: "CIEMNOŚĆ",
        },
    },
    [
        [
            "MIZANDRIA",
            "MACHISMO",
            "Równość",
            "PŁEĆ",
            "Uznanie różnic biologicznych nie usprawiedliwia nierówności praw. Całkowite ich negowanie ignoruje materialną rzeczywistość. Równość ma wymiar prawny i moralny, nie biologiczny.",
            "WSZYSCY SĄ<br />WINNI",
            "MĘSKOŚĆ TO RAK.",
            "WRACAJ DO<br />KUCHNI",
            "NATURALNY PORZĄDEK JEST ŚWIĘTY.",
        ],
        [
            "TOKSYCZNOŚĆ",
            "CZYSTA WIĘŹ",
            "Społeczeństwo",
            "ALGORYTM",
            "Media społecznościowe mogą wzmacniać głosy grup marginalizowanych i demokratyzować wiedzę, lecz ich obecny model biznesowy zarabia na polaryzacji i lęku.",
            "USUŃ<br />WSZYSTKO",
            "ŻYJEMY W SYMULACJI EGO.",
            "OPUBLIKUJ<br />SWOJĄ DUSZĘ",
            "JEŚLI TEGO NIE UDOSTĘPNISZ, NIE ISTNIEJESZ.",
        ],
        [
            "NIEUCHRONNY UPADEK",
            "NEGACJONIZM",
            "Planeta",
            "EKO-LOGIKA",
            "Panika paraliżuje, a negowanie skazuje na zgubę. Potrzebujemy śmiałych innowacji technologicznych i selektywnego postwzrostu, a nie powrotu do jaskiń ani udawania, że nic się nie dzieje.",
            "WYDOBYCIE<br />TO MORDERSTWO",
            "CZŁOWIEK JEST PLAGĄ.",
            "KLIMAT<br />ZAWSZE SIĘ ZMIENIA",
            "GOSPODARKI SIĘ NIE RUSZA.",
        ],
        [
            "PRZECIĘTNOŚĆ",
            "PRACOHOLIZM",
            "Życie",
            "SUKCES",
            "Sukces to nie tylko pieniądze czy sława, lecz życie z poczuciem celu. Ignorowanie potrzeby zasobów materialnych w społeczeństwie kapitalistycznym jest jednak naiwnością, nie cnotą.",
            "POGÓDŹ SIĘ Z TYM",
            "AMBICJA JEST DLA PSYCHOPATÓW.",
            "NIGDY<br />NIE ŚPIJ",
            "ODPOCZYNEK JEST DLA SŁABYCH.",
        ],
        [
            "WOJUJĄCY WEGANIZM",
            "CZYSTY KARNIWORYZM",
            "Żywienie",
            "ŻYWIENIE KULTUROWE",
            "Jedzenie jest aktem etycznym i biologicznym. Możemy ograniczać cierpienie zwierząt, nie zaprzeczając naszej wszystkożernej historii ewolucyjnej. Nie istnieje święta dieta.",
            "JESZ<br />ZWŁOKI",
            "JESTEŚ GATUNKISTYCZNYM MORDERCĄ.",
            "SŁABY<br />SOYBOY",
            "TYLKO KREW DAJE SIŁĘ.",
        ],
        [
            "RADYKALNY ATEIZM",
            "FANATYZM",
            "Duchowość",
            "WIARA I ROZUM",
            "Nauka wyjaśnia jak, duchowość szuka odpowiedzi dlaczego. Możemy przyjąć metodę naukową, nie tracąc zachwytu nad tajemnicą istnienia.",
            "BÓG<br />UMARŁ",
            "JESTEŚMY PRZYPADKOWYMI WORKAMI MIĘSA.",
            "PŁAĆ DZIESIĘCINĘ<br />ALBO PŁOŃ",
            "WĄTPIENIE TO GRZECH ŚMIERTELNY.",
        ],
        [
            "CZYSTE PONZI",
            "NOWY ŁAD",
            "Pieniądze",
            "WARTOŚĆ CYFROWA",
            "Blockchain jest rewolucyjną technologią pełną oszustów. Banki centralne okradają nas przez inflację, ale pełna decentralizacja to dżungla.",
            "PIRAMIDA<br />FINANSOWA",
            "WSZYSTKO TO DYMY I PRANIE PIENIĘDZY.",
            "HODL<br />AŻ DO ŚMIERCI",
            "JUTRO PIENIĄDZ FIAT BĘDZIE WART ZERO.",
        ],
        [
            "KSENOFOBIA",
            "BEZPAŃSTWOWOŚĆ",
            "Przynależność",
            "TOŻSAMOŚĆ NARODOWA",
            "Miłość do własnej kultury nie oznacza nienawiści do kultury sąsiada. Bycie obywatelem świata jest pustym przywilejem, jeśli najpierw nie dbasz o lokalną wspólnotę.",
            "ZAMKNĄĆ<br />GRANICE",
            "NAJPIERW SWOI.",
            "NARODY<br />TO WIĘZIENIA",
            "ŻADEN CZŁOWIEK NIE JEST NIELEGALNY.",
        ],
        [
            "CHAOTYCZNA POLIAMORIA",
            "POSIADANIE",
            "Relacje",
            "WIĘŹ",
            "Wolność jednostki nie powinna wykluczać głębokiego zobowiązania. Kochać to zrezygnować z możliwości innych światów, by zbudować jeden wspólny i trwały.",
            "NIC NIE NALEŻY<br />DO NIKOGO",
            "ZOBOWIĄZANIE TO WIĘZIENIE.",
            "JESTEŚ<br />MOJĄ WŁASNOŚCIĄ",
            "ZAZDROŚĆ TO MIŁOŚĆ.",
        ],
        [
            "SKŁOTING",
            "SPEKULACJA",
            "Dom",
            "GODNY DACH",
            "Mieszkanie jest prawem, nie tylko aktywem finansowym. Jednak pewność prawa i prywatne inwestycje są konieczne, by to prawo urzeczywistnić.",
            "WYWŁASZCZYĆ<br />WSZYSTKO",
            "WYNAJMUJĄCY TO PASOŻYTY.",
            "RYNEK<br />REGULUJE SIĘ SAM",
            "JEŚLI JESTEŚ BIEDNY, TO TWOJA WINA.",
        ],
        [
            "SNOBIZM",
            "AUTOMATYZACJA",
            "Kreatywność",
            "SYNTETYCZNA DUSZA",
            "Sztuka to nie tylko rezultat, lecz ludzki proces nadawania sensu. AI demokratyzuje technikę, ale nigdy nie zdemokratyzuje bólu ani doświadczenia.",
            "TO NIE JEST<br />SZTUKA",
            "TYLKO FARBA OLEJNA MA DUSZĘ.",
            "DOSTOSUJ SIĘ<br />ALBO ZGIŃ",
            "ARTYSTA JEST ZBĘDNY.",
        ],
        [
            "INDOKTRYNACJA",
            "ZDZICZENIE",
            "Edukacja",
            "UCZENIE SIĘ",
            "Szkoła powinna uczyć, jak myśleć, a nie co myśleć. Jednak uporządkowana i wspólna wiedza jest fundamentem cywilizacji, nie uciskiem.",
            "FABRYKA<br />CEGIEŁ",
            "ZABIJAJĄ TWOJĄ KREATYWNOŚĆ.",
            "WOLNA<br />IGNORANCJA",
            "MOJE DZIECKO UCZY SIĘ Z TIKTOKA.",
        ],
        [
            "PAŃSTWO POLICYJNE",
            "ANARCHIA",
            "Bezpieczeństwo",
            "WSPÓŁISTNIENIE",
            "Chcemy spokojnie chodzić po ulicy, lecz nie za cenę całodobowej inwigilacji. Prawdziwe bezpieczeństwo rodzi się ze spójności społecznej, nie z kamer.",
            "KAMERY<br />W ŁAZIENCE",
            "KTO NIE MA NIC DO UKRYCIA, NIE MA SIĘ CZEGO BAĆ.",
            "PRAWO<br />SILNIEJSZEGO",
            "KUP BROŃ ALBO ZGIŃ.",
        ],
        [
            "PROHIBICJA",
            "NARKOPAŃSTWO",
            "Zdrowie publiczne",
            "ALTER EGO",
            "Wojna z narkotykami poniosła klęskę, ale niekontrolowane używanie niszczy życie. Potrzebujemy edukacji, regulacji i odpowiedzialności, nie moralizatorstwa ani chaosu.",
            "TWOJE CIAŁO<br />NALEŻY DO PAŃSTWA",
            "POWIEDZ ŻYCIU NIE.",
            "ZOMBIE<br />NA ULICY",
            "WSZYSTKO WOLNO, JEŚLI ODURZA.",
        ],
        [
            "ANTYNATALIZM",
            "INKUBATOR",
            "Rodzina",
            "DZIEDZICTWO",
            "Sprowadzanie dzieci na świat jest aktem radykalnej nadziei, nie patriotycznym obowiązkiem ani ekologiczną zbrodnią. Świadome rodzicielstwo to nasz największy wkład w przyszłość.",
            "ŻYCIE TO<br />CIERPIENIE",
            "DOBROWOLNE WYGINIĘCIE TERAZ.",
            "RODŹ ALBO<br />ZGIŃ",
            "KOBIETY SĄ FABRYKAMI.",
        ],
        [
            "PRZEJRZYSTOŚĆ",
            "DUCH",
            "Dane",
            "PRYWATNOŚĆ",
            "Prywatność jest konieczna dla wolności. Lecz pełna anonimowość chroni również potworne zbrodnie. Gdzie przebiega granica między bezpieczeństwem a prawem do tajemnicy?",
            "TAJEMNICA<br />OZNACZA WINĘ",
            "OPUBLIKUJ CAŁY SWÓJ CZAT.",
            "DARK<br />WEB",
            "KRYPTOGRAFICZNA BEZKARNOŚĆ.",
        ],
        [
            "BIG PHARMA",
            "PSEUDONAUKA",
            "Zdrowie",
            "UZDROWIENIE",
            "Współczesna medycyna ratuje życie, ale nie zawsze leczy duszę ani zapobiega chorobom. Słuchanie ciała nie oznacza odrzucania antybiotyków.",
            "PIGUŁKA<br />NA WSZYSTKO",
            "TWÓJ BÓL TO RYNEK.",
            "RAK<br />JEST W GŁOWIE",
            "WYSOKIE WIBRACJE I WODA Z CUKREM.",
        ],
        [
            "GERONTOKRACJA",
            "AGEIZM",
            "Czas",
            "DOJRZAŁOŚĆ",
            "Starzenie się jest przywilejem, nie chorobą. Musimy dbać o tych, którzy dbali o nas, nie zastawiając przyszłości młodych.",
            "NIEŚMIERTELNOŚĆ<br />ZA WSZELKĄ CENĘ",
            "MŁODZI NIC NIE WIEDZĄ.",
            "JESTEŚ ZBĘDNY,<br />DZIADKU",
            "UCIECZKA LOGANA BYŁA DOKUMENTEM.",
        ],
        [
            "DOCHÓD PODSTAWOWY",
            "LUDDYZM",
            "Przyszłość",
            "CEL",
            "Jeśli pracują maszyny, co robimy my? Praca uszlachetnia, wyzysk nie. Musimy zdefiniować wartość człowieka na nowo, poza produktywnością.",
            "DARMOWE<br />PIENIĄDZE",
            "NIKT NIGDY NIE POWINIEN PRACOWAĆ.",
            "SPALCIE<br />MASZYNY",
            "TECHNOLOGIA JEST DIABŁEM.",
        ],
        [
            "SKALPEL",
            "ZANIEDBANIE",
            "Estetyka",
            "POCZUCIE WŁASNEJ WARTOŚCI",
            "Chęć dobrego wyglądu jest ludzka; nienawiść do siebie przynosi zysk. Zdrowie powinno być normą, lecz różnorodne piękno jest rzeczywistością.",
            "STAŁY<br />FILTR",
            "TWOJA PRAWDZIWA TWARZ TO WADA.",
            "OTYŁOŚĆ<br />TO ZDROWIE",
            "NEGOWANIE BIOLOGII DAJE SIŁĘ.",
        ],
        [
            "DYKTATURA",
            "RZĄDY TŁUMU",
            "Władza",
            "RZĄD",
            "Silny przywódca obiecuje porządek, lecz przynosi tyranię. Tłum obiecuje głos, lecz przynosi chaos. Nudne instytucje są jedyną ochroną przed nami samymi.",
            "TWARDA RĘKA",
            "WOLNOŚĆ JEST PRZEREKLAMOWANA.",
            "SPALIĆ<br />PARLAMENT",
            "LUD ZAWSZE MA RACJĘ.",
        ],
        [
            "KARA ŚMIERCI",
            "BEZKARNOŚĆ",
            "Sprawiedliwość",
            "NAPRAWA",
            "Oko za oko czyni nas ślepymi, ale ignorowanie ofiar tworzy potwory. Resocjalizacja jest ideałem, ochrona społeczeństwa obowiązkiem.",
            "ZABIĆ ICH<br />WSZYSTKICH",
            "ZEMSTA JEST SŁODKA.",
            "ZLIKWIDOWAĆ<br />WIĘZIENIA",
            "ŻADNE PRZESTĘPSTWO NIE ZASŁUGUJE NA KARĘ.",
        ],
        [
            "CZARNA LEGENDA",
            "RÓŻOWA LEGENDA",
            "Pamięć",
            "PRZESZŁOŚĆ",
            "Nie możemy osądzać XV wieku moralnością XXI ani wybielać ludobójstw. Historia nie jest bajką o bohaterach i złoczyńcach, lecz lekcją złożoności.",
            "WSZYSTKO BYŁO<br />LUDOBÓJSTWEM",
            "TWOJA KULTURA JEST WINNA.",
            "CHWALEBNE<br />IMPERIUM",
            "NIGDY NIE ZROBILIŚMY NIC ZŁEGO.",
        ],
        [
            "RELIGIA NAUKOWA",
            "SPISEK",
            "Prawda",
            "DOWODY",
            "Nauka jest metodą ograniczania błędów, nie niezmiennym dogmatem. Kwestionowanie jest zdrowe, lecz negowanie obserwowalnej rzeczywistości prowadzi w otchłań urojenia.",
            "EKSPERT<br />JEST BOGIEM",
            "NIE MYŚL, UFAJ.",
            "ZIEMIA<br />JEST PŁASKA",
            "WSZYSTKO JEST USTAWIONE.",
        ],
        [
            "FUTRZANE DZIECI",
            "UPRZEDMIOTOWIENIE",
            "Natura",
            "GATUNKI",
            "Zwierzęta czują i zasługują na szacunek, lecz uczłowieczanie ich jest inną formą krzywdzenia. Kochać je to rozumieć ich naturę, nie przebierać za niemowlęta.",
            "WIĘCEJ NIŻ<br />LUDZIE",
            "URATUJ PSA, ZABIJ DZIECKO.",
            "TO TYLKO<br />RZECZY",
            "UŻYJ I WYRZUĆ.",
        ],
        [
            "MUNDUR",
            "FAST FASHION",
            "Wizerunek",
            "EKSPRESJA",
            "Ubranie jest językiem, lecz kompulsywna konsumpcja jest zniszczeniem. Możemy mieć styl bez wyzyskiwania planety i zamieniania siebie w billboardy.",
            "NOŚ<br />SZAROŚĆ",
            "WYRÓŻNIANIE SIĘ TO PRÓŻNOŚĆ.",
            "KUP<br />I WYRZUĆ",
            "NOWE UBRANIA DAJĄ SZCZĘŚCIE.",
        ],
        [
            "ZAKAZ",
            "HAZARD",
            "Nałóg",
            "PRZYPADEK",
            "Hazard jest rozrywką dla dorosłych, ale drapieżna branża niszczy rodziny. Regulowanie agresywnej reklamy chroni wolność wyboru przed pułapkami.",
            "NIELEGALNA<br />ZABAWA",
            "PRZYJEMNOŚĆ TO GRZECH.",
            "POSTAW<br />DOM",
            "NASTĘPNY OBRÓT CIĘ URATUJE.",
        ],
        [
            "TOURIST GO HOME",
            "PARK ROZRYWKI",
            "Podróże",
            "ODKRYWANIE",
            "Podróże otwierają umysł, lecz masowa turystyka zamyka dzielnice. Chcemy poznawać świat, nie zamieniając go w tekturową dekorację.",
            "WYNOŚ SIĘ<br />STĄD",
            "CUDZOZIEMCY PRZESZKADZAJĄ.",
            "SPRZEDAJ SWOJĄ<br />DZIELNICĘ",
            "WSZYSTKO JEST AIRBNB.",
        ],
        [
            "JĘZYK INKLUZYWNY",
            "PURYZM JĘZYKOWY",
            "Komunikacja",
            "SŁOWA",
            "Język ewoluuje wraz ze społeczeństwem, ale narzucanie sztucznych zmian budzi sprzeciw. Mówmy po to, by się rozumieć, nie by demonstrować polityczną cnotę.",
            "MÓW POPRAWNIE,<br />CHOLERA",
            "NEUTRALNY JĘZYK NISZCZY RODZINĘ.",
            "RADA JĘZYKA JEST<br />SEKSISTOWSKA",
            "ZMIEŃ SIĘ ALBO JESTEŚ WROGIEM.",
        ],
        [
            "ZWYCIĘSTWO TO WSZYSTKO",
            "UCZESTNICTWO",
            "Rywalizacja",
            "WYSIŁEK",
            "Doskonałość wymaga poświęcenia i są zwycięzcy oraz przegrani. Sport masowy powinien jednak kształtować wartości, nie przedwczesne frustracje.",
            "DRUGI<br />TO PIERWSZY PRZEGRANY",
            "UPOKÓRZ RYWALA.",
            "WSZYSCY SĄ<br />MISTRZAMI",
            "PORAŻKA TRAUMATYZUJE NA CAŁE ŻYCIE.",
        ],
        [
            "HIKIKOMORI",
            "WYMUSZONA SOCJALIZACJA",
            "Wspólnota",
            "WIĘŹ",
            "Umieć być samemu jest niezbędne, ale izolacja jest patologiczna. Jesteśmy zwierzętami społecznymi i potrzebujemy plemienia, choć czasem ono przytłacza.",
            "NIENAWIDZĘ<br />LUDZI",
            "MÓJ POKÓJ JEST MOIM ŚWIATEM.",
            "UŚMIECHNIJ SIĘ<br />I DOŁĄCZ",
            "INTROWERSJĘ MOŻNA WYLECZYĆ.",
        ],
    ]
);
