import { createNuanceTexts } from "./create";

export const NUANCE_PT_TEXTS = createNuanceTexts(
    {
        hud: {
            defaultLeft: "Esquerda",
            defaultRight: "Direita",
            hint: "Deslize para descobrir",
            sliderLabel: "Equilíbrio entre extremos",
        },
        intro: {
            labelLeft: "VAZIO",
            labelRight: "ESCURIDÃO",
            title: "NUANCE",
            descriptionFirst: "O mundo real está cheio de cor.",
            descriptionSecond: "Os extremos são a sua ausência.",
            leftTitle: "BRANCO",
            leftDescription: "Sem sombras. Sem dúvidas.",
            rightTitle: "PRETO",
            rightDescription: "Sem luz. Sem esperança.",
        },
        outro: {
            firstLine: "O mundo quer que escolhas um lado.",
            secondLine: "A verdadeira revolução é recusar.",
            exit: "Sair do ciclo",
            left: "VAZIO",
            right: "ESCURIDÃO",
        },
    },
    [
        [
            "MISANDRIA",
            "MACHISMO",
            "Igualdade",
            "GÉNERO",
            "Reconhecer as diferenças biológicas não justifica a desigualdade de direitos. Negá-las por completo ignora a realidade material. A igualdade é jurídica e moral, não biológica.",
            "SÃO TODOS<br />CULPADOS",
            "A MASCULINIDADE É UM CANCRO.",
            "VOLTA PARA A<br />COZINHA",
            "A ORDEM NATURAL É SAGRADA.",
        ],
        [
            "TÓXICO",
            "LIGAÇÃO PURA",
            "Social",
            "ALGORITMO",
            "As redes sociais podem amplificar vozes marginalizadas e democratizar o conhecimento, mas o seu atual modelo de negócio monetiza a polarização e a ansiedade.",
            "APAGA<br />TUDO",
            "VIVEMOS NUMA SIMULAÇÃO DO EGO.",
            "PUBLICA<br />A TUA ALMA",
            "SE NÃO PARTILHAS, NÃO EXISTES.",
        ],
        [
            "COLAPSO INEVITÁVEL",
            "NEGACIONISMO",
            "Planeta",
            "ECO-LÓGICA",
            "O pânico paralisa e o negacionismo condena. Precisamos de inovação tecnológica agressiva e decrescimento seletivo, não de voltar às cavernas nem de fingir que nada acontece.",
            "EXTRAÇÃO<br />É ASSASSÍNIO",
            "O SER HUMANO É A PRAGA.",
            "O CLIMA<br />MUDA SEMPRE",
            "NA ECONOMIA NÃO SE TOCA.",
        ],
        [
            "MEDIOCRIDADE",
            "VÍCIO NO TRABALHO",
            "Vida",
            "SUCESSO",
            "O sucesso não é apenas dinheiro ou fama; é viver com propósito. Mas ignorar a necessidade de recursos materiais numa sociedade capitalista é ingenuidade, não virtude.",
            "CONFORMA-TE",
            "A AMBIÇÃO É DE PSICOPATAS.",
            "NUNCA<br />DURMAS",
            "O DESCANSO É PARA OS FRACOS.",
        ],
        [
            "VEGANISMO MILITANTE",
            "CARNIVORISMO PURO",
            "Nutrição",
            "NUTRIÇÃO CULTURAL",
            "Comer é um ato ético e biológico. Podemos reduzir o sofrimento animal sem negar a nossa história evolutiva omnívora. Não existe uma dieta santa.",
            "COMES<br />CADÁVERES",
            "ÉS UM ASSASSINO ESPECISTA.",
            "SOYBOY<br />FRACO",
            "SÓ O SANGUE DÁ FORÇA.",
        ],
        [
            "ATEÍSMO RADICAL",
            "FANATISMO",
            "Espiritualidade",
            "FÉ E RAZÃO",
            "A ciência explica o como; a espiritualidade procura o porquê. Podemos abraçar o método científico sem perder o espanto perante o mistério da existência.",
            "DEUS ESTÁ<br />MORTO",
            "SOMOS SACOS DE CARNE ALEATÓRIOS.",
            "DÁ O DÍZIMO<br />OU ARDE",
            "A DÚVIDA É UM PECADO MORTAL.",
        ],
        [
            "PONZI TOTAL",
            "NOVA ORDEM",
            "Dinheiro",
            "VALOR DIGITAL",
            "A blockchain é uma tecnologia revolucionária cheia de burlões. Os bancos centrais roubam-nos através da inflação, mas a descentralização total é uma selva.",
            "ESQUEMA<br />PIRAMIDAL",
            "É TUDO FUMO E BRANQUEAMENTO DE CAPITAIS.",
            "HODL<br />ATÉ À MORTE",
            "A MOEDA FIAT VAI A ZERO AMANHÃ.",
        ],
        [
            "XENOFOBIA",
            "APÁTRIDA",
            "Pertença",
            "IDENTIDADE NACIONAL",
            "Amar a tua cultura não implica odiar a do vizinho. Ser cidadão do mundo é um privilégio vazio se não cuidares primeiro da tua comunidade local.",
            "FECHA AS<br />FRONTEIRAS",
            "PRIMEIRO OS NOSSOS.",
            "AS NAÇÕES<br />SÃO PRISÕES",
            "NENHUM SER HUMANO É ILEGAL.",
        ],
        [
            "POLIAMOR CAÓTICO",
            "POSSE",
            "Relações",
            "VÍNCULO",
            "A liberdade individual não deveria impedir um compromisso profundo. Amar é renunciar à possibilidade de outros mundos para construir um mundo partilhado e sólido.",
            "NADA É<br />DE NINGUÉM",
            "O COMPROMISSO É UMA PRISÃO.",
            "ÉS<br />MINHA PROPRIEDADE",
            "CIÚME É AMOR.",
        ],
        [
            "OCUPAÇÃO",
            "ESPECULAÇÃO",
            "Lar",
            "TETO DIGNO",
            "A habitação é um direito, não apenas um ativo financeiro. Mas a segurança jurídica e o investimento privado são necessários para construir esse direito.",
            "EXPROPRIA<br />TUDO",
            "OS SENHORIOS SÃO PARASITAS.",
            "O MERCADO<br />REGULA-SE",
            "SE ÉS POBRE, A CULPA É TUA.",
        ],
        [
            "SNOBISMO",
            "AUTOMATIZAÇÃO",
            "Criatividade",
            "ALMA SINTÉTICA",
            "A arte não é apenas o resultado; é o processo humano de criar sentido. A IA democratiza a técnica, mas nunca poderá democratizar a dor nem a experiência.",
            "ISSO NÃO É<br />ARTE",
            "SÓ A TINTA A ÓLEO TEM ALMA.",
            "ADAPTA-TE<br />OU MORRE",
            "O ARTISTA É DISPENSÁVEL.",
        ],
        [
            "DOUTRINAÇÃO",
            "SELVAGERIA",
            "Educação",
            "APRENDIZAGEM",
            "A escola deve ensinar a pensar, não o que pensar. Mas o conhecimento estruturado e partilhado é a base da civilização, não uma opressão.",
            "FÁBRICA DE<br />TIJOLOS",
            "MATAM A TUA CRIATIVIDADE.",
            "IGNORÂNCIA<br />LIVRE",
            "O MEU FILHO APRENDE A VER TIKTOK.",
        ],
        [
            "ESTADO POLICIAL",
            "ANARQUIA",
            "Segurança",
            "CONVIVÊNCIA",
            "Queremos andar tranquilos na rua, mas não à custa de sermos vigiados vinte e quatro horas por dia. A segurança real nasce da coesão social, não das câmaras.",
            "CÂMARAS NA<br />CASA DE BANHO",
            "QUEM NÃO DEVE NÃO TEME.",
            "LEI DO<br />MAIS FORTE",
            "COMPRA UMA ARMA OU MORRE.",
        ],
        [
            "PROIBICIONISMO",
            "NARCOESTADO",
            "Saúde pública",
            "ALTER EGO",
            "A guerra contra as drogas fracassou, mas o consumo sem controlo destrói vidas. Precisamos de educação, regulação e responsabilidade, não de moralismo nem de caos.",
            "O TEU CORPO<br />É DO ESTADO",
            "DIZ NÃO À VIDA.",
            "ZOMBIS<br />NA RUA",
            "TUDO VALE SE DER MOCADA.",
        ],
        [
            "ANTINATALISMO",
            "INCUBADORA",
            "Família",
            "LEGADO",
            "Trazer filhos ao mundo é um ato de esperança radical, não um dever patriótico nem um crime ecológico. Uma parentalidade consciente é o maior contributo para o futuro.",
            "A VIDA É<br />SOFRIMENTO",
            "EXTINÇÃO VOLUNTÁRIA JÁ.",
            "PROCRIA OU<br />MORRE",
            "AS MULHERES SÃO FÁBRICAS.",
        ],
        [
            "TRANSPARÊNCIA",
            "FANTASMA",
            "Dados",
            "INTIMIDADE",
            "A privacidade é necessária à liberdade. Mas o anonimato total também protege crimes atrozes. Onde está o limite entre segurança e direito ao segredo?",
            "O SEGREDO<br />É CULPA",
            "PUBLICA TODA A TUA CONVERSA.",
            "DARK<br />WEB",
            "IMPUNIDADE CRIPTOGRÁFICA.",
        ],
        [
            "BIG PHARMA",
            "PSEUDOCIÊNCIA",
            "Saúde",
            "CURA",
            "A medicina moderna salva vidas, mas nem sempre cura a alma ou previne a doença. Escutar o corpo não significa rejeitar os antibióticos.",
            "UM COMPRIMIDO<br />PARA TUDO",
            "A TUA DOR É UM MERCADO.",
            "O CANCRO<br />É MENTAL",
            "VIBRAÇÕES ALTAS E ÁGUA COM AÇÚCAR.",
        ],
        [
            "GERONTOCRACIA",
            "IDADISMO",
            "Tempo",
            "MATURIDADE",
            "Envelhecer é um privilégio, não uma doença. Devemos cuidar de quem cuidou de nós sem hipotecar o futuro dos jovens.",
            "IMORTALIDADE<br />A QUALQUER PREÇO",
            "OS JOVENS NÃO SABEM NADA.",
            "ESTÁS A MAIS,<br />AVÔ",
            "LOGAN’S RUN ERA UM DOCUMENTÁRIO.",
        ],
        [
            "RENDIMENTO BÁSICO",
            "LUDISMO",
            "Futuro",
            "PROPÓSITO",
            "Se as máquinas trabalham, o que fazemos nós? O trabalho dignifica, a exploração não. Precisamos de redefinir o valor humano para além da produtividade.",
            "DINHEIRO<br />GRÁTIS",
            "NINGUÉM DEVERIA TRABALHAR NUNCA.",
            "QUEIMA AS<br />MÁQUINAS",
            "A TECNOLOGIA É O DEMÓNIO.",
        ],
        [
            "BISTURI",
            "ABANDONO",
            "Estética",
            "AUTOESTIMA",
            "Querer ter bom aspeto é humano; odiarmo-nos é rentável. A saúde deve ser o padrão, mas a beleza diversa é a realidade.",
            "FILTRO<br />PERMANENTE",
            "A TUA CARA REAL É UM DEFEITO.",
            "OBESIDADE<br />É SAÚDE",
            "NEGAR A BIOLOGIA É EMPODERADOR.",
        ],
        [
            "DITADURA",
            "GOVERNO DA MULTIDÃO",
            "Poder",
            "GOVERNO",
            "O líder forte promete ordem, mas traz tirania. A multidão promete voz, mas traz caos. As instituições aborrecidas são a única coisa que nos protege de nós próprios.",
            "MÃO DE FERRO",
            "A LIBERDADE É SOBREVALORIZADA.",
            "QUEIMEM O<br />PARLAMENTO",
            "O POVO TEM SEMPRE RAZÃO.",
        ],
        [
            "PENA DE MORTE",
            "IMPUNIDADE",
            "Justiça",
            "REPARAÇÃO",
            "Olho por olho deixa-nos cegos, mas ignorar as vítimas cria monstros. A reinserção é o ideal; proteger a sociedade é o dever.",
            "MATEM-NOS<br />A TODOS",
            "A VINGANÇA É DOCE.",
            "ABOLIR AS<br />PRISÕES",
            "NENHUM CRIME MERECE CASTIGO.",
        ],
        [
            "LENDA NEGRA",
            "LENDA COR-DE-ROSA",
            "Memória",
            "PASSADO",
            "Não podemos julgar o século XV com a moral do XXI, nem branquear genocídios. A história não é um conto de heróis e vilões; é uma lição de complexidade.",
            "FOI TUDO<br />GENOCÍDIO",
            "A TUA CULTURA É CULPADA.",
            "IMPÉRIO<br />GLORIOSO",
            "NUNCA FIZEMOS NADA DE MAL.",
        ],
        [
            "RELIGIÃO CIENTÍFICA",
            "CONSPIRAÇÃO",
            "Verdade",
            "EVIDÊNCIA",
            "A ciência é um método para reduzir o erro, não um dogma imutável. Questionar é saudável, mas negar a realidade observável é cair no abismo do delírio.",
            "O ESPECIALISTA<br />É DEUS",
            "NÃO PENSES, CONFIA.",
            "A TERRA<br />É PLANA",
            "ESTÁ TUDO MANIPULADO.",
        ],
        [
            "FILHOS DE QUATRO PATAS",
            "COISIFICAÇÃO",
            "Natureza",
            "ESPÉCIES",
            "Os animais sentem e merecem respeito, mas humanizá-los é outra forma de maus-tratos. Amá-los é compreender a sua natureza, não vesti-los como bebés.",
            "MAIS QUE<br />HUMANOS",
            "SALVA O CÃO, MATA A CRIANÇA.",
            "SÃO APENAS<br />COISAS",
            "USA-OS E DEITA-OS FORA.",
        ],
        [
            "UNIFORME",
            "FAST FASHION",
            "Imagem",
            "EXPRESSÃO",
            "A roupa é linguagem, mas o consumo compulsivo é destruição. Podemos ter estilo sem explorar o planeta nem transformar-nos em painéis publicitários.",
            "VESTE<br />CINZENTO",
            "DESTACAR-SE É VAIDADE.",
            "COMPRA<br />E DEITA FORA",
            "ESTREAR ROUPA É FELICIDADE.",
        ],
        [
            "PROIBIÇÃO",
            "DEPENDÊNCIA DO JOGO",
            "Vício",
            "ACASO",
            "O jogo é entretenimento para adultos, mas uma indústria predatória destrói famílias. Regular a publicidade agressiva é proteger a liberdade de escolher sem armadilhas.",
            "DIVERSÃO<br />ILEGAL",
            "O PRAZER É PECADO.",
            "APOSTA<br />A CASA",
            "A PRÓXIMA JOGADA VAI SALVAR-TE.",
        ],
        [
            "TOURIST GO HOME",
            "PARQUE TEMÁTICO",
            "Viagens",
            "EXPLORAÇÃO",
            "Viajar abre a mente, mas o turismo de massas fecha bairros. Queremos conhecer o mundo sem o transformar num cenário de cartão.",
            "FORA<br />DAQUI",
            "OS ESTRANGEIROS INCOMODAM.",
            "VENDE O TEU<br />BAIRRO",
            "TUDO É UM AIRBNB.",
        ],
        [
            "LINGUAGEM INCLUSIVA",
            "PURISMO LINGUÍSTICO",
            "Comunicação",
            "PALAVRAS",
            "A língua evolui com a sociedade, mas impor mudanças artificiais gera rejeição. Falemos para nos entendermos, não para exibir virtude política.",
            "FALA BEM,<br />RAIOS",
            "A LINGUAGEM NEUTRA DESTRÓI A FAMÍLIA.",
            "A ACADEMIA É<br />MACHISTA",
            "MUDA OU ÉS O INIMIGO.",
        ],
        [
            "GANHAR É TUDO",
            "PARTICIPAÇÃO",
            "Competição",
            "ESFORÇO",
            "A excelência exige sacrifício e há vencedores e vencidos. Mas o desporto de formação deve promover valores, não frustrações prematuras.",
            "O SEGUNDO<br />É O PRIMEIRO DOS DERROTADOS",
            "HUMILHA O TEU ADVERSÁRIO.",
            "TODOS SÃO<br />CAMPEÕES",
            "PERDER TRAUMATIZA PARA SEMPRE.",
        ],
        [
            "HIKIKOMORI",
            "SOCIALIZAÇÃO FORÇADA",
            "Comunidade",
            "LIGAÇÃO",
            "Saber estar só é vital, mas isolar-se é patológico. Somos animais sociais que precisam da tribo, embora a tribo por vezes sufoque.",
            "ODEIO<br />PESSOAS",
            "O MEU QUARTO É O MEU MUNDO.",
            "SORRI E<br />PARTICIPA",
            "A INTROVERSÃO TEM CURA.",
        ],
    ]
);
