import { createNuanceTexts } from "./create";

export const NUANCE_SV_TEXTS = createNuanceTexts(
    {
        hud: {
            defaultLeft: "Vänster",
            defaultRight: "Höger",
            hint: "Dra för att upptäcka",
            sliderLabel: "Balans mellan ytterligheter",
        },
        intro: {
            labelLeft: "TOMHET",
            labelRight: "MÖRKER",
            title: "NYANS",
            descriptionFirst: "Den verkliga världen är full av färg.",
            descriptionSecond: "Ytterligheterna är dess frånvaro.",
            leftTitle: "VITT",
            leftDescription: "Inga skuggor. Inga tvivel.",
            rightTitle: "SVART",
            rightDescription: "Inget ljus. Inget hopp.",
        },
        outro: {
            firstLine: "Världen vill att du väljer sida.",
            secondLine: "Den verkliga revolutionen är att vägra.",
            exit: "Lämna loopen",
            left: "TOMHET",
            right: "MÖRKER",
        },
    },
    [
        [
            "MANSFÖRAKT",
            "MACHOKULTUR",
            "Jämlikhet",
            "KÖN",
            "Att erkänna biologiska skillnader rättfärdigar inte ojämlika rättigheter. Att helt förneka dem bortser från den materiella verkligheten. Jämlikhet är juridisk och moralisk, inte biologisk.",
            "DE ÄR ALLA<br />SKYLDIGA",
            "MANLIGHET ÄR CANCER.",
            "TILLBAKA TILL<br />KÖKET",
            "DEN NATURLIGA ORDNINGEN ÄR HELIG.",
        ],
        [
            "GIFTIGT",
            "REN GEMENSKAP",
            "Socialt",
            "ALGORITM",
            "Sociala medier kan förstärka marginaliserade röster och demokratisera kunskap, men deras nuvarande affärsmodell tjänar pengar på polarisering och ångest.",
            "RADERA<br />ALLT",
            "VI LEVER I EN SIMULERING AV EGOT.",
            "PUBLICERA<br />DIN SJÄL",
            "OM DU INTE DELAR DET FINNS DU INTE.",
        ],
        [
            "OUNDVIKLIG KOLLAPS",
            "FÖRNEKELSE",
            "Planeten",
            "EKO-LOGIK",
            "Panik förlamar och förnekelse dömer. Vi behöver kraftfull teknisk innovation och selektiv nedväxt, inte återvända till grottorna eller låtsas att inget händer.",
            "UTVINNING<br />ÄR MORD",
            "MÄNNISKAN ÄR PESTEN.",
            "KLIMATET<br />FÖRÄNDRAS ALLTID",
            "EKONOMIN ÄR ORÖRBAR.",
        ],
        [
            "MEDELMÅTTA",
            "ARBETSNARKOMANI",
            "Livet",
            "FRAMGÅNG",
            "Framgång är inte bara pengar eller berömmelse, utan att leva med mening. Att ignorera behovet av materiella resurser i ett kapitalistiskt samhälle är dock naivt, inte dygdigt.",
            "NÖJ DIG",
            "AMBITION ÄR FÖR PSYKOPATER.",
            "SOV<br />ALDRIG",
            "VILA ÄR FÖR DE SVAGA.",
        ],
        [
            "MILITANT VEGANISM",
            "REN KARNIVORISM",
            "Näring",
            "KULTURELL NÄRING",
            "Att äta är en etisk och biologisk handling. Vi kan minska djurs lidande utan att förneka vår allätande utvecklingshistoria. Ingen kost är helig.",
            "DU ÄTER<br />LIK",
            "DU ÄR EN SPECIESISTISK MÖRDARE.",
            "SVAG<br />SOYBOY",
            "BARA BLOD GER STYRKA.",
        ],
        [
            "RADIKAL ATEISM",
            "FANATISM",
            "Andlighet",
            "TRO OCH FÖRNUFT",
            "Vetenskapen förklarar hur, andligheten söker varför. Vi kan omfamna den vetenskapliga metoden utan att förlora förundran inför tillvarons mysterium.",
            "GUD ÄR<br />DÖD",
            "VI ÄR SLUMPMÄSSIGA SÄCKAR AV KÖTT.",
            "BETALA TIONDE<br />ELLER BRINN",
            "TVIVEL ÄR EN DÖDSSYND.",
        ],
        [
            "RENT PONZIBEDRÄGERI",
            "NY VÄRLDSORDNING",
            "Pengar",
            "DIGITALT VÄRDE",
            "Blockkedjan är en revolutionerande teknik full av bedragare. Centralbankerna stjäl från oss genom inflation, men total decentralisering är en djungel.",
            "PYRAMID-<br />SPEL",
            "ALLT ÄR LUFT OCH PENNINGTVÄTT.",
            "HODL<br />TILL DÖDEN",
            "FIAT ÄR VÄRDELÖST I MORGON.",
        ],
        [
            "FRÄMLINGSFIENTLIGHET",
            "STATSLÖSHET",
            "Tillhörighet",
            "NATIONELL IDENTITET",
            "Att älska sin kultur innebär inte att hata grannens. Att vara världsmedborgare är ett tomt privilegium om man inte först tar hand om sitt lokalsamhälle.",
            "STÄNG<br />GRÄNSERNA",
            "DE EGNA FÖRST.",
            "NATIONER<br />ÄR FÄNGELSER",
            "INGEN MÄNNISKA ÄR ILLEGAL.",
        ],
        [
            "KAOTISK POLYAMORI",
            "ÄGANDE",
            "Relationer",
            "BAND",
            "Individuell frihet borde inte hindra djup hängivenhet. Att älska är att avstå från andra möjliga världar för att bygga en gemensam och stabil.",
            "INGENTING TILLHÖR<br />NÅGON",
            "ENGAGEMANG ÄR ETT FÄNGELSE.",
            "DU ÄR<br />MIN EGENDOM",
            "SVARTSJUKA ÄR KÄRLEK.",
        ],
        [
            "HUSOCKUPATION",
            "SPEKULATION",
            "Hem",
            "ETT VÄRDIGT TAK",
            "Bostaden är en rättighet, inte bara en finansiell tillgång. Men rättssäkerhet och privata investeringar behövs för att förverkliga den rätten.",
            "EXPROPRIERA<br />ALLT",
            "HYRESVÄRDAR ÄR PARASITER.",
            "MARKNADEN<br />REGLERAR SIG SJÄLV",
            "OM DU ÄR FATTIG ÄR DET DITT EGET FEL.",
        ],
        [
            "SNOBBERI",
            "AUTOMATISERING",
            "Kreativitet",
            "SYNTETISK SJÄL",
            "Konst är inte bara resultatet, utan den mänskliga processen att skapa mening. AI demokratiserar tekniken, men kan aldrig demokratisera smärta eller erfarenhet.",
            "DET DÄR ÄR INTE<br />KONST",
            "BARA OLJEFÄRG HAR EN SJÄL.",
            "ANPASSA DIG<br />ELLER DÖ",
            "KONSTNÄREN KAN UNDVARAS.",
        ],
        [
            "INDOKTRINERING",
            "VILDMARK",
            "Utbildning",
            "LÄRANDE",
            "Skolan ska lära oss hur vi tänker, inte vad vi ska tänka. Men strukturerad och delad kunskap är civilisationens grund, inte ett förtryck.",
            "TEGELSTENS-<br />FABRIK",
            "DE DÖDAR DIN KREATIVITET.",
            "FRI<br />OKUNSKAP",
            "MITT BARN LÄR SIG GENOM TIKTOK.",
        ],
        [
            "POLISSTAT",
            "ANARKI",
            "Trygghet",
            "SAMLEVNAD",
            "Vi vill kunna gå tryggt på gatan, men inte till priset av övervakning dygnet runt. Verklig trygghet föds ur social sammanhållning, inte kameror.",
            "KAMEROR<br />I BADRUMMET",
            "DEN SOM INGET HAR ATT DÖLJA HAR INGET ATT FRUKTA.",
            "DEN STARKES<br />RÄTT",
            "KÖP ETT VAPEN ELLER DÖ.",
        ],
        [
            "FÖRBUDSPOLITIK",
            "NARKOSTAT",
            "Folkhälsa",
            "ALTER EGO",
            "Kriget mot droger har misslyckats, men okontrollerad konsumtion förstör liv. Vi behöver utbildning, reglering och ansvar, inte moralism eller kaos.",
            "DIN KROPP<br />TILLHÖR STATEN",
            "SÄG NEJ TILL LIVET.",
            "ZOMBIER<br />PÅ GATAN",
            "ALLT ÄR TILLÅTET OM DET GER ETT RUS.",
        ],
        [
            "ANTINATALISM",
            "KUVÖS",
            "Familj",
            "ARV",
            "Att sätta barn till världen är en handling av radikalt hopp, inte en patriotisk plikt eller ett ekologiskt brott. Medvetet föräldraskap är vårt största bidrag till framtiden.",
            "LIVET ÄR<br />LIDANDE",
            "FRIVILLIGT UTDÖENDE NU.",
            "FÖD BARN<br />ELLER DÖ",
            "KVINNOR ÄR FABRIKER.",
        ],
        [
            "TRANSPARENS",
            "SPÖKE",
            "Data",
            "PRIVATLIV",
            "Privatliv är nödvändigt för frihet. Men total anonymitet skyddar också avskyvärda brott. Var går gränsen mellan trygghet och rätten till hemligheter?",
            "HEMLIGHET<br />ÄR SKULD",
            "PUBLICERA HELA DIN CHATT.",
            "DARK<br />WEB",
            "KRYPTOGRAFISK STRAFFRIHET.",
        ],
        [
            "BIG PHARMA",
            "PSEUDOVETENSKAP",
            "Hälsa",
            "LÄKNING",
            "Modern medicin räddar liv, men läker inte alltid själen och förebygger inte all sjukdom. Att lyssna på kroppen betyder inte att förneka antibiotika.",
            "ETT PILLER<br />FÖR ALLT",
            "DIN SMÄRTA ÄR EN MARKNAD.",
            "CANCER<br />SITTER I HUVUDET",
            "HÖGA VIBRATIONER OCH SOCKERVATTEN.",
        ],
        [
            "GERONTOKRATI",
            "ÅLDERSDISKRIMINERING",
            "Tid",
            "MOGNAD",
            "Att åldras är ett privilegium, inte en sjukdom. Vi måste ta hand om dem som tog hand om oss utan att belåna de ungas framtid.",
            "ODÖDLIGHET<br />TILL VARJE PRIS",
            "UNGA VET INGENTING.",
            "DU ÄR<br />ÖVERFLÖDIG, FARFAR",
            "FLYKTEN FRÅN FRAMTIDEN VAR EN DOKUMENTÄR.",
        ],
        [
            "BASINKOMST",
            "LUDDISM",
            "Framtid",
            "MENING",
            "Om maskinerna arbetar, vad gör då vi? Arbete ger värdighet, exploatering gör det inte. Vi måste omdefiniera människovärdet bortom produktivitet.",
            "GRATIS<br />PENGAR",
            "INGEN BORDE NÅGONSIN ARBETA.",
            "BRÄNN<br />MASKINERNA",
            "TEKNIKEN ÄR DJÄVULEN.",
        ],
        [
            "SKALPELL",
            "VANVÅRD",
            "Estetik",
            "SJÄLVKÄNSLA",
            "Att vilja se bra ut är mänskligt; att hata sig själv är lönsamt. Hälsa bör vara normen, men skönhetens mångfald är verkligheten.",
            "PERMANENT<br />FILTER",
            "DITT RIKTIGA ANSIKTE ÄR ETT FEL.",
            "FETMA<br />ÄR HÄLSA",
            "ATT FÖRNEKA BIOLOGIN ÄR EGENMAKT.",
        ],
        [
            "DIKTATUR",
            "PÖBELVÄLDE",
            "Makt",
            "STYRE",
            "Den starke ledaren lovar ordning men ger tyranni. Massan lovar en röst men ger kaos. Tråkiga institutioner är det enda som skyddar oss från oss själva.",
            "HÅRDA TAG",
            "FRIHET ÄR ÖVERSKATTAD.",
            "BRÄNN<br />RIKSDAGEN",
            "FOLKET HAR ALLTID RÄTT.",
        ],
        [
            "DÖDSSTRAFF",
            "STRAFFRIHET",
            "Rättvisa",
            "UPPRÄTTELSE",
            "Öga för öga gör oss blinda, men att ignorera offren skapar monster. Återanpassning är idealet; att skydda samhället är plikten.",
            "DÖDA DEM<br />ALLIHOP",
            "HÄMNDEN ÄR LJUV.",
            "AVSKAFFA<br />FÄNGELSERNA",
            "INGET BROTT FÖRTJÄNAR STRAFF.",
        ],
        [
            "SVART LEGEND",
            "ROSASKIMRANDE LEGEND",
            "Minne",
            "DET FÖRFLUTNA",
            "Vi kan inte döma 1400-talet med 2000-talets moral, och inte heller skönmåla folkmord. Historien är ingen saga om hjältar och skurkar, utan en lektion i komplexitet.",
            "ALLT VAR<br />FOLKMORD",
            "DIN KULTUR ÄR SKYLDIG.",
            "ÄRORIKT<br />IMPERIUM",
            "VI HAR ALDRIG GJORT NÅGOT FEL.",
        ],
        [
            "VETENSKAPSRELIGION",
            "KONSPIRATION",
            "Sanning",
            "BELÄGG",
            "Vetenskap är en metod för att minska fel, inte en oföränderlig dogm. Att ifrågasätta är sunt, men att förneka observerbar verklighet är att falla ner i vanföreställningens avgrund.",
            "EXPERTEN<br />ÄR GUD",
            "TÄNK INTE, LITA PÅ OSS.",
            "JORDEN<br />ÄR PLATT",
            "ALLT ÄR MANIPULERAT.",
        ],
        [
            "PÄLSBARN",
            "OBJEKTIFIERING",
            "Natur",
            "ARTER",
            "Djur känner och förtjänar respekt, men att förmänskliga dem är en annan form av vanvård. Att älska dem är att förstå deras natur, inte att klä ut dem till bebisar.",
            "MER ÄN<br />MÄNNISKOR",
            "RÄDDA HUNDEN, DÖDA BARNET.",
            "DE ÄR BARA<br />SAKER",
            "ANVÄND DEM OCH KASTA DEM.",
        ],
        [
            "UNIFORM",
            "FAST FASHION",
            "Image",
            "UTTRYCK",
            "Kläder är språk, men tvångsmässig konsumtion är förstörelse. Vi kan ha stil utan att exploatera planeten eller göra oss själva till reklampelare.",
            "KLÄ DIG<br />I GRÅTT",
            "ATT STICKA UT ÄR FÅFÄNGA.",
            "KÖP<br />OCH SLÄNG",
            "NYA KLÄDER ÄR LYCKA.",
        ],
        [
            "FÖRBUD",
            "SPELBEROENDE",
            "Last",
            "SLUMP",
            "Spel är vuxenunderhållning, men en rovlysten industri förstör familjer. Att reglera aggressiv reklam skyddar friheten att välja utan fällor.",
            "OLAGLIGT<br />NÖJE",
            "NJUTNING ÄR SYND.",
            "SATSA<br />HUSET",
            "NÄSTA SNURR RÄDDAR DIG.",
        ],
        [
            "TOURIST GO HOME",
            "TEMAPARK",
            "Resor",
            "UPPTÄCKT",
            "Resor öppnar sinnet, men massturismen stänger bostadsområden. Vi vill lära känna världen utan att göra den till en kuliss av papp.",
            "BORT<br />HÄRIFRÅN",
            "UTLÄNNINGAR ÄR BESVÄRLIGA.",
            "SÄLJ DITT<br />KVARTER",
            "ALLT ÄR ETT AIRBNB.",
        ],
        [
            "INKLUDERANDE SPRÅK",
            "SPRÅKPURISM",
            "Kommunikation",
            "ORD",
            "Språket utvecklas med samhället, men påtvingade konstgjorda förändringar väcker motstånd. Låt oss tala för att förstå varandra, inte för att skylta med politisk dygd.",
            "TALA ORDENTLIGT,<br />FÖR FAN",
            "KÖNSNEUTRALT SPRÅK FÖRSTÖR FAMILJEN.",
            "AKADEMIEN ÄR<br />SEXISTISK",
            "FÖRÄNDRA DIG ELLER BLI FIENDEN.",
        ],
        [
            "ATT VINNA ÄR ALLT",
            "DELTAGANDE",
            "Tävling",
            "ANSTRÄNGNING",
            "Förträfflighet kräver uppoffring, och det finns vinnare och förlorare. Men breddidrotten ska främja värderingar, inte tidig frustration.",
            "TVÅAN<br />ÄR FÖRSTA FÖRLORAREN",
            "FÖRNEDRA DIN MOTSTÅNDARE.",
            "ALLA ÄR<br />MÄSTARE",
            "ATT FÖRLORA GER LIVSLÅNGA TRAUMAN.",
        ],
        [
            "HIKIKOMORI",
            "TVINGAT UMGÄNGE",
            "Gemenskap",
            "KONTAKT",
            "Att kunna vara ensam är livsviktigt, men isolering är sjuklig. Vi är sociala djur som behöver flocken, även när den ibland känns kvävande.",
            "JAG HATAR<br />MÄNNISKOR",
            "MITT RUM ÄR MIN VÄRLD.",
            "LE OCH<br />DELTA",
            "INTROVERSION KAN BOTAS.",
        ],
    ]
);
