import { createNuanceTexts } from "./create";

export const NUANCE_TR_TEXTS = createNuanceTexts(
    {
        hud: {
            defaultLeft: "Sol",
            defaultRight: "Sağ",
            hint: "Keşfetmek için kaydır",
            sliderLabel: "Uçlar arasındaki denge",
        },
        intro: {
            labelLeft: "BOŞLUK",
            labelRight: "KARANLIK",
            title: "NÜANS",
            descriptionFirst: "Gerçek dünya renklerle doludur.",
            descriptionSecond: "Uçlar, rengin yokluğudur.",
            leftTitle: "BEYAZ",
            leftDescription: "Gölge yok. Şüphe yok.",
            rightTitle: "SİYAH",
            rightDescription: "Işık yok. Umut yok.",
        },
        outro: {
            firstLine: "Dünya bir taraf seçmeni istiyor.",
            secondLine: "Gerçek devrim, bunu reddetmektir.",
            exit: "Döngüden çık",
            left: "BOŞLUK",
            right: "KARANLIK",
        },
    },
    [
        [
            "ERKEK DÜŞMANLIĞI",
            "MAÇOLUK",
            "Eşitlik",
            "TOPLUMSAL CİNSİYET",
            "Biyolojik farklılıkları kabul etmek, hak eşitsizliğini meşrulaştırmaz. Bunları tümden inkâr etmek maddi gerçekliği görmezden gelir. Eşitlik hukuki ve ahlakidir, biyolojik değil.",
            "HEPSİ<br />SUÇLU",
            "ERKEKLİK BİR KANSERDİR.",
            "MUTFAĞA<br />DÖN",
            "DOĞAL DÜZEN KUTSALDIR.",
        ],
        [
            "ZEHİRLİ",
            "SAF BAĞLANTI",
            "Sosyal",
            "ALGORİTMA",
            "Sosyal ağlar dışlanmış sesleri güçlendirebilir ve bilgiyi demokratikleştirebilir; ancak bugünkü iş modelleri kutuplaşma ve kaygıyı paraya çevirir.",
            "HER ŞEYİ<br />SİL",
            "EGO SİMÜLASYONUNDA YAŞIYORUZ.",
            "RUHUNU<br />PAYLAŞ",
            "PAYLAŞMIYORSAN YOKSUN.",
        ],
        [
            "KAÇINILMAZ ÇÖKÜŞ",
            "İNKÂRCILIK",
            "Gezegen",
            "EKO-MANTIK",
            "Panik felç eder, inkâr mahkûm eder. Mağaralara dönmek ya da hiçbir şey olmuyormuş gibi davranmak değil, güçlü teknolojik yenilik ve seçici küçülme gerekiyor.",
            "MADENCİLİK<br />CİNAYETTİR",
            "İNSANLIK BİR VEBADIR.",
            "İKLİM<br />HEP DEĞİŞİR",
            "EKONOMİYE DOKUNULMAZ.",
        ],
        [
            "VASATLIK",
            "İŞKOLİKLİK",
            "Hayat",
            "BAŞARI",
            "Başarı yalnızca para ya da şöhret değil, amaçla yaşamaktır. Kapitalist bir toplumda maddi kaynak ihtiyacını yok saymak ise erdem değil saflıktır.",
            "YETİN",
            "HIRS PSİKOPATLAR İÇİNDİR.",
            "ASLA<br />UYUMA",
            "DİNLENMEK ZAYIFLAR İÇİNDİR.",
        ],
        [
            "MİLİTAN VEGANLIK",
            "SAF ETÇİLLİK",
            "Beslenme",
            "KÜLTÜREL BESLENME",
            "Yemek hem etik hem biyolojik bir eylemdir. Hepçil evrimsel geçmişimizi inkâr etmeden hayvanların acısını azaltabiliriz. Kutsal bir beslenme biçimi yoktur.",
            "CESET<br />YİYORSUN",
            "TÜRCÜ BİR KATİLSİN.",
            "ZAYIF<br />SOYBOY",
            "YALNIZCA KAN GÜÇ VERİR.",
        ],
        [
            "RADİKAL ATEİZM",
            "FANATİZM",
            "Maneviyat",
            "İNANÇ VE AKIL",
            "Bilim nasıl sorusunu açıklar, maneviyat neden sorusunu arar. Varlığın gizemi karşısındaki hayretimizi yitirmeden bilimsel yöntemi benimseyebiliriz.",
            "TANRI<br />ÖLDÜ",
            "RASTGELE ET TORBALARIYIZ.",
            "ONDALIK VER<br />YA DA YAN",
            "ŞÜPHE ÖLÜMCÜL GÜNAHTIR.",
        ],
        [
            "TAM BİR PONZİ",
            "YENİ DÜZEN",
            "Para",
            "DİJİTAL DEĞER",
            "Blokzincir dolandırıcılarla dolu devrimci bir teknolojidir. Merkez bankaları enflasyonla bizi soyar, ama tam merkeziyetsizlik de bir ormandır.",
            "PİRAMİT<br />SİSTEMİ",
            "HEPSİ DUMAN VE KARA PARA AKLAMA.",
            "ÖLENE DEK<br />HODL",
            "İTİBARİ PARA YARIN SIFIR.",
        ],
        [
            "YABANCI DÜŞMANLIĞI",
            "VATANSIZLIK",
            "Aidiyet",
            "ULUSAL KİMLİK",
            "Kendi kültürünü sevmek komşununkinden nefret etmeyi gerektirmez. Önce yerel topluluğuna sahip çıkmıyorsan dünya vatandaşı olmak içi boş bir ayrıcalıktır.",
            "SINIRLARI<br />KAPAT",
            "ÖNCE BİZİMKİLER.",
            "ULUSLAR<br />HAPİSHANEDİR",
            "HİÇBİR İNSAN YASA DIŞI DEĞİLDİR.",
        ],
        [
            "KAOTİK ÇOKAŞKLILIK",
            "SAHİPLİK",
            "İlişkiler",
            "BAĞ",
            "Bireysel özgürlük derin bağlılığa engel olmamalı. Sevmek, ortak ve sağlam bir dünya kurmak için başka dünyaların ihtimalinden vazgeçmektir.",
            "HİÇBİR ŞEY<br />KİMSENİN DEĞİL",
            "BAĞLILIK BİR HAPİSHANEDİR.",
            "BENİM<br />MÜLKÜMSÜN",
            "KISKANÇLIK SEVGİDİR.",
        ],
        [
            "İŞGAL",
            "SPEKÜLASYON",
            "Yuva",
            "İNSANCA BİR ÇATI",
            "Konut yalnızca finansal bir varlık değil, bir haktır. Ancak bu hakkı inşa etmek için hukuk güvenliği ve özel yatırım gereklidir.",
            "HER ŞEYE<br />EL KOY",
            "EV SAHİPLERİ PARAZİTTİR.",
            "PİYASA<br />KENDİNİ DÜZENLER",
            "YOKSULSAN SUÇ SENİN.",
        ],
        [
            "ZÜPPELİK",
            "OTOMASYON",
            "Yaratıcılık",
            "SENTETİK RUH",
            "Sanat yalnızca sonuç değil, insanın anlam verme sürecidir. Yapay zekâ tekniği demokratikleştirir, fakat acıyı ve deneyimi asla demokratikleştiremez.",
            "BU SANAT<br />DEĞİL",
            "YALNIZCA YAĞLIBOYANIN RUHU VARDIR.",
            "UYUM SAĞLA<br />YA DA ÖL",
            "SANATÇI GEREKSİZDİR.",
        ],
        [
            "BEYİN YIKAMA",
            "VAHŞİLİK",
            "Eğitim",
            "ÖĞRENME",
            "Okul ne düşüneceğimizi değil, nasıl düşüneceğimizi öğretmelidir. Ancak yapılandırılmış ve ortak bilgi, baskı değil medeniyetin temelidir.",
            "TUĞLA<br />FABRİKASI",
            "YARATICILIĞINI ÖLDÜRÜYORLAR.",
            "ÖZGÜR<br />CEHALET",
            "ÇOCUĞUM TİKTOK İZLEYEREK ÖĞRENİYOR.",
        ],
        [
            "POLİS DEVLETİ",
            "ANARŞİ",
            "Güvenlik",
            "BİRLİKTE YAŞAM",
            "Sokakta huzurla yürümek istiyoruz, ama yirmi dört saat gözetlenme pahasına değil. Gerçek güvenlik kameralardan değil, toplumsal dayanışmadan doğar.",
            "BANYODA<br />KAMERA",
            "SAKLAYACAK ŞEYİ OLMAYANIN KORKACAĞI ŞEY YOKTUR.",
            "GÜÇLÜNÜN<br />KANUNU",
            "SİLAH AL YA DA ÖL.",
        ],
        [
            "YASAKÇILIK",
            "NARKO-DEVLET",
            "Halk sağlığı",
            "ALTER EGO",
            "Uyuşturucuyla savaş başarısız oldu, fakat denetimsiz kullanım hayatları yok ediyor. Ahlakçılık ya da kaos değil; eğitim, düzenleme ve sorumluluk gerekiyor.",
            "BEDENİN<br />DEVLETİNDİR",
            "HAYATA HAYIR DE.",
            "SOKAKTA<br />ZOMBİLER",
            "KAFA YAPIYORSA HER ŞEY SERBEST.",
        ],
        [
            "ANTİNATALİZM",
            "KULUÇKA MAKİNESİ",
            "Aile",
            "MİRAS",
            "Dünyaya çocuk getirmek vatansever bir görev ya da ekolojik bir suç değil, radikal bir umut eylemidir. Bilinçli ebeveynlik geleceğe en büyük katkımızdır.",
            "HAYAT<br />ISTIRAPTIR",
            "GÖNÜLLÜ YOK OLUŞ ŞİMDİ.",
            "DOĞUR<br />YA DA ÖL",
            "KADINLAR FABRİKADIR.",
        ],
        [
            "ŞEFFAFLIK",
            "HAYALET",
            "Veri",
            "MAHREMİYET",
            "Mahremiyet özgürlük için gereklidir. Ancak tam anonimlik korkunç suçları da korur. Güvenlik ile sır saklama hakkı arasındaki sınır nerede?",
            "SIR<br />SUÇ DEMEKTİR",
            "TÜM SOHBETİNİ YAYIMLA.",
            "KARANLIK<br />AĞ",
            "KRİPTOGRAFİK CEZASIZLIK.",
        ],
        [
            "BÜYÜK İLAÇ ŞİRKETLERİ",
            "SÖZDE BİLİM",
            "Sağlık",
            "İYİLEŞME",
            "Modern tıp hayat kurtarır, ama ruhu her zaman iyileştirmez ve hastalığı her zaman önlemez. Bedeni dinlemek antibiyotikleri reddetmek değildir.",
            "HER ŞEYE<br />BİR HAP",
            "ACIN BİR PAZARDIR.",
            "KANSER<br />ZİHİNSELDİR",
            "YÜKSEK TİTREŞİM VE ŞEKERLİ SU.",
        ],
        [
            "GERONTOKRASİ",
            "YAŞ AYRIMCILIĞI",
            "Zaman",
            "OLGUNLUK",
            "Yaşlanmak hastalık değil, ayrıcalıktır. Bize bakanlara bakarken gençlerin geleceğini ipotek etmemeliyiz.",
            "HER NE PAHASINA<br />OLURSA OLSUN ÖLÜMSÜZLÜK",
            "GENÇLER HİÇBİR ŞEY BİLMEZ.",
            "FAZLASIN,<br />DEDE",
            "LOGAN’IN KAÇIŞI BİR BELGESELDİ.",
        ],
        [
            "TEMEL GELİR",
            "LUDİZM",
            "Gelecek",
            "AMAÇ",
            "Makineler çalışırsa biz ne yapacağız? İş onur verir, sömürü vermez. İnsan değerini üretkenliğin ötesinde yeniden tanımlamalıyız.",
            "BEDAVA<br />PARA",
            "HİÇ KİMSE ASLA ÇALIŞMAMALI.",
            "MAKİNELERİ<br />YAK",
            "TEKNOLOJİ ŞEYTANDIR.",
        ],
        [
            "NEŞTER",
            "İHMAL",
            "Estetik",
            "ÖZ SAYGI",
            "İyi görünmek istemek insanidir; kendinden nefret etmek kârlıdır. Ölçüt sağlık olmalı, ama farklı güzellikler gerçektir.",
            "KALICI<br />FİLTRE",
            "GERÇEK YÜZÜN BİR KUSUR.",
            "OBEZİTE<br />SAĞLIKTIR",
            "BİYOLOJİYİ İNKÂR ETMEK GÜÇLENDİRİR.",
        ],
        [
            "DİKTATÖRLÜK",
            "KALABALIK İKTİDARI",
            "İktidar",
            "YÖNETİM",
            "Güçlü lider düzen vaat eder ama zorbalık getirir. Kalabalık söz hakkı vaat eder ama kaos getirir. Sıkıcı kurumlar bizi kendimizden koruyan tek şeydir.",
            "DEMİR YUMRUK",
            "ÖZGÜRLÜK ABARTILIYOR.",
            "MECLİSİ<br />YAK",
            "HALK HER ZAMAN HAKLIDIR.",
        ],
        [
            "İDAM CEZASI",
            "CEZASIZLIK",
            "Adalet",
            "ONARIM",
            "Göze göz hepimizi kör eder, ancak mağdurları görmezden gelmek canavarlar yaratır. Topluma yeniden kazandırma idealdir; toplumu korumak ise görevdir.",
            "HEPSİNİ<br />ÖLDÜR",
            "İNTİKAM TATLIDIR.",
            "HAPİSHANELERİ<br />KALDIR",
            "HİÇBİR SUÇ CEZAYI HAK ETMEZ.",
        ],
        [
            "KARA EFSANE",
            "PEMBE EFSANE",
            "Bellek",
            "GEÇMİŞ",
            "On beşinci yüzyılı yirmi birinci yüzyıl ahlakıyla yargılayamayız, soykırımları da aklayamayız. Tarih kahramanlarla kötülerin masalı değil, karmaşıklık dersidir.",
            "HER ŞEY<br />SOYKIRIMDI",
            "KÜLTÜRÜN SUÇLU.",
            "ŞANLI<br />İMPARATORLUK",
            "BİZ HİÇ YANLIŞ YAPMADIK.",
        ],
        [
            "BİLİM DİNİ",
            "KOMPLO",
            "Hakikat",
            "KANIT",
            "Bilim hatayı azaltma yöntemidir, değişmez bir dogma değil. Sorgulamak sağlıklıdır; gözlemlenebilir gerçeği inkâr etmek ise hezeyan uçurumuna düşmektir.",
            "UZMAN<br />TANRIDIR",
            "DÜŞÜNME, GÜVEN.",
            "DÜNYA<br />DÜZDÜR",
            "HER ŞEY MANİPÜLE EDİLDİ.",
        ],
        [
            "TÜYLÜ ÇOCUKLAR",
            "NESNELEŞTİRME",
            "Doğa",
            "TÜRLER",
            "Hayvanlar hisseder ve saygıyı hak eder; ancak onları insanlaştırmak da bir istismar biçimidir. Onları sevmek, bebek gibi giydirmek değil doğalarını anlamaktır.",
            "İNSANDAN<br />ÜSTÜN",
            "KÖPEĞİ KURTAR, ÇOCUĞU ÖLDÜR.",
            "ONLAR SADECE<br />EŞYA",
            "KULLAN VE AT.",
        ],
        [
            "ÜNİFORMA",
            "HIZLI MODA",
            "İmaj",
            "İFADE",
            "Giyim bir dildir, ama dürtüsel tüketim yıkımdır. Gezegeni sömürmeden ya da kendimizi reklam panosuna çevirmeden tarz sahibi olabiliriz.",
            "GRİ<br />GİY",
            "ÖNE ÇIKMAK KİBİRDİR.",
            "SATIN AL<br />VE AT",
            "YENİ GİYSİ MUTLULUKTUR.",
        ],
        [
            "YASAK",
            "KUMAR BAĞIMLILIĞI",
            "Bağımlılık",
            "ŞANS",
            "Kumar yetişkin eğlencesidir, ama yağmacı bir sektör aileleri yıkar. Saldırgan reklamları düzenlemek, tuzaksız seçim özgürlüğünü korumaktır.",
            "YASA DIŞI<br />EĞLENCE",
            "HAZ GÜNAHTIR.",
            "EVİ<br />ORTAYA KOY",
            "SONRAKİ TUR SENİ KURTARACAK.",
        ],
        [
            "TOURIST GO HOME",
            "TEMA PARKI",
            "Seyahat",
            "KEŞİF",
            "Seyahat zihni açar, fakat kitle turizmi mahalleleri kapatır. Dünyayı kartondan bir sahneye çevirmeden tanımak istiyoruz.",
            "DEFOL<br />BURADAN",
            "YABANCILAR RAHATSIZ EDER.",
            "MAHALLENİ<br />SAT",
            "HER YER AIRBNB.",
        ],
        [
            "KAPSAYICI DİL",
            "DİL SAFLIĞI",
            "İletişim",
            "SÖZCÜKLER",
            "Dil toplumla birlikte gelişir, ama yapay değişimleri dayatmak tepki doğurur. Siyasi erdem sergilemek için değil, birbirimizi anlamak için konuşalım.",
            "DÜZGÜN KONUŞ,<br />LANET OLSUN",
            "CİNSİYETSİZ DİL AİLEYİ YIKIYOR.",
            "DİL KURUMU<br />CİNSİYETÇİ",
            "DEĞİŞ YA DA DÜŞMANSIN.",
        ],
        [
            "KAZANMAK HER ŞEYDİR",
            "KATILIM",
            "Rekabet",
            "ÇABA",
            "Mükemmellik fedakârlık ister ve kazananlarla kaybedenler vardır. Ancak taban sporu erken hayal kırıklığını değil, değerleri beslemelidir.",
            "İKİNCİ<br />İLK KAYBEDENDİR",
            "RAKİBİNİ AŞAĞILA.",
            "HERKES<br />ŞAMPİYON",
            "KAYBETMEK ÖMÜR BOYU TRAVMADIR.",
        ],
        [
            "HİKİKOMORİ",
            "ZORUNLU SOSYALLEŞME",
            "Topluluk",
            "BAĞLANTI",
            "Yalnız kalabilmek yaşamsaldır, fakat kendini yalıtmak patolojiktir. Bazen bunaltıcı olsa da topluluğa ihtiyaç duyan sosyal hayvanlarız.",
            "İNSANLARDAN<br />NEFRET EDİYORUM",
            "ODAM BENİM DÜNYAM.",
            "GÜLÜMSE VE<br />KATIL",
            "İÇE DÖNÜKLÜK TEDAVİ EDİLİR.",
        ],
    ]
);
